### ISSUE TITLE
"Using any but need to use chrome" error

### ISSUE THREAD

**Issue by pscohn** [rainforestapp/tester-chrome-extension#10]
Tester says:

"I have installed the testerChrome Extension onChrome browser, but it works rarely. In most cases instead of finding a test I receive this message "You are using any but need to use chrome". I'm using only chrome for browsing the Internet and working on Rainforest tests."

**Comment by KabakF** [comment]
For today. I don't get work even when there is 1000 active tester and a lot running test. Did something change idk. My plugin didn't find works. I wonder why. Waiting for your answer Russ Boss :)

**Comment by ukd1** [comment]
@pscohn very few hits should require a specific browser these days, but it's true this does look for "any" hits not "chrome" specifically.

**Comment by nerdatwork** [comment]
https://cloud.githubusercontent.com/assets/15882196/11201600/7af38f88-8d05-11e5-8714-ec7cf56cfbd1.png

As seen I am using safari but the error message is still there. Why is that ?

**Comment by ukd1** [comment]
@nerdatwork it's a bug - the actual reason (like at our end) is that the hit and the job requirements are not matching correctly.

@pscohn can we fix? Suggest v1 fix is to check that the hit and job are matching, aka "any"

**Comment by pscohn** [comment]
@ukd1 will take a look.

**Comment by pscohn** [comment]
Closing until we have any new reports of this.
