### ISSUE TITLE
On Premise Crowd: Extension focuses their work page instead of opening job

### ISSUE THREAD

**Issue by pscohn** [rainforestapp/tester-chrome-extension#100]
If on-premise workers have open their work listing and try to use the extension, it will just focus that tab instead of opening a new one with an actual job.

**Comment by nishak14** [comment]
Meaning that the extension is exclusive for the browser irrespective of user browsing different sites or working. You may want to communicate with users about availability of your extension on chromium, too. It works OK, and I did 2 hits.

It would be better if your extensions incorporates an audible warning along with flashing tabs/icons.

**Comment by helloworld111gh** [comment]
tell the on premise workers to close the tab in order get the job?

**Comment by pscohn** [comment]
@helloworld111gh sure, but it's better to just fix it, since they should be able to have their work page open and still use the extension :)
