### ISSUE TITLE
You reached maximum of unsubmitted applications

### ISSUE THREAD

**Issue by Ljiljica2609** [rainforestapp/tester-chrome-extension#102]
Hi , i have problem with HIT. I started working ( opened chrome from last session , i wasnt working few hours and everything was turned off before this start ( pc , chrome , extension ) , and hit i got from extension was saying "You have reached maximum..." but i didnt have any job opened. 
My tester ID is : 858b3c41-7d9f-423d-b317-6946848412af

**Comment by dreicaan** [comment]
The same thing happened to me today. The extension opened new tab with " You have reached the maximum number of unsubmitted..."  and I have finished the previous job 10 minutes earlier. Could it have something to do with the fact that the bonus for that job is still pending? 
I've just checked and the bonus has been paid and the "maximum number.." has turned into oops after a refresh.

**Comment by dreicaan** [comment]
The same thing happened just now. I turned on the extension, new tab opened but with a "maximum number" message. I finished the last hit 7 hours ago.

**Comment by BonesKnows** [comment]
did you guys found fix for this? I am having exact issue for a week now

**Comment by pscohn** [comment]
Added some information here: https://github.com/rainforestapp/tester-chrome-extension/wiki/Troubleshooting-&-Common-Errors-Explained

**Comment by BonesKnows** [comment]
@pscohn i have one account i dont share it with anyone and i still have problem. Almost everytime when extension gives me a link i get "you have reached.." message. When i try to refresh it still getting this message for 1 hour or more. I hardly get a hit for a week now because this is issue is happenig more than it supposed.
