### ISSUE TITLE
Bug:  Total rejections (30 days) shows cumulative total

### ISSUE THREAD

**Issue by JPierreS** [rainforestapp/tester-chrome-extension#103]
The total rejections (last 30 days) in tester portal still shows the cumulative total and not the actual admin rejections for past 30 days.

The ones shown under rejection tab is correct though.

**Comment by pscohn** [comment]
@JPierreS A tester alerted us to this in a ticket, we're pushing out a fix today.

**Comment by RezwanulHaque** [comment]
Same here
