### ISSUE TITLE
Mac OS Terminal freeze often

### ISSUE THREAD

**Issue by BonesKnows** [rainforestapp/tester-chrome-extension#105]
many times i have problems with  terminal freeze when i work in mac so i need to refresh HIT to get a new vm,sometimes froze 2-3 times even when i refresh. It is very annoying when i am on the last step and need to refresh HIT.

**Comment by erdeminofff** [comment]
This problem continues for a long time. You may be think that terminal is freezing, but its not. It only loses mouse control (mostly). But keyboard works and you can click some button or links with "tab" and "space" keys. But its very limited. It does not seem difficult to solve and looks like that could be easily fix.  Rainforest must do something about it.

**Comment by nerdatwork** [comment]
Please check the posts before opening up a new one. This is already covered in #40
