### ISSUE TITLE
Oops while extension says "Yes"

### ISSUE THREAD

**Issue by vladfuller** [rainforestapp/tester-chrome-extension#106]
Since yesterday i got only 2 hits.... always as extension opens a new tab it says oops... and still say "YES" green color for 5 o 6 seconds.... what is happening?

**Comment by pupijevi** [comment]
I have same problem this week

**Comment by neuro15** [comment]
I am having the same problem, not getting a single hit.

**Comment by NeoWorker** [comment]
Just keep reloading the page until you get the hit. Remember that there's a lot of testers out there. Just be patient.

**Comment by nerdatwork** [comment]
Please check the posts before opening up a new one. This is already covered in #49
