### ISSUE TITLE
not working today

### ISSUE THREAD

**Issue by androwg** [rainforestapp/tester-chrome-extension#11]
today i noticed that the extension is not working and no get me any hits although i got about 6 hits manually 
i removed it and reinstall but the problem is still excist

**Comment by KabakF** [comment]
Same thing happens to me too, Idk what to do, just waiting a reply from Russ

**Comment by helloworld111gh** [comment]
I believe all HIT's are broken, even Crowdflower HIT's give a "Hit 888888 can't be assigned new HIT's" error

**Comment by KabakF** [comment]
@helloworld111gh  but then no one could work, there is active testers and runs (https://www.rainforestqa.com/)

**Comment by androwg** [comment]
@ukd1 What is the problem?

**Comment by ukd1** [comment]
hey @androwg @KabakF @helloworld111gh -- are you getting errors, or anything weird?

If you can send me your worker ID's, I can pull the logs and check what's actually been happening individually.

**Comment by nihlathar** [comment]
I'm having the same issue, and thought it was a global problem before I saw your response udk1. Obviously many people have the same problem. It just stopped finding work about a day ago, I can do it fine through crowdflower though.

**Comment by helloworld111gh** [comment]
Using chrome devtools I was able to catch this error:
Uncaught SyntaxError: Unexpected end of inputxhr.onreadystatechange @ main.js:186(anonymous function) @ main.js:203
main.js:185
Worker ID is 12219174

**Comment by androwg** [comment]
@ukd1 
i get no errors but i get no work from extension 
my workerId=32916100

**Comment by KabakF** [comment]
@ukd1 Russ I didn't get a job for two days, my plugin doesn't find any job/work for two days. I don't think it's a normal thing to happen
(My Worker ID: 31122298 )

**Comment by isen86** [comment]
extension is not working since yesterday,my worker id is 31839548

**Comment by qpPykT** [comment]
Yeah, two days ago, the plugin(extension) just stopped issuing tasks. 
My Worker ID: 31275106

**Comment by vanessa180479** [comment]
Hello are like, me neither extension works me for days, I hope you can solve my ID: 33902955

**Comment by KabakF** [comment]
@vanessa180479 well I hope haha and happy for you :)

**Comment by androwg** [comment]
@ukd1 seems to be a global problem we hope you can manage it

**Comment by KabakF** [comment]
@androwg I exactly agree with you :+1: 

@ukd1 Many testers can't work for several days Russ, we're waiting for a solutionnn, coome :clock1130:  :stuck_out_tongue:

**Comment by helloworld111gh** [comment]
Any updates on this issue? ETA on fix?

**Comment by qpPykT** [comment]
Tester Chrome Extension - Major bug 2015-11-17 01:36:53 UTC, Russ

'Hey all - thanks to reports from workers, we've found a major bug in the Chrome extension which is stopping it finding most work for you. We've got a fix being worked on now, it should be shipped today. There will be nothing to change at your end. Sorry about this, thanks for all the reports. Russ'

**Comment by androwg** [comment]
It is working right now

**Comment by pscohn** [comment]
@KabakF @isen86 @vanessa180479 others can you confirm it is working for you now?

**Comment by nihlathar** [comment]
Yes, other than standard "oops" error and "hit xyz cant be assigned more work" it works like it should.

**Comment by KabakF** [comment]
@pscohn Yes Paul, It is working so well, thanks to all programmers :)

**Comment by isen86** [comment]
yes it works now
