### ISSUE TITLE
Safari - Problem with speed and cannot type in or paste the URL in the browser.

### ISSUE THREAD

**Issue by akshithaaravi** [rainforestapp/tester-chrome-extension#110]
Facing slow terminals, and safari - not accepting the URL . I just had a 4 step hit and I couldn't complete because the terminal would not accept the URL, it will  back to its original URL - abrigo....no matter what, CTRL V , typing manually...nothing worked and the numbers at the end would increase. like 66, 67, 68 ....etc and when I refreshed again, the assignment was completed.

**Comment by warpten09025** [comment]
that's because someone is faster than you in submitting the job , better find yourself a way to submit  faster

**Comment by JPierreS** [comment]
@warpten09025   No, once you are assigned a job it is yours to complete, nobody else can complete your assignment.  What happened here is that this particular job exceeded the idle policy, once that happens the job becomes invalid.  At step 0 (before pasting the initial URL) there is a 10 minute limit to start job, step 1 and beyond, 15 minute idle policy per step, 60 total minutes for work completion.

@akshithaaravi   yes this happens sometimes, you will see the initial landing page auto complete in the bar.
You can try the following tips, they may help in many cases.

Before pasting the URL, click the URL bar until you see the whole url selected (blue), hit esc few times then delete it, so the bar becomes blank.  Now proceed by pasting the link.  You can also double click on any blank area of the page first.

**Comment by nerdatwork** [comment]
Its already covered in #40. Please check existing threads before opening new ones since having all issues related to a single bug/problem in 1 place helps RF address it better. Thank you.
