### ISSUE TITLE
SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by pscohn** [rainforestapp/tester-chrome-extension#111]
```
SyntaxError

Unexpected end of input
chrome-extension://immdjpjbcikbffjifkbncgfbohbjicpo/js/main.js in XMLHttpRequest.xhr.onreadystatechange at line 2631:22

chrome-extension://immdjpjbcikbffjifkbncgfbohbjicpo/js/main.js in XMLHttpRequest.wrapped at line 262:29
```

**Comment by helloworld111gh** [comment]
I've have seen this error before, typically it occurs when servers are on
fire.

**Comment by pscohn** [comment]
This is the line that triggers it: https://github.com/rainforestapp/tester-chrome-extension/blob/develop/src/app.js#L228 @juliankrispel or @nxvl know off of the top of your head where this could be coming from?

**Comment by juliankrispel** [comment]
I'm guessing there's an empty response

Julian Krispel-Samsel
rainforestqa.com
goodafternoon.co

**Comment by juliankrispel** [comment]
JSON.parse will through that error I believe if the string is empty or invalid json

Julian Krispel-Samsel
rainforestqa.com
goodafternoon.co
