### ISSUE TITLE
"We cannot assign this job at the moment..".Error messageٍ appear Repeatedly!

### ISSUE THREAD

**Issue by ahmedofhell** [rainforestapp/tester-chrome-extension#113]
This's Error Message appear for too long time:
"**We cannot assign this job at the moment. Please refresh this page to get a new job.**"

**Comment by rifatrahman** [comment]
Same here.

**Comment by A1xx** [comment]
I have the same problem(((

**Comment by pscohn** [comment]
This is being fixed right now - you should see things go back to normal shortly.

**Comment by JPierreS** [comment]
It is fixed right now, oops is back in town ;-)

![1oops](https://cloud.githubusercontent.com/assets/7692133/13697765/aaf0f526-e73d-11e5-8054-6c7cda1054f4.jpg)

**Comment by marius11** [comment]
Everything is normal now. The "cannot assign this job" errors are gone.

**Comment by A1xx** [comment]
Everything seams to be ok, cannot assign... error has gone. Thanks;)

**Comment by ahmedofhell** [comment]
Yes, It's Fixed.
Thanks @pscohn
