### ISSUE TITLE
After Failed to report Screenshot error Reporting button is not Clickable.Have to restart Hit.

### ISSUE THREAD

**Issue by Ranky2211** [rainforestapp/tester-chrome-extension#114]
Hi Rf Team,

Previously when Failed to report screenshot error occur reporting button works after repeatedly  pressing the button but now all reporting button greyed out and not working or clickable.Therefore have to restart Hit from beginning.Please Fix this.

Worker ID: 33432784

**Comment by pscohn** [comment]
We're working on fixing this right now @Ranky2211

**Comment by Ranky2211** [comment]
@pscohn Thanks so i am closing this issue.

**Comment by hunt40** [comment]
@Ranky2211 please open this again,this problem still continue i am stuck at 32 step hit,great job rf great job,now i have to start all over again.

**Comment by andywrt** [comment]
Same problem

**Comment by pscohn** [comment]
@hunt40 is the button greyed out after the first time clicking a button, or does it allow you to retry?

**Comment by hunt40** [comment]
@pscohn its stuck on greyed out buttons not active again

what i did is i was on step 21-22 cant remember now,click on yes to move to next step then failed screenshot pop up show up and after that all butons stay in greyed out,waited 2-3 min. and its still stuck to greyed out and then i have to restart the terminal to start from beginning.

**Comment by Ranky2211** [comment]
@pscohn  I faced the the same issue.First Failed to report screenshot then All button greyed out then i restart Hit something went wrong Terminal is not loading.After 4 or 5 retries You requested this job too often Lost 4 Hit So Sad.

**Comment by marius11** [comment]
Having this issue again, but this time the buttons are not greyed out.

**Comment by Hanifmamun** [comment]
it is happening over and over again, failed to report screenshot even after waiting for few moment and restarting the hit but nothing changes just popup appear.

**Comment by jbarber** [comment]
@marius11 / @Hanifmamun I think your problem was solved yesterday in #129

**Comment by Ranky2211** [comment]
Problem is solved now.Thanks RF Team.
