### ISSUE TITLE
Rejection

### ISSUE THREAD

**Issue by Dolazim** [rainforestapp/tester-chrome-extension#115]
Job ID:4884974
Assignment ID:cxe2b686-683e-4d31-8e75-65d562c54847

I work this task and I got ss error then terminal offline...
I Refresh  hit and start work again but email is already taken for last time I go to 10 setep where I get ss error and contine to work but get rejection
what now?

**Comment by pscohn** [comment]
@Dolazim please send us a support ticket from your profile for this type of request.
