### ISSUE TITLE
Cursor being unresponsive in MacOS terminals

### ISSUE THREAD

**Issue by pat87** [rainforestapp/tester-chrome-extension#117]
I had a very large 48 step hit and the cursor stopped working at hit 44. 
These are hits that cant be restarted.. 
A) took nearly 40 minutes so it'll never be done in 1 hr if i start again.
B) use certain emails to register and proceed. So cant restart and work with the same instructions 

I can also not report hits with terminal issues.. 
So what am I supposed to do? close the terminal and forget it? Its not even about the money.. I thought starting hits and not completing counts towards rejections too.

terrible situation to be in. 
Any official stance on what I'm supposed to do in a scenario like this ?

**Comment by Genesis2015** [comment]
Same happen to me this morning. Veeery annoying situation :(

**Comment by ahmedofhell** [comment]
Same problem here.

**Comment by nerdatwork** [comment]
This has already been covered in #40 so please check the existing threads before opening new ones with same issue. Thank you.

**Comment by pat87** [comment]
This is not about reporting the issue.
I am asking what I'm supposed to do in that situation so that it doesnt register as a rejection. 
Reporting terminal issue is a rejection.
Abandoning hits is a rejection.

**Comment by nerdatwork** [comment]
Its about Mac and issues with the terminal. Since theres already a thread about it, if you post it in the same thread RF people will be better to address them. Opening multiple threads is cumbersome and time consuming. They can devote that time fixing bugs instead of reading throw different threads addressing same issues with MAC. 
I am trying to say, just read the title of the thread and make a post in that thread.
Thank you for understanding.

**Comment by hunt40** [comment]
yeah mac terminals is the worst,specially mac with safari is deadly combo,very lethal your mental health,god know i lost how many hits and start all over again,and not the mention you watch sites open in slideshow you can go make some shopping and come back while opening.

**Comment by JPierreS** [comment]
@pat87 You will never get rejected for work that you were not able to complete and abandon under these extreme circumstances.  Rejections can only happen on work that was submitted, and this only happens at the end of the assignment when you click the blue submit button on the last screen, OR when you fail a step (report) and submit.  You will also receive an auto rejection if you report an issue on step 0 without opening the initial job link in the terminal or if it did not convert to the site URL for that specific test.  So no rejections for abandoned jobs or request too often (lost hits) as these were not submitted assignments.

This works along the same principles if you ever make a mistake during a test such as clicking the wrong answer or other, you can safely restart over and your previous answers are discarded as you have not submitted the whole assignment for verification yet.

**Comment by nerdatwork** [comment]
Everything is running great in Mac after the updates so I think its safe to close this thread :+1:

**Comment by pscohn** [comment]
cool! 👍
