### ISSUE TITLE
Lost hit due to terminal connection lost

### ISSUE THREAD

**Issue by uangonline** [rainforestapp/tester-chrome-extension#118]
Hi admin

At first i got hit from rainforestqa extention, but than it said "reach concurent bla bla". So after couple of minute i refresh the page still " reach concurent bla bla". But finally i manage to get the terminal working, so i do the step until step 6 and the terminal suddenly lost it connection. So the only thing i can do was refresh the page again. After refresh than BOOM "You request job to often" and lost the time and money. But i hope someone can help?

hitId=3294573

workerId=17830581

Thanks for your help.

**Comment by maciejgryka** [comment]
Please open a support ticket through the tester portal for any issues specific to your account. This repository is only used to track bugs in he Chrome extension itself.
