### ISSUE TITLE
"You must open this link inside the terminal" message 

### ISSUE THREAD

**Issue by pat87** [rainforestapp/tester-chrome-extension#119]
This when I am opening the link inside the terminal.
Doesnt make sense.. 
![errorterminal](https://cloud.githubusercontent.com/assets/17265000/13963381/224752a4-f08b-11e5-908a-68202dabb9cb.PNG)

**Comment by uangonline** [comment]
Yap I have the same problem.

**Comment by shrestha15207** [comment]
and i got 1 auto rejection for reporting this issue :(

**Comment by uangonline** [comment]
@shrestha15207: Yes i have the same rejection.

**Comment by pscohn** [comment]
This was an error we faced yesterday during an outage - it should be resolved now, and you won't be blocked for any rejections you have gotten for this error.
