### ISSUE TITLE
Problem opening the initial link inside the terminal's browser

### ISSUE THREAD

**Issue by marius11** [rainforestapp/tester-chrome-extension#121]
Hello,

I'm having an issue with the initial link that we're given. When I copy/paste it in the terminal's browser and try to enter it, I received the following message:
![rferr](https://cloud.githubusercontent.com/assets/11650839/13964330/e21132f4-f071-11e5-90f4-0f7868253fa8.png)

This happened with two hits. In the first hit, while trying to copy the given link, I accidentally clicked it and it opened in the browser. I realised the mistake, closed the tab, then tried to open it inside the terminal's browser, but I received the same message, even though I was inside the terminal.

I reported it, then I received the second hit and the same thing happened. Pretty strange things happen when the servers are under heavy, I assume this is one of them.

EDIT: Also covered here at #119.

EDIT 2: The two hits I reported appearing in my history tab:
![image](https://cloud.githubusercontent.com/assets/11650839/13963998/65dcc636-f070-11e5-809f-c541e19353e7.png)

**Comment by shrestha15207** [comment]
so did u get rejections?

**Comment by marius11** [comment]
@shrestha15207 No, but I don't really see why anyone would get a rejection for that. It looks like a lot of people are having the same issue.

**Comment by shrestha15207** [comment]
but i got rejection on that. anything can be done to overcome the rejection?

**Comment by marius11** [comment]
@shrestha15207 I would likely contact support using the help button (you can find it in your Rainforest profile), but I would wait 24 hours at least. They are most likely aware of what's happening and probably everything will be back to normal.

**Comment by shrestha15207** [comment]
contacted support...thanks bro..and got reply as well

Hello,

I sincerely apologize for the inconvenience. Earlier today we were experiencing some issues with our virtual machines, which caused tests and screenshots to fail. This problem is now fixed, but we can't do anything about the failed tests. I apologize for the inconvenience. Please let us know if you continue to experience this problem in the future.

Sincerely,

Rainforest Support
rainforestqa.com

**Comment by hunt40** [comment]
terminal not even load on my case,i got this when i got few hits last 2 or 2 hours

Oops. Something went wrong.

**Comment by marius11** [comment]
It happened again (2 hrs after I started this thread), this time I noticed that when the hit opened, the modal that has all the rules doesn't show up like it used to do before any hit.

**Comment by pscohn** [comment]
This was an error we faced yesterday during an outage - it should be resolved now, and you won't be blocked for any rejections you have gotten for this error.
