### ISSUE TITLE
Payment step value 8 cent or 4 cent?

### ISSUE THREAD

**Issue by mukikuki** [rainforestapp/tester-chrome-extension#125]
Dear Rainforest Support Team,
Can you please clarify how much is a value o a completed step. Today i noticed in the help section during a test,  that the value o a completed step is 8 cent and plus 4 cent for accepting the job. But when i check the history of completed jobs  i get only 4 cent per step, and i do not get the 4 cent for accepting the test as written in the payment section. I know that there is a commission taken from the contributor channel about 19%, but here is not the case as the payment is listed in the history of tester portal. for example a 17 step completed job i get paid 68 cents meaning 4 cent per step, not 8 cent as described in the help section and not even the 4 cent for accepting the job. I have attached some screenshots to be more clear.
Can you please clarify this issue.
Thank you 
Best Regards
Mukikuki
![step](https://cloud.githubusercontent.com/assets/16766980/14103008/465094a4-f59e-11e5-99d3-03c540edb71b.png)
![17 steps hit id 4359354](https://cloud.githubusercontent.com/assets/16766980/14103014/4c0a0740-f59e-11e5-95a9-80247f98e78d.png)
![17 step on tester portal](https://cloud.githubusercontent.com/assets/16766980/14103027/5635a4e0-f59e-11e5-87af-cd30e89bd2f6.png)

**Comment by marius11** [comment]
It's still 4c per step.

**Comment by pscohn** [comment]
We have not changed payment - this looks like a bug, we'll fix shortly.

**Comment by JPierreS** [comment]
@pscohn  LOL - Interesting bug ;)  Or perhaps someone's idea of an April Fool's joke :dancer: 
Would have been amusing if this bug occurred on April 1st though :dancer:

**Comment by ando100** [comment]
@pscohn  Well, change the payment and you don`t have to take care of this little bug  :) Makes your life easier you know, thank me later  :)

**Comment by nberchev** [comment]
Bug fixed at my terminal.

**Comment by mukikuki** [comment]
Thanks. I noticed that the 8 cent bug was already fixed, will you fix the 4 cent bug for accepting the job? When i have a 7 step job i receive 28 cent for a competed job, not 32 cent as explained in help section.

Thanks again for your quick reply.

**Comment by helloworld111gh** [comment]
I think you only get paid the job accepted bonus if you do the job via
mturk or cf

**Comment by pscohn** [comment]
@mukikuki we will fix this as well very soon - this is left over from when hits were gotten through CrowdFlower directly.

**Comment by helloworld111gh** [comment]
@pscohn Fixing it as in removing the text or paying the bonus (2nd option
preferred)?

**Comment by pscohn** [comment]
@helloworld111gh ;)

In the short term, removing the text. However, I'll discuss with the team whether it's possible to do the 2nd option.
