### ISSUE TITLE
Everytime i get a job from today it stay on a blank page, no oops no job.

### ISSUE THREAD

**Issue by khristianjose** [rainforestapp/tester-chrome-extension#127]
Hi, everytime the plugging gets a new job, the page that opens is on blank, no job on it, and no oops or another message, im putting two screenshots that i looked different from today, i was working yesterday and it was fine.

![sin titulo](https://cloud.githubusercontent.com/assets/17553414/14156580/f9c2abd8-f690-11e5-891a-68bae5d38bd3.png)
![sin titulo2](https://cloud.githubusercontent.com/assets/17553414/14156581/f9fe7564-f690-11e5-954c-b1aab48bafca.png)

**Comment by khristianjose** [comment]
Worker ID 33833144

**Comment by limsanto** [comment]
it's happen to me too, it seems because of the IP address, i try change my internet connection and the problem is solved.

**Comment by jbarber** [comment]
Someone else on your network is being naughty and abusing the service, this message is shown when that happens to prevent the naughtiness.
