### ISSUE TITLE
Bonus payments

### ISSUE THREAD

**Issue by manishflyboy** [rainforestapp/tester-chrome-extension#128]
Recently I had noticed that the some bonus payments are shown in RF history and CF history also but the bonus were not added in clixsense not the task were added. this is happening to me from 5 to 6 day. Anybody facing the same problem. please help.

**Comment by JPierreS** [comment]
There is sometimes a delay in CrowdFlower sending payments to channels.  Payments will show in your inbox and Rainforest history but not received in your channel balance.  These payments will eventually be processed and you should receive them to your balance.  If you did not receive payments within 24h, contact CrowdFlower support (in the case where those payments are non pending and show up in your CrowdFlower inbox).

**Comment by manishflyboy** [comment]
thanks
