### ISSUE TITLE
Failed to take screenshot.

### ISSUE THREAD

**Issue by GreekGuy** [rainforestapp/tester-chrome-extension#129]
I got my first 2 tests today and i couldn't do anything.. I stuck on the first step where you copy paste the url for the job. When i click "Take screenshot" it does not wait for 2-3 sec but it throws me "Failed to take screenshot" so i have to refresh again and again until "You have requested too often for the job" ....

**Comment by ahmedofhell** [comment]
Same problem here.

**Comment by roko777** [comment]
Same problem here.4tests today and i couldn't do anything.(((
![5](https://cloud.githubusercontent.com/assets/16417121/14168458/34e5acca-f72b-11e5-8477-d064fc310b1a.jpg)

**Comment by helloworld111gh** [comment]
screenshot is sending req to
*https://tester.rainforestqa.com/tester/assignment/crowd_flower
<https://tester.rainforestqa.com/tester/assignment/crowd_flower>*/
tester.rainforestqa.com/public/v1/machines/x/screenshots/?job_id=x
bold part is broken part

**Comment by mukikuki** [comment]
same here with 2 test , cannot take screenshot

**Comment by mojenLXXXIII** [comment]
Although its showing that All Systems Operational.

 https://status.rainforestqa.com/

**Comment by diabolic012** [comment]
Same here, several lost jobs because I am unable to take screenshoot.

**Comment by ZoiaCosmo** [comment]
Same here, 4 lost jobs because I am unable to take screenshoot.

**Comment by mdmunabbir** [comment]
Still no solution
Same here, several lost jobs because I am unable to take screenshoot.

**Comment by JPierreS** [comment]
@helloworld111gh  There is a 404 condition, a resource is not found  - Looks like they probably changed the path / but something was not updated to reflect the change.

**Comment by jbarber** [comment]
Hi guys, we're looking into this. If you have any jobs in progress you should stop them and try again.

**Comment by JPierreS** [comment]
@jbarber Thank you - things are back to normal now. (so far) :)

**Comment by jbarber** [comment]
We found the problem and fixed it, thanks for the heads up guys!
