### ISSUE TITLE
You are using any but need to use safari.

### ISSUE THREAD

**Issue by nerdatwork** [rainforestapp/tester-chrome-extension#13]
As you can see in the screenshot I am using safari but it still wont let me work on the job

![image](https://cloud.githubusercontent.com/assets/15882196/11201600/7af38f88-8d05-11e5-8714-ec7cf56cfbd1.png)

**Comment by pscohn** [comment]
There is already an issue open for this - see https://github.com/rainforestapp/tester-chrome-extension/issues/10. You may repost your screenshot there if you like.
