### ISSUE TITLE
Microsoft Office missing

### ISSUE THREAD

**Issue by marius11** [rainforestapp/tester-chrome-extension#131]
Hello,

In a hit I have received earlier, I was asked to open a .csv file, but the terminal didn't have Microsoft Office installed.

Terminal ID: 9708549

**Comment by GreekGuy** [comment]
You can open them with notepad, csv files are like text files..

**Comment by qpPykT** [comment]
What about files format .xlsx or .pdf. If we don't have "Microsoft Office" or "PDF viewers".

**Comment by marius11** [comment]
@GreekGuy I opened the file in WordPad, but the problem was that the Excel file had a lot of columns, making it very difficult to read.

**Comment by nihlathar** [comment]
If there is no explicit explanation for how you are supposed to do something (navigate through the OS to find a program etc), then you just report you were unable to open it and that's it.

**Comment by nerdatwork** [comment]
It is for the same reasons like these the TEST NOTES option is provided and I would like to suggest to use that option to let the Test owner/author(person posting the job) know what issues the (testers) you are facing.

**Comment by marius11** [comment]
@nerdatwork Test notes was not enabled for that test.

**Comment by nerdatwork** [comment]
@marius11 in that case you are in a pickle. In my understanding Rainforest are just providing a platform for websites to be tested. The test owner/author decides what to ask whether to ask to download csv or xls or pdf file. I maybe wrong but lets see what RF staff says.
