### ISSUE TITLE
Terminal Does not Load

### ISSUE THREAD

**Issue by Deepak0988** [rainforestapp/tester-chrome-extension#132]
The terminal does not load and finally got the message, job abandon

**Comment by ahmedofhell** [comment]
Same here.

**Comment by androwg** [comment]
@pscohn  @jbarber right now it is not working it gives a black screen even you wait a long time 
![4](https://cloud.githubusercontent.com/assets/15823279/14286343/ff6d0282-fb4e-11e5-968f-bbd7db617334.png)

**Comment by pscohn** [comment]
@androwg did you try interacting with the terminal before refreshing? It's possible there's a screensaver, or clicking in it will kick it in gear

**Comment by androwg** [comment]
@pscohn sure but it didn't give any sense i lost the hit that i posted its link and when i received another hit it is the same after 4 refreshes , terminal worked.

**Comment by Deepak0988** [comment]
In my case I tried clicking on the terminal, But it remains freeze

**Comment by JPierreS** [comment]
Actually it may not be frozen.  How long do you wait before refreshing ? In some cases it might show a black area but will eventually appear - try giving it some time before restarting.

**Comment by Deepak0988** [comment]
waited for the max time rainforest provide for a hit, and eventually lost the hit
