### ISSUE TITLE
Error daily payment bonus % 10

### ISSUE THREAD

**Issue by philips13** [rainforestapp/tester-chrome-extension#133]
Hello
I want to report an error with bonus payment of 10% daily , because in my case I have paid the same bonus 32 times in one day .
They could tell me how I should proceed in this case? I understand that I am not the only user who happened to him .
I am looking forward to your response. Thank you

**Comment by ahmedofhell** [comment]
Same happened with me.

**Comment by qpPykT** [comment]
I have a similar situation here. A few hours ago, it was a lot of payment at the same time. This has never happened before.

![rf-n-bux](https://cloud.githubusercontent.com/assets/4960092/14224811/3a262c22-f8b2-11e5-8415-3aee875b975b.jpg)

**Comment by shrestha15207** [comment]
same here..donno what is going on..already sent a support ticket.

**Comment by Dolazim** [comment]
Omg how this happend I think this i crowdflower missake not rainforest but very crazy mistake you get 34,56$ for noting :D

**Comment by kamrishwwzj** [comment]
Today at 06:08	60483368	Test A Web Application Using Any Browser	
$0.42
Today at 06:08	60483362	Test A Web Application Using Any Browser	
$0.42
Today at 06:08	60483354	Test A Web Application Using Any Browser (and 1 other job)	
$0.85
Today at 06:08	60483347	Test A Web Application Using Any Browser	
$0.42
Today at 06:08	60483342	Test A Web Application Using Any Browser	
$0.42
Today at 06:08	60483336	Test A Web Application Using Any Browser	
$0.42
Today at 06:08	60483331	Test A Web Application Using Any Browser	
$0.42
Today at 06:08	60483323	Test A Web Application Using Any Browser	
$0.42
Today at 06:08	60483317	Test A Web Application Using Any Browser	
$0.42
Today at 06:08	60483310	Test A Web Application Using Any Browser	
$0.85
Today at 06:08	60483299	Test A Web Application Using Any Browser	
$0.42
Today at 06:08	60483294	Test A Web Application Using Any Browser (and 1 other job)	
$0.85
Today at 06:08	60483287	Test A Web Application Using Any Browser	
$0.42
Today at 06:08	60483279	Test A Web Application Using Any Browser	
$0.42
Today at 06:08	60483272	Test A Web Application Using Any Browser	
$0.42
Today at 06:08	60483261	Test A Web Application Using Any Browser	
$0.42
Today at 06:08	60483256	Test A Web Application Using Any Browser	
$0.42
Today at 06:08	60483249	Test A Web Application Using Any Browser	
$0.42
Today at 06:08	60483245	Test A Web Application Using Any Browser (and 2 other jobs)	
$1.27
Today at 06:08	60483241	Test A Web Application Using Any Browser	
$0.42
Today at 06:08	60483235	Test A Web Application Using Any Browser	
$0.42
Today at 06:08	60483229	Test A Web Application Using Any Browser	
$0.42
Today at 06:08	60483223	Test A Web Application Using Any Browser	
$0.42
Today at 06:08	60483215	Test A Web Application Using Any Browser	
$0.42
Today at 06:08	60483207	Test A Web Application Using Any Browser	
$0.85
Cancel

**Comment by mdmunabbir** [comment]
I've also been paid. Is this an error?

**Comment by jitsatya** [comment]
Not paid here. Horrible glitch

**Comment by ecliptica777** [comment]
same problem. I hope it will not affect the rainforest. CF need to adjust the balance
[img]https://pp.vk.me/c629514/v629514959/40f36/7tPjdUmC-Wk.jpg[/img]

**Comment by GreekGuy** [comment]
Same here!! I can see the daily bonus as pending in my history on my rainforest account and i was paid 30+ times in crowdflower

**Comment by nummuss** [comment]
same problem

01 Apr 2016 21:08 EST	Test A Web Application Using Any Browser	$0.4900
01 Apr 2016 21:08 EST	Test A Web Application Using Any Browser (and 2 other jobs)	$1.4700
01 Apr 2016 21:08 EST	Test A Web Application Using Any Browser	$0.4900
01 Apr 2016 21:08 EST	Test A Web Application Using Any Browser (and 1 other job)	$1.9500
01 Apr 2016 21:08 EST	Test A Web Application Using Any Browser	$0.4900
01 Apr 2016 21:08 EST	Test A Web Application Using Any Browser	$0.4900
01 Apr 2016 21:08 EST	Test A Web Application Using Any Browser (and 1 other job)	$0.9800
01 Apr 2016 21:08 EST	Test A Web Application Using Any Browser (and 1 other job)	$0.9800
01 Apr 2016 21:07 EST	Test A Web Application Using Any Browser (and 1 other job)	$0.9800
01 Apr 2016 21:07 EST	Test A Web Application Using Any Browser	$0.4900
01 Apr 2016 21:07 EST	Test A Web Application Using Any Browser	$0.4900
01 Apr 2016 21:07 EST	Test A Web Application Using Any Browser (and 1 other job)	$0.9800
01 Apr 2016 21:07 EST	Test A Web Application Using Any Browser (and 1 other job)	$0.9800
01 Apr 2016 21:07 EST	Test A Web Application Using Any Browser	$0.4900
01 Apr 2016 21:07 EST	Test A Web Application Using Any Browser	$0.4900
01 Apr 2016 21:07 EST	Test A Web Application Using Any Browser	$0.4900
01 Apr 2016 21:07 EST	Test A Web Application Using Any Browser	$0.4900
01 Apr 2016 21:07 EST	Test A Web Application Using Any Browser (and 2 other jobs)	$1.9500

**Comment by CliX-er** [comment]
Same here but I can't send them a message because the green "help" button in the bottom right corner of my profile doesn't work. Neither the e-mails sent to tester@rainforestqa.com...

**Comment by nihlathar** [comment]
I thought this was bonus for some of the missing payments past few days. So what happens now?   ..

**Comment by nerdatwork** [comment]
Rainforest staff is probably enjoying family time on their weekends and they will respond as soon as they start work on Monday. I am humbled how many honest testers I have the pleasure to work with. Keep up the good work guys.

**Comment by GreekGuy** [comment]
Its better to say the truth instead of having your account banned from rainforest

**Comment by Aleksandar85** [comment]
Yes it is, i also got a bonus about 10$

**Comment by irj9** [comment]
I got this too, I was thinking that it might be an end of the financial year thing, but now I am very concerned that it's an error. The website that I receive my payment through gave me a bonus for the extra payment, I hope I don't get into trouble for this!

**Comment by uangonline** [comment]
Same happened to me. But since i open my elite id before i open the rainforest id, i already ask for withdraw, but it still in pending state though. Maybe someone can adjust the withdraw?

**Comment by nerdatwork** [comment]
Big Bonuses 2016-04-04 13:30:47 UTC, Kristen Hohenstein
**Hello! We had an issue over the weekend with bonus payments being multiplied by 30. Thank you to everyone who reported it! I will post an update when I have more information.**

Please refer to: [https://portal.rainforestqa.com/](url)

**Comment by ecliptica777** [comment]
Update: All issues from Friday with Bonuses have been resolved. If you have any issues, please let us know! :)

___________________________________
how the issue was resolved? I don't see any changes in the balance.

**Comment by kristen-allie** [comment]
Hello @ecliptica777  and everyone else! People affected by the bug will be emailed an update about their balance by the end of they day. Thanks for your patience as we worked out the issue!

**Comment by philips13** [comment]
It has already reached my email confirmation , I guess other users too, so I close the subject.

thanks to the team Rainforest!!!

**Comment by kristen-allie** [comment]
You're welcome @philips13! A lot of people might not receive the email until later today -- this doesn't mean we forgot you! Just takes time :)
