### ISSUE TITLE
Rainforest is so awesome!!!

### ISSUE THREAD

**Issue by uangonline** [rainforestapp/tester-chrome-extension#134]
Friday Over-Bonus from Rainforest Hi gwbanget! On Friday we accidentally overpaid bonuses to you and a small number of workers by a lot more than normal. This was due to a bug in Rainforest’s code, which has since been fixed. A number of you have contacted us, offering to refund it - we are overwhelmed by this honesty, and we have decided you should keep the extra bonuses as a gift from Rainforest. Thanks for being awesome! <3 Russ Co-founder and CTO Rainforest QA p.s. you can use our Chrome Extension to find work quickly; https://portal.rainforestqa.com/tester/b9bbbead-6028-4297-86b5-6667d9037aee

I just got the above email just now... And i really surprise by Rainforestqa kindness. Thanks a lot and long life Rainforstqa.

**Comment by nummuss** [comment]
Thanks a lot and long life Rainforstqa.

**Comment by pscohn** [comment]
:)
