### ISSUE TITLE
Security Error (Error#2048)

### ISSUE THREAD

**Issue by Hanifmamun** [rainforestapp/tester-chrome-extension#135]
I lost a hit because of this error. It says "an security error occured (error#2048) check your policy-policy server configuration. I refreshed the hit but same error appeared all the time. 
![error](https://cloud.githubusercontent.com/assets/18037395/14290760/3519c572-fb82-11e5-85c5-b9dd65d7e8d5.jpg)

**Comment by limsanto** [comment]
It severally happen to me too, send ticket to Rainforest and after checking by them, their answer is nothing wrong in their side.
Try to change the encoding and clear browsing history, many times it help.

**Comment by JPierreS** [comment]
Are you using your home connection or office ? Something on your end is blocking communication.  Are you using adblockers, script blockers, firewall ?

**Comment by marius11** [comment]
If I use my university's WiFi (or broadband) connection (which has some ports blocked) I receive the same error. This error doesn't appear if I use my connection at home.

**Comment by Hanifmamun** [comment]
I never used ad-blockers, script blockers or firewall.

**Comment by jbarber** [comment]
Your computer must be able to reach port 843 on the servers. If it can't then the terminal will display this message. This is a security requirement of the terminal client.
