### ISSUE TITLE
The test is not noted in history, ALSO NO BONUS

### ISSUE THREAD

**Issue by roko777** [rainforestapp/tester-chrome-extension#136]
3 tests were left without payment. They do not exist in history. final test by 35 steps
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx23b7b4-4e43-41fa-af73-24c00da2bd00&browser=any&hitId=4447600&sig=5cce387a4b2bb7df5e1cfd13560eee7560efb97936ff71213193a5d484b3bd31&turkSubmitTo=%2Fthanks&workerId=6594279

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cxd2bff2-e6c8-437e-b5f1-9fa2528c32ec&browser=any&hitId=4527956&sig=42f40ce08fe796b8818cd1e29cb3ccaa3a0fe9043e485c19a5bfde0168899d1a&turkSubmitTo=%2Fthanks&workerId=31275106

**Comment by marius11** [comment]
When you submit a hit, it doesn't always appear immediately in the history tab. You should wait at least 30 minutes before asking help.

Speaking of help, you should use the help link from your Rainforest profile. This forum is used to address issues with the extension, and not individual problems.

**Comment by roko777** [comment]
It has already passed more than 2 hours

**Comment by pscohn** [comment]
Please use the help form for these individual history/bonus issues.
