### ISSUE TITLE
Why the new No button ack strange?

### ISSUE THREAD

**Issue by uangonline** [rainforestapp/tester-chrome-extension#137]
The "No" button for the security question such as "Find Salmon Egg on the page" etc2, ack strange. When click on the button a popup for a reason came up and must click the report button. But the most strange things is it send me to the finish button and can't continue to the next step.

**Comment by shrestha15207** [comment]
same here...whats wrong?? should we report the test questions now??

**Comment by pscohn** [comment]
This has been fixed, though you may have to refresh the page if you still see this issue.

**Comment by helloworld111gh** [comment]
Authors can set questions so that no is correct answer
