### ISSUE TITLE
New modification on tester interface

### ISSUE THREAD

**Issue by pvenkat7** [rainforestapp/tester-chrome-extension#138]
New modifications on tester interface are simple and concise. The only bug is "**No**" button has no control over security checks (if we click no for those checks it require to report and leave other steps).
In my opinion you can modify it like "**Other**" which has two choices. Means when we click "**No**" it opens pop up with two choices to choose either "**Not exact instructions**" or "**security check**"

**Comment by pscohn** [comment]
Thanks for reporting and your feedback @pvenkat7 - it should be fixed now!
