### ISSUE TITLE
Invalid parameter:Crowd_Flower

### ISSUE THREAD

**Issue by Deepak0988** [rainforestapp/tester-chrome-extension#139]
Got an error today 
Here is the link for the error 
"Invalid parameter:Crowd_Flower"
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx168c5e-f951-485c-94c9-b05e83b43c0a&browser=any&hitId=4623090&sig=3ba26aaf40f69e772ddc2a83e57d53d70fcf0a78bf3816c19d2e7b7778791bd2&turkSubmitTo=%2Fthanks&workerId=32687648

**Comment by pscohn** [comment]
We've rolled back the buggy code, this is now fixed. Thanks for reporting!
