### ISSUE TITLE
Unable to get any job loaded properly

### ISSUE THREAD

**Issue by nerdatwork** [rainforestapp/tester-chrome-extension#14]
Everytime I get a notification for new job I encounter either the browser mismatch error or this error.

You have reached the maximum number of unsubmitted assignments. So we are fair to other workers, we stop you doing too much for us at once. You can complete the other assignment(s) and refresh this page, or simply return this hit.

What is wrong with it ?

**Comment by nerdatwork** [comment]
What does "Invalid state" mean ? after loading the url inside the terminal.

**Comment by ando100** [comment]
It means your timer ran out, 10 min/ 15 min. Check the rules. But it`s small problem, Whole site is having problems yesterday and today. App errors all over. I really do hope it gets fixed and maybe someone drops a line- what`s going on and why?

**Comment by nerdatwork** [comment]
Instead of posting just on the job, I think the rules must be on the portal too.

**Comment by nerdatwork** [comment]
Ooops: another worker accepted the job before you! It doesn't look like there is any more work for any of our hits; please try again shortly - you can refresh this page, or return this hit.

Story of my life. Out of 20 notifications of a job, 19.5 of them end up showing the above message and the 0.5 is the one that actually loads but by the time I reach the step 3 or 5 of it, its already been submitted. Talk about height of frustration :(

I think it could be a geographical reason. By the time I get a notification someone somewhere closer to the server has already submitted the job. I maybe wrong but lets see what the developers have to say.

**Comment by nihlathar** [comment]
People have ways to beat others to the tasks and there arent that many available so we and up with nothing. Yesterday I had the same situation as you, many tasks available but all with some sort of error. Anyway, if you got the task and you can work on it then you will be able to submit it and get paid for it (unless you are idle for more than 15 minutes during the task, or dont accept it within 60min)

**Comment by nerdatwork** [comment]
I disagree that if I get a job I always get to submit it. There are instances where it takes forever for the screenshot to be taken or the page inside the terminal to load. There I am waiting on the terminal to respond back and by the time I get to the next step that job has already been submitted since the screenshot button wont work and if I refresh the page I get the annoying "This assignment was already submitted....." message.

**Comment by nihlathar** [comment]
It's true the screenshot reporting doesnt always work, but then you can refresh the terminal and get a new one (in case of other problems too). Usually helps.

**Comment by ando100** [comment]
@nerdatwork : I think the rules must be on the portal too-

holy grail is coming towards you:
https://tester.rainforestqa.com/guide/
:)

**Comment by nerdatwork** [comment]
@ando100 Thank you but I think it would be logical if it was shown as a button/tab on the tester profile here: https://portal.rainforestqa.com/tester/(tester id) Since the guide is seen only through that link.

**Comment by nihlathar** [comment]
I now realized you're right.. it's a new problem with the task submitting itself before you finish, didn't have it before. Errors just keep piling up

**Comment by nerdatwork** [comment]
@nihlathar who is right and about what. I didnt follow you there.

**Comment by nihlathar** [comment]
Well you of course. Last 2 days I had the same problem with the "task's already been submitted" message. When you refresh it should give you a new terminal but lately that doesn't always happen. They already promised to take care of it so we just need to wait

**Comment by nerdatwork** [comment]
All day for last 2 days I am getting this:
You have reached the maximum number of unsubmitted assignments. So we are fair to other workers, we stop you doing too much for us at once. You can complete the other assignment(s) and refresh this page, or simply return this hit.

When no other rainforest window is open. This makes no sense

**Comment by nihlathar** [comment]
You may want to restart pc, reinstall extension, and relog on your RFQA account. Might help.

**Comment by pscohn** [comment]
@nerdatwork what is your worker ID?

**Comment by nerdatwork** [comment]
@pscohn What will that do ?

**Comment by pscohn** [comment]
@nerdatwork it can help us debug the issue by looking into your Rainforest account. If you want to send it privately you can send a message to tester@rainforestqa.com referencing this conversation.

**Comment by nerdatwork** [comment]
@pscohn done, email sent. Thank you.

**Comment by nerdatwork** [comment]
@nihlathar I did that but still get the same annoying "another worker....." message I havent got a job in 3 to 4 days but about 100 notifications of a job :(

**Comment by Savan47** [comment]
I have this problem too! It's so annoying, i sent email yesterday but still not response.

**Comment by qpPykT** [comment]
Sometimes I get the same error message.

**Comment by begsoon** [comment]
Same here!

**Comment by nerdatwork** [comment]
Remember the time when you get a YES notification and you find this message: 
Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

over and over and over for over 30 mins.... yes I dont like it at all :(

**Comment by nerdatwork** [comment]
Application error all day long since 2 days. So annoying :-1:

**Comment by Genesis2015** [comment]
Same annoying problem here :-1:

**Comment by pscohn** [comment]
Closing as there are other issues that cover specific errors.
