### ISSUE TITLE
Invalid parameter: crowd_flower

### ISSUE THREAD

**Issue by ahmedofhell** [rainforestapp/tester-chrome-extension#141]
"Invalid parameter: crowd_flower" This message appeared instead of "Another worker accepted the job before you! It doesn't look like there is any more work for any of our hits; please try again shortly - you can refresh this page, or close and wait for a new job." message!

**Comment by nummuss** [comment]
Same: Invalid parameter: crowd_flower

**Comment by Dolazim** [comment]
Same there...

**Comment by roko777** [comment]
the same as in the new work

**Comment by BonesKnows** [comment]
same here

**Comment by mkdige** [comment]
yup same here Invalid parameter: crowd_flower

**Comment by kwimy** [comment]
Another more with the same issue.

**Comment by akvinod** [comment]
same here

**Comment by pscohn** [comment]
Thanks for reporting - we're looking into this now.

**Comment by nuevao** [comment]
same here

**Comment by obiwanke** [comment]
Hey Obi there... The same problem =)

**Comment by Dolazim** [comment]
Problem is fix ty... :)

**Comment by ahmedofhell** [comment]
Problem Solved!

**Comment by pscohn** [comment]
Thanks for reporting so quickly - we've rolled back the buggy code!
