### ISSUE TITLE
Abandoning Hit because of "take screenshot" VS "Click to Take Screenshot"

### ISSUE THREAD

**Issue by Hanifmamun** [rainforestapp/tester-chrome-extension#143]
In the beginning of a hit it asks "take screenshot" but I see "Click to Take Screenshot". What should I do? Abandon the hit or proceed by ignoring it? You know there is no button to report. I am asking this because it is not included in wiki's frequently asked questions about the new rules.

**Comment by pscohn** [comment]
We have fixed this and you should see the text updated in the next 5-10 minutes.
