### ISSUE TITLE
3 bonus payment instead of one

### ISSUE THREAD

**Issue by chmi16** [rainforestapp/tester-chrome-extension#144]
Hello,
I have received 3 bonus payment instead of one.Other payments are ok.
I also send you message from RF test portal with more details (copy of messages).

**Comment by nerdatwork** [comment]
@chmi16 Rainforest already emailed all testers regarding this so I recommend closing this thread.

**Comment by luisdanielvc** [comment]
Lucky you

**Comment by marius11** [comment]
@nerdatwork This post is two months old and it should have been closed by now.

**Comment by pscohn** [comment]
We have also released a fix that should stop multiple payments.
