### ISSUE TITLE
Errors errors so many errors..

### ISSUE THREAD

**Issue by GreekGuy** [rainforestapp/tester-chrome-extension#147]
Server errors again and again i can not get tests  [http://prnt.sc/asd9m0](http://prnt.sc/asd9m0).. Anyone has the same problem?

**Comment by manishflyboy** [comment]
yes. same here. it is started around 2200 hrs IST.

**Comment by pscohn** [comment]
This may have been an intermittent outage - is it better now, can this be closed?

**Comment by GreekGuy** [comment]
I am still getting some Errors Something went wrong but its okay you can close it. Thank you.
