### ISSUE TITLE
Payment accumulated

### ISSUE THREAD

**Issue by rojita7** [rainforestapp/tester-chrome-extension#148]
Since yesterday, I have accumulated payments.
Does anyone happens the same?

**Comment by Genesis2015** [comment]
Same to me - more then 20 pending payments :(

**Comment by khristianjose** [comment]
same here, like 10 jobs in pending payments.

**Comment by BonesKnows** [comment]
same here

**Comment by pscohn** [comment]
This was due to an error in processing Crowdflower payments - it should be fixed now.
