### ISSUE TITLE
Only can hit "Yes" if screenshot error

### ISSUE THREAD

**Issue by helloworld111gh** [rainforestapp/tester-chrome-extension#149]
If there is a screenshot error, the no and other buttons get locked and you can only press "Yes"

**Comment by pscohn** [comment]
@helloworld111gh Did this happen on a particular test or step that you can recall?

**Comment by lilymar** [comment]
Same thing but all buttons stuck. Terminal 10665388, "Paperlesspost", ID 34867195

**Comment by pscohn** [comment]
This is a bug on the frontend - until we fix it, you should be able to solve the problem by typing any character in the "report problem" textbox and then deleting it.
