### ISSUE TITLE
Hit xxxx cannot have new jobs assigned to it.

### ISSUE THREAD

**Issue by androwg** [rainforestapp/tester-chrome-extension#15]
Sometimes when i get a hit from the extension it says 
Hit xxxxxx cannot have new jobs assigned to it.(xxxx means any numbers)
It wasn't like this in the past

**Comment by nerdatwork** [comment]
I get the same message its like -
Hit 4564280 cannot have new jobs assigned to it.

**Comment by KabakF** [comment]
@ukd1 I'm getting same error very often for two days, my extension finds jobs rarely and job is being with an error(Hit xxx cannot have new jobs assigned to it)

I was getting much more jobs so I wonder Is it special to me or just less running test?

**Comment by ukd1** [comment]
@androwg @nerdatwork this is a bug at our end - can you give me your worker ID and Hit ID and we'll fix?

**Comment by nerdatwork** [comment]
hitId=4570330 with following message: Ooops: another worker accepted the job before you! It doesn't look like there is any more work for any of our hits; please try again shortly - you can refresh this page, or return this hit.

**Comment by KabakF** [comment]
@ukd1 Russ I was checking old jobs to find if there available one, now" It says me you have reached the max. ....  we have to be fair to other workers" but really I didn't complete even one job, I think it's a small bug.
( My Worker ID: 35273503 )

[ also, Hit 4614869 cannot have new jobs assigned to it. ]

**Comment by AlexandruVerenca** [comment]
I also have this problem. Worker ID: 34555717  Hit 4487432

**Comment by nummion** [comment]
Hi 
I have same problem
Hit 4338042 Worker ID:32387530

**Comment by JPierreS** [comment]
@ukd1 @pscohn I am seeing this error message from time to time from hits from the extension.  Also noticed that HIT IDs are being used more than once, is this normal / intentional ? In my history I see several JOBs listed under the SAME HIT ID !  Is this why we are seeing this error, that a HIT ID can only be assigned a certain number of times ?   mind you it is not as frequent as before, but I do see it from time to time  still.

**Comment by pscohn** [comment]
@JPierreS it is normal for the same Hit Id to be used more than once.

**Comment by pscohn** [comment]
We've found a possible cause for this problem and the fix will be out within the next few hours.
