### ISSUE TITLE
There are no virtual machines currently available. Please retry in a few minutes.

### ISSUE THREAD

**Issue by ahmedofhell** [rainforestapp/tester-chrome-extension#150]
**"There are no virtual machines currently available. Please retry in a few minutes."** This message appeared instead of **"Another worker accepted the job before you! It doesn't look like there is any more work for any of our hits; please try again shortly - you can refresh this page, or close and wait for a new job."** message!

**Comment by pscohn** [comment]
This is a new message to clarify why the job didn't load in some cases. Previously it would just show "Another worker" even if the reason was that we ran out of VMs. Now the error is more specific in those cases.

I'll leave this open for now for visibility, but this is not actually a new error.

**Comment by ahmedofhell** [comment]
Thanks @pscohn It's changed to "Another worker" again.

**Comment by pscohn** [comment]
You should see both messages from time to time, depending on why you didn't get the job :)

**Comment by ahmedofhell** [comment]
Yes, Got it! :)

**Comment by roko777** [comment]
There are no virtual machines currently available. Please retry in a few minutes.?????what is it?

**Comment by marius11** [comment]
@roko777 Tester are required to use the terminal in order to complete hits. If there aren't enough terminals, you will receive that message.

**Comment by helloworld111gh** [comment]
Shouldn't terminals be dynamically started based on demand? Pretty sure
it's better to have less workers waiting for terminals and more workers
doing the tests.

**Comment by hunt40** [comment]
this system have to change ,like i did maybe 6 test today,some people on forums said he did 35 and 40 task respectively in 2 days,whos have fast internet then other got way more test.this is since late november and looks like its keep going as like this.

**Comment by NeoWorker** [comment]
I agree with @hunt40, it's not very nice when you're doing something in the Internet, watching a video, playing games on browser and have to stop everything just to receive error messages in a new tab.

**Comment by roko777** [comment]
It used to be a lot of work, but now it is almost there (((unfairly

**Comment by braneb** [comment]
Its not unfair...some people work more, sleep less and have a bit more luck...like every other task, we didnt get promise to have much work as we want to...i wish that there is much more work for all of us, someday it may be, but for now thats how it is

**Comment by hunt40** [comment]
to be honest i have no job so i am doing this and other tasks and sitting on pc and looking this screen 15-16h everday and when i see 30-40 time oops or any other error you'll getting frustared,angry,and i know this is crouwdsource stuff there is no fairness at all and this test differnt then other tasks but this is getting out of hand when other people talk like on forums saying like ''i did 25+ test today haha.'' this affect me and my mood,while i keep seeing red error screen most of the time.

**Comment by JrRandy** [comment]
Any way to reserve the job for the worker who got the "No VM's available" message?  Nothing more annoying than finally getting work, there not being a VM available, and then losing that job to someone else after trying to get a VM to work in.

**Comment by srsaurabh32** [comment]
No VM's available is the most irritating message i ever see, as you still believe that there are chances you will get work on refreshing but no 90% of the refreshes you will be disappointed.
