### ISSUE TITLE
New operating systems - issues with Linux/Windows 10

### ISSUE THREAD

**Issue by marius11** [rainforestapp/tester-chrome-extension#151]
On Linux based machines, scrolling will toggle the desktop selector which might hide the browser.

~~Also, on Windows 10, some licenses are about to expire and the browsers are not maximized by default when the terminal starts up.~~

**Comment by ukd1** [comment]
@rainforestapp/tester-product ?

**Comment by marius11** [comment]
I've done a test on a Linux machine today and experienced the same issue. While scrolling the page to complete a form, the screen went dark grey and a desktop selector (having 4 desktops to choose from) appeared on the screen.

**Comment by gallois** [comment]
Fixed in upstream. Next Linux VM updates will have scroll on titlebar and scroll to change desktop disabled.
