### ISSUE TITLE
How do I register a new account Rainforest?

### ISSUE THREAD

**Issue by Begushhij** [rainforestapp/tester-chrome-extension#154]
Correspond with crowdflower useless. 
I can to re-register a new account Rainforest?
Discussion topics: https://github.com/rainforestapp/tester-chrome-extension/issues/146#event-633484051

**Comment by marius11** [comment]
https://github.com/rainforestapp/tester-chrome-extension/issues/24

**Comment by Begushhij** [comment]
A little history: 
I had a clixsense account, and accordingly account for rainforest, but I had to close clixsense account. Now I registered a new account clixsense. Tied account crowdflower, but each new binding account CF give a new channel ID, which does not match the account rainforest.

**Comment by cambinator** [comment]
I have same problem, I created new neobux account and get new channel ID. Support responds that I have to wait until I complete one job directly through CrowdFlower in order to use my new ID. And it's currently very difficult according to thread #24

**Comment by pscohn** [comment]
When #24 is closed (which we're working on) you'll be able to get a job and create a new rainforest account.
