### ISSUE TITLE
An annoying problem

### ISSUE THREAD

**Issue by GersonTavare** [rainforestapp/tester-chrome-extension#157]
Hey guys, anyone can help me?

A few days ago - about 5 - I started to receive a strange error. 

![toqxq4zvjia](https://cloud.githubusercontent.com/assets/17014154/14856254/c45e1e44-0c6d-11e6-95da-7a344b16fdad.jpg)

I have no idea what caused it. I didn't change anything on my computer or on my internet. The windows firewall is enabled, but I think it is not blocking the rainforest site. I called my internet provider and everything seems to be normal. 

Has anyone experienced this error? Does anyone have an idea what I can do? 

Since now, thank you all and have a great day!

**Comment by Hanifmamun** [comment]
Reload the Hit works for me sometimes it is not. I think it is terminal
security issue not your browser or ISP problem. I opened a thread on this
issue few days ago but did not get satisfactory answer.

**Comment by GersonTavare** [comment]
Hi, Hanifmamun. Thanks for the response. I tried to send an email to Rainforest support but also not received any satisfactory answer. My problem is that I receive everytime this message, so I need reload the page several times and I lost a lot of time in a single hit. Hope they get a solution to our error.

**Comment by MarinaCec** [comment]
Reload the Hit works for me, sometimes it is not.

**Comment by pscohn** [comment]
This is a pretty rare error and refreshing should help - added some information here https://github.com/rainforestapp/tester-chrome-extension/wiki/Troubleshooting-&-Common-Errors-Explained.
