### ISSUE TITLE
Terminal problem, help

### ISSUE THREAD

**Issue by MarinaCec** [rainforestapp/tester-chrome-extension#160]
I have received this message "Your job cannot be completed. Plese reload the page and try again"... So, when I reload the page be all white without test, and again, and again... I lost a few tests today with this problem. Is an error in my browser something like that or is a rainforest error, maybe the terminal?
![sem titulo1](https://cloud.githubusercontent.com/assets/18725046/14896459/3dc79ae4-0d54-11e6-8749-e8b83cb53dc0.png)

**Comment by pscohn** [comment]
This could be a network error - I don't see any errors on our end. If you see it again, can you check the chrome developer console and network tab and take screenshots of any errors you might see? @MarinaCec

**Comment by MarinaCec** [comment]
@pscohn ok, I'll see, thanks for help.

**Comment by manishflyboy** [comment]
The same thing happens to me also

**Comment by pscohn** [comment]
Added some info here - https://github.com/rainforestapp/tester-chrome-extension/wiki/Troubleshooting-&-Common-Errors-Explained
