### ISSUE TITLE
Add an example about wrong redirect to the "Confusing Scenarios"

### ISSUE THREAD

**Issue by maciejgryka** [rainforestapp/tester-chrome-extension#162]
@kristen-allie Here's something that we might want to add to https://github.com/rainforestapp/tester-chrome-extension/wiki/Guide-Rules:-Confusing-Scenarios

`If you get redirected to a page that does not allow you to perform a specified action, answer No. Do not do anything that's not asked for in the instructions, including navigating back to the previous page. If you cannot follow instructions exactly, answer No.`

(This already assumes the new rules, i.e. answering No instead of Other. We might want to hold of with this until next week.)

Context: in [one of our recent runs](https://app.rainforestqa.com/runs/64398/tests/34018?show[]=failed) we had a mistake, where testers were wrongly redirected away from a page. Of 3 browsers, only 1 JobGroup failed - the rest incorrectly passed the test by navigating away from the page they were redirected to.

/cc @prayogoa

**Comment by kristen-allie** [comment]
@maciejgryka I'll add this when the updated "yes" "no" rules go into effect since I'll be revamping the whole "confusing scenarios" page when that happens!

**Comment by nberchev** [comment]
But the instructions of some similarly created tests do not offer Yes/No possible answer of the question asked, more like Other/ couldnt follow instr. How we have report for now - No or Other?

**Comment by nerdatwork** [comment]
@maciejgryka I hope your issue was addressed by our awesome Miss Kristen and if you are satisfied with the reply I kindly urge you to close the thread so Rainforest can address other open threads.

**Comment by maciejgryka** [comment]
Indeed, thanks for pointing it out @nerdatwork!
