### ISSUE TITLE
Sometimes no terminal appears in the box

### ISSUE THREAD

**Issue by helloworld111gh** [rainforestapp/tester-chrome-extension#163]
Sometimes the terminal box just doesn't have anything in it, or a black box appears for a moment then it disappears. There is no error message.
Image: http://puu.sh/oErLh/dfd3f6bb85.png
URL: https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cxbb32c7-1ea3-4f07-ad75-280d474c6fc3&browser=any&hitId=4151004
Console; http://puu.sh/oErPC/cd8bd5a192.png

**Comment by helloworld111gh** [comment]
FYI: I've found that deleting the type parameter in the terminal flash <object> fixes this issue.

**Comment by pscohn** [comment]
Haven't seen any other reports of this, so closing.
