### ISSUE TITLE
"You have reached the maximum number of unsubmitted assignments. So we are fair to other workers, we stop...

### ISSUE THREAD

**Issue by phahoai** [rainforestapp/tester-chrome-extension#164]
![1](https://cloud.githubusercontent.com/assets/19165215/14979648/de0e2444-114d-11e6-8656-52097ae518fb.png)
Hi! I get error message "You have reached the maximum number of unsubmitted assignments. So we are fair to other workers, we stop you doing too much for us at once. You can complete the other assignment(s) and refresh this page, or simply return this hit.". Now i am getting very low hits. Please check help me and solve this problem, thanks. My worker ID is: 33102233

**Comment by Genesis2015** [comment]
I have this message from least one hour ago and I have no new hits :(

**Comment by BonesKnows** [comment]
i have this message 7 hours constantly.

**Comment by BonesKnows** [comment]
i have this message one day constantly i managed to do few hits but after few hits this message again appear and now wont change

**Comment by chmi16** [comment]
In past several days I often have this message even if past more that hour of last hit. Sometimes, during refresh, this message appear instead of  Another worker....

**Comment by BonesKnows** [comment]
extension gives me almost every time link with this message.

**Comment by nerdatwork** [comment]
@BonesKnows I recommend clearing your google chrome cache and if it doesnt work try reinstalling google chrome. I have personally seen this message a few times. I hope that helps.

**Comment by BonesKnows** [comment]
@chmi16 i have same problem. Do you still experience this?

**Comment by chmi16** [comment]
Yes but not so often. I always keep my OS and apps up to date.

**Comment by chmi16** [comment]
Still same situation. Till 1 pm CET all worked fine but now it open new tab with this message. It looks like another worker begin to work at this time and now we are fighting for hit.
I hope that this will be fix soon

**Comment by BonesKnows** [comment]
me 2 but i think there is not many people who are experience this. Its so frustrating

**Comment by BonesKnows** [comment]
i got a reply from RF support 
	
Rainforest Support (Rainforest)
May 24, 13:34

Hello,

You are experiencing this because we have more workers than available jobs. As rainforest grows and adds more customers, we hope this will be less of an issue moving forward. I apologize for the inconvenience in the meantime.

Sincerely,

Rainforest Support

If this is the case why are we getting this "reached" message instead of "another worker"??

**Comment by BonesKnows** [comment]
In my opinion this is unfair...But what can I do...

**Comment by nerdatwork** [comment]
@BonesKnows I dont understand, when the current testers arent getting enough jobs and we still face issues that need to be addressed first. Why are new testers being added ?? Reminds me of the saying, Put the cart before the horse.

**Comment by braneb** [comment]
@nerdatwork im thinking the same as you...when new testers starts working it will be much worse, for us and for RF, more errors,more problems

**Comment by nerdatwork** [comment]
@braneb Exactly. New workers can be recruited any time of any day if there is abundant amount of work for everybody. We all know there are potential testers out there that are willing to work 24/7/365. But to be fair towards current testers, in my opinion the current string of issues need to be addressed before inviting more people to the party. A survey should be sent out asking current testers
Do you want new testers to be recruited/added to Rainforest ? **Yes** or **No** with a textbox to get detailed opinions.

**Comment by marius11** [comment]
Why would anyone ask current testers if they _want_ new testers to be recruited? It's not up to us. If Rainforest has more clients by each week or so, then they will need more testers, and they should invite them without asking us.

**Comment by nerdatwork** [comment]
@marius11 Just for the sake of an opinion what would you answer it as Yes or No ?

**Comment by marius11** [comment]
@nerdatwork My answer would be: Do what it's best to deliver your clients the best service in QA, even if that includes recruiting more testers.

**Comment by nerdatwork** [comment]
@marius11 Exactly my point, opinions do matter and help shape better products. Hence we have a place for suggestions ;) Whatever our opinions are or would be, Rainforest will do whats best for the company there is no doubt in that but having an opinion would surely help ignite new ideas in my humble opinion. Happy testing :)

**Comment by BonesKnows** [comment]
still no solution for my problem..I am experiencing  this problem for 15 days...

**Comment by chmi16** [comment]
Me too. I also got answer from RF support staff that this is by design but I think it is quite unfair. It is very hard to get some work from 01 pm till 7-8 pm and sometimes even later in evening. At least they can change this message to something different when appear when there is more worker that jobs

**Comment by phahoai** [comment]
The problem is not solved in a very long time

**Comment by BonesKnows** [comment]
its unfair,my friends for example dont have this problem at all.

**Comment by nerdatwork** [comment]
@BonesKnows Have you tried, reinstalling Chrome and RF extension ?

**Comment by BonesKnows** [comment]
@nerdatwork Yes i tried but no changes.

**Comment by nerdatwork** [comment]
@BonesKnows Have you ever used CCleaner ?

**Comment by BonesKnows** [comment]
Yes but no help either.

**Comment by BonesKnows** [comment]
wow it is so frustrating

**Comment by nerdatwork** [comment]
@BonesKnows I totally understand your frustration. I humbly urge you to give them time to reply considering the shear amount of support tickets, updates and other work they do. Bumping thread wont help anyone ;)

**Comment by BonesKnows** [comment]
@chmi16 @phahoai Do you guys still experience this?

**Comment by chmi16** [comment]
Yes. Today I haven't see it but that is because almost every hit was direct and there was no need to refresh them. But there was wide gap in tasks from 1pm cet till 7 pm. Maybe I share some id with someone else and only one can do hits? Or after some number of hits I get blocked so someone else can do it? I am hoping that this will be resolved because small number of us have this problem. I am very active (at least 14 h per working day much less in weekends ) so maybe this got to do something with it

**Comment by BonesKnows** [comment]
@chmi16 I dont know,i am hoping too. Does extension giving you links with "reached" message?

**Comment by luisdanielvc** [comment]
I was having this since two hours ago, but now i got a 31 steps job, it's very annonying when that screen appears, even if you have no pending bonuses

**Comment by chmi16** [comment]
@BonesKnows It does sometimes

**Comment by BonesKnows** [comment]
I ask supports again for help and again no solve for the problem they are saying that this is normal. For 15 hours today trying to get work i managed to do 6 hits,if this is normal then ok . I will stop doing this job definitely.

**Comment by marius11** [comment]
Can someone explain why this message appeares? I have received this message 12-16 hours after the last submitted task. It doesn't make sense.

**Comment by nerdatwork** [comment]
@marius11 Please read this:
[]([](https://github.com/rainforestapp/tester-chrome-extension/wiki/Troubleshooting-&-Common-Errors-Explained#you-reached-maximum-of-unsubmitted-applications))

**Comment by marius11** [comment]
I have and it didn't clear up anything. There are probably more cases when this error appears which are not listed in the wiki.

**Comment by nerdatwork** [comment]
@marius11 Have you tried reinstalling Chrome and the extension ?

**Comment by luisdanielvc** [comment]
This problem is horrible, it appears at any moment, i was happy because i did $4 in 30 minutes and after that i was unable to do more thanks to this error, it took almost one hour and ten minutes to disappear, do you guys know how to fix this? Because i see this thread inactive. Thanks

**Comment by marius11** [comment]
@nerdatwork I personally don't see how reinstalling the browser could fix this, from a technical point of view. I usually reinstall the extension every time there is a new version, since Chrome doesn't do a great job keeping the extensions up-to-date.

Hopefully they will peek an eye at this.

**Comment by luisdanielvc** [comment]
I still have this problem
