### ISSUE TITLE
Why im getting from yesterday only jobs with 4 or 3 steps

### ISSUE THREAD

**Issue by khristianjose** [rainforestapp/tester-chrome-extension#165]
Hello, i am going back to work with you guys, i was inactiva for a while, so i came back this monday and im only receiving jobs with 3 or 4 steps maximun, is this because i was inactive or another reason?

**Comment by helloworld111gh** [comment]
Maybe you're just unlucky? Pretty sure every worker gets the same jobs,
regardless of their activity.

**Comment by khristianjose** [comment]
Nope because i have a friend working on RF too and hes not receiving the same jobs that im receiving.

**Comment by pscohn** [comment]
@khristianjose it's possible you're receiving training hits if you've been gone a while. You can open a support ticket and send your worker ID if you'd like more information.
