### ISSUE TITLE
ERROR SSL

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#166]
![image](https://cloud.githubusercontent.com/assets/19192312/15022409/510a4b6a-11f5-11e6-87e3-6ec4a0e431b1.png)
alot time this error

**Comment by jguerrero2** [comment]
Here the reason...

SSL Errors 2016-05-04 17:38:24 UTC, Kristen Hohenstein
Hey all! A customer released some tests that are resulting in an SSL error. They are working on rolling these tests back now. If you experience an SSL error, you should report that test as a failure. I apologize for the inconvenience!

source:
https://portal.rainforestqa.com/

**Comment by nerdatwork** [comment]
I think your issue is addressed by the above reply so I kindly urge you to close this thread so Rainforest can focus on other open threads.
