### ISSUE TITLE
New issue: server error

### ISSUE THREAD

**Issue by GreekGuy** [rainforestapp/tester-chrome-extension#168]
I got a new issue today 4 times in the last hour. When i get a new test it shows me "Error: Something went wrong.." but i can not open any other test it shows me "You have reached the maximum number ..." if i use an old link so i have to refresh the link with the Server error until it shows me "You have requested the job to often". So i get the test but the terminal can not be loaded.

**Comment by rifatrahman** [comment]
Same here.

**Comment by GreekGuy** [comment]
Everything seems to be working fine.

**Comment by nerdatwork** [comment]
@GreekGuy If your issue is resolved please close the thread so Rainforest can focus on other threads.

**Comment by GreekGuy** [comment]
@nerdatwork sorry man i didnt knew i could.
