### ISSUE TITLE
problem with my account hope i found support from you :( :( 

### ISSUE THREAD

**Issue by axartstyle** [rainforestapp/tester-chrome-extension#169]
hello i had to join the army 2 years ago so i left my account  for my little brother i was good member did over 250 task but unfortunately when i finished and back to home i found my account status blocked hope it solved please kindly i just looking for 1 more chance i know its my fault to leave my account for someone else but i was scared from closing my account 
hope i found help here 
regards <3

**Comment by akshithaaravi** [comment]
Send a mail to tester@rainforestqa.com pronto

**Comment by nerdatwork** [comment]
As per what I have read so far in the updates if your account is blocked/banned you cannot get it back. I hope you have sent support ticket on the above mentioned email to get a satisfactory reply from Rainforest.

**Comment by pscohn** [comment]
We can't unblock an account unless it was done an error.
