### ISSUE TITLE
Windows message "You must restart your computer to apply these changes" when the terminal is loaded.

### ISSUE THREAD

**Issue by qpPykT** [rainforestapp/tester-chrome-extension#170]
When the terminal is loaded, a message appears on the home page "You must restart your computer to apply these changes". There's also a message about the activation windows appears.

![rf-start-wm](https://cloud.githubusercontent.com/assets/4960092/15152470/11e351be-16de-11e6-957e-a8e94fd01cbb.jpg)

![rf-start-wm-terminal-number](https://cloud.githubusercontent.com/assets/4960092/15152514/2e4d1b78-16de-11e6-9623-671e67686fcf.jpg)

**Comment by Dolazim** [comment]
10.If the terminal shows you a message along the lines of "You must restart your computer to apply these changes", dismiss the message. Do not reboot the terminal. You can find in Help.

**Comment by qpPykT** [comment]
My bad. I missed it. Closed.
