### ISSUE TITLE
Error: Something wrong

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#172]
![image](https://cloud.githubusercontent.com/assets/19192312/15216778/56f71f34-1822-11e6-9881-9898c8710766.png)
and application error

this problem have 30minutes or more

**Comment by GreekGuy** [comment]
same here.. and now it shows me "You have reached the maximum number of unsubmitted... " if i open a previous test..

**Comment by Genesis2015** [comment]
Same here :(

**Comment by hunt40** [comment]
today once again they managed to make me angry out of blue ,with constantly no virtual machines,application errors,and we are sorry too many worker and then somebody already did that assignment,amazing just amazing.

**Comment by Genesis2015** [comment]
5th time for 2 days: Hit apeear with ERROR mesaage -> one refresh -> You request this jib too often -> one hour with the "maximum" message (angry) :-1:

**Comment by GreekGuy** [comment]
Please you must fix the "requested this job too often" or make a changeo we can not do anything..

**Comment by nerdatwork** [comment]
There is a policy at Rainforest when you refresh the job page 4 times you get the message "You have requested this job too often. Please return this job." As a fellow tester I recommend to please close the page whenever you get an error message in RED so you can get good working jobs the next time the extension says YES.

@zfonck123 If I may recommend you to check if flash is correctly working on chrome and try reinstalling chrome and/or extension. Also you can submit a support ticket to Rainforest so they can look into the issue.

**Comment by pscohn** [comment]
Please keep tickets to one issue. The application error happens occasionally when there is a problem with our server, and those are fixed as they come up.
