### ISSUE TITLE
New bug or error ?

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#173]
![image](https://cloud.githubusercontent.com/assets/19192312/15231619/13c2ee8e-1866-11e6-9c6b-3a6244e3cac5.png)
  why open  rainforest qa guide affter each reload ??? what happen ?

**Comment by BonesKnows** [comment]
i got this problem also

**Comment by vladfuller** [comment]
I have this issue too, its really confusing if it appear when we have not the hit there, hope they remove this

**Comment by sigitsenyo** [comment]
same here...

**Comment by pscohn** [comment]
This is a result of some refactored code, but we'll push out a fix in the next release so that it will hide the modal if an error happens.
