### ISSUE TITLE
slow connection

### ISSUE THREAD

**Issue by tulko** [rainforestapp/tester-chrome-extension#178]
I'm having problems with the terminal velocity in some test today in most. This makes it almost impossible to test when the site is heavily loaded with images or motion. sometimes really I do not know what to do, if I update the page goes no improvement. Sometimes that is not responding. Put NO and report the problem?

**Comment by nerdatwork** [comment]
As a fellow tester I would recommend a few things. First please make sure your computer isnt slow with other apps running example. if you are playing a flash based game on facebook and the job loads it will be a little bit slower. Also if your computer has low specifications it might also lead the CPU to take lot of time to process through steps. Please try doing this. When your get a job, close all other applications/programs/websites other than Rainforest job. I hope this will help you.

**Comment by nerdatwork** [comment]
@tulko Are you still facing this issue ?
