### ISSUE TITLE
job abandon when on progress doing it, make me very frustated

### ISSUE THREAD

**Issue by sigitsenyo** [rainforestapp/tester-chrome-extension#179]
job abandon when on progress doing it, make me very frustrated
https://tester.rainforestqa.com/abandoned/

**Comment by tulko** [comment]
if many are experiencing problems. frustration and pass the recignacion

**Comment by sigitsenyo** [comment]
if many are experiencing problems. frustration and pass the recignacion
What this mean ?
English please...

**Comment by lilymar** [comment]
I waited less than 10 minutes to pass "Application error for maintenance" and I got "Job abandoned..."

**Comment by nerdatwork** [comment]
@sigitsenyo I think @tulko is trying to say that other testers in his opinion are also experiencing the same issue which is frustrating and testers "resign" from the job.

@lilymar As per the new rules every error message is to be reported. Please read this [https://paper.dropbox.com/doc/AMA-Questions-May-2016-Shared-with-Testers-fx4Uv47P2ZlbQeXhIghi2](url) . You should click NO and mention the error in the pop up box that shows up to report it and submit the hit.

**Comment by pscohn** [comment]
Jobs are only abandoned if you are idle for too long. Please make sure not to switch tabs and do something else, go to the bathroom, etc :)
