### ISSUE TITLE
No back feature on report issue page

### ISSUE THREAD

**Issue by cookin2** [rainforestapp/tester-chrome-extension#181]
I just noticed that the back feature on the report issue page is missing.  I don't know if this omission was intentional or an oversight.  I'm hoping that it was an oversight because it was very handy.  I just had a fairly long HIT and ran into an inconsistency.  I clicked No and started to type and then changed my mind because I thought that I was being too picky.  I went to click back which previously made the report page/modal disappear, and realized that there was no "back" or arrow or "x" to close the modal.  My only options were to go ahead and report or start the HIT all over again (it was a long HIT and was loading pages painfully slowly).  If you intentionally removed the back feature, please consider putting it back, it was helpful!  If it was an oversight, please consider making it functional again :)

**Comment by pscohn** [comment]
@cookin2 I'm not sure what back feature you mean - when you click "no" you should get a popover which you can easily close if you open it by mistake, either by clicking "no" again or by just clicking "yes" instead.

**Comment by cookin2** [comment]
That was simple enough lol!  I didn't know that you could click No again to
get rid of the popover.  Before the "other" was removed, there was a back
feature in the upper left hand corner of the popover - I know because I
used it a time or two :)

Everything is great now, thank you!

**Comment by pscohn** [comment]
😄
