### ISSUE TITLE
Terminal never shows the browser

### ISSUE THREAD

**Issue by khristianjose** [rainforestapp/tester-chrome-extension#182]
Hi, i was working today, and since last few hours im getting jobs but the terminal is not showing anything, its on black, ill put screenshot so you can see.
![sin titulo](https://cloud.githubusercontent.com/assets/17553414/15336416/823e4188-1c44-11e6-84f6-8418956ae0e3.png)

**Comment by nerdatwork** [comment]
I recommend uninstalling/removing that ADBLOCK extension that blocks advertisements. It could be blocking the scripts that run on the page that shows the terminal. Also try updating your google chrome browser too. I hope it helps.

**Comment by pscohn** [comment]
Thanks, @nerdatwork - I've added your suggestions to a new troubleshooting doc here: https://github.com/rainforestapp/tester-chrome-extension/wiki/Troubleshooting-&-Common-Errors-Explained
