### ISSUE TITLE
Blank screen in RF app

### ISSUE THREAD

**Issue by chmi16** [rainforestapp/tester-chrome-extension#184]
Hello,
There is blank screen in RainForest app after submitting email and password

**Comment by nerdatwork** [comment]
Next time please take a screenshot of the page so Rainforest can better help you with your issue. Did you receive any error message ? It was a white blank or a black blank page ?

**Comment by qpPykT** [comment]
@nerdatwork Now is working properly. Previously not loaded rainforest (test) site. I had 2 of these task today, there was just a white screen (page).

**Comment by pscohn** [comment]
If this is happening during a job inside the terminal please use the "No" button to report it.
