### ISSUE TITLE
Dummy files

### ISSUE THREAD

**Issue by marius11** [rainforestapp/tester-chrome-extension#187]
Would it be possible to add some dummy text files on these machines? I was asked to upload random files but didn't had any (Mac OS) and wasn't provided with a link to download them either.

**Comment by Genesis2015** [comment]
Same story here :(

**Comment by qpPykT** [comment]
Report it, what is the problem :) Mac OS does not have any images in documents or ect?

**Comment by bendmi** [comment]
Compressed .zip is a file.

**Comment by marius11** [comment]
@qpPykT It is a problem, especially on Mac OS, since Windows _probably_ has some default files in the Pictures folder. Rainforest makes it very easy to upload files into a step and that feature should be made more known among test authors.

@bendmi There are absolutely no files in Mac OS, and that includes archives.

**Comment by qpPykT** [comment]
Mac OS like a pain in the as... always have some problems.

**Comment by nerdatwork** [comment]
@marius11 I recommend going through the systems folder, since its asking for "any" file. Its a operating system there are always files in the Mac :) I hope that works

**Comment by marius11** [comment]
@nerdatwork Those system files are hidden (for good reasons) and very hard to access by the average user because you have to use a terminal (command prompt) and you have to be familiar with UNIX commands.

**Comment by nerdatwork** [comment]
@marius11 Which command prompt are you referring to ? I have never come across any task involving "typing commands". It has always been a webpage.

**Comment by marius11** [comment]
@nerdatwork http://superuser.com/questions/366824/how-to-access-hidden-or-system-files-in-os-x

Anyway, using system files as you suggested is not a good idea. Test authors should provide us with files or at least add some files to these computers.

**Comment by marius11** [comment]
@nerdatwork http://superuser.com/questions/366824/how-to-access-hidden-or-system-files-in-os-x

Anyway, using system files as you suggested is not a good idea. Test authors should provide us with files or at least add some files to these computers.

**Comment by pscohn** [comment]
We have an issue open for this internally.
