### ISSUE TITLE
How about give 10 time to refresh  active jobs  ?

### ISSUE THREAD

**Issue by sigitsenyo** [rainforestapp/tester-chrome-extension#189]
Hi...I want tell my misery in here...
How about give 10 time to refresh  active jobs  ?
Because I had this...

We're sorry, we've reached the maximum number of concurrent testers we can support. Please reload and try again.

Than I refresh 5 time...
And got this...

You have requested this job too often. Please return the work.

I frustrated about this...

**Comment by qpPykT** [comment]
It was previously 3. Enjoy the fact that even now is 5. I think have 5 attempts is quite normal.

**Comment by sigitsenyo** [comment]
Ok thanks...

**Comment by nerdatwork** [comment]
@sigitsenyo The rule is 4 refresh at the max. After that the job is released back to other worker. As previously mentioned the number 4 was fixed after careful consideration. Practically a worker can lock a job forever with 10 refresh. 

@qpPykT Its not 5 it is 4

I hope that helps.

**Comment by qpPykT** [comment]
@nerdatwork 1 you have initially when a hit comes to you and 4 times you can refresh page until the moment when there an error "too often" appears.
Or I'm I wrong?

**Comment by nerdatwork** [comment]
@qpPykT the first time job loads on the page cant be referenced as "refresh" in my opinion. Technically a "refresh" is when you hit the refresh icon on chrome or F5 on your keyboard.
