### ISSUE TITLE
How to get more jobs ?

### ISSUE THREAD

**Issue by sigitsenyo** [rainforestapp/tester-chrome-extension#190]
How to get more jobs ?

**Comment by marius11** [comment]
Keep the extension set to "NO" as much as possible and be near your computer. Most tests are scheduled to run during the workweek (Mondays through Fridays) and a lot less during the weekends.

**Comment by sigitsenyo** [comment]
Ok thanks...

**Comment by nerdatwork** [comment]
If you are satisfied with the reply please close this thread so Rainforest can focus on other open threads.
