### ISSUE TITLE
We're sorry, we've reached the maximum number of concurrent testers we can support. Please reload and try again.

### ISSUE THREAD

**Issue by hunt40** [rainforestapp/tester-chrome-extension#191]
what is going on with this often overcapacitiy servers message.

almost everyday happens since last week with very frequently

i waited always 1-2 minute before each refresh and even after 6-7 minutes still same problem continue then you see this eventually because you cant nothing but have to refresh to get the job

and this infamous You have requested this job too often. Please return the work.and this job already completed message.

its like our fault and we punished this is so annoying.

**Comment by Fish667** [comment]
Yep same with me. Almost every HIT in the last couple of days is having that message. I usually get HIT after I refresh about 5-10 minutes but it is little annoying because if refresh too much I could get "Return work" message. I thought they said on last AMA that they will release a bunch of new servers to increase capacity but for me it seems like they reduce their servers.

**Comment by nerdatwork** [comment]
Rainforest have recently added new servers which will help in reducing the number of times this message will occur. I understand its frustrating but Rainforest is improving its efficiency every day with the help from testers like us. Our input will help them serve better to their clients. Please keep reporting issues and **make sure you dont create duplicate threads for same issu**e.

**Comment by hunt40** [comment]
this topic is deverve own thread, i lost hits because of this error and there is more people out there with same problem.i dont think they added any server or anything and they are not improving in anyway if you do their test you should now better,how slow most of the their server with some sites and tons of application errors everyday and add with this overcapacity and some more.

**Comment by nerdatwork** [comment]
@hunt40 I totally understand your frustration and Rainforest is striving each day to give better performance to testers as you can see that evidently with Mac/iOS terminals. Also application error are considerably less in my opinion from what they were few weeks back. Its a fact that new servers were added but also know there are testers who do 100 plus jobs in 24 hours imagine what they must be feeling about the issues. We hardly do 5 to 10 jobs in 24 hours so their frustration is way more than our frustration. I hope their new updates will help your issue at the earliest. Till then keep the faith and enjoy Testing :)
