### ISSUE TITLE
Don't get payment...please help...105 steps...thanks...

### ISSUE THREAD

**Issue by sigitsenyo** [rainforestapp/tester-chrome-extension#192]
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx7b6e92-aad9-4339-ba27-20da5303ff57&browser=any&hitId=4206350&sig=49e474e8ea042b72cfafdc267806fad2b2e1748db84016d445553bcc128d24b0&turkSubmitTo=%2Fthanks&workerId=33401104

This assignment has already been completed. If you have already 
submitted this assignment (by pressing the blue button at the end), we 
have received your work and you will be paid shortly. You can now 
close this assignment and find another one from the list of work where 
you found this one.

Don't get payment...please help...105 steps...thanks...

http://oi63.tinypic.com/331g9rb.jpg

http://oi63.tinypic.com/2ekr5gm.jpg

http://oi66.tinypic.com/14bukxu.jpg

**Comment by sigitsenyo** [comment]
test

**Comment by nerdatwork** [comment]
@sigitsenyo How much time has it been since you submitted the Task ?

**Comment by sigitsenyo** [comment]
Where I should report it ?

**Comment by sigitsenyo** [comment]
Until now...I don't receive payment in my history jobs...

**Comment by nerdatwork** [comment]
@sigitsenyo Go to your tester profile and read the NOTE above. For clearing it up for other testers here it is

"NOTE: Bonuses are normally paid within 24 hours, usually less. **Occasionally there are delays. If a bonus takes longer than 48 hours during Monday-Friday**, _please contact support_. "

**Comment by sigitsenyo** [comment]
Ok...let's we see after 48 hour...
usually...it come a few minute after I finish the job...
but this one not come for a few hour...

**Comment by sigitsenyo** [comment]
Still no receive...
What can I do???

**Comment by pscohn** [comment]
Please wait at least 24 hours to receive the bonus. If you still have not received it, you can open a ticket in your profile.

**Comment by sigitsenyo** [comment]
24 may now...
It already 24 hour I wait...
But still not received payment for this big fish...
What should I do ?
Is this big fish should I let to gone ?
Or there another ways ?
Please help ?
Thanks...

**Comment by nerdatwork** [comment]
@sigitsenyo As @pscohn said open a support ticket from your profile. Click the HELP on the right hand bottom in your profile and give all the necessary details.
