### ISSUE TITLE
Didn't get payment...please help...105 steps...thanks...

### ISSUE THREAD

**Issue by sigitsenyo** [rainforestapp/tester-chrome-extension#193]
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx7b6e92-aad9-4339-ba27-20da5303ff57&browser=any&hitId=4206350&sig=49e474e8ea042b72cfafdc267806fad2b2e1748db84016d445553bcc128d24b0&turkSubmitTo=%2Fthanks&workerId=33401104

This assignment has already been completed. If you have already 
submitted this assignment (by pressing the blue button at the end), we 
have received your work and you will be paid shortly. You can now 
close this assignment and find another one from the list of work where 
you found this one.

Didn't get payment...please help...105 steps...thanks...

http://oi63.tinypic.com/331g9rb.jpg

http://oi63.tinypic.com/2ekr5gm.jpg

http://oi66.tinypic.com/14bukxu.jpg

**Comment by sigitsenyo** [comment]
closed

**Comment by sigitsenyo** [comment]
why this don't want to closed...?
Double post...

**Comment by sigitsenyo** [comment]
Double post...
Please help closed...

**Comment by sigitsenyo** [comment]
test

**Comment by sigitsenyo** [comment]
24 may now...
It almost 24 hour I wait...
But still not received payment for this big fish...
What should I do ?
Is this big fish should I let to gone ?
Or there another ways ?
Please help ?
Thanks...

**Comment by sigitsenyo** [comment]
I already sent help ticket in my profile..
But where I can see that if it already read or answered ?

**Comment by sigitsenyo** [comment]
Is it helpful if I sent help ticket ?
Is it have any solution ?

**Comment by pscohn** [comment]
You will receive an email when we have responded to your ticket, but it may take a little time since we are backed up in support at the moment.
