### ISSUE TITLE
"This assignment has already been completed" appears instantly after accepting a job.

### ISSUE THREAD

**Issue by ahmedofhell** [rainforestapp/tester-chrome-extension#195]
Hello,

After copied the URL into the Terminal browser "Invalid state" Message appears.
Refreshing the page shows "This assignment has already been completed" message.

Also, It appears in the portal history page :
743465597	5919630	 2016-05-23	chrome_1440_900	 	00:00:00	—	—

But I didn't submit it!
After copied the URL into the Terminal browser "Invalid state" Message appears.

**Comment by mkdige** [comment]
The same happened with me 
Hit Id 834387010	
Job Id 5919645

**Comment by sigitsenyo** [comment]
How to look job id and hit id ?
Would you tell me please ?
Thanks...

**Comment by mkdige** [comment]
In History tab on your RF page

**Comment by sigitsenyo** [comment]
Ok thanks...

**Comment by st53stefanov** [comment]
The same happened with me:
721784580	5942919	2016-05-24	firefox	 	00:00:00	—	—

**Comment by ahmedofhell** [comment]
Happened again today !!
742582982	5948378	2016-05-25	safari 	00:00:00	—	—
