### ISSUE TITLE
Test notes not saved when clicking No

### ISSUE THREAD

**Issue by marius11** [rainforestapp/tester-chrome-extension#197]
Unlike clicking _Other_ (when the button was still there) and _Test Notes_, the text is not saved when you click _No_ multiple times. I noticed this when I had to gather more information from the terminal, but that part of the terminal was blocked by the modal that appears when you click _No_.

Would it be possible to save the text inside the modal when _No_ is clicked more than once?

**Comment by pscohn** [comment]
That's a good suggestion, thanks. I will close this issue but open a new one internally.
