### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by GreekGuy** [rainforestapp/tester-chrome-extension#198]
I get all the time Application Error when a test appears anyone else?

**Comment by khristianjose** [comment]
I get the same and then when i reload i get Too often, meh.

**Comment by st53stefanov** [comment]
ERROR: Something went wrong on our server, sorry about this. Please reload and try again.

**Comment by sigitsenyo** [comment]
Yes...ERROR now...

**Comment by Genesis2015** [comment]
Same here :-1:

**Comment by sigitsenyo** [comment]
How Long This Error Usually ?
