### ISSUE TITLE
Clipboard!

### ISSUE THREAD

**Issue by cookin2** [rainforestapp/tester-chrome-extension#199]
WoW!!  I absolutely love this feature, thank you so much :)

**Comment by pscohn** [comment]
<3

This one was just for you @cookin2

**Comment by cookin2** [comment]
LoL - well in that case, I guess I'll push my luck a little :)

Would you consider putting that clipboard icon next to the name and password info that we have to paste in?  Please?

**Comment by nerdatwork** [comment]
Kudos @pscohn looks like super updates are coming next ;)

**Comment by sigitsenyo** [comment]
Great feature...it's very helpful :+1:

**Comment by pscohn** [comment]
@cookin2 that will be possible, not right away but we're going to add the clipboard to lots of things

**Comment by tulko** [comment]
Clipboard? where?

**Comment by marius11** [comment]
In the very first step there is a clipboard icon at the end of the URL. If you click it, it will copy the URL.

**Comment by JPierreS** [comment]
@pscohn   You think you can add an automatic paste feature to fill the forms for us too ;-))))

**Comment by nerdatwork** [comment]
@JPierreS more automation and they wont need testers at all lol

**Comment by cookin2** [comment]
Thank you for the update, Paul, sounds wonderful :)

Our own JPierre has made me a star on the Clixsense forum.  Everyone **loves** the new clipboard and he told members that I was the one responsible LoL

**Comment by pscohn** [comment]
I think automatic paste will be a bit trickier, so don't hold your breath ;)
