### ISSUE TITLE
Getting rate-limited without having multiple threads running

### ISSUE THREAD

**Issue by helloworld111gh** [rainforestapp/tester-chrome-extension#20]
I am getting rate-limited using the extension when there is only one thread/timer running. This happens every 3-6 checks.
Worker ID is 12219174

**Comment by nerdatwork** [comment]
Please refer to #17 and mention your worker id there since having a single thread helps RA staff to work on the issue.

**Comment by pscohn** [comment]
@helloworld111gh How do you know you are getting rate limited / can you post a screenshot of the issue?

**Comment by helloworld111gh** [comment]
Pic: http://puu.sh/lEJuX/dbc19c367e.png

**Comment by pscohn** [comment]
@helloworld111gh Thanks - and you are not running the chrome extension in any other browser window, Chrome profile, or computer?

**Comment by helloworld111gh** [comment]
I am only running the extension in one window/profile/computer

**Comment by pscohn** [comment]
Looks like it could be a legitimate bug, so I'll look into it after some other more pressing fixes. In the meantime, it shouldn't cause too much trouble, as it only happens once every several checks. @helloworld111gh

**Comment by sizika66** [comment]
Hi! I have the same problem for last 7 days. 
![005](https://cloud.githubusercontent.com/assets/16043846/11500482/bde0fda2-982d-11e5-8068-7374a3a984e4.JPG)

ID 1236854

**Comment by helloworld111gh** [comment]
Has the rate limit been reduced? I had to raise the check interval to 5 seconds today in order to avoid errors when before it worked fine on 2.4 seconds.

**Comment by shosti** [comment]
The rate limit has been reduced intentionally due to load issues. For now, I'd recommend a lower check interval (such as 5 seconds).

**Comment by nihlathar** [comment]
How can you change the rate limit interval for yourself?

**Comment by jbarber** [comment]
@nihlathar You shouldn't change anything because there is no benefit to fiddling with the values because the rate limiting happens on the server side. There is also no problem with getting the error because it is only informational.
