### ISSUE TITLE
holiday, day of memory.

### ISSUE THREAD

**Issue by tulko** [rainforestapp/tester-chrome-extension#202]
as it is a holiday, on this day we had a few test.
How many jobs might do?

**Comment by sigitsenyo** [comment]
Rainforest QA holiday this monday...
Less jobs appear today...

**Comment by nerdatwork** [comment]
This place is for reporting issues fellow testers, we will be having a forum soon where we can wish them Happy Holidays :)

**Comment by cookin2** [comment]
@nerdatwork Will we really be having a forum soon?

If so, I'm excited!!

Is it appropriate to spread the word?

**Comment by qpPykT** [comment]
I do not understand why they are so long can not create a simple place (forum) for testers. Where would we be able to communicate with each other.

**Comment by nerdatwork** [comment]
@cookin2, I would recommend not to spread a word just yet or they will keep asking and sending support tickets about it

@qppykt Every good thing takes time :)

**Comment by cookin2** [comment]
@nerdatwork Okie dokie :)  I hadn't thought about that!
