### ISSUE TITLE
How many tests can be done?

### ISSUE THREAD

**Issue by tulko** [rainforestapp/tester-chrome-extension#203]
I'm having some probem to receive test in the last days
Or I do not receive test
or no virtual machines

First he says, there are no virtual machines, a few moments later another worker take my job.
Now how is this possible, if they had not virtual machines.

This happen so often catches my attention.

Sent a tiket, the answer is that they will see it and get in contact with me, are always the same words, but never come in contact with me.

I only have one currently rejection, I infer that I am a good tester.
Sometimes I have afraid to put NO because it always means less test.

I think there are situations that affect my own and that have nothing to do with the rejections.
If I not when did wrong test. as I can learn to do the test well?

Before, back in 2014, we could see the responses of the other testers to control. That was very good and took off.

As a tester may make 500 test in a week, and another 150 being hours and hours waiting and reload.

How many test can do daily? in my case 30 or 40.
lately less

**Comment by qpPykT** [comment]
@tulko 
In a usual day I catch about 10-25 tasks. 
Top "Testers" here doing about 700 hits per week = 100 per day = about 20-40$
If you want to make money on testing then take a look towards projects such as utest, testlio, testbirds and ect. 
You can not do on rainforest a lot of money, but I like them.

**Comment by sigitsenyo** [comment]
@qpPykT
projects such as utest, testlio, testbirds and ect. 
where can find them ?

**Comment by qpPykT** [comment]
@sigitsenyo in google :D it can help you

**Comment by sigitsenyo** [comment]
Thanks...

**Comment by sigitsenyo** [comment]
Less jobs today...

**Comment by marius11** [comment]
@sigitsenyo That's not an issue. You should close this thread.

**Comment by sigitsenyo** [comment]
@marius11 
I am not admin...
So...I can't close this thread...

**Comment by sigitsenyo** [comment]
No button to close this thread...

**Comment by sigitsenyo** [comment]
Sorry...
