### ISSUE TITLE
Very long jobs (more than 50 steps)

### ISSUE THREAD

**Issue by luisdanielvc** [rainforestapp/tester-chrome-extension#208]
Hello, i see sometimes a few jobs that are extremely long, this is good for us but it's very frustrating when the terminal is too slow or some steps require more time to complete and the abandoned screen appears, i don't know if this happens to you too, we have like 40 minutes to complete them and we have to do the job very quickly, i believe that the time for completing this kind of jobs is very low, this can be solved by giving more time or by putting a limit for the ammount of steps per job. What do you think?

**Comment by luisdanielvc** [comment]
I was in a 49 step job and i lost the connection at step 30, it was not my internet, it was the server

**Comment by khristianjose** [comment]
It would be nice if Rainforest could add a timer on the job, so people could see how much time they have to do it.

**Comment by pscohn** [comment]
We are constantly working with customers to make jobs shorter, as well as fixing some of the failure points for long jobs. For now, please send any complaints about long jobs (with the job id or assignment id) by opening a ticket in portal.
