### ISSUE TITLE
There are no virtual machines

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#209]
3 hours in same windows, app say yes, and  open a windows with there are no virtual machines.

**Comment by GreekGuy** [comment]
Same here.. I get only "there are no virtual machines"

**Comment by GreekGuy** [comment]
I didn't saw "Another worker accepted the job ..." the last 4 hours so i believe some of the "there are no virtual machines" appears instead of "Another worker...."

**Comment by hunt40** [comment]
yeah today same screen no virtual machines and that pop up open up everytime too.

**Comment by nerdatwork** [comment]
@zfonck123 Its normal when there is a job but all current VMs are occupied. You will have to close that window/tab so new job can load. Rainforest has recently added new servers and we (testers) hope that will improve performance.
