### ISSUE TITLE
Choosing between different channels - Elite, NeoBux ...

### ISSUE THREAD

**Issue by direkkundk** [rainforestapp/tester-chrome-extension#21]
Is there any option to choose between the channels mentioned in the title? I've claimed profiles for different channels and now the extension constantly opens hits for one channel only. No matter what I do, I'm not able to change it.
Thanks

**Comment by KabakF** [comment]
@direkkundk 
1- log out from  " https://portal.rainforestqa.com/login " and log in with your new ID
2- remove your extension and re-install it 
3- make your extension "active" (note: if you see a portal login page, just login with your new ID)

that's it

**Comment by direkkundk** [comment]
Thanks for the reply. I've got more questions. What do you mean by new ID, Elite or NeoBux IDs or new mail and passwords because when I change password for one rainforest profile it gets changed for the other profile as well.

**Comment by KabakF** [comment]
One email adress must belong to one RF test account. You should decide that which account you want to use. I suggest you to use EliteCrowdflower for no interruption of the money. 
Lets say you have 2 email adresses;
                                                   1- elite@rainforest.com = It belongs to your Elite account(ID)
                                                   2- neobux@rainforest.com  It belongs to your Neobux account(ID)

and then lets say you want to work by using Elite; so all you have to do is to login  here( https://portal.rainforestqa.com/profile ) by using elite@rainforest.com and its password.

**Comment by direkkundk** [comment]
Appreciate your help but nothing seems to work. I did as you instructed but the extension still gives ooopses for the same RF profile, not the one I want.

**Comment by pscohn** [comment]
@direkkundk I'm closing this issue, but if you are still having an issue logging in please contact tester@rainforestqa.com.
