### ISSUE TITLE
Bonus 

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#210]
we have a bonus 10% for 10 task complete

is a posible complete 100 and same day ? for 20% ?  check that

**Comment by luisdanielvc** [comment]
Yes, it's possible but it's very hard.

**Comment by sigitsenyo** [comment]
I have not get chance to work for 100 task
Is it  have another way to get it ?

**Comment by qpPykT** [comment]
@sigitsenyo perhaps pray all day :)

**Comment by sigitsenyo** [comment]
Hahahahaha.....

**Comment by erdeminofff** [comment]
I am checking tests under browser 14 hour, sometimes 16 hour every day. For all that, I can only finish 40-50, rarely 60 test in one day.  Over 1 year period I did not reach 100 test.  Pray time :)

**Comment by sigitsenyo** [comment]
@erdeminofff 
Lucky you...
Because I usually only get about 30 jobs only

**Comment by zfonck123** [comment]
i dont more of 100 when , we are can do 4 jobs same time. but in this moment with only one job  for windows is very very hard

**Comment by nerdatwork** [comment]
@zfonck123 There are some testers who claimed to have done 100 plus tasks in 24 hours on few days so its very much possible. If you are satisfied with the response so far I urge you to close this thread since its not an issue and just a question. 
Thank you.

**Comment by sigitsenyo** [comment]
@netdatwork
How it possible receive 100 jobs for 24 hour, because jobs not come every time, isn't it ?
Is it any tips for that ?
Please share...would you ?
Because I stay a long time in front my computer, receive jobs are 10 - 20 only...
Sometimes 30 jobs...
Thanks before...

**Comment by nerdatwork** [comment]
@sigitsenyo Yes its possible and there is no trick/tip to get more jobs. Some lucky testers do get 100 plus jobs. We are the unlucky ones and we are in majority ;)

**Comment by sigitsenyo** [comment]
Hahaha...
I hope someday...I'll be that lucky tester...
Thanks...
