### ISSUE TITLE
delayed payments

### ISSUE THREAD

**Issue by ddiiego1** [rainforestapp/tester-chrome-extension#211]
Hi, since like 4 hours I've been without receiving my bonuses. I think is not just me, this have to be a general problem with the platform, so, I just wanted you to know about it.
ID: 35076405
Thanks.

**Comment by luisdanielvc** [comment]
I've received all my bonuses but i have a lot of "you have reached the maximum number" errors, maybe we all have different problems

**Comment by pscohn** [comment]
If you don't receive your payments after 24 hours please open a ticket
