### ISSUE TITLE
@pscohn Please help...My account is blocked...what should I do ?

### ISSUE THREAD

**Issue by sigitsenyo** [rainforestapp/tester-chrome-extension#213]
My account is blocked...what should I do ?

**Comment by marius11** [comment]
@sigitsenyo Send a support ticket by clicking "Help" in your profile.

**Comment by sigitsenyo** [comment]
Ok thanks...

**Comment by sigitsenyo** [comment]
@pscohn 
Please help me to release my account ... 
Please give me a second chance... 
I promise to work carefully in the future... 
Please help me to work again in rainforest QA 
Thanks...

**Comment by sigitsenyo** [comment]
@qpPykT 
Yes...I had some rejected in training test before blocked...

**Comment by sigitsenyo** [comment]
@pscohn 
Please help me... 
Rainforest income is my priority income... 
Has been blocked make me depressed... 
Please forgive me... 
I promise to work carefully in the future... 
Help please... 
Thanks...

**Comment by helloworld111gh** [comment]
Account issues cannot be resolved via this forum.
The only way is to contact support via the support form. You can access it
when you login.

**Comment by sigitsenyo** [comment]
@helloworld111gh 
I know, but I ask for pscohn help...
Because I know he is an admin for us...
Thanks...

**Comment by sigitsenyo** [comment]
http://oi66.tinypic.com/2pr74hz.jpg

**Comment by qpPykT** [comment]
@sigitsenyo  
Omg, 16 rejections you like a rock star :) 
I have 2 and I'm ashamed of it. The first was my experiment on the training task. The second just my mistake.

**Comment by sigitsenyo** [comment]
@qpPykT
It my mistake man..
Because I not very good in english...
But I will try to be more carefully next time...
Thanks...

**Comment by hendrafreaks** [comment]
@sigitsenyo 
Ouch! sorry to hear that you got ban. But 16 rejection in a month? Wow thats a record! Just be patient and hope for the best!
I wish you a good luck.

**Comment by sigitsenyo** [comment]
@hendrafreaks 
Thanks man...
I wish I get mercy too...

**Comment by hendrafreaks** [comment]
@sigitsenyo 
Have you look at the rejection page carefully? I also get 1 rejection for the training job. But when i look at the rejection page, i can't find the mistake i'v made for that job. It's really strange.

**Comment by sigitsenyo** [comment]
@hendrafreaks 
Yes...it my mistake...
I know too late...

**Comment by helloworld111gh** [comment]
Reviewing the pic it seems you failed the training jobs.
As an analogy it would be like getting low accuracy on Crowdflower Quiz
Mode.
It is unlikely you will be unblocked.

**Comment by sigitsenyo** [comment]
@helloworld111gh 
That I afraid so...
But I try...
I wish I get a mercy...
Because I have done 1164 good jobs...
May be that can be consideration...
I wish rainforest QA have a mercy for that...
Thanks...

**Comment by hendrafreaks** [comment]
@sigitsenyo 
What i don't understand is that you got more than 1000 jobs without rejection and than suddenly you make 16 mistake in a row?

**Comment by sigitsenyo** [comment]
@hendrafreaks 
May be this my unlucky day...
Many happen in my day today...
It make me frustrated...
Very unlucky day...

**Comment by rnfrst** [comment]
have you been clicking 'yes' even if you don't understand the steps?

**Comment by sigitsenyo** [comment]
@rnfrst
Sometimes...I really understand...I click yes...
But in the future...I will click no...for safety...

**Comment by khristianjose** [comment]
Just, lol, i have a lot of work completed too and i dont have any rejections yet, you should be working more carefull if you need it so much like i do. https://gyazo.com/56ca57b949a07bfa2c6ebc16fe59d7eb

**Comment by sigitsenyo** [comment]
@khristianjose
I wish you always lucky...

**Comment by khristianjose** [comment]
I wish you good luck too, maybe they will help you.

**Comment by sigitsenyo** [comment]
@khristianjose
Thanks man...

**Comment by qpPykT** [comment]
We have a line that we can not cross, but in your case you got too far over the line.

**Comment by sigitsenyo** [comment]
@qpPykT
That I know...
We have a line that we can not cross...
But I very happy to receive very much jobs today...
It make me forget the line...
I am doing not accidentally...
That make me very very sorry for that...
I wish they forgive me for a second chance...

**Comment by tulko** [comment]
I have two rejections, one sum and one for training earlier this month. It fools also because they were so easy did not seem to tests or training and neglect me. I always put "NO" when I have a problem explaining why.
At first it was not very good tester, see my history of "2014" gives me shame.

**Comment by nerdatwork** [comment]
@sigitsenyo I am afraid but once an account is blocked it **cannot** be unblocked. Its a golden rule to keep out testers that **do not follow the STRICT rules**.

I feel deeply about the frustration you are facing but its been repeated several times to **read the rules**, **follow the rules**, **carefully do every step** and **report errors**. Looking from the perspective of Rainforest as a fellow tester, there are abundant amount of testers and Rainforest will not spend time on testers that do not follow the rules.

Again I feel your pain but I hope you find the response you are hoping from any of the Rainforest employees.

**Comment by sigitsenyo** [comment]
@nerdatwork 
Thanks for support my misery, man...
I really grateful...

**Comment by sigitsenyo** [comment]
Until now support rainforest don't answer my support ticket yet...
I blocked without warning first...
Do not receive warning email or something else...
Just blocked like this...
I am very depressed now...

**Comment by sigitsenyo** [comment]
Look like pschon just ignore me right now...
I really really feel sad right now...

**Comment by nerdatwork** [comment]
@sigitsenyo Rainforest has strict rules and I urge you to be calm. Let someone reply you on your support ticket or here from Rainforest. The title is self explanatory so wait for them to reply. Repeated replies on this thread will not help your case. Please have patience.
Thank you.

**Comment by sigitsenyo** [comment]
@nerdatwork
I regret had did something stupid that make my account blocked...
Now...I just hope a mercy...
If I get mercy...
I will use it carefully...
And I will try hard to not break the rule again...
I hope pschon will consider my past work and forgive my mistake for my second chance...
Thanks...

**Comment by nerdatwork** [comment]
@sigitsenyo I totally understand but I will humbly urge you to simply wait for someone from Rainforest to reply your support ticket or this thread.

**Comment by sigitsenyo** [comment]
@nerdatwork
Okay man...I understand...
I will wait pschon respon my thread with patience...
Thanks...

**Comment by sigitsenyo** [comment]
@tulko...
I am will follow your way for safety if I get second chance...
Thanks for support, man...

**Comment by tulko** [comment]
I hope you can recover your account, please note that we are "QA" that is we do quality. This activity can not be done with poor quality.

**Comment by sigitsenyo** [comment]
@tulko
It true man...
I will remember...
Thanks...

**Comment by pscohn** [comment]
If your block is unfair you can open a ticket, but it is rare that we unblock someone.

**Comment by sigitsenyo** [comment]
Oh please dear pschon...
Please make exception for me...
Because I will work carefully for next time...
I will not doing something wrong in the future...
I regret for my mistake...
Please give me a final chance to work again...
I beg you to help me...please...?
Thank you so much for your respond....

**Comment by souvik7pal** [comment]
Me also blocked in rf. Is there any chance to unblock or any other way ?

**Comment by nerdatwork** [comment]
@souvik7pal Once blocked you can **NEVER** work for rainforest. There is no other way.

**Comment by souvik7pal** [comment]
@nerdateork but there is no my fault. Its for my poor internet connectivity the inner browser not loaded

**Comment by marius11** [comment]
@nerdatwork Don't tell that to users if you didn't review their accounts (which you can't). That's what RF support will do.

@souvik7pal Your only way of contacting RF is via your profile by clicking "Help" and the top of the page, or if you can, by posting on the forums: https://forum.rainforestqa.com/

**Comment by souvik7pal** [comment]
@marius11 i  contact rf but they tell that there is no way... how i  realise rf that there is no my fault all is for connection.

**Comment by sweeneyapps** [comment]
I fail to see how rainforest block you for poor connection..  There must be other reason.  They already wrote down reason on your profile page.  If its bad like not following instruction so many times then I don't think they will unblock you.    Like others saying to click Help on the profile page and send message to Rainforest and they will explain to you why.    It ll take a while for Rainforest to response you back.

**Comment by souvik7pal** [comment]
@sweeneyapps they told me that i have done yes yes yes without doing... but the inner browser not going up and down and if sometimes going then stuck in a position and i am unable to move in almost every job and so i tell for conection.
Rf say truely but they dont understand what i am saying. Thankx for your relply.

**Comment by sweeneyapps** [comment]
it seems impossible because if RF doesn't see any activity on Virtual Machine and you keep on clicking YES.   That's what RF thinks that u did.    How can you keep clicking YES if you can't work on the Virtual Machine.   That sounds illogical.    But I'm sorry..  I guess you'll have to accept your error at your part and move on.
