### ISSUE TITLE
appication error ( how to proceed?)

### ISSUE THREAD

**Issue by philips13** [rainforestapp/tester-chrome-extension#214]
Hello
In many tasks to load the link into the terminal appears "application error" sometimes at the beginning or at some more advanced step . Sometimes I update the page in the terminal several times and reenters and can continue. But it also occurs to me that I update and update and follow "application error" until the time period expires and step appears "job abandoned"

 My question is:
how I should proceed?
When I have updated several times and still appears the "application error" error should be reported or even wait until the time period expires step and redirect to "job abandoned"

Thanks

**Comment by cookin2** [comment]
This issue came up here:  https://github.com/rainforestapp/tester-chrome-extension/issues/212#issuecomment-223725094

The answer was:  "application errors are issues with the website under test, so you should just click no and you have done your job"

HTH :)

**Comment by philips13** [comment]
Thanks cookin2
