### ISSUE TITLE
New ERROR????? What's that??

### ISSUE THREAD

**Issue by MarinaCec** [rainforestapp/tester-chrome-extension#219]
Heroku | No such app
There is no app configured at that hostname.
Perhaps the app owner has renamed it, or you mistyped the URL.

**Comment by ahmedofhell** [comment]
same here

**Comment by nerdatwork** [comment]
@MarinaCec @ahmedofhell There is some issue with the portal and Rainforest is working on fixing it. As soon as its fixed you will be able to access it normally.Thank you for your patience.

**Comment by pscohn** [comment]
This is an issue with our server and we're working on fixing ASAP.

**Comment by MarinaCec** [comment]
@ahmedofhell @nerdatwork Heroku is a platform as a service (PaaS) that enables developers to build and run applications entirely in the cloud.

It's not their fault kkk

**Comment by pscohn** [comment]
Fixed.
