### ISSUE TITLE
Another worker accepted the job before you

### ISSUE THREAD

**Issue by pscohn** [rainforestapp/tester-chrome-extension#22]
We should try to reduce this error, possibly by reserving hits before opening the tab.

**Comment by nerdatwork** [comment]
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cxa3931d-4faa-4e67-8484-4972f902f644&browser=any&hitId=3979334&sig=9b4233a96b98382752ae0a9b1e1ca52a8ea3a0821cb22abf5e4140c83c289431&turkSubmitTo=%2Fthanks&workerId=NERDATWORK

Same oops message, I hope this task url helps

**Comment by nerdatwork** [comment]
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx3cffd3-6c4a-4692-8c92-5163bd849931&browser=any&hitId=4371211&sig=56e9a0e72f92f2a46b3f40a488ce3a5a2bbc35a1c16aefa048b15ebef93e64f3&turkSubmitTo=%2Fthanks&workerId=NERDATWORK

Another 1

**Comment by nerdatwork** [comment]
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx5904cb-5b51-4f6c-8962-46a2515d04c2&browser=any&hitId=4570330&sig=8c25458b9b64898d67073656e3d07361a249ad4bc5110c06500c342a14628146&turkSubmitTo=%2Fthanks&workerId=nerdatwork

another

**Comment by nerdatwork** [comment]
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cxf87fb8-69d9-478c-807f-26fe98e80f42&browser=any&hitId=3326957&sig=05d2e6fdc784b332a99b4f05e77607d169cfd4ad3dcd8b53c131f865617375d8&turkSubmitTo=%2Fthanks&workerId=nerdatwork

**Comment by nerdatwork** [comment]
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx7f3ea8-bedf-494f-853c-05a921073bbb&browser=any&hitId=3326891&sig=7b1ff12398b314ba59fa0804f674fa5f3aa384d686ee1d18651b6696b776f98d&turkSubmitTo=%2Fthanks&workerId=nerdatwork

**Comment by cookin2** [comment]
Pasted below is the latest Ooops message - I've had many the last several hours, and not one hit.

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx33ccf8-ba4e-4ae5-b44b-e04405357a3d&browser=any&hitId=4504031&sig=facdb68f7bae71fd63ed485b117e959b548d1b5f5cd6a51806086d9c98e25ddd&turkSubmitTo=%2Fthanks&workerId=XXXX

**Comment by cookin2** [comment]
Another

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx21ff8b-8635-4739-805a-7203b51644a5&browser=any&hitId=4478765&sig=160e12655c4e67d5e6c06e39ccbade0a40637ad1dbb6ae412a319e8363a2f3f2&turkSubmitTo=%2Fthanks&workerId=XXXX

**Comment by nerdatwork** [comment]
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx077af5-3107-4b97-b85a-f7a831036867&browser=any&hitId=3979334&sig=bf4f2dd0df54a779b1f73b90eae738facbaf3486230036205921df09874e2b39&turkSubmitTo=%2Fthanks&workerId=nerdatwork

**Comment by helloworld111gh** [comment]
@nerdatwork @cookin2 There is no point in posting links because RF do not have a "reserve hits" feature, and the actual reservation of HIT only occurs when the tab is opened. As opening a tab is very slow many time all the HIT will be gone before the tab loads
So this is a feature request, not bug.

**Comment by cookin2** [comment]
Got it, thanks for explaining :)  I thought that I was helping, sorry for cluttering things up!

**Comment by ukd1** [comment]
Yeah; @helloworld111gh is right. Screenshots or pasting the message is good, the links are less valuable to debugging this.

BTW, this error is currently expected. We're thinking of changing to pre-assign the work to you when before opening the new tab.

Russ

p.s. The current process does a check, then opens a tab which tries the reserve (taking 0-5s to do it), sometimes this means it's gone by the time it's finished.

**Comment by nerdatwork** [comment]
@ukd1  All these links gave the same OOPS ... message and it was a way to show you how much work I could have done with those many links in 1 day. Shows my patience in a way and hard work ( not trying to brag ) I only tried to help and maybe show my frustration a bit :)

**Comment by AlexandruVerenca** [comment]
Out of 50 hits I get in one day, I can maybe do 5, if I'm lucky. Sometimes they fully load in less than a second and they've already been taken by someone else. It's a bit annoying, especially considering the  chrome plugin forces my browser to focus on the window it opened. Most times I gotta wait up to a minute for the page to fully load, time in which it won't let me do anything else on my browser, just so it can tell me the job has already been taken.

**Comment by nihlathar** [comment]
They are aware of the problem, but so far all their attempts to fix it have failed. I'm in the same boat, sometimes I "get" 20 hits within an hour, but I can do 1 or 2 if I'm lucky. Eventually, they said, it will reserve the job before opening the tab for you, but that means for me that whoever gets away with cheating now, will do so in the future as well. It's quite frustrating, really.

**Comment by hunt40** [comment]
last 1.5h plenty of hits come and go and what i get is just Ooops more then 30 times and not a single time i get any hit just Ooops this Ooops that, when i write this i got another Ooops looks like today Ooops day very frustrating and annoying.

**Comment by pscohn** [comment]
@hunt40 I'm sorry about the increase in "oops" - this is still mostly due to too many testers requesting work at the same time, but part of the reason may be that yesterday's fix for "hit xxx cannot..." may cause those errors to turn into "oops," if there is still no job available. We're still planning on finding a way to reduce "oops."

**Comment by mukikuki** [comment]
hi, many opps! hit's today ,  and if not oops!, many screen shots sending error messages (2-3 min to send a screen shot )

**Comment by hunt40** [comment]
yeah a lot of application errors in the last 2 days i am literally looking blank browser page for a minute most of time then application error and if not error its oops,i did total 3 hit in 2 day.

**Comment by hunt40** [comment]
another sad day with god knows how many oops screen,maybe 150+ i lost counts , on some forums people say same things too, so i dont know who get all those hits while we sitting here with that red flashy oops another............

**Comment by nan43528** [comment]
Lots and lots of oops someone else took the hit or it's an application error.  Only able to do 2 hits out  of 10...like right now just flipped me to the testing screen but oops someone else took it. @pscohn
