### ISSUE TITLE
Extension cant turn on.

### ISSUE THREAD

**Issue by josejecr97** [rainforestapp/tester-chrome-extension#222]
Im trying to do jobs.. but extension is always off.. even if i click its still offline..

yes.. i'm logged ig

**Comment by nerdatwork** [comment]
@josejecr97 Sometimes it takes around 3 seconds to turn on, make sure you click and wait for few seconds to turn it on. It happens with me too

**Comment by qpPykT** [comment]
@josejecr97  Check the version of the extension. The latest version 1.2.7.

**Comment by nerdatwork** [comment]
@josejecr97 If your issue is resolved please close the thread or update it if its not resolved.
