### ISSUE TITLE
Hello Admin, Payment issue ?

### ISSUE THREAD

**Issue by samballode6** [rainforestapp/tester-chrome-extension#223]
Hello dear Admin,

I do jobs well in Rainforest QA
But I didn't receive payment
After I check, apparently my id on portal Rainforest QA is different with contributor id CrowdFlower and Neobux
Contributor id on CrowdFlower and Neobux was same it 38173505
But my portal id on Rainforest QA it 31722590

I was contact CrowdFlower support team
I am received this message from CrowdFlower support team :

Hi samballode6,
Thanks for writing in.
Rainforest provides their own support for their “Test a web
application” jobs. Please contact their support team at
tester@rainforestqa.com to see if they are willing to change your
Contributor/Worker ID.
To respond to this ticket, click Reply, type REOPEN TICKET, type your
message and click Send.
Sincerely,
The Community Support Team

I did contact help support Rainforest QA since Friday, 10 june 2016
Until now after weekend, still no answer
Are help support Rainforest QA still active or not ?
Are they still help worker issue ?

Here some information about this issue :

There's an update to your ticket #12009. To respond, just reply to this email or go to http://support.rainforestqa.com/hc/requests/12009.

http://oi64.tinypic.com/s1nwrd.jpg
http://oi64.tinypic.com/281rk7r.jpg
http://oi67.tinypic.com/905di1.jpg
http://oi68.tinypic.com/1znvjsz.jpg
http://oi67.tinypic.com/b4yy3n.jpg
http://oi68.tinypic.com/2aeqio0.jpg

Is there any solution about this issue ?
I think if Rainforest QA willing to change my worker id, it can be solve this problem
But until now still no answer
I am worry about that
Hope can be solved soon
Thank you

**Comment by nerdatwork** [comment]
@samballode6 How do you have 2 Neobux ids ? Did you check with Neobux ? Currently Rainforest does not change worker ids so your best bet is to check with Neobux whether 31722590 is active with them if its not tell them to activate it and tell CF to make 31722590 as your active Neobux id. Now your Neobux and Rainforest id will match. This will make sure you get paid for the tasks.

I hope that was helpful and resolves your issue.

**Comment by samballode6** [comment]
@nerdatwork,
Thank you for your suggestion,
I directly contact Neobux,
Neobux answer me like this :
It's technically impossible Neobux can change IDs.
Only Rainforest support can make changes related to IDs.

**Comment by nerdatwork** [comment]
Unfortunately at this moment Rainforest does NOT change ids.

**Comment by samballode6** [comment]
This doesn't make any sense, even your first IDs have been hacked by someone ?
Like my email have been hacked by someone, It force me to leave my past IDs on Neobux long time ago and make my past IDs not active again, Now someone told me to claim IDs Rainforest because Rainforest have a good payment for their worker,so I make new IDs on Neobux that linked to my contributor IDs on CrowdFlower but Rainforest still have my past IDs, that make me didn't get payment of my work, I think it will be fair if I get support from Rainforest 
Because my profile on portal Rainforest still active and I work well
Thank you

**Comment by JrRandy** [comment]
The issue is the "My account was hacked" is an excuse most online companies have heard likely a million times.  Maybe its true, maybe someone got caught doing something they shouldnt, got banned, and all of a sudden their account was hacked.  To prevent multiple accounts on a single person, RainforestQA has locked the account to your "Contributor ID".  This is not a bug, so likely best taken up with the support team directly and not posted on this bug forum :)

**Comment by samballode6** [comment]
@JrRandy,
 I don't get banned from Neobux
Here is a proof :

Yesterday at 18:38 by Support
Hello,

Unfortunately, your "samballode" account has been permanently suspended due to inactivity, and thus it cannot be restored under any circumstances (it's technically impossible).
Please keep in mind that only CrowdFlower and / or RainForet support can make changes related to IDs.

Best regards,
Dave E.
NeoBux Support

**Comment by helloworld111gh** [comment]
I would note that having 2 ID's from the same site on one account is
against CF ToS. You should contact them to see if they can change it to the
old ID, as your account may be suspended if you don't get that resolved.

**Comment by zfonck123** [comment]
cliksense and neobux have a problem with get a payment from crowflower task  have a delay about 36hours

**Comment by samballode6** [comment]
@helloworld111gh,
I did contact CrowdFlower support team,
I get this answer :

Hi samballode6,

Thanks for writing in.

Rainforest provides their own support for their “Test a web application” jobs. Please contact their support team at tester@rainforestqa.com to see if they are willing to change your Contributor/Worker ID.

To respond to this ticket, click Reply, type REOPEN TICKET, type your message and click Send.

Sincerely,

The Community Support Team

**Comment by samballode6** [comment]
Problem solved, 
Case closed, thank you
