### ISSUE TITLE
Server Errors

### ISSUE THREAD

**Issue by JrRandy** [rainforestapp/tester-chrome-extension#224]
Opens new tab when work is available, get the intructions and click OK, then large delay (30-45 secs) before application error is recieved.  Upon multiple reloads, work has to be returned due to too many requests.

**Comment by Hanifmamun** [comment]
Work page does not load but it shows you have requested this job too often.

**Comment by marius11** [comment]
That happens often when there are many testers online.

**Comment by zfonck123** [comment]
same here

**Comment by hunt40** [comment]
yeah application error and after just 1 refresh you requested this job too often,they have problems you can see on status page

**Comment by zfonck123** [comment]
you have reached... about 40minutes o.o

**Comment by JrRandy** [comment]
@marius11 - Thanks!  I had no idea that page existed.  Book marked and subscribed for future use.  +1 to you!

**Comment by shrestha15207** [comment]
have to wait 60 mins for "you have reached..." to end. what is this??

**Comment by hunt40** [comment]
it says resolved but no its still continue too slow terminals ,and still something went wrong messages and application errors still present

**Comment by Deepak0988** [comment]
Terminal is taking a lot of time to load, even the message that "No virtual machines available" takes a lot of time to show. Seems that there is some issue at RF, not because of too many online tester.

**Comment by qpPykT** [comment]
Again, a blank page. What is wrong with the r-f site.

![r-f-blank-page](https://cloud.githubusercontent.com/assets/4960092/16041220/dcd12792-323c-11e6-8f41-160d871720fa.jpg)

**Comment by zfonck123** [comment]
again you have reached, affter completed one job... 30minutes

**Comment by Genesis2015** [comment]
Same here :-1:

**Comment by marius11** [comment]
Click "No" and report the problem.

**Comment by srsaurabh32** [comment]
too many, just too many errors, cant take it now. I am so irritated. Please rainforest do something or i'll through my laptop away.

**Comment by hunt40** [comment]
well last 4 hours nothing but no virtual machines,this is insane not a single hit i got just no vm

**Comment by GreekGuy** [comment]
@hunt40 with so many new members there is no work anymore..

**Comment by Genesis2015** [comment]
Since the new testers came, now there is less work, more load on the servers and less motivation to work :-1:

**Comment by shrestha15207** [comment]
extremely disappointed..errors everywhere, no work, refreshes, requested job too often, unsubmitted assignments,  ERROR: Something went wrong, no virtual machines. Worst days, Worst week. where is rf heading?

**Comment by GreekGuy** [comment]
I hope rf will fix the errors and add more vms in the future because we are so many now

**Comment by hunt40** [comment]
this is new joke no vm,there is no point to wait to get jobs because there is no job.have a nice day.

**Comment by JrRandy** [comment]
Unusual issues today.  Status page shows everything fine, with no latency, but getting "Internal" errors, and service not available errors inside the RF hits, and random unexpected results in other hits I have worked this morning.  I dont believe I have had 1 job come to completion yet today.  Anyone else seeing the same?

**Comment by suplazam** [comment]
I have the same issue

**Comment by nerdatwork** [comment]
8 new servers have been added and they will start working from Monday 20th, 2016. Total 14 servers will be active so the message of "There are no VMs..." will not be seen that often (hopefully). Lets keep our fingers crossed and hope it resolves this issue.

**Comment by JrRandy** [comment]
An eternity between jobs, and finally get one and no VM's available.  That just doesn't seem right, unless someone is sucking up the VM's.  I completely understand through the week when there is lots of work being done, but what is the deal on a Saturday? lol

**Comment by qpPykT** [comment]
@nerdatwork 
How many VMs can be run on one server? We do not know how powerful they are. But hope dies last. Now problem with VMs one of the most annoying for me.

**Comment by marius11** [comment]
@qpPykT In their last AMA, they said that they will add 8 more servers next Monday. Yay!

**Comment by pscohn** [comment]
If there is a problem inside the browser of the terminal, that should be reported. If you see errors in the actual testing interface, you can post screenshots here with the javascript console open to help us debug.

**Comment by nerdatwork** [comment]
@JrRandy If you arent facing this issue again I would recommend closing this thread so Rainforest can focus on other open threads.
