### ISSUE TITLE
error or is only me ?

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#225]
after login
![image](https://cloud.githubusercontent.com/assets/19192312/16020096/25268c8e-3176-11e6-8876-724e6a3a8fb4.png)

**Comment by zfonck123** [comment]
other error
![image](https://cloud.githubusercontent.com/assets/19192312/16020311/32fa4f16-3177-11e6-823b-07d634da2851.png)

**Comment by qpPykT** [comment]
I have a blank page too. Minus 3 tasks. :(

**Comment by stranger20** [comment]
I  finished a  task with 28 steps and after submiting the task the site went offline and the task is not shown in history, although a success message appeared after a few refreshings....

**Comment by marius11** [comment]
Just click the "No" button and explain what happened.
