### ISSUE TITLE
How to change worker id/ contributor id in rainforest?

### ISSUE THREAD

**Issue by aneesahmad** [rainforestapp/tester-chrome-extension#228]
Can anyone tell me how to change the worker id/contributor id in rainforest? For some wierd reason my worker id got automatically changed. Don't know how it happened.

**Comment by samballode6** [comment]
Same issue here :
https://github.com/rainforestapp/tester-chrome-extension/issues/223
#223

**Comment by nerdatwork** [comment]
@aneesahmad At this moment Rainforest doesnt allow to change worker id/contributor id.

**Comment by marius11** [comment]
Send a help ticket through your profile regarding this issue.

**Comment by aneesahmad** [comment]
already send a help ticket, but they are not even replying to it. Waiting for the last 2-3 days.

**Comment by samballode6** [comment]
I did contact help support Rainforest QA since Friday, 10 june 2016
Until now after weekend, still no answer
Are help support Rainforest QA still active or not ?
Are they still help worker issue ?

**Comment by aneesahmad** [comment]
@samballode6 so sad that we are missing those jobs and don't know if they will make it right. I did more than 70 hits without knowing this and they were sending the money to an old neobux account of mine which doesn't exist anymore. Literally they have not send the money. Hope i would get that too.

**Comment by samballode6** [comment]
Hahaha...
Don't be sad, stay cool and just wait...
I know also after I doing that job, I didn't get payment of my jobs...
Honestly, they pay worker with a good payment...
So... It must be fought...
Hopefully they more wise...
Hopefully they appreciate our struggle...
Hopefully there any good solution about our problem...

**Comment by marius11** [comment]
@aneesahmad How is it possible that you worked on 70 tasks and not notice that you didn't get credited?

**Comment by aneesahmad** [comment]
What if i start a new account in rainforest? Can someone send me a link for a new account. I can't find it?

**Comment by nerdatwork** [comment]
@aneesahmad If it was that simple someone would have suggested it to you in the first reply. Its not possible to open new account unless new Rainforest jobs are posted on Crowdflower.

**Comment by aneesahmad** [comment]
ok again lost hope

**Comment by uangonline** [comment]
@aneesahmad Don't lost hope. Everyday RF post a new apply link in CF wall. Infact i just saw it about 15 minutes ago. You can't change your ID after join in. Just make sure your Neobux account always active.

**Comment by aneesahmad** [comment]
@uangonline thanx for the info :)

**Comment by MoonLightShadws** [comment]
hey i have the same problem only that i dont get any jobs because a climed my profile with a probux ID i didnt know this u.u thats my bad but like @uangonline said i got a id from clixsence to claim a new profile and after i did it goes to my old probux id so i cant get jobs u_u im so sad right now i sent a ticket like 2 weeks ago didnt got an answere im still wating

**Comment by pscohn** [comment]
We don't change IDs, but you can create a new account in Crowdflower and get a new RF profile.

**Comment by aneesahmad** [comment]
We are not supposed to have more than one account in crowdflower. I would like to ask you, do you have any connection/relation with the technical members of RF? Because this thing happened because of a fault from RF side, they are supposed correct it for me. RF changed my id once for no reason and now they are saying that they can't change it back. Actually the support from RF replied that they are looking in to this problem. But i am waiting for more than 1 week now. If there anything you could do, please help. 

    On Wednesday, June 22, 2016 10:36 PM, Paul Cohn <notifications@github.com> wrote:
 

 We don't change IDs, but you can create a new account in Crowdflower and get a new RF profile.—
