### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Dolazim** [rainforestapp/tester-chrome-extension#229]
![fd14033f57174aa18cdc99321f501642](https://cloud.githubusercontent.com/assets/15851077/16077032/a60188d2-32f6-11e6-9950-8c8343251e2f.png)
Any solution for this?

**Comment by Hanifmamun** [comment]
Same to me. Sent support ticket.

**Comment by nerdatwork** [comment]
@Dolazim Send a support ticket from the HELP button on the profile page of your portal at your left hand bottom or email them at tester@rainforestqa.com explaining the issue in detail.

**Comment by kristen-allie** [comment]
Thanks, all! I've shared this with the team.

**Comment by jbarber** [comment]
We're looking into this, but it's only cosmetic and doesn't have any consequences.
