### ISSUE TITLE
Server not responding

### ISSUE THREAD

**Issue by nerdatwork** [rainforestapp/tester-chrome-extension#23]
![image](https://cloud.githubusercontent.com/assets/15882196/11528139/e55f3442-990a-11e5-9803-81bf5e24b921.png)

Have been facing this for few hits that actually work.

After refreshing it 3 times I got this message

This assignment has already been completed. If you have already submitted this assignment (by pressing the blue button at the end), we have received your work and you will be paid shortly. You can now close this assignment and find another one from the list of work where you found this one.

**Comment by pscohn** [comment]
There is a slash missing in the url after the .com, did you accidentally delete it somehow after pasting?

**Comment by nerdatwork** [comment]
yes I accidentally deleted the slash but I always copy paste the url so I am sure it gave the same server issue the first few tries.

**Comment by ando100** [comment]
@pscohn - have faced the same thing several times, deleted nothing- it happens usually and only I might say with Mac/ iOS related browsers in VM. Copy-paste URL or something in task- does not pick the whole URL etc. So either after lots of copy-paste it works or just to check and go letter by letter and fix it manually gets this working.

**Comment by ando100** [comment]
to clarify- I did not get the message- This assignment has already been completed..
Only issue was- copy-paste url or text to VM is not working in Safari and iOS perfectly.
But as of today- no probléms. Don`t know, maybe fixed?
Have not seen the disco lights- meaning blinking Safari- for a while.
