### ISSUE TITLE
Very Very Lag connection!!!

### ISSUE THREAD

**Issue by uangonline** [rainforestapp/tester-chrome-extension#230]
Hi All
Why the connection is so slow today? Almost not workable.
Also a lot of Application error. Rainforestqa status is operational, but still a lot of application error.

**Comment by uangonline** [comment]
@pscohn The lag saga continue. lol

**Comment by zfonck123** [comment]
applicattion error alot times

**Comment by marius11** [comment]
If there are errors, report them by clicking "No".

**Comment by uangonline** [comment]
@marius11 Yap i know that. If the VM already loading and Application error happened inside the VM we should report it. But the application error that i'm talking about was happend before VM even loading. So no button to report it.
