### ISSUE TITLE
You have reached the maximum number of unsubmitted assignments

### ISSUE THREAD

**Issue by GreekGuy** [rainforestapp/tester-chrome-extension#231]
Are you trying to fix it because when that occurs it does not leave me to do tests for 1-4 hours it says that i have reached the maximum number of unsubmitted assignments but i do not have any tests open.

**Comment by Hanifmamun** [comment]
First, Something went wrong on getting terminal.
Second, You have requested the job too often.
I have to wait long time for another task just refreshing one time because of the message "You have requested the job too often"

**Comment by Genesis2015** [comment]
Same f*****g story here :-1:

**Comment by nerdatwork** [comment]
@Genesis2015 I would advice NOT to use profanity while replying to any posts. I understand its frustrating but it gives you no right to be swearing at anybody.

**Comment by BonesKnows** [comment]
i get this message after only one refresh

**Comment by qpPykT** [comment]
It's not funny guys. The whole day the message appear "There are no virtual machines currently available. Please retry in a few minutes." and a little caught hits.

**Comment by pscohn** [comment]
Please keep issues to one topic - it seems like the issue here is about "maximum number of unsubmitted assignments" happening for too long. If you send in a ticket and give the ticket number here, we can try to see why that's happening.

**Comment by cayejon** [comment]
Hello Goodnight. I have the same problem. I sent a ticket to support, where I explain the possible causes (unsolvable). Would please solve my problem. Greetings and long life to Rainforest.

Note: Ticket # 12297

**Comment by cayejon** [comment]
Hello Goodnight. I have the same problem. I sent a ticket, where I explain the possible causes (unsolvable). Would please solve my problem. Greetings and long life to Rainforest.

Note: Request #12297
