### ISSUE TITLE
payments CF  (this is not a Issue, I promise to erase soon)

### ISSUE THREAD

**Issue by tulko** [rainforestapp/tester-chrome-extension#233]
Congratulations, you were bonused 65.6 cents for your work on Test A Web Application Using Any Browser! Hey Horacio, You work was submitted; here is the promised bonus of 80 for completing unit cx0.....3c-896d-4401-a9bd-ef96f8.....
that never charge you extra bonus, it must be

**Comment by tulko** [comment]
That same I sent requesting a ticket. I expound here to see your account CrowdFlower See how paying them

something has me really worried about CrowdFlower
Look this:
Congratulations, you were bonused 66.42 cents for your work on Test A Web Application Using Any Browser! Hey Horacio, Good news. You earned 812c for 28 approved tasks you completed between 2016-06-17 00:00:00 UTC and 2016-06-17 23:59:59 UTC. Today we're bonusing you 81c (10.0%) as you did 10 or more tasks, and we liked your work! Great job! Did you know, if you do over 100 tasks tomorrow, you'll earn a 20% bonus!" Rainforest QA Team p.s. view your profile here: https://portal.rainforestqa.com/tester/ea85f0fa-ce93-xxxx-a612-xxxxxxxx. Get our Chrome plugin here: https://chrome.google.com/webstore/detail/immdjpjbcikbffjifkbncgfbohbjicpo Paid reward: 812c Bonus: 81c Total: 893c ref: 4603070-14908

- You see I got paid only 66 of the 92 paying RF,  It is by its commission
Also it says this is 10% of the 812c in my day
You know how see in my neobux, something over $ 4 not counting the last day bonus

**Look this
This is a payment for a test
 - - - Congratulations, you were bonused 65.6 cents for your work on Test A Web Application Using Any Browser! Hey Horacio, You work was submitted; here is the promised bonus of 80 for completing unit cx0b9f3c-896d-4401-a9bd-xxxxxxxx. Rainforest QA Team p.s. view your profile here: https://portal.rainforestqa.com/tester/ea85f0fa-ce93-431e-xxxxxxx. Get our Chrome plugin here: https://chrome.google.com/webstore/detail/immdjpjbcikbffjifkbncgfbohbjicpo ref: 6432024 ref: 4583286-14908   -   
*** as seen deduct their commission: but the second part, when he says:..... You work was submitted; here is the promised bonus of 80 for completing unit cx0b9f3c-896d-4401-a9bd-xxxxxxx7 
These 80 cents were never paid. of any test

Really do not know if Russ is aware of this. It seems really unfair that CrowdFlower stay with the most money of my test

I hope you can understand

**Comment by helloworld111gh** [comment]
Crowdflower users are paid 4 credits per step, and Crowdflower determines the conversion rate from credits to cash/points/whatever. https://github.com/rainforestapp/tester-chrome-extension/wiki/Payment-Details
This is normal.

**Comment by tulko** [comment]
I get it -  The bonus is the promised
I close
