### ISSUE TITLE
Not gating jobs

### ISSUE THREAD

**Issue by radisa10** [rainforestapp/tester-chrome-extension#234]
I was do my first job 2 years ago..i claim my account 2 week ago and i not gat any job..what is problem people from my country gat to many jobs

**Comment by marius11** [comment]
Make sure the text on the extension says "NO". If it says "OFF", click in once and you should be able to receive jobs in a new tab if any.

Keep in mind that most tests are scheduled during the weekdays (Monday through Friday) and a lot less during the weekends.

**Comment by JrRandy** [comment]
You will also need to keep an eye on the extension when it is slow.  If you leave your PC idle, the extension will turn itself off (Which is annoying when you are watching netflix, but I understand why they do it)

**Comment by radisa10** [comment]
its say all day NO 
in last 4-5 days i am more then 10 hour on computer xD

**Comment by JrRandy** [comment]
hmm, not sure what is going on then.  Has it ever worked?  I have done an average of 40 or so tasks per weekday, and probly a total of 150+ over the last 5 days.

**Comment by radisa10** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20026055/16180011/0ccd1602-362c-11e6-8df5-f63794ed6239.JPG)

**Comment by radisa10** [comment]
and this is windows service pack 3 but same problem on windows 7 :D

**Comment by JrRandy** [comment]
Try submitting a ticket.  Its very possible that you have not been given the training tests, so therefor cannot receive the real jobs that are out there.  I think I had about 10 training hits I had to pass before the real jobs started coming.  Based on the age of the account, the tests may need to be manually resent/activated.

*Note:  This is just my assumption based on you only having the 1 initial job*

**Comment by radisa10** [comment]
where to write ticket ?

**Comment by JrRandy** [comment]
Help button on bottom right corner of your screenshot :)

**Comment by radisa10** [comment]
tnx you

**Comment by nerdatwork** [comment]
@radisa10 Whenever your problem is resolved, please do not forget to close this thread.

**Comment by tulko** [comment]
I returned after a period of inactivity. I also spent some time until they received test

**Comment by radisa10** [comment]
fixed
