### ISSUE TITLE
connection lost in a 87 steps job

### ISSUE THREAD

**Issue by luisdanielvc** [rainforestapp/tester-chrome-extension#240]
It normally starts as a screenshot error but after some time trying to continue the horrible screen of connection lost appears, i really hate this. Does this happen to you too?
![zzzzzzzzzzzzzzzz](https://cloud.githubusercontent.com/assets/16393092/16241122/dff40834-37b1-11e6-9d13-21b09bfee083.PNG)

**Comment by Genesis2015** [comment]
Same to me almost whole the day :-1:

**Comment by ecliptica777** [comment]
How to make a nervous tester?

Step 1: terminal with Saffari browser
Step 2: play video in this Saffari browser
Step 3: approximately 67 test step (Application Error)
Step 4: in penultimate step: connection lost

Congrats, you got the nervous tester. XD
(just a joke)
