### ISSUE TITLE
Hello im not gatting the training jobs

### ISSUE THREAD

**Issue by MoonLightShadws** [rainforestapp/tester-chrome-extension#241]
As the tittle says im not getting the training jobs :( i claimed my profile about 2 weeks ago i send a ticket to rainforest in the help down to the left they have, about 1 weeks ago they send me a email that they got my report but they didnt replay, so now im here trying to get answers i send a ticket to github too today, anyone like me here?
![capt ura](https://cloud.githubusercontent.com/assets/20072714/16241662/83e187b8-37b8-11e6-9515-4da93ff55c87.JPG)

**Comment by nerdatwork** [comment]
Your ticket will be addressed soon. The support desk is filled with tickets. Please have patience. Rainforest will reply soon.

**Comment by tulko** [comment]
you signed the contracts?

**Comment by MoonLightShadws** [comment]
yes i did sign the contracts

**Comment by pscohn** [comment]
Please post your worker ID or your ticket reference number here and I'll look into it.

**Comment by MoonLightShadws** [comment]
@pscohn Hello mister Paul i detected the error, the problem was that i claimed the profile with and old id from neobux, i now you guys dont change id i we have to claim another profile with a crowdflower job and, i did this i claimed it with another email and set a password but when i did they put me in to my old profile :( the id that i want to use is this one the last that i claimed on june CS:28921280 ans here is the neobux id:29067901, another thing i try to change the pass with the new email to see if i loged to my new profile but im not getting the reset pass.
thanks in advance Moon
