### ISSUE TITLE
White Screen on Login during RF hits

### ISSUE THREAD

**Issue by JrRandy** [rainforestapp/tester-chrome-extension#244]
I have done 3 hits testing the RF platform, in which they all hit a white screen upon login.  Please see below screenshot with error in Console.

![image](https://cloud.githubusercontent.com/assets/6944427/16276730/9cd6029c-387d-11e6-9d06-84b08dacb3a7.png)

**Comment by nerdatwork** [comment]
Same thing happened with me. I hope you reported the error.

**Comment by JrRandy** [comment]
Yes, all 3 times including the screenshot above with the console open on the 3rd instance :)

**Comment by JrRandy** [comment]
Just had 1 work, so hopefully its fixed now.

**Comment by nerdatwork** [comment]
It could be one of the tests that gets away being mischievous ;) They will surely fix this.

**Comment by zfonck123** [comment]
same here, and in another jobs same too

**Comment by khristianjose** [comment]
Same here, With Rf test and Twyla too, white and gray screens.

**Comment by pscohn** [comment]
It's not your job to worry about bugs that happen for websites under test. Please just follow the test instructions and answer "Yes" or "No", and only report issues with the testing interface/assignment/extension here.
