### ISSUE TITLE
I cant claim my profile

### ISSUE THREAD

**Issue by duda72** [rainforestapp/tester-chrome-extension#246]
I cant claim my profile, i click on claim, but no notification message come in my crowflower notification inbox, please help me.

**Comment by nerdatwork** [comment]
@duda72 After you click on the claim profile link, you need to login to the portal at https://portal.rainforestqa.com/login. After you login to the portal you can install the Google Chrome plugin by clicking the "Get Chrome Extension" button in your portal. There is no notification in Crowdflower for any of this process.

**Comment by duda72** [comment]
@nerdatwork
I did so and again
I can not log in to the portal to this link. Login
Invalid email and/or password.

**Comment by nerdatwork** [comment]
@duda72 Click the "Forgot Password" link and try again.

**Comment by duda72** [comment]
@nerdatwork
Thank you. I repeated to himself by repeatedly but nothing we do not arrive at the email

**Comment by nerdatwork** [comment]
@duda72 You need to wait for the email to arrive in your inbox. Did you successfully request your forgotten password ?

**Comment by duda72** [comment]
@nerdatwork
 how long i should wait ?
i go on forgot password before ,and nothing.

**Comment by nerdatwork** [comment]
It depends on the email provider. Sometimes it gets within few mins sometimes it takes hours. If you dont get the email for a long time. You can send a support ticket at tester@rainforestqa.com

**Comment by duda72** [comment]
Thank you. I am waiting

2016-06-24 14:06 GMT+02:00 nerdatwork <notifications@github.com>:

**Comment by DarrE9o** [comment]
I think that you dont understand her, she dont have link to claim.  When i claim my profile, i go on claim it, then i give notification that says, you want to claim your profile, good to hear that and then they give me link to go, something like that... ANd when she go on claim it, nothing happened...

**Comment by uqbiii** [comment]
same happened to me in 2 time, then i repeated the whole procedure and when it comes to submit my email and password at signup, i clicked Save instead of hitting enter and it worked. I hope it works for you. Another thing you won't receive any email about forgotten password, because in their system you are not signed up.

**Comment by nerdatwork** [comment]
@duda72 Is your issue resolved ?

**Comment by duda72** [comment]
I have not succeeded. The order I made in December but the new members are
not able to operate TV. That's why I did not pay much attention and now I
do not know the password to join the order. When I go to the forgot
password option is stated that she would send me instructions but nothing
happens

2016-06-27 8:17 GMT+02:00 nerdatwork <notifications@github.com>:

**Comment by Josephapq** [comment]
Good morning.

My brother has the same problem. He performs the test today, and the notification remains no send to his crowdflower account.

A admin can say:

How solved the problem?

**Comment by luisdanielvc** [comment]
Same here, a friend wanted to work and the email never arrived, he did the job via crowdflower and nothing happened, can you please check? His ID is 38418874
