### ISSUE TITLE
Account Blocked during Training mode

### ISSUE THREAD

**Issue by iamdric** [rainforestapp/tester-chrome-extension#247]
When I was doing the training mode, I reported errors with the steps. But the system rejected my answer. I kept doing it and I ended up getting rejected for 12 times. Now my account is blocked. After sending a ticket, I received a notification that the job I did was accepted. But my account is still BLOCKED. My ID is 37267524
![evidence 1](https://cloud.githubusercontent.com/assets/20128671/16339658/6f53d97c-3a56-11e6-9d6a-d739f2ede384.jpg)
![evidence 2](https://cloud.githubusercontent.com/assets/20128671/16339659/6f8b0956-3a56-11e6-8919-3826de75c446.jpg)

**Comment by marius11** [comment]
Your tasks will be approved (and paid) regardless if you did them correct or wrong. Use the green "Help" button from the top right to contact Rainforest.

**Comment by iamdric** [comment]
I already did. I'm worried of what Wiki states that if I'm blocked, I'm blocked forever... Which is why I'm raising this issue. I've been assisted but I'm still blocked.

**Comment by nerdatwork** [comment]
@iamdric The sheer amount of rejections is the keyword here. It clearly states the reason too. Rarely accounts are unblocked so I would advice not to raise your hopes up. Since you have already raised a support ticket. It will be answered in due time.

**Comment by iamdric** [comment]
That is exactly what I'm worried about. Hopefully, they investigate the screenshots automatically made by the system. It was hard getting a profile and losing it just because I reported the right answer is just frustrating.

**Comment by nerdatwork** [comment]
It clearly said you didnt follow instructions and trust me I have seen other testers that have been blocked. They surely will check before replying to your support ticket but again dont get your hopes up.

**Comment by iamdric** [comment]
First picture shows that my job is accepted after filing a ticket. But still blocked.

**Comment by nerdatwork** [comment]
It isnt a job acceptance notification that you see at the very first message from Crowdflower. That was a bonus notification which you got after you did 13 jobs. Currently you get 10% bonus for doing 10 or more jobs and 20% for 100 or more. So after your account got blocked you wont be able to do any jobs but since you did do more than 10 jobs you got the bonus. Was that helpful ?

**Comment by iamdric** [comment]
Even when it stated that it approved 13 jobs earning 13c ? In RF, you still get a bonus even if your job is rejected ? And yes, your comment is helpful.

**Comment by nerdatwork** [comment]
All jobs that show paid to you amounts to you doing them and getting credited for the same. Since you did 13 jobs and were paid for them, you met the criteria for the bonus.

**Comment by iamdric** [comment]
I see.. so now all I can do is wait. How long does it usually takes to at least to reply to me based from your experience?

**Comment by iamdric** [comment]
Okay I've received a reply. This is frustrating. Any RF qa here please explain how I failed to follow instructions. I print screened 1 job only. there's another 11 which I will not print screen for now. RF please explain. Whoever check my ticket, please re-check again.

![rf unfair 2](https://cloud.githubusercontent.com/assets/20128671/16354190/3f3106bc-3abe-11e6-973e-467da793c734.jpg)
![rf unfair 3](https://cloud.githubusercontent.com/assets/20128671/16354191/3f33f4da-3abe-11e6-96b1-eddbdda27047.jpg)
![rf unfair](https://cloud.githubusercontent.com/assets/20128671/16354192/3f35cf4e-3abe-11e6-94b6-363e5ec3d85b.jpg)

**Comment by nerdatwork** [comment]
@iamdric Double screenshots is an automatic rejection in your case.

**Comment by iamdric** [comment]
What do you mean by double screenshots? I only clicked once during the 1st step ! This is the system's record that I can see in my profile.

**Comment by kaytsu** [comment]
The step that you didn't follow will have a red X next to the word yes or no. On the step before did you use the white search box to look for the book title or did you just scroll down? The directions said to use the search box.

**Comment by iamdric** [comment]
Manually searched it. But the 1st job I did was correct and I did exactly the same.

**Comment by nerdatwork** [comment]
@iamdric If you had used the search box only 1 entry should have been shown on the page. Since it doesnt it means you didnt use the search box hence "Didnt follow instructions"

**Comment by iamdric** [comment]
Yep I understand. But the first job I passed with the same method. So I thought all are the same. which is to just locate. Now I can't get another RF account. great. GG

**Comment by nerdatwork** [comment]
The keyword is "FOLLOW INSTRUCTIONS", if the first job was done according to the instructions then it was accepted else it would have been 13 out of 13 for you.

**Comment by iamdric** [comment]
Yes it was accepted without using the search box. That's why I thought it is the same throughout. My bad.

**Comment by kaytsu** [comment]
When you failed your 2nd job you needed to look and see why you had failed so you wouldn't continue to make the same mistakes. But you continued to fail the training lessons without apparently learning from your mistakes so they blocked you from continuing.

**Comment by nerdatwork** [comment]
@iamdric If you are satisfied with the responses you got, I would recommend closing this thread.

**Comment by iamdric** [comment]
I understand. No more RF for me then.Since I can't get another account anyways.
