### ISSUE TITLE
Any ideas on why this error came up?

### ISSUE THREAD

**Issue by sbanquez922** [rainforestapp/tester-chrome-extension#248]
![lost 2](https://cloud.githubusercontent.com/assets/19278419/16343470/f4782b1c-39fc-11e6-93a1-e0383d536e38.png)
![lost 3](https://cloud.githubusercontent.com/assets/19278419/16343474/f8a8db6e-39fc-11e6-9b5d-27b09a094385.png)

I keep getting this error today. 
Refreshing the browser is not helping.

**Comment by nerdatwork** [comment]
Is this happening to all the jobs that load. If so try reinstalling Chrome and it might help. Also could you tell me what is the icon to the left of Rainforest Extension ?
