### ISSUE TITLE
 problem with work crowflower

### ISSUE THREAD

**Issue by alfredolol** [rainforestapp/tester-chrome-extension#250]
I have a problem never before I created a profile to work with rainforest but when entering the work from crowflower I get a message saying that I already have an account that I can do? , and try recuperr password but never arrives already have more than 48 hours waiting for the message in my mail has not arrived

**Comment by nerdatwork** [comment]
Send a support ticket at tester@rainforestqa.com with all the details and Rainforest will help you.

**Comment by Josephapq** [comment]
Good morning.

My brother has the same problem. He performs the test today, and the notification remains no send to his crowdflower account.

A admin can say:

How solved the problem?

**Comment by JrRandy** [comment]
Please close this thread if this issue has been resolved.
