### ISSUE TITLE
Latest Updated Extension polls for work less frequently which means less work for testers ...20 Jun 16  

### ISSUE THREAD

**Issue by Deepak0988** [rainforestapp/tester-chrome-extension#251]
Recently on 20 Jun 16 the extension was updated which polls for the work less frequently when compared to the previous version of extensions. 

Surely it will reduce the load on Rainforest servers but ultimately we testers are getting less work from past week. 

Please update are you facing the issue too.

**Comment by tulko** [comment]
no longer I need to be recharged. also it is less the message "missing virtual machines"

**Comment by marius11** [comment]
Every user of the extension uses the same polling frequency, which is 16 seconds.

I don't really see the issue in that.

**Comment by nerdatwork** [comment]
@Deepak0988 How did you figure out the extension is polling less frequently now ?

@marius11  How do you know its polling for exactly 16 seconds ?

**Comment by marius11** [comment]
@nerdatwork You can check the extension's source code by clicking the "Code" tab next to the "Issues (_)" where _ can be any number at the top of the page. :)

- The file which was recently modified: https://github.com/rainforestapp/tester-chrome-extension/blob/develop/src/constants.js
- The list of modifications to the above file: https://github.com/rainforestapp/tester-chrome-extension/commit/a89f98768c94a34f5f3ae46a91f38c85052c427b#diff-a7748843fbda5167d065231e3a2e7a1f

**Comment by nberchev** [comment]
Yep, definetely I receive twice less work this week. RF warned about it on the AMA's but said that they are also adding new clients and the two things will balance eventually. I just hope the quality of work do not lower during the process.

**Comment by nerdatwork** [comment]
@marius11 Thank you, that was insightful.

**Comment by nerdatwork** [comment]
@Deepak0988 I understand you not getting more jobs but this is an update done by Rainforest to better address the error messages that testers are facing. This **IS NOT AN** issue since github is a place to report issues. I recommend closing the thread.
