### ISSUE TITLE
extension 'YES' but no job receving

### ISSUE THREAD

**Issue by RezwanulHaque** [rainforestapp/tester-chrome-extension#252]
Hi, I have noticed chrome extension is YES but no Job is reeving. Its happening from last two day's. 
Please check.

**Comment by nerdatwork** [comment]
So you have not done any job in last 2 days ? Even after receiving YES on the extension ?

**Comment by RezwanulHaque** [comment]
It was. But now I am receiving job. Did two jobs in last 5/6 hrs.

**Comment by qpPykT** [comment]
@nerdatwork 
Fellow, how many hits you get in an usual day?

**Comment by nerdatwork** [comment]
@RezwanulHaque If your issue is resolved please close this thread.

**Comment by RezwanulHaque** [comment]
Usually I get 15/20 jobs per day (in week days). But last couple of days I did get very minimum jobs. from this morning I am getting jobs, like I got~10 jobs. 

Thank you
