### ISSUE TITLE
Missed payments after 1 day

### ISSUE THREAD

**Issue by ddiiego1** [rainforestapp/tester-chrome-extension#256]
Hi, yesterday I worked all the day, and in my count, I made at least 15$ but in my gift hunter account I did just receive like 6$, there's a lot of payments that I dont see added to my gifthunter account, even if it appears as paid in crowdflower and the portal, specially these payments: 678335071  678335071  678335071. But that ones are not the only delayed, there's a lot of bonuses I did not receive, the system is failing and is bad for the workers.
I had wrote to the testers support, but as always, they did not help me, just said "how can we fix that?", thing that I cant believe, thats why I came here.
Thanks a lot and please give us a real solution.

**Comment by ddiiego1** [comment]
I'm tester 35076405

**Comment by felipeinsanobr** [comment]
here are normal !
I work in Elite ... don't have discounts equal others sites ... Clixsense, neobux ...

**Comment by Julekhaakhter** [comment]
It happened to me also. Rainforest Job ID's are: 6627000 and 6626680.

**Comment by ddiiego1** [comment]
It still happening today, its frustrating to know that I'm working for nothing, look at the first image, there appear the bonuses as paid, but look at the second image, in my gifthunter account, it was not added, so I'm working for nothing.
![2](https://cloud.githubusercontent.com/assets/19738677/16427818/d21d4abc-3d34-11e6-9ff6-1fee0faa3f84.png)
![1](https://cloud.githubusercontent.com/assets/19738677/16427819/d220408c-3d34-11e6-974d-cc535ee24d53.png)
I know in this case is not since 24h but yesterday missed bonuses was the same, and looks like today I will work all the day for nothing again, this system error is hurting workers.
Please take a look at this. Thanks.

**Comment by felipeinsanobr** [comment]
Well come on, I will try to explain to you what's going on ...
The CF is like the central payment network ... the only company that is the CF is the Elite.
Other companies like Neobux, Clixsense, IntaGC and others (including yours) they are companies of which are linked with CrowdFlower. ie they take a certain% of your gain for them ... then there is the Rainforest standing stealing ... but you are paying a fee to be able to work in this his PTC.
understood?
if you want to gain the right amount of Rain, you make an ID by EliteCrowdflower you will normally receive! right value without discounts!

**Comment by felipeinsanobr** [comment]
which site for which you do the tasks?

**Comment by ddiiego1** [comment]
Oh man, I understand that, I know that the only page that does not have a fee is CFElite, and that's not the problem, just take a look at the images, I work in gift hunter club, and I know that they pay me 3,68c for every 4c that I made, I know it. The problem is that the bonuses just appeard as paid (with ghclub taking the fee) but I did not receive my part. do you understand me now?

**Comment by felipeinsanobr** [comment]
So the problem is with your PC and not with the Rain.

**Comment by uangonline** [comment]
@ddiiego1 You should contact gifthunter since it seems the problem is between CF and gifthunter. It was happened before with clixsense. If you already received email in your CF notification for the work you've done, it's mean RF already send the payment to your CF id account.

**Comment by tulko** [comment]
I can make myself CF elite using the same identifier currently I have with neobux?

**Comment by Julekhaakhter** [comment]
I have two other missing payments today for ID's 6687396 and 6687164. Rainforest portal and CF says paid but did not arrive at gifthunterclub. Is there any way to migrate from gifthunterclub to other channel?

**Comment by nerdatwork** [comment]
@ddiiego1 The problem is with gifthunterclub since payment is released by Rainforest to CrowdFlower and CrowdFlower shows you via notification in their portal. Ask gifthunter support to look into this and give you details of any payments made and show them the payment proof. Since from your screenshots its evident that Rainforest and Crowdflower have paid you.

@tulko Yes you can but since you are currently getting paid on your regular account for working on Rainforest HITs, you are advised not to open another account. Testers are only allowed to open another account if they have issues getting paid in their original account (as per the recent updates).

I hope that was helpful.

**Comment by ddiiego1** [comment]
@nerdatwork Thanks a lot, I understand that the problem is the gift hunter page, so I will close this thread because rainforest has nothing to do with this.

**Comment by nerdatwork** [comment]
@ddiiego1 I got a notification for your message about closing the thread but its not on this thread. Did you create then delete your post ?

**Comment by JPierreS** [comment]
The issue you are having is between CrowdFlower and the channel you are working from. You should contact gifthunter directly in this case.  Are you getting issues with other tasks not paying ?

Also keep in mind sometimes you can receive bonus payments merged together on some channels, for instance 2 tasks' bonuses merged into 1.  It will show individually on your CrowdFlower inbox, but you might get them merged together to your channel.

**Comment by ddiiego1** [comment]
Yes, I understand that rainforest has nothing to do with this problem, but I cant close the thread. Thanks everyone, and for the persons that see this, GIFT HUNTER CLUB is not paying the bonuses, time to get out of there.
