### ISSUE TITLE
Fewer and fewer jobs

### ISSUE THREAD

**Issue by tulko** [rainforestapp/tester-chrome-extension#257]
I understand they want to have new testers, but think we are experiencing frustration old testers.
Explain which is the ideal configuration to be on equal terms.
According to RF is not about speed or the ping?
Then randomly assigned?
That way your system simulates randomness.
They continue to work to change the system to assign test?

**Comment by tulko** [comment]
RF said that whoever comes first is who has the job
I have to run a marathon, train there anything I can do to make deserving of a test?
I took almost two years and nearly 2000 test, there are new testers who are doing more tests and takes less than a month.
RF I ask to you that seems just?

Use channels, allocate medals, priority system.

I think RF is not taken into account nor old, neither the quality nor the effort. or the waiting time.
It does not consider if I take 2 years 1 year 6 months 1 month 1 day to you that seems just?
You think that does not affect the quality of work?

It seems to you just a tester 1 week has a test   87 steps, then test 20 or more per day and someone of almost two years make less than 10 in a day?

not mean to be sarcastic or annoy the staff but I think that these issues should be taken into account.

**Comment by qpPykT** [comment]
It's so unfair when some testers get 40-60 hits per day while others get 5-15 hits. It's like a chaos.

**Comment by nuevao** [comment]
Everything was fine until Monday, you can not be going but I think RF is updating the platform, I think you have to have a little patience, no one should be few hit's otherwise we will take our time and devote ourselves to something else, and RF will always be new people who arrive and are disappointed by low incomes. let's hope that everything goes better in the remainder of the week. Greetings.

**Comment by khristianjose** [comment]
Yep ive been receiving like 15 jobs per day when the last week i was doing like 40 per day, its so sad, im an old tester too, have like 2k+ jobs done. Lets hope this will be fixed soon.

**Comment by zfonck123** [comment]
new update with alot errors u.u, and need more speed conection and better pc lol... soo bad

**Comment by CassianoTerzi** [comment]
I agree.
I think they are worrying more with customers than with the testers, but they forget that who does all the work are the testers.
If we can't do the Jobs, who will do it ?
6.266
Testers (24h)
6,266 testers, 2 weeks agoo It was about 4,000...
RainforestQA needs to know that quantity doesn't ensures quality.

**Comment by normensstounss** [comment]
Rainforest respected new testers not old testers..

**Comment by RezwanulHaque** [comment]
Same things here also, I am old user and have completed ~ 2600 job. But recently receiving few test daily. Not sure why. If RF dont like old user, they can let us know. so that we will not sit in the computer to do RF jobs. Thanks RF team for considering old users concern.
