### ISSUE TITLE
you have reached.

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#258]
You have reached the maximum number of unsubmitted assignments. So we are fair to other workers, we stop you doing too much for us at once. You can complete the other assignment(s) and refresh this page, or simply return this hit.

How many minutes for can dissapear that ?  i have this error, when visual of plataform change...

**Comment by zfonck123** [comment]
my friends have a same problem

**Comment by jombere** [comment]
me to.

**Comment by zfonck123** [comment]
.... about 50minutes in you have reached :/

**Comment by ahmedofhell** [comment]
same with me.

**Comment by erdeminofff** [comment]
Every tester have same problem. We are not getting any hit becasue of this reason

**Comment by GersonTavare** [comment]
More than 1 hour in this error here.

**Comment by zfonck123** [comment]
yeh and this problem continue :(

**Comment by BonesKnows** [comment]
same here

**Comment by AndyARB** [comment]
Same here.

**Comment by shrestha15207** [comment]
more than 2 hours now

**Comment by zfonck123** [comment]
yes :(

**Comment by samballode6** [comment]
Same here.

**Comment by shrestha15207** [comment]
3 hours and counting :(

**Comment by ahmedofhell** [comment]
almost 5 hours for me :((

**Comment by samballode6** [comment]
Is good now..

**Comment by zfonck123** [comment]
5 hours and counting T_T

**Comment by GreekGuy** [comment]
same here.... for 5 hours..
