### ISSUE TITLE
Unexpected token < in JSON at position

### ISSUE THREAD

**Issue by felipeinsanobr** [rainforestapp/tester-chrome-extension#259]
What's it ?

**Comment by pscohn** [comment]
When someone sees this, can they provide a screenshot of the javascript or network console, wherever they see an error? It will be due to some bad network request.

**Comment by zfonck123** [comment]
same here, and you have reached too

**Comment by felipeinsanobr** [comment]
when it appears again I send print.
now he stopped ... but that tava appearing in place of another ...
and now is just stuck on you have done ... I have a group of friends in vk.com, everyone is trapped You have done the maximum and submit the time the portal. rainforest, profile ta buggy TBM.
in addition to the delay when we submit it is taking too long to appear on the list of historical and payment be pending.
http://puu.sh/pKnH7/cfdd51e631.png

**Comment by felipeinsanobr** [comment]
It is just so ...
http://puu.sh/pKnKW/567e464cd6.jpg

**Comment by GersonTavare** [comment]
Same here and maximum error since the exchange of layout was made.

**Comment by zfonck123** [comment]
60minutes with a same error

**Comment by GersonTavare** [comment]
Same as here. Or more  than 1 hour. Always when there's some layout change we receive a lot of errors during the day. RF should take weekend to make this changes,
