### ISSUE TITLE
Is there any way that new user install RF extension

### ISSUE THREAD

**Issue by chmi16** [rainforestapp/tester-chrome-extension#26]
How can new user install this extension without doing any job from ID? There wasn't new ID for quite long

**Comment by Genesis2015** [comment]
One of my frends have the sam problem. Hi reched 3th level on CF but there is no way to begin to compelting tests in RF.

**Comment by pscohn** [comment]
This is related to https://github.com/rainforestapp/tester-chrome-extension/issues/24, so closing as duplicate.

The short answer is that it's very difficult for new testers to start with us right now as work is assigned to Chrome plugin testers faster than Crowdflower's task list, but we will fix this.

**Comment by Genesis2015** [comment]
"...but we will fix this"
We'll waiting with impatience. Thank you  :+1:
