### ISSUE TITLE
Becarefull of IOFFICE job.

### ISSUE THREAD

**Issue by uangonline** [rainforestapp/tester-chrome-extension#260]
You will get rejection even you give correct answer. And no submitted time appear in the history.
![rainforest tester portal1](https://cloud.githubusercontent.com/assets/17927929/16461007/93f979a6-3e54-11e6-9816-4b68efc32c5e.jpeg)

**Comment by ellmirr0001** [comment]
yeah. I got the same problem, everything is correct but it got rejected

**Comment by MarinaCec** [comment]
I need a real job, rainforest is getting very unstable, just falling ... I will not be able to pay my bills this month :(

**Comment by qpPykT** [comment]
I have same problem. This hit was rejected.

**Comment by cookin2** [comment]
I got a rejection too on the same task.  No red "x".  Math and attention questions were not marked wrong.  I could really use some guidance here - have shut off the extension until I can find out what I did wrong.

Please help!

**Comment by JrRandy** [comment]
Same

**Comment by priggy** [comment]
same thing... and what is the worst... after this does not let you do anything else...

**Comment by priggy** [comment]
Add 245 and 122 using a calculator. 
Is the sum 376?	

answer: no

**Comment by uangonline** [comment]
Yap. For now i just closed the ioffice job everytime it's appear.  I don't know if the RF team will fix this and reversing the rejection. But i hope so.

**Comment by rahayusri** [comment]
I even got 2 rejection. 
![rainforest tester portal](https://cloud.githubusercontent.com/assets/20210695/16461442/c2cc13f4-3e56-11e6-8c02-790c0307c314.jpeg)

AND

![rainforest tester portal1](https://cloud.githubusercontent.com/assets/20210695/16461468/f036f7d2-3e56-11e6-94e5-b73f415a72d2.jpeg)

**Comment by pscohn** [comment]
We're reverting today's update to fix this, it should be working again soon and we'll reverse the rejections.

**Comment by ilegalna** [comment]
Hi,

Same here. I got rejection but don't see any mistake. My worker ID is 29166275
