### ISSUE TITLE
BUG REJECTION

### ISSUE THREAD

**Issue by felipeinsanobr** [rainforestapp/tester-chrome-extension#263]
all the works I did were rejected that?

**Comment by kaytsu** [comment]
Mine was also - I had 3 hits rejected without me making any mistakes/doing any errors. It has to be a bug with the new coding/terminals..... I've turned off the extension until they get it fixed. 
![image](https://cloud.githubusercontent.com/assets/20136128/16462029/0e1faac6-3df5-11e6-8d5f-4e08235c5cd8.png)

**Comment by qpPykT** [comment]
https://github.com/rainforestapp/tester-chrome-extension/issues/260

**Comment by achernovRF** [comment]
just now I got one and got unfairly rejected, It had two "browse to ----> take screenshot" steps and those where counted with another step as a single step (is it rejected becouse RF marked them as missing steps), is it the new interface? time taken is marked as 00:00:00 and there is no submitted information

**Comment by priggy** [comment]
all jobs are like this.... unsubmited, but paid, and time taken 0:00:00... and rejected as well...

**Comment by nuevao** [comment]
The same around here, I have only one task with the new interface and have rejected

**Comment by nuevao** [comment]
guys read https://portal.rainforestqa.com/

**Comment by nerdatwork** [comment]
@felipeinsanobr This was a bug and has been rectified. Please close this thread. Unless you are still facing this issue.
