### ISSUE TITLE
Notifier keep getting jobs eventhough i'm already got a job todo.

### ISSUE THREAD

**Issue by uangonline** [rainforestapp/tester-chrome-extension#265]
Notifier keep getting jobs eventhough i'm already got a job todo. Have to turn off the extension everytime i got a job.

**Comment by priggy** [comment]
lucky you... you are getting jobs... we are not getting any!!!

**Comment by uangonline** [comment]
Sorry to hear that. Currentlly i'm turning off the extension to see if that's help.

**Comment by uangonline** [comment]
Updated: Turn the extension back on and all seems back to normal. Case close.

**Comment by uangonline** [comment]
Sorry seems the problem returns. Have turn off extension every time i got a job since the extension keep give me a yes notification.
