### ISSUE TITLE
6 Hours with a same problems

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#266]
![image](https://cloud.githubusercontent.com/assets/19192312/16467758/7f9a5abc-3e12-11e6-8508-525149a43c1d.png)

can say what happen  plz plz

**Comment by pscohn** [comment]
What is your worker ID? @zfonck123

**Comment by zfonck123** [comment]
34044189

**Comment by zfonck123** [comment]
![image](https://cloud.githubusercontent.com/assets/19192312/16467825/e323fe8a-3e12-11e6-99b6-8c8c6f607f9b.png)

**Comment by st53stefanov** [comment]
Same with me: ID 16657692

**Comment by pscohn** [comment]
@zfonck123 is it better now?

**Comment by zfonck123** [comment]
yes thanks very much @pscohn

**Comment by pscohn** [comment]
@st53stefanov have you shared ip addresses or computers with another worker?

**Comment by st53stefanov** [comment]
No I have fixed IP only for me

**Comment by st53stefanov** [comment]
Now I see :Another worker accepted the job before you! It doesn't look like there is any more work for any of our hits; please try again shortly - you can refresh this page, or close and wait for a new job.

**Comment by zfonck123** [comment]
@st53stefanov  it is a normal message by waiting for jobs. n.n

**Comment by st53stefanov** [comment]
Yes I know that but 4,5 hours i was like you

**Comment by sizika66** [comment]
Hello! I have the same problem. The last HIT I've done with the new interface 2016-06-29 15:57:54 UTC and from that time "You have reached the maximum number of unsubmitted assignments. So we are fair to other workers, we stop you doing too much for us at once. You can complete the other assignment(s) and refresh this page, or simply return this hit."
No shared IP.
ID 12316854
thank you! :)

**Comment by uangonline** [comment]
@pscohn The problem was also happened to me. But now everything seems back to normal.

**Comment by sizika66** [comment]
It's back to normal. Thank you ! :)

**Comment by zfonck123** [comment]
.
