### ISSUE TITLE
I get received a hit when I was doing another .

### ISSUE THREAD

**Issue by philips13** [rainforestapp/tester-chrome-extension#267]
Hello
While performing a task came out a hit on another tab.
Thanks

**Comment by uangonline** [comment]
@philips13 I also have encaunter the same bugs, at first it's also open a new tab. But now even the extension still send a yes notification, it's no longer open a new tab.

**Comment by Electroglitch** [comment]
I also can confirm this bug, had to turn off extension because it opened another tab luckily with no virtual machines message 
and it was just couple of seconds maybe 10 after it opened first tab
 and i just pasted url at beginning of the test (Browse to/take screenshot part)

**Comment by philips13** [comment]
I still have the same problem.
I'll leave it off for the rest of today.

**Comment by dreicaan** [comment]
this is happening to me as well. What should we do? Should we just do all the work we get?

**Comment by pscohn** [comment]
We temporarily increased the number of jobs a worker could take at once during a high load period yesterday, we've decreased it back to the normal level, so you can turn your extension back on @philips13 :)
