### ISSUE TITLE
Test Applications For Qa Id Rainforest no Notificactions Neobux

### ISSUE THREAD

**Issue by Lomaximo** [rainforestapp/tester-chrome-extension#268]
Hello day 06/21/2016 realize this traballo called Test Applications For Qa Id Rainforest 919,467 by Neobux but have not received their Nofificacion to create the account and follow the steps I sent them email and do not answer me Thanks
![sin titulo3](https://cloud.githubusercontent.com/assets/20029178/16472809/25b8a886-3e31-11e6-935c-8aaf173b89f4.png)

**Comment by samballode6** [comment]
Have you check carefully in here ?
https://tasks.crowdflower.com/notifications

**Comment by josejecr97** [comment]
i  have 2 friends with the same problem.. their contribuitor id is : 38560198 
and 38593155      pls help them .. thanks

**Comment by Lomaximo** [comment]
hello samballode6 I do not notice that bar after having done the job of sending emails and Rain and do not respond

**Comment by luisdanielvc** [comment]
Same here, a friend with id 38418874 didn't receive the email for getting his profile in RF
