### ISSUE TITLE
[URGENT] Missing payments

### ISSUE THREAD

**Issue by nerdatwork** [rainforestapp/tester-chrome-extension#27]
Some jobs are not showing up in the RF history and there is no way to cross check which hits were paid and which were not since there is no matching HIT ID. 

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cxffe049-cced-4100-af54-e369778637bc&browser=any&hitId=3981469&sig=049704fadd2e4572f577630fb6b8ebb35f4da7077d30b02b770a8a11321608a2&turkSubmitTo=%2Fthanks&workerId=11244952

10 steps missing from history

**Comment by mueller2511** [comment]
Hi RF Team,

I am also having the issue like others and some of the hits are not getting credited and not seeing them in the Bonus history page as well even after couple of days , Can you please confirm whether this is a bug or any rules have been changed , so that i can work on hits that will be paid and not on the ones which don't. 

Thanks

**Comment by Genesis2015** [comment]
Same situation here :(

**Comment by pscohn** [comment]
This seems to be related to https://github.com/rainforestapp/tester-chrome-extension/issues/25 but I'll leave it open until we figure out what's going on.

Just to give a quick update, we're aware this is a serious bug and we're looking into why this is happening. I'll update you again when we know what the fix is and have an ETA for it.

**Comment by mueller2511** [comment]
Thanks @pscohn for the info.

**Comment by KabakF** [comment]
@pscohn It's mostly happenin when I finish the job by clicking "Other" to give you detailed report

**Comment by KabakF** [comment]
@pscohn It's mostly happening when I finish the job by clicking "Other" to give you detailed report

**Comment by mueller2511** [comment]
Another thing i noticed that when doing the hit if the extension starts to blink and shows Yes in the middle of hit then also after completing that hit it doesn't show up in the bonus history and goes missing, this is happening when doing bigger hits especially even happening for 8 or more steps hits, they seems to get timeout and the extension shows yes but can't open another tab as there is already a hit opened which was not the case before this issue.

**Comment by KabakF** [comment]
I'm missing payment for hit **4474734** . 22 steps :rabbit: My Worker ID is **35273503**

**Comment by Ranky2211** [comment]
I have same problem.Yesterday i reported HIT on 22 step and its missing and In between step due to hang in website and terminal is not responding when i crop or resize image so i waited for responding and i cant refresh the whole HIT because i am middle of 30 step HIT so it took me some more time to report.Previously i think 2 HIT missing.I dont know its due to time out or some other reason.  @mueller2511 you are right when doing HIT extension turned yes in between and blinking and sometime it turned yes and not opening the working Tab.So what i am doing right now when i got HIT then i turned Extension off and when i complete HIT then again turned ON.

**Comment by nerdatwork** [comment]
@pscohn Hits that are answered anything other than YES dont show up in history and neither they are paid. I confirmed it with lot of hits by now.

**Comment by pscohn** [comment]
@nerdatwork thanks - I'll pass on that info. Has it affected ANY hits that are all answered "Yes"?

**Comment by nerdatwork** [comment]
Only few hits that are completed with all YES(s) dont show up. Its pure gamble when I do the HIT. I have quite a list of hits that are answered YES and yet not paid or showing up in history. Also emails arent answered yet.

**Comment by nerdatwork** [comment]
@pscohn Also noteworthy fact, the count of Total Jobs is wrong. If I have a working hit with terminal and I am away for too long that hit is done by someone else. I get the Invalid STATE message. If I refresh it tells me the HIT is already done. Here it still adds that job to my TOTAL JOBS count. This is not correct at all.

**Comment by Ranky2211** [comment]
@pscohn  Has it affected ANY hits that are all answered "Yes"? Yes No Bug Found.Today 15 step Attend Hit Url of that Hit - https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cxd36cdf-cd4f-4aef-bcbc-5287dc1eceb6&browser=any&hitId=4399243&sig=6b51ded732da83b84f2e7c51ed4f13222af1c697d478bfc681d9a3e02cea1f1d&turkSubmitTo=%2Fthanks&workerId=33432784.Thanks

**Comment by BV25** [comment]
I agree with @Ranky2211 I also had an Attend HIT which was passed (All YES, no report). It was a long-stepper and it really is disappointing to not get paid as it took 20 minutes to complete.

**Comment by Genesis2015** [comment]
It happened with Avant test too :(

**Comment by pscohn** [comment]
The core development team identified a possible fix and pushed it out last night PST - has anyone experienced the issue in the last 12 hours or so?

**Comment by nerdatwork** [comment]
Nothing is fixed as of this moment. Hits with NO or other answers are definitely not credited. Some hits dont show up even after clicking all answers as YES. Mac OS terminals are still truncating urls on their own after we press enter in the safari browser. Failed to take screenshot still happening. My favorite Application error still there. Oops another worker ... still there. What was the fix about ??

**Comment by pscohn** [comment]
@nerdatwork we're focusing on the issue in this topic - there are other open issues for the other bugs, but let's keep the discussions separate.

**Comment by nerdatwork** [comment]
@pscohn Duly noted. Regarding the issue in this topic. Few hours ago I did a jobs and they havent showed up.

**Comment by Ranky2211** [comment]
@pscohn Hi Yes I experienced today Zenifits 20 step Hit.I think this issue with those HIT who have more than 15 step.It is very disappointing putting so much labour and time and got nothing.Url of HIT https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cxe021f8-daad-4025-a56d-99906c1f98da&browser=any&hitId=4520423&sig=38cfca98666204ac1dd073f9b4e67ed3ccdaa7abf6c0300afc9017130585434a&turkSubmitTo=%2Fthanks&workerId=33432784  Thanks.
![zenifits hit](https://cloud.githubusercontent.com/assets/15828832/11825303/5378d192-a3a4-11e5-8da5-68a99deab797.png)

**Comment by nerdatwork** [comment]
This hit never showed up in the history

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx6963aa-eb12-4a7f-9fde-7f08bb1baab3&browser=any&hitId=3979334&sig=1938a9b50b7b0073783f9a099ffd0655e484cdbbac0ea4eec8022c430e859e57&turkSubmitTo=%2Fthanks&workerId=11244952 6 steps

If it helps at all.

**Comment by pscohn** [comment]
@nerdatwork Did you get paid for that job? It is showing up in your account on our end that you completed the job and it was paid.

**Comment by nerdatwork** [comment]
@pscohn Yes but it was like after an hour or so I waited for 15 mins after doing the task before posting it here. Are the bonuses being paid for 10 or more jobs ?

**Comment by Ranky2211** [comment]
Hi @nerdatwork you can crosscheck it by seeing bonus notification in Crowd flower dashboard in which assignment id mentioned (cxfdd328-2d70-4a48-870f-d3ece8dc70ac) like Congratulations, you were bonused xx cents for your work on Test A Web Application Using Any Browser! Hey nerdatwork , You work was approved; here is the promised bonus of xx for completing unit cxfdd328-2d70-4a48-870f-d3ece8dc70ac

**Comment by nerdatwork** [comment]
@Ranky2211 Thanks I will look into it ;)

**Comment by begsoon** [comment]
Guys it  is not only problem when we go NO or when we have hit with 15+ steps.I have both situations when bonus dind't come. Most of hits didn't come when I do 4 5 hits in row..and 1 or 2 bonuses didn't come :)

**Comment by belmaMes** [comment]
In the last few days I did about 20 jobs that weren't paid.I did most of them two days ago, but today I had the same problem. My ID is 34464690

**Comment by ihorpolianetskyi** [comment]
over the same number of job (hit) https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx332f02-a8bc-4610-856e-4a88e8847a63&browser=any&hitId=4601340&sig=2f46693d8c5baab344f7258eb5fd3f047001b99723a8c0929cb135eb353cde39&turkSubmitTo=%2Fthanks&workerId=33330543

**Comment by L4kshmi** [comment]
I Dont have received any payment. My id is 35548639

**Comment by zykezzz** [comment]
Hello there,if you find a complete fix on this issue, will you compensate all the unpaid hits? Even if we dont file tickets? Im sure there are contributors out there like me who doesn't remember all the hits we did. I hope you can find a fix soon. Thanks for the hard work.

**Comment by begsoon** [comment]
No bonus of 10% tonight :-1:

**Comment by pscohn** [comment]
Just a quick update -

We identified a possible reason for this problem and made a change that might fix it in the short term. If anyone performs a job (after this message) and it doesn't show up in your history/bonuses within an hour or so, you can post the job url here so we can keep debugging.

**Comment by nerdatwork** [comment]
Awesome @pscohn rocks. My fingers are itching to do the next job ;)

**Comment by awnosa** [comment]
this test not paid and I'm finished this task to the end without any problem, this is url of task

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx1053c7-b4ef-443a-81b5-b0fcdccff033&browser=any&hitId=4622631&sig=6d5e58d3ce23cb9749f3a2f3317250034ceeaef83f8a427f803fb57b22f404e3&turkSubmitTo=%2Fthanks&workerId=32656569

11 steps

my ID 32656569

this is url of failed test not paid

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx6a2d94-26f4-48e1-915e-1764a37ef434&browser=any&hitId=4622425&sig=60c5e7ccbd753d7954dc0ed455c703b9481641a9abeadd59bafd13159bb0598e&turkSubmitTo=%2Fthanks&workerId=32656569#

17 steps

![2](https://cloud.githubusercontent.com/assets/16338438/11873312/b6f77e7c-a48e-11e5-9d4b-3f292cc5a847.png)

![default](https://cloud.githubusercontent.com/assets/16338438/11873316/ba10b984-a48e-11e5-8968-ee26278ca2b7.png)

**Comment by Dizel9** [comment]
@pscohn 

Here is my last hit , Polleverywhere , 29 steps , i didnt paid for it.I finished it without error and its not in my statistcs. 
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx583ebb-b8d5-4325-9a32-0cb1f7b2cf1d&browser=any&hitId=4574834&sig=f006e4ebbeb7a0fb005a735261fa6a464a400758ee4015a8498c0fdaae38f9cd&turkSubmitTo=%2Fthanks&workerId=31852896

**Comment by pscohn** [comment]
So, it looks like no one has spoken up about hits from today actually missing payments (awnosa's were older), so after tomorrow if there are no new reports I'll close the issue.

**Comment by pscohn** [comment]
I'll also add that we'll try and see if there's a way to credit those of you who missed payments due to this (but it may not be possible to know which jobs to credit).

**Comment by awnosa** [comment]
This task I finished it today to the end without any error, but not shown in history job and not paid until now.

16 steps

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cxf19062-2c8f-4d78-8dc1-8d907de52452&browser=any&hitId=4611342&sig=788cf91f2dd2c7a4efa1f53f0ff935f13e35d2256f5a34cc3ff14fa4476e037c&turkSubmitTo=%2Fthanks&workerId=32656569

**Comment by Acromastyc** [comment]
Hello, I already contacted CrowdFlower regarding my problem, but they have told me to contact RainForest support. My problem is that I receive the payments for each job done and it says that I have received all the bonuses ( a total of 308c ), but I haven't received any of them. 
Hit Id of the jobs that I have completed and haven't received the bonuses: 834602794 / 818477798 / 817510214 / 816981779 / 817510214 / 831910219 / 817510102 / 835535396 / 817510102 / 818477798. My contribuitor id is: 9974830 .

**Comment by YOYO50** [comment]
Still missing payments from 9 days ago and 1 from today.  I had to report an error and the hit never filtered to my dashborad, so I was not paid

https://app.rainforestqa.com/job/4087020/2d6a587dba05f98e7

**Comment by kwimy** [comment]
The mistery of the missing hits...
Today I missed another and don´t know how can I claim, I can´t find the URL in the history of my browser but it was a 19 steps hit of PollEverywhere, in step 10 had to say if a picture that had upload in step 9 was visible,I've been waiting more than 10 minutes for the image load but image stays loading and never appears.
I´ve reported the hit and doesn´t appear in my hits history like many others who have disappeared during the last 2 weeks or so.

**Comment by nerdatwork** [comment]
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx8cd69a-70ed-4827-a7ea-4a87957fb718&browser=any&hitId=3979334&sig=03803eab2c373a279d297f98d558af2666a8faad648e2f343222b71f548f4217&turkSubmitTo=%2Fthanks&workerId=

Doesnt show up in the history. I finished it just now

**Comment by pscohn** [comment]
@nerdatwork that job is showing up in our system as paid to you. Do they show up now / have you received payments?

**Comment by Dizel9** [comment]
@pscohn 
I didnt have problem 2 days in row but today , there is 1 missing payment in my notifications. I looked 3 times until until now and its not recived. Here is HIT ID :
- https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx91d660-4e8c-47fe-b0be-b481664183b5&browser=any&hitId=4559864&sig=bcf124ad229e76450ad6574f09253220f6adbbda403b7fb81a05ebe191433aa7&turkSubmitTo=%2Fthanks&workerId=31852896

**Comment by begsoon** [comment]
Polly of 31 step didn't come to bonus history :-1:

**Comment by kwimy** [comment]
The mystery of the missing hits remains unresolved.
A few minutes ago I had to report Attend hit, was 19 steps and I had to report it in step 16,doesn´t appear in my history and I´ll stay without being paid, should correct this error as soon as possible.
I'll have to start making screenshots to see if that way you can check that I sent that hit and can pay me.

**Comment by nerdatwork** [comment]
@pscohn yes that second hit was paid but the updated hits above are still pending.

**Comment by ihorpolianetskyi** [comment]
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cxcb4a85-9de7-44f2-9f23-ad7016f39a5b&browser=any&hitId=4651548&sig=525724db658598e9b59aba02f873d835ca62fc7eaa300c7f8bd75c2fafd258bf&turkSubmitTo=%2Fthanks&workerId=33330543
and
again in the history of paid work is not reflected very pity


2015-12-24 10:07 GMT+02:00 nerdatwork <notifications@github.com>:

**Comment by ihorpolianetskyi** [comment]
a very big thank you! You are the best!!!

**Comment by koolorcool** [comment]
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx6e8fa1-883d-415b-a532-bf84bc88379a&browser=any&hitId=3658547&sig=362ec57ba35663dc03a4a5a128714a36c8df1549122e43e21d9237b332e6d7e2&turkSubmitTo=%2Fthanks&workerId=21039758

Not paid and not showing in history.

**Comment by YOYO50** [comment]
I have still not been paid, for the 2 missing hits from December 8th.  Is there a time frame when I will be paid?

**Comment by awnosa** [comment]
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx44e978-2e36-4d86-9d8f-e38180074abc&browser=any&hitId=4622192&sig=eb08cab70beaea9be985aab5e15fe5cb77952e726a029241452dcc5863733ffb&turkSubmitTo=%2Fthanks&workerId=32656569

this task not paid until now, if this happen beacuse other tester do this task or not

**Comment by YOYO50** [comment]
I have still not been paid, for the 2 missing hits from December 8th.

**Comment by suchitra1957** [comment]
I have not received the bonus for Hit ID: 3VJ4PFXFJ37L78SQ7VZZX9HW61AUAM. It is now over 24 hrs.

**Comment by KabakF** [comment]
This issue still goes on

**Comment by mueller2511** [comment]
Hi RF Team,

i see the bonus is missing for some of the hits again which i noticed from last 2 days for me. Here are some of the links which are missing payments. i hope you fix the issue soon.

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx8f1d6e-db5a-4a91-bd79-63dd9de9b079&browser=any&hitId=4349769&sig=c28df04fd62236242e16af423229a550314190176b8c86f2587265eb659d6e96&turkSubmitTo=%2Fthanks&workerId=34225825

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx064909-0c2c-4251-8159-91bad4efaaaa&browser=any&hitId=4501389&sig=4424e817331cdc648e56a98fe7831c3e1b3f1e8c0aa3836b108c35bcfa95e61f&turkSubmitTo=%2Fthanks&workerId=34225825


https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cxaa1b5b-4d9f-4bae-8a85-ae5685960419&browser=any&hitId=4368372&sig=95dd2ba0a89be5f6190e10c3fac4fda0cf53522f25ad9b7f28a72e1547c9ae0a&turkSubmitTo=%2Fthanks&workerId=34225825

Thanks

**Comment by Dizel9** [comment]
HIT not paid , now its more then 24h from submited this job. 
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cxc993f7-3c5b-42b3-bd14-016dccb1c7f9&browser=any&hitId=4551739&sig=1eb35c6c498b09f6b70903407b0d2346587081e0d7dce8a19c5c2d9daeaeb268&turkSubmitTo=%2Fthanks&workerId=31852896

**Comment by nerdatwork** [comment]
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cxe93132-eb47-400a-aa47-8afdfcf37514&browser=any&hitId=3326891&sig=ac8937171b40bc81147b90e0dcc3a718cbb9c1add89aa3fc61872c8fc69aeccf&turkSubmitTo=%2Fthanks&workerId=nerdatwork

still not paid after more than 12 hours

**Comment by YOYO50** [comment]
I have still not been paid, for the 2 missing hits from December 8th.

**Comment by nerdatwork** [comment]
Missing payment 1 more time
2. https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cxe24268-83df-4de6-9b58-3da860d9d428&browser=any&hitId=3981469&sig=4df229d6c4c0182fda5a719b9e82ee31cdce2b67733b663eacc4a024f231999b&turkSubmitTo=%2Fthanks&workerId=nerdatwork

When are the missing payments going to be made. I usually get replies when I post a link and its paid but there is absolutely no word for posted links and missing payments. Could you please elaborate as to what you are doing with them ?

**Comment by YOYO50** [comment]
Today I have a missing payment
https://app.rainforestqa.com/job/4525568/57619383ff220ae3f

On the job history tab it shows 779110886	ie11	 	00:00:00	—	—

I submitted the task and on the first step reported an error

**Comment by roko777** [comment]
This hit never showed up in the history

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx4dca93-7ca6-44ba-84f6-776d221ec44e&browser=any&hitId=3454440&sig=d03a1f27b8a539c9faca88709fa99f707bf69a3778644066188ca8b39f417c8f&turkSubmitTo=%2Fthanks&workerId=6594279

Yesterday it was the same thing, I have a missing payment.Hit about 30 steps (creating test students website.)

**Comment by yoges9** [comment]
i have not recieved bonus for this 34 steps job , it was  done successfully but not show in history nor bonus , it takes more than my half hour ,feeling  Fustrated.

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cxafcd0a-659a-44ab-b466-79dfbba251e2&browser=any&hitId=3971825&sig=ef1ed3e6008dd61ad07576cf50dfe1efa9a82c7a8a805e9dbbc9d0e161f4207f&turkSubmitTo=%2Fthanks&workerId=27799195

**Comment by ukd1** [comment]
@pscohn can we get an update here?

**Comment by pscohn** [comment]
Sorry for not updating when this happened - on Jan 20 we paid for 113 jobs due to this error, if you have an instance after this date where you haven't been paid, please open a ticket in your profile and we'll take a look.

**Comment by yoges9** [comment]
hi thanks ,

Yogesh
