### ISSUE TITLE
hello, good night friends, regarding payments gifhunterclub.

### ISSUE THREAD

**Issue by jombere** [rainforestapp/tester-chrome-extension#270]
I would like to know who besides me are not paying you anything at all? I miss more than $ 7 today, of which I have paid around $ 1.5. If anyone has information, please pasarmela, thanks in advance

**Comment by nerdatwork** [comment]
Read this  #256

**Comment by Julekhaakhter** [comment]
Got the payments after reporting it to gifthunterclub.

**Comment by JrRandy** [comment]
Please close thread if issue has been resolved.
