### ISSUE TITLE
About my worker id

### ISSUE THREAD

**Issue by SliderKPP** [rainforestapp/tester-chrome-extension#274]
Hello everyone.

I have a really big problem and it's stupid in the same time...So let start, I have my rainforest account for more than one year, since when I had my neobux account, the thing is when I start to do jobs on rainforest money went directly on neobux account with this worker id "32206861" now my neobux account no longer exist, now I raise money directly in crowdflower elite, and 2 days ago in jobs list I saw "Web Test application for Rainforest QA" I knew I have already an account and I said to do jobs again...and now it's the stupid part..I forget this account had my old worker id from neobux "32206861" and I worked 2 days for nothing...I think the money are lost..that neobux account no longer exist, but it's a way to change now my worker id with the new one from crowdflower elite "32207386"??? I don't think it's soo hard are just some simple numbers..

P.S. Sorry for my english and have a nice day.

**Comment by nerdatwork** [comment]
Send support ticket to **tester@rainforestqa.com** mentioning all the details so Rainforest can help you better.

**Comment by SliderKPP** [comment]
Thank you for your answer, I opened already a ticket this morning, now I'm waiting for them to answer, I hope at least they can change my worker id I don't care for that 2 days when I worked for nothing.

**Comment by angelfelixgarciamolina** [comment]
Este problema es muy común y trae locos a muchos, yo por ejemplo soy uno de ellos, lo que voy a hacer es resetaer todas mi cuentas y empezar de nuevo

**Comment by SliderKPP** [comment]
Angelfelix I think you said it's a common problem or something like this? Can you translate, if you don't mind?

**Comment by angelfelixgarciamolina** [comment]
Excuse me jejejeje it is the translate:

"This problem is very common and brings many crazy, I for example am one of them, what I'm going to do is resetaer all my accounts and start over"

**Comment by SliderKPP** [comment]
Thank you very much, and how I can reset/delete rainforest tester account? And after that I need to find another task in crowdflower jobs list?

**Comment by angelfelixgarciamolina** [comment]
That would open a new account on each web page, including CF, RF, and the channel you use

**Comment by SliderKPP** [comment]
To open a new account on CF too?? But you are not allowed to have more than one account on CF.

"Please be reminded that, per our Terms of Service, your CrowdFlower account will be subject to automatic suspension if you: 

1) create more than one (1) CrowdFlower account
2) link 5 or more Contributor IDs from SuperRewards, or more than 1 Contributor ID from any other task distribution channel
3) link more than 25 (total) Contributor IDs to your CrowdFlower account"

**Comment by angelfelixgarciamolina** [comment]
Yes, you're right.

That such a bad thing that of the id, seems that there is a rally between CF and RF and none resolves the channel where you pay.

It seems to me that willingness to resolve it there is, the only thing close to a solution RF gave me, they told me that I could request another id but it turns out that when I click on the task of RF CF message is that I have already made the maximum of possible tasks.

I hope to see if they throw a new registration link. We must have patience.

**Comment by SliderKPP** [comment]
Yes, the patience is everything.

**Comment by kristen-allie** [comment]
Hey, @SliderKPP! We're looking into this and will update you when we know more. Sorry for the wait!

**Comment by kristen-allie** [comment]
@SliderKPP I don't think it will be possible for you to retrieve funds from the RF profile (32206861) associated with your deleted neobux account. I'm trying to find out for sure though! 

If you are having trouble logging in or using your new RF profile (32207386) associated with your CrowdFlower Elite account, you can try to claim the profile again. You should have the claim profile link in your provider inbox. 

And make sure that your CrowdFlower Elite RF profile has a different email address from the RF profile associated with your deleted neobux account :)

**Comment by kristen-allie** [comment]
Hi @SliderKPP. All your bonuses for account 32206861 were paid on our end as you completed jobs, but since your Neobux account was deleted, you didn't receive those payments. You'll have to contact Neobux about whether or not you'll be able to receive those payments. Sorry there's nothing we can do :(  Unfortunately, I wasn't able to find contact info for Neobux support.

**Comment by angelfelixgarciamolina** [comment]
Hello, is it possible to unsubscribe from Rainforest and start again with my kannst channel? This is my id 31266106 active.

My count of neobux not exists

**Comment by angelfelixgarciamolina** [comment]
Excuse me, not is "kannst", is clixsense
