### ISSUE TITLE
Failed To Screen And You Have Done Maximum Every Time Back Again !

### ISSUE THREAD

**Issue by felipeinsanobr** [rainforestapp/tester-chrome-extension#275]
Dear Staff RainforestQa
Good afternoon, good day today was not bad ... but I realized that the Rainforest made a new update, it again put the You Have done the maximum .... because she put again? because before was giving to 2 hit at the same time and so you again withdrew it this damn message back!
Simply you have to see it further during the HIT all the time ta giving Failed to Screen ...
Please fix this because is very hard work, to the month end .. I have 3 kids to support and so here is my source of income.
Sincerely
Felipe
await response

**Comment by felipeinsanobr** [comment]
ERROR: Something went wrong on our server, sorry about this. Please reload and try again.

**Comment by MarinaCec** [comment]
"Failed" all the time =/

**Comment by erdeminofff** [comment]
Got 38 step Slated Hit but I can't finish becasue of this screenshot errors and terminal connection lost. Very annoying

**Comment by felipeinsanobr** [comment]
And more, every time the Failed to screen, we have to F5 and start all JIT

**Comment by zfonck123** [comment]
same here

**Comment by felipeinsanobr** [comment]
the system is too slow ... so the terminal both the payment in history

**Comment by nerdatwork** [comment]
@felipeinsanobr Could you try to be polite and **NOT** use all caps.
