### ISSUE TITLE
Testing errors

### ISSUE THREAD

**Issue by mlujan** [rainforestapp/tester-chrome-extension#279]
I get a lot of screenshot errors. Also I have noticed that the app sometimes has errors during test.  This leads to either redoing the test or not being able to finish at all.  

Anyone have experience in multiple os(mac,linux.win) that could tell me which platform is the most stable.  

My current Environment:
Win 10
i5 desktop 8gb ssd

Tomorrow I will test on a live boot of linux and see if I notice any difference on same hardware or the laptop.

**Comment by mlujan** [comment]
![image](https://cloud.githubusercontent.com/assets/1491534/16506156/a426062e-3eee-11e6-9bb6-2120aeed1c32.png)

**Comment by mlujan** [comment]
That is an example of an error that makes me restart the whole test.  This uses more vm time and prevents me from doing quality work efficiently.

**Comment by nerdatwork** [comment]
@mlujan You can use any computer and operating system. Its **NOT** dependent on hardware.
