### ISSUE TITLE
HITs expire within a minute

### ISSUE THREAD

**Issue by BV25** [rainforestapp/tester-chrome-extension#28]
Hello @pscohn  and @ukd1 

This is with respect to a new (and serious) error that has been going on for a few days.

The problem unfolds only with 'We've reached the maximum number of concurrent users" message. The plugin opens a HIT but the page changes to the aforementioned error due to maximum testers.

Once this message comes up, we only have 1 minute to be able to get a working Terminal. It is almost impossible to get this within a minute. After 1 minute, if one tries to secure a terminal, it says "This assignment is already completed". This is kind of, unfair.

This is a serious problem and I urge you to kindly look into it urgently, as there are many more users who are plagued with it too, so it's not an isolated case.

Thank you.

**Comment by nerdatwork** [comment]
There are already working on it and this issue has been covered in earlier threads.

**Comment by BV25** [comment]
I haven't come across this 1-min assignment completed timeout issue in any other threads here.
