### ISSUE TITLE
Screenshot reporting

### ISSUE THREAD

**Issue by priggy** [rainforestapp/tester-chrome-extension#280]
it has became a pain in the ass with this error returning from browser... Failed to report a screenshot... especially when hit job with lots of steps, and the problem happens somewhere near the end... and you need to refresh browser because half an hour waiting and clicking same YES or NO button and waiting to move on to next step is so frustrating! And then you do it all over again!
...............................................

**Comment by rifatrahman** [comment]
same.

**Comment by algset777** [comment]
same here
A full hour with the job, and in the end ... nothing !

**Comment by rubikks** [comment]
same for me since yesterday but not for all hits

**Comment by hunt40** [comment]
screenshot errors all time since yesterday

**Comment by edwardbass** [comment]
This is fustranting I had this problem in a hit I tried and tried many times but It was always the same message: Failed to report a screenshot so I decide to restart the hit. The fact is that When I introduced the datas (email) I got this message: the customer email already exist this because I used before. What can I do?

**Comment by algset777** [comment]
I got (job abandoned) Because of this error !!
It's so frustrating !

**Comment by nerdatwork** [comment]
@priggy If you are not facing this issue please close this thread.

**Comment by JrRandy** [comment]
@nerdatwork : Issue happens at least a few times daily to me, and I am sure others.  Most of us just power through it now I think :)

**Comment by JrRandy** [comment]
#7 Looks like this has been a long outstanding issue.  Can we close this thread to keep a single thread on the issue?

**Comment by kaytsu** [comment]
same - step 18 of 22 had the same error and then refreshed (after trying to get the screenshot for 5 minutes) and got to step 6 of the same test before it did the same screenshot stuff - finally just had to close the task because it wouldn't let me finish.
