### ISSUE TITLE
"Application Offline for Maintenance"

### ISSUE THREAD

**Issue by AndyARB** [rainforestapp/tester-chrome-extension#281]
In the last half hour, I could not do any work due to an error that appears to enter a web in the terminal.

![pruebarain](https://cloud.githubusercontent.com/assets/20212027/16506526/f4dc7c54-3ef0-11e6-8ed0-7e6dd2d52c4b.png)

Currently I lost almost 5 job due to this maintenance error, is normal? It is true they are doing such maintenance?

**Comment by mlujan** [comment]
Yes I have this error too on a few recent jobs.

**Comment by Electroglitch** [comment]
Click No report and your job is done. :)

**Comment by nerdatwork** [comment]
@AndyARB This is **NOT** an issue. Whenever you encounter any error INSIDE the terminal or face issue with the interface while testing, report it.

**Comment by dreicaan** [comment]
I believe that the application error AndyARB is talking about is not the one inside of the terminal browser, but the one that shows up instead of the entire job page inside your browser, so there is no way to report it. As you can see in the screenshot, there are no Yes and No buttons. :)

**Comment by nerdatwork** [comment]
@dreicaan If you see the image properly you can see its a screenshot of terminal and not outside the terminal. When you paste the main URL and it leads to such page, click Take Screenshot and then in next step click NO and report it mentioning all the details.

**Comment by dreicaan** [comment]
@nerdatwork Oops, didn't notice the terminal number in the top left corner, sorry! :)
Yes, in that case, report it. But what if it happens outside of the terminal? I was working on a step and got connection lost,

**Comment by nerdatwork** [comment]
@AndyARB If you arent facing this issue please close this thread.
