### ISSUE TITLE
NO VMs FREE FOR TASK, LOST 10-15 JOBS ON MY FIRST DAY!!!!!!!

### ISSUE THREAD

**Issue by sighanchi** [rainforestapp/tester-chrome-extension#284]
on my very first day i got 10-15 jobs in about 5-6 hours but was unable to start & complete a single task as it states error **"No virtual machines free. try after some moments** after refreshing after 40-60 seconds sometime 2-3 minute it changes error to "another tester accepted the task" so haven't got a single task from RF can anyone tell the possible cause for it and the solution to the problem. PLEASE

**Comment by zfonck123** [comment]
not is a error...

**Comment by zfonck123** [comment]
another tester aceepted the task is a normal message. only u need refreashing and waiting...

**Comment by zfonck123** [comment]
Another worker accepted the job before you! It doesn't look like there is any more work for any of our hits; please try again shortly - you can refresh this page, or close and wait for a new job. this is a normal message

**Comment by felipeinsanobr** [comment]
Another worker accepted the job before you! It doesn't look like there is any more work for any of our hits; please try again shortly - you can refresh this page, or close and wait for a new job. this is a normal message .
It's normal !
Wait 
This message is more than You have done the maximum amount of work on this job. You have done the maximum amount of work on this job.

**Comment by zfonck123** [comment]
and in ur firts job u get alots jobs training

**Comment by sighanchi** [comment]
i have completed my training and now its second day i still get jobs with chrome extension but as i accept it message is shown as per above so is my net slow or any other problem from my side also my extension opens page after sometime of displaying "YES" in extension so can it be a possible cause.

**Comment by nagabhyru** [comment]
"No VM's" and "Another worker" messages are common when you are working in weekends (Saturday and Sunday) due to less number of jobs and more number of workers. In week days you will get jobs.

**Comment by nerdatwork** [comment]
@sighanchi The extension is working perfectly and whenever you get such messages, close the tab and wait for the next job. There is nothing that you can do for getting "more" jobs. Everybody gets these messages.
