### ISSUE TITLE
I do not receive my bonus 10%

### ISSUE THREAD

**Issue by tulko** [rainforestapp/tester-chrome-extension#286]
a while ago I not collect my daily bonuses. Send a tiket two days ago and no response

**Comment by felipeinsanobr** [comment]
here is normal ... You do 10 Tasks for day?
I do more 10 normaly

**Comment by zfonck123** [comment]
this problem is with CF , not Rainforest. i think

**Comment by tulko** [comment]
No, because there is no payment notice in my history of RF. Do not make me explain, a lot is happening.
