### ISSUE TITLE
I do not receive payment of my work.

### ISSUE THREAD

**Issue by jombere** [rainforestapp/tester-chrome-extension#287]
good, today I present the case of a friend, who is not receiving payments rainforest, would like to know this, thanks in advance is due.
![13528089_1010238879024743_3579203983318619829_o](https://cloud.githubusercontent.com/assets/15624230/16537227/62516058-3fcb-11e6-8b51-d4ddb4e064f5.jpg)

**Comment by kaytsu** [comment]
Did they just start today? When i did my training tasks I didn't get any bonuses. Neither did my mom if I remember correctly.

**Comment by samballode6** [comment]
This is training jobs ?
Training jobs indeed don't get payment.
Will get payment in next actual jobs if you past the training test.

**Comment by nerdatwork** [comment]
@jombere Why are you posting your friend's issue ? Why cant he post it himself or herself ?

**Comment by samballode6** [comment]
Yes, this is very funny...
Posting profile someone else ...
Very suspicious...

**Comment by jombere** [comment]
@samballode6 @nerdatwork  It is new in rainforest and has no knowledge of these forums, I did just the favor.

**Comment by nerdatwork** [comment]
@jombere Everybody is new at first. Ask that person to post his/her problem. We are all here to help.

**Comment by maciejgryka** [comment]
@jombere please open a support ticket for any payment issues. We only track problems with the Chrome extension itself in this repository.
