### ISSUE TITLE
When refreshing/closing the tab while doing a hit, ask for sure

### ISSUE THREAD

**Issue by NeoWorker** [rainforestapp/tester-chrome-extension#292]
Just a suggestion. I just had to redo a hit because I accidentally clicked the refresh button in my browser. So it would be nice to have a popup asking for sure when closing or refreshing the tab while doing a hit. Sorry my english.

**Comment by ahmedofhell** [comment]
Nice idea +1

**Comment by playpin** [comment]
Good suggestion
Even i refreshed my browser once instead of refreshing in terminal. 
Of course my mistake but a confirmation will be handy

**Comment by pscohn** [comment]
That's a good idea. I'll close this issue and open one internally.
