### ISSUE TITLE
Tester Notifier and Fullscreen Video

### ISSUE THREAD

**Issue by IceCreamCake** [rainforestapp/tester-chrome-extension#293]
I just want to ask is the Rainforest Tester Notifier still working normal (popup new test when it's availble) when i watch video with full screen (like youtube....) on chrome. Really precious any help, thank you and have nice day!

**Comment by nerdatwork** [comment]
Yes it is working normally. If you are watching a youtube video and the job loads but you fail to start it in time by the time  you finish watching the video, you will see the Job Abandoned page. This is assuming that the extension doesnt turn OFF while you are watching the video.

**Comment by IceCreamCake** [comment]
I got it, thank you very much.... oh, and does it still popup when i'm watching full screen. I worry about the job not popup, so i don't know and missed it.

**Comment by nerdatwork** [comment]
It wont notify you as such when in fullscreen, you have to manually check it.

**Comment by IceCreamCake** [comment]
That's all i need to know. Thanks, your're wonderful :)

**Comment by nerdatwork** [comment]
You are most welcome. I would suggest closing this thread if you are satisfied with the responses.
