### ISSUE TITLE
how to get more jobs?

### ISSUE THREAD

**Issue by mircka** [rainforestapp/tester-chrome-extension#294]
How can I get more jobs? It says 20% bonus for 100 jobs at day, but I hardly get 10-15 jobs for a day.

**Comment by helloworld111gh** [comment]
to get jobs, you have to turn on the extension, and stay active.

**Comment by nerdatwork** [comment]
There is nothing extra you can do to get "more" jobs. As long as you are active (meaning **extension says NO**) you will get jobs when they are available.

**Comment by mircka** [comment]
So,is there anyone that had 100 jobs for a day?I'd really like to know.

**Comment by helloworld111gh** [comment]
yes, it is possible to get 20% bonus, there are many people who have done
so. as this is not a problem with extension/tester interface, can you
please close this issue?

**Comment by mircka** [comment]
o.k.

**Comment by qpPykT** [comment]
@helloworld111gh "there are many people who have done
so"
Ha-ha you mean what it's a small group who have unlimited tasks per day or have high prioritize with getting tasks.
