### ISSUE TITLE
Unknown Error?

### ISSUE THREAD

**Issue by srsaurabh32** [rainforestapp/tester-chrome-extension#295]
![what is this error](https://cloud.githubusercontent.com/assets/19935406/16581935/a04d1342-42c9-11e6-8fcd-f2145e83f84a.PNG)

What does it even mean?
No error...And this is happening since last week. Anyone else? Unable to do jobs because of this pink bar, having no clues, what's happening?

**Comment by ilegalna** [comment]
See the end of the link ... Are you missing thanks&workerId=.....(your ID)

**Comment by nerdatwork** [comment]
@srsaurabh32 I dont think the URL of the HIT is right. This URL is specific to "browser=ie8". Rainforest HITs are usually "browser=any" kind.

**Comment by srsaurabh32** [comment]
@ilegalna its not missing, it is there. I have contacted RF for the same but they did not respond. Anyways thanks for suggestion.

**Comment by ilegalna** [comment]
I hope you'll get an answer from RF. Be sure to try one more time to delete the extension and re-install it.

**Comment by pscohn** [comment]
Are you still seeing this frequently @srsaurabh32 ? How often? If you see it again, you can open up the Chrome developer tools and look for errors in the javascript or network tabs, and post a screenshot here.

**Comment by srsaurabh32** [comment]
@pscohn yes i am still seeing it. several times in a row. I dont know why. I will post the screen shots soon, as this thing never stops.

**Comment by srsaurabh32** [comment]
![what is this error 4](https://cloud.githubusercontent.com/assets/19935406/16696239/b817e2be-4561-11e6-82a3-fc2290a9b385.PNG)
![what is this error 1](https://cloud.githubusercontent.com/assets/19935406/16696240/b825c7d0-4561-11e6-8f3e-9d3a09dc04df.PNG)
![what is this error 2](https://cloud.githubusercontent.com/assets/19935406/16696242/b82e6ac0-4561-11e6-9baf-1b05c74cc243.PNG)
![what is this error 3](https://cloud.githubusercontent.com/assets/19935406/16696241/b82e48b0-4561-11e6-907a-603708372dab.PNG)


if need something else please tell me....i want to get rid of this problem. Thank you.

waiting for your response.

**Comment by nerdatwork** [comment]
@srsaurabh32 Are you using Mturk to do those HITs ?

**Comment by pscohn** [comment]
@srsaurabh32 are you using the chrome extension or making your own links?

**Comment by srsaurabh32** [comment]
i am definitely using chrome extension not making my own and @nerdatwork i do some hits on mturk as well.

**Comment by srsaurabh32** [comment]
and now this error....this also make its presence several times
![error](https://cloud.githubusercontent.com/assets/19935406/16697043/5e2c6a28-4565-11e6-86cd-c786baa38555.PNG)

**Comment by nerdatwork** [comment]
@srsaurabh32 Now this is the right error message also like I mentioned earlier check the URL of this HIT. It shows browser=any and not browser=ie8

**Comment by srsaurabh32** [comment]
and on refreshing this came

![error 1](https://cloud.githubusercontent.com/assets/19935406/16697105/b6875250-4565-11e6-8017-7019465589de.PNG)

**Comment by srsaurabh32** [comment]
@nerdatwork i knew you were correct, but it does not mean the error I asked about does not exist....it does and it is irritating.

**Comment by pscohn** [comment]
@srsaurabh32 If you stick to using the extension and not mturk you'll have the same experience as other testers, and I would suggest not refreshing links unless you have reached the job page, so it is fair for all testers to get a job.

**Comment by srsaurabh32** [comment]
i know that how refreshing page works but that is not the solution.....i am getting this error without any refresh. something is terribly wrong....why am i getting browser=ie8 instead of browser=any as @nerdatwork suggest.

**Comment by srsaurabh32** [comment]
@nerdatwork you are right that whenever this browser=ie8, It has not landed me on the job window but the same error each time.

**Comment by nerdatwork** [comment]
Let the extension open the HIT. You will definitely land on a working HIT like rest of us. Dont do anything to the URL.

**Comment by srsaurabh32** [comment]
@nerdatwork  look i value your suggestions and respect....but i am aware of these facts, i have done each and every thing:
1. wait for the extension to load the test.
2. do not refresh the page
3. removed the extension 
4. reinstalled the extension
5. reinstalled chrome as well

what else?

sorry no offense but i am frustrated.

**Comment by nerdatwork** [comment]
I understand and I am only trying to help. Can you try it on another computer ?

**Comment by srsaurabh32** [comment]
I can agree on this....I will try. May be there is an error in my machine. And why has @pscohn closed this issue. This is absolutely rude.

**Comment by nerdatwork** [comment]
He isnt being rude. He is one of the most helpful RF members here. He has to rectify issues and manage this place. So other open threads can be resolved. Try the things we talked and open another thread if you face any more problem. We are all here to help.

**Comment by srsaurabh32** [comment]
okay.....thanks. I will open another thread if problem still exists. thanx again @nerdatwork for your time. Sorry if I was rude somewhere..

**Comment by nerdatwork** [comment]
Thank me when its resolved :) Good luck

**Comment by srsaurabh32** [comment]
yup...sure

**Comment by srsaurabh32** [comment]
@pscohn I am still facing the **same** issue.
