### ISSUE TITLE
Job Abandoned on long hits

### ISSUE THREAD

**Issue by Leonaam** [rainforestapp/tester-chrome-extension#296]
I've got the message "Job Abandoned" when doing a hit a little longer than the usual (25 steps).

It hadn't passed much time since i'd began the task and I got this message. It wasn't enough time for me to complete the job.

**Comment by muerte01** [comment]
same here i was trying to complete a hit (35 steps) and in the step 25 lost conection and star over then page show me job abandoned :s

**Comment by nerdatwork** [comment]
@Leonaam @muerte01 Please read this

https://github.com/rainforestapp/tester-chrome-extension/wiki/Idle-Policy

**Comment by Leonaam** [comment]
@nerdatwork none of this apply to my case. I was doing the hit and then I got "Job Abandoned", aproximately 10 minutes after accepting the job.

**Comment by pscohn** [comment]
@Leonaam do you have the job ID? If not you can give your worker ID and the approximate day and time of your job.

**Comment by limsanto** [comment]
i think RF should check their idle timer rules
it happen to me twice, "job abandon" when job in progress, usually in long hit
From my observation, it must because the idle rules is set by how long from we get the job not from how long we have been idle
