### ISSUE TITLE
you have to close the tab when done in order to get the next job

### ISSUE THREAD

**Issue by ukd1** [rainforestapp/tester-chrome-extension#3]

**Comment by sweeneyapps** [comment]
if u accept my pull request https://github.com/rainforestapp/tester-chrome-extension/pull/340

then this solve this problem.  w/ my code, you don't have to close the tab when you re done in order to get the next job.

**Comment by cookin2** [comment]
Hi Paul!

Have the people at RF given the ok for members to use your app?

**Comment by sweeneyapps** [comment]
@cookin2  this is only proposal to do Pull Request.  we'll see if they accept my Pull Request.  If they do.. then that's great..  It will solves all the problem at once.

**Comment by cookin2** [comment]
@Paul, I didn't know how things work, thank you for the explanation :)

**Comment by sweeneyapps** [comment]
@cookin2 that's ok..   What I really did was, I read their code and test them.  I find bugs and then fix them by editing them.  It's my own copy from their copy.   Then if I want my code to merge with their code, I have to submit Pull Request, it's a request for Rainforest to evaluate my code and approve it.   Once they approve it, then they might wait for another developer at their company to add some features and make some changes.. then the big boss approves the whole thing and it will be on the next update.

**Comment by sweeneyapps** [comment]
I closed my Pull Request anyway...  because in 2.0 is underway.

**Comment by pscohn** [comment]
This is no longer an issue with 2.0, right @sweeneyapps ?

**Comment by sweeneyapps** [comment]
@pscohn yeah, issues already resolved w/ 2.0
