### ISSUE TITLE
 worker type

### ISSUE THREAD

**Issue by Blackls** [rainforestapp/tester-chrome-extension#301]
Hello everybody, when enables here to be able to receive the hits is only appearing this message:

"Hit 2xxxxx7 is not valid for your worker type."

I would like a help to solve this, 
thank you

**Comment by luisdanielvc** [comment]
This is the same as #246 but nobody answers there, i have a friend with ID number 38418874 in the same situation.

**Comment by pscohn** [comment]
How often are you facing this?

**Comment by Blackls** [comment]
Direct. I made the record and say that I already have account since 2014 and can not do anything.
