### ISSUE TITLE
Is it possible to click to get a job instead of waiting notifier popup new job.

### ISSUE THREAD

**Issue by IceCreamCake** [rainforestapp/tester-chrome-extension#302]
I ask because sometime i saw RTesterNotifier transfer to "Yes" but no job popup, and few second (3-5s) later it change to No again. Any help would be great, thanks.

**Comment by nerdatwork** [comment]
That is not how the extension works. The extension polls the work pool for job and when there are jobs it will open the tab for you. We all sometimes see the extension turn to YES and no tab opens so dont worry its not just you :)

**Comment by IceCreamCake** [comment]
ohh, thank you very much. I just thought it's just me, so.. everything good :) Thanks thanks!
