### ISSUE TITLE
Question about You Have Done The Maximum 07/07/2016

### ISSUE THREAD

**Issue by felipeinsanobr** [rainforestapp/tester-chrome-extension#303]
Good evening / morning / afternoon good come talk about this maximum and I think it's the possible causes of advent.
Well what I have been noticing is that after finishing the HIT and give the submit it HIT this holding in the terminal and it is # Unavailable to do to carry out other work, given that even the finished terminal considers that I am / we are the old HIT to do.
So I do not know what it is, whether it is or BUG is a system event if it is anyway.
I would like to RainforestQa that an answer about it.
For yesterday from the evening it was impossible to perform a task when I HIT was performed, and after 10 ~ 20 minutes the server returned, then making me lose other HIT's.

I await a response

**Comment by felipeinsanobr** [comment]
Sometimes encounter BUG on the site and I report and also takes a century to return to normal, is always stuck in the Maximum.
When performing work without BUG he usually returns to normal without giving Maximum.
Sometimes we make the right to report the BUG and losing a HIT 30 steps, losing in Step room and only in ferramos after being arrested in the Maximum

**Comment by qpPykT** [comment]
@felipeinsanobr 
I can not understand what do you mean.

**Comment by qpPykT** [comment]
@nerdatwork 
Google translator is so insidious (tricky). Sometimes it translates text very differently than sometimes wants to say.

**Comment by felipeinsanobr** [comment]
kkk
I used the translator that he is bugged

summary :From what I barely understood was that you get stuck after clicking the button to submit and it took forever to submit thereby triggering the Idle Policy rule. So you lost lot of HITs because of that.
But because some friends are normal? without the maximum.
And in the morning I was normal? the afternoon for the evening was so.
this seems to be luck, not be with the maximum

**Comment by nerdatwork** [comment]
@felipeinsanobr You broke Google Translator buddy.

**Comment by felipeinsanobr** [comment]
What happens is that when you give submit on the HIT he holds the ID in the terminal, and with this there is the problem of the maximum.

**Comment by felipeinsanobr** [comment]
And this ta turning routine lately, is random ... sometimes it is me sometimes with some friends

**Comment by felipeinsanobr** [comment]
One day a friend got stuck in MAXIMUM all day, always when it came to hit all the other for she was holding, and yesterday it happened to me

**Comment by felipeinsanobr** [comment]
I'm thinking that the terminal once in a while Cali with some ID and leaves stuck in the Terminal for about 10 minutes as if it had stopped without nobody mess

**Comment by felipeinsanobr** [comment]
One day I counted, so that started coming from the HIT FR my hold on maximum and the others were normally, but 10 minutes later returned to normal giving another worker.

**Comment by felipeinsanobr** [comment]
Work on it here for almost 2 years and these errors comes only given after these latest updates.

**Comment by felipeinsanobr** [comment]
Finally, I think that once in a while this bug has been occurring randomly.

**Comment by qpPykT** [comment]
@felipeinsanobr 
Did you and your friend use same ip-address and id's or different?

**Comment by felipeinsanobr** [comment]
We are a group that do Rain, which we know only through the internet.

**Comment by pscohn** [comment]
I'm still not really sure what the problem is, but the "maximum" message usually happens after you finish a job until we are done processing your results. If you are using the extension it shouldn't give you another job until it is ready. If you have some other issue you open a new issue with some more details like your worker ID and a screenshot if it's relevant.
