### ISSUE TITLE
Good I have a question that can be mturk and CrowdFlower work simultaneously with rainforest ?

### ISSUE THREAD

**Issue by Niopup** [rainforestapp/tester-chrome-extension#304]
Good I have a question that can be mturk and CrowdFlower work simultaneously with rainforest ?

**Comment by nerdatwork** [comment]
@Niopup Could you try to explain more ?

Just so you know. Rainforest uses CrowdFlower to post jobs which can be accessed using the Google Chrome extension after you claim your profile. Mturk is an independent platform like CrowdFlower. Mturk is managed and owned by Amazon. Amazon, CrowdFlower and Rainforest are all different companies.

**Comment by helloworld111gh** [comment]
Unlikely, you are not allowed multiple active accounts on RF

**Comment by Niopup** [comment]
@nerdatwork 
I mean, if I can do tasks rainforest in mturk which is a different platform and perform tasks asu see the extension and CrowdFlower . Because I have mturk account and yesterday saw the tasks rainforest.

**Comment by nerdatwork** [comment]
Yes you can do Rainforest tasks from the mturk platform but you will get jobs ONLY from the Google Chrome extension. The jobs that are posted on CrowdFlower via Mturk are for recruiting new members only. If you read the instruction it says if you have already claimed a profile you SHOULD NOT do the job. 

Was that helpful ?

**Comment by pscohn** [comment]
You can do RF jobs from only one account at a time. It doesn't matter whether you go through CF or mturk.
