### ISSUE TITLE
Unknown Error? with the same blank pink bar.

### ISSUE THREAD

**Issue by srsaurabh32** [rainforestapp/tester-chrome-extension#308]
As notified earlier and did not get a satisfactory answer from RF, this problem still exists. 

whenever I get this browser=ie8 this error shows up, please don't send me this link if it does not work.

screenshot: 
![1](https://cloud.githubusercontent.com/assets/19935406/16712656/7dd2661a-46ab-11e6-8ce3-64a3e83545cd.PNG)

**Comment by nerdatwork** [comment]
@srsaurabh32 were you ever paid for any Rainforest HIT ? If so which website is it ?

**Comment by qpPykT** [comment]
@srsaurabh32 
Another testers don't have it. Apparently that problem is on your side. Maybe you do something wrong or do you have specific settings, operating system or any plug-ins (extensions) that can interfere with tasks receipt in your browser and break the proper work of the rainforest extention.

**Comment by srsaurabh32** [comment]
@nerdatwork yeah sure. I use Google Chrome Version 51.0.2704.106 m (64-bit). My machine is Acer manufactured and run on windows 7 OS. The extension I am using is Rainforest Tester Notifier 1.2.8. 

And yes I have completed around 400 tests for RF and I have been paid for each of it. I work only through extension and through Mturk.

**Comment by srsaurabh32** [comment]
@qpPykT I don't understand what the problem is? Do you suggest me to reinstall everything. Then i already did it, except reinstalling the OS. Should i do that? I guess not, there must be a solution to this.

**Comment by nerdatwork** [comment]
@srsaurabh32 Could you also tell me which are those other icons besides Rainforest ?

**Comment by srsaurabh32** [comment]
1. userbrain testing: it is a sreen recorder.
2. TurkOpticon: A forum for Mturk workers and requester.
3. TamperMonkey: used for running scripts on Mturk.
4. Hideyourass: A proxy or VPN ; i have removed it now.

Still the problem exists.

**Comment by helloworld111gh** [comment]
Can you go into your F12 -> Network tab, then look for the "
tester.rainforestqa.com/api/1/jobs/get/..." section (you may need to
refresh the page), then go to "Response".
Can you copy and paste what is in that box?

**Comment by srsaurabh32** [comment]
@helloworld111gh ok let me try.

**Comment by srsaurabh32** [comment]
@helloworld111gh 
this is the response code:

<!DOCTYPE html>
<html>
<head>
<script>
  var _sf_startpt=(new Date()).getTime()
</script>
<script>
  var PUNCHCLOCK_URL="https://punchclock.rainforestqa.com"
</script>
<script src='//cdn.ravenjs.com/1.1.19/native/raven.min.js'></script>
<script>
  Raven.config("https://44446efb6f624ad88006c0cd44b3fd79@app.getsentry.com/18148", {
    whitelistUrls: ["tester.rainforestqa.com","tester.rnfrstqa.com","tester.rnfrst.com"],
    tags: {"environment":"production","aws_assignment_id":"cxbd9eb6-dc1c-442d-9f00-dd5086e9243b","aws_hit_id":"2TFKNQY2RCJKNEV1PR8R8KUIQI33SI","test_token":null,"dry_run":null,"aws_worker_id":"A3QP3LRCVC20M0"}
  }).install();
  
  Raven.setUser({
    aws_worker_id: "A3QP3LRCVC20M0"
  });
</script>
<title>Rainforest Tester</title>
<meta charset='utf-8'>
<script type="text/javascript">window.NREUM||(NREUM={});NREUM.info={"beacon":"bam.nr-data.net","errorBeacon":"bam.nr-data.net","licenseKey":"f7fe9e9f17","applicationID":"2306087","transactionName":"IV9eFhdYXgpXQxkDQxJcWQEEQ1sJXB5fDFcHSA==","queueTime":2,"applicationTime":11,"agent":""}</script>
<script type="text/javascript">(window.NREUM||(NREUM={})).loader_config={xpid:"UA4OVFRVGwEDVFdSDwY="};window.NREUM||(NREUM={}),__nr_require=function(t,e,n){function r(n){if(!e[n]){var o=e[n]={exports:{}};t[n][0].call(o.exports,function(e){var o=t[n][1][e];return r(o||e)},o,o.exports)}return e[n].exports}if("function"==typeof __nr_require)return __nr_require;for(var o=0;o<n.length;o++)r(n[o]);return r}({1:[function(t,e,n){function r(t){try{c.console&&console.log(t)}catch(e){}}var o,i=t("ee"),a=t(12),c={};try{o=localStorage.getItem("__nr_flags").split(","),console&&"function"==typeof console.log&&(c.console=!0,o.indexOf("dev")!==-1&&(c.dev=!0),o.indexOf("nr_dev")!==-1&&(c.nrDev=!0))}catch(s){}c.nrDev&&i.on("internal-error",function(t){r(t.stack)}),c.dev&&i.on("fn-err",function(t,e,n){r(n.stack)}),c.dev&&(r("NR AGENT IN DEVELOPMENT MODE"),r("flags: "+a(c,function(t,e){return t}).join(", ")))},{}],2:[function(t,e,n){function r(t,e,n,r,o){try{d?d-=1:i("err",[o||new UncaughtException(t,e,n)])}catch(c){try{i("ierr",[c,(new Date).getTime(),!0])}catch(s){}}return"function"==typeof f&&f.apply(this,a(arguments))}function UncaughtException(t,e,n){this.message=t||"Uncaught error with no additional information",this.sourceURL=e,this.line=n}function o(t){i("err",[t,(new Date).getTime()])}var i=t("handle"),a=t(13),c=t("ee"),s=t("loader"),f=window.onerror,u=!1,d=0;s.features.err=!0,t(1),window.onerror=r;try{throw new Error}catch(l){"stack"in l&&(t(5),t(4),"addEventListener"in window&&t(3),s.xhrWrappable&&t(6),u=!0)}c.on("fn-start",function(t,e,n){u&&(d+=1)}),c.on("fn-err",function(t,e,n){u&&(this.thrown=!0,o(n))}),c.on("fn-end",function(){u&&!this.thrown&&d>0&&(d-=1)}),c.on("internal-error",function(t){i("ierr",[t,(new Date).getTime(),!0])})},{}],3:[function(t,e,n){function r(t){for(var e=t;e&&!e.hasOwnProperty(u);)e=Object.getPrototypeOf(e);e&&o(e)}function o(t){c.inPlace(t,[u,d],"-",i)}function i(t,e){return t[1]}var a=t("ee").get("events"),c=t(14)(a),s=t("gos"),f=XMLHttpRequest,u="addEventListener",d="removeEventListener";e.exports=a,"getPrototypeOf"in Object?(r(document),r(window),r(f.prototype)):f.prototype.hasOwnProperty(u)&&(o(window),o(f.prototype)),a.on(u+"-start",function(t,e){if(t[1]){var n=t[1];if("function"==typeof n){var r=s(n,"nr@wrapped",function(){return c(n,"fn-",null,n.name||"anonymous")});this.wrapped=t[1]=r}else"function"==typeof n.handleEvent&&c.inPlace(n,["handleEvent"],"fn-")}}),a.on(d+"-start",function(t){var e=this.wrapped;e&&(t[1]=e)})},{}],4:[function(t,e,n){var r=t("ee").get("raf"),o=t(14)(r),i="equestAnimationFrame";e.exports=r,o.inPlace(window,["r"+i,"mozR"+i,"webkitR"+i,"msR"+i],"raf-"),r.on("raf-start",function(t){t[0]=o(t[0],"fn-")})},{}],5:[function(t,e,n){function r(t,e,n){t[0]=a(t[0],"fn-",null,n)}function o(t,e,n){this.method=n,this.timerDuration="number"==typeof t[1]?t[1]:0,t[0]=a(t[0],"fn-",this,n)}var i=t("ee").get("timer"),a=t(14)(i),c="setTimeout",s="setInterval",f="clearTimeout",u="-start",d="-";e.exports=i,a.inPlace(window,[c,"setImmediate"],c+d),a.inPlace(window,[s],s+d),a.inPlace(window,[f,"clearImmediate"],f+d),i.on(s+u,r),i.on(c+u,o)},{}],6:[function(t,e,n){function r(t,e){d.inPlace(e,["onreadystatechange"],"fn-",c)}function o(){var t=this,e=u.context(t);t.readyState>3&&!e.resolved&&(e.resolved=!0,u.emit("xhr-resolved",[],t)),d.inPlace(t,v,"fn-",c)}function i(t){y.push(t),h&&(w=-w,x.data=w)}function a(){for(var t=0;t<y.length;t++)r([],y[t]);y.length&&(y=[])}function c(t,e){return e}function s(t,e){for(var n in t)e[n]=t[n];return e}t(3);var f=t("ee"),u=f.get("xhr"),d=t(14)(u),l=NREUM.o,p=l.XHR,h=l.MO,m="readystatechange",v=["onload","onerror","onabort","onloadstart","onloadend","onprogress","ontimeout"],y=[];e.exports=u;var g=window.XMLHttpRequest=function(t){var e=new p(t);try{u.emit("new-xhr",[e],e),e.addEventListener(m,o,!1)}catch(n){try{u.emit("internal-error",[n])}catch(r){}}return e};if(s(p,g),g.prototype=p.prototype,d.inPlace(g.prototype,["open","send"],"-xhr-",c),u.on("send-xhr-start",function(t,e){r(t,e),i(e)}),u.on("open-xhr-start",r),h){var w=1,x=document.createTextNode(w);new h(a).observe(x,{characterData:!0})}else f.on("fn-end",function(t){t[0]&&t[0].type===m||a()})},{}],7:[function(t,e,n){function r(t){var e=this.params,n=this.metrics;if(!this.ended){this.ended=!0;for(var r=0;r<d;r++)t.removeEventListener(u[r],this.listener,!1);if(!e.aborted){if(n.duration=(new Date).getTime()-this.startTime,4===t.readyState){e.status=t.status;var i=o(t,this.lastSize);if(i&&(n.rxSize=i),this.sameOrigin){var a=t.getResponseHeader("X-NewRelic-App-Data");a&&(e.cat=a.split(", ").pop())}}else e.status=0;n.cbTime=this.cbTime,f.emit("xhr-done",[t],t),c("xhr",[e,n,this.startTime])}}}function o(t,e){var n=t.responseType;if("json"===n&&null!==e)return e;var r="arraybuffer"===n||"blob"===n||"json"===n?t.response:t.responseText;return h(r)}function i(t,e){var n=s(e),r=t.params;r.host=n.hostname+":"+n.port,r.pathname=n.pathname,t.sameOrigin=n.sameOrigin}var a=t("loader");if(a.xhrWrappable){var c=t("handle"),s=t(8),f=t("ee"),u=["load","error","abort","timeout"],d=u.length,l=t("id"),p=t(11),h=t(10),m=window.XMLHttpRequest;a.features.xhr=!0,t(6),f.on("new-xhr",function(t){var e=this;e.totalCbs=0,e.called=0,e.cbTime=0,e.end=r,e.ended=!1,e.xhrGuids={},e.lastSize=null,p&&(p>34||p<10)||window.opera||t.addEventListener("progress",function(t){e.lastSize=t.loaded},!1)}),f.on("open-xhr-start",function(t){this.params={method:t[0]},i(this,t[1]),this.metrics={}}),f.on("open-xhr-end",function(t,e){"loader_config"in NREUM&&"xpid"in NREUM.loader_config&&this.sameOrigin&&e.setRequestHeader("X-NewRelic-ID",NREUM.loader_config.xpid)}),f.on("send-xhr-start",function(t,e){var n=this.metrics,r=t[0],o=this;if(n&&r){var i=h(r);i&&(n.txSize=i)}this.startTime=(new Date).getTime(),this.listener=function(t){try{"abort"===t.type&&(o.params.aborted=!0),("load"!==t.type||o.called===o.totalCbs&&(o.onloadCalled||"function"!=typeof e.onload))&&o.end(e)}catch(n){try{f.emit("internal-error",[n])}catch(r){}}};for(var a=0;a<d;a++)e.addEventListener(u[a],this.listener,!1)}),f.on("xhr-cb-time",function(t,e,n){this.cbTime+=t,e?this.onloadCalled=!0:this.called+=1,this.called!==this.totalCbs||!this.onloadCalled&&"function"==typeof n.onload||this.end(n)}),f.on("xhr-load-added",function(t,e){var n=""+l(t)+!!e;this.xhrGuids&&!this.xhrGuids[n]&&(this.xhrGuids[n]=!0,this.totalCbs+=1)}),f.on("xhr-load-removed",function(t,e){var n=""+l(t)+!!e;this.xhrGuids&&this.xhrGuids[n]&&(delete this.xhrGuids[n],this.totalCbs-=1)}),f.on("addEventListener-end",function(t,e){e instanceof m&&"load"===t[0]&&f.emit("xhr-load-added",[t[1],t[2]],e)}),f.on("removeEventListener-end",function(t,e){e instanceof m&&"load"===t[0]&&f.emit("xhr-load-removed",[t[1],t[2]],e)}),f.on("fn-start",function(t,e,n){e instanceof m&&("onload"===n&&(this.onload=!0),("load"===(t[0]&&t[0].type)||this.onload)&&(this.xhrCbStart=(new Date).getTime()))}),f.on("fn-end",function(t,e){this.xhrCbStart&&f.emit("xhr-cb-time",[(new Date).getTime()-this.xhrCbStart,this.onload,e],e)})}},{}],8:[function(t,e,n){e.exports=function(t){var e=document.createElement("a"),n=window.location,r={};e.href=t,r.port=e.port;var o=e.href.split("://");!r.port&&o[1]&&(r.port=o[1].split("/")[0].split("@").pop().split(":")[1]),r.port&&"0"!==r.port||(r.port="https"===o[0]?"443":"80"),r.hostname=e.hostname||n.hostname,r.pathname=e.pathname,r.protocol=o[0],"/"!==r.pathname.charAt(0)&&(r.pathname="/"+r.pathname);var i=!e.protocol||":"===e.protocol||e.protocol===n.protocol,a=e.hostname===document.domain&&e.port===n.port;return r.sameOrigin=i&&(!e.hostname||a),r}},{}],9:[function(t,e,n){function r(){}function o(t,e,n){return function(){return i(t,[(new Date).getTime()].concat(c(arguments)),e?null:this,n),e?void 0:this}}var i=t("handle"),a=t(12),c=t(13),s=t("ee").get("tracer"),f=NREUM;"undefined"==typeof window.newrelic&&(newrelic=f);var u=["setPageViewName","setCustomAttribute","finished","addToTrace","inlineHit"],d="api-",l=d+"ixn-";a(u,function(t,e){f[e]=o(d+e,!0,"api")}),f.addPageAction=o(d+"addPageAction",!0),e.exports=newrelic,f.interaction=function(){return(new r).get()};var p=r.prototype={createTracer:function(t,e){var n={},r=this,o="function"==typeof e;return i(l+"tracer",[Date.now(),t,n],r),function(){if(s.emit((o?"":"no-")+"fn-start",[Date.now(),r,o],n),o)try{return e.apply(this,arguments)}finally{s.emit("fn-end",[Date.now()],n)}}}};a("setName,setAttribute,save,ignore,onEnd,getContext,end,get".split(","),function(t,e){p[e]=o(l+e)}),newrelic.noticeError=function(t){"string"==typeof t&&(t=new Error(t)),i("err",[t,(new Date).getTime()])}},{}],10:[function(t,e,n){e.exports=function(t){if("string"==typeof t&&t.length)return t.length;if("object"==typeof t){if("undefined"!=typeof ArrayBuffer&&t instanceof ArrayBuffer&&t.byteLength)return t.byteLength;if("undefined"!=typeof Blob&&t instanceof Blob&&t.size)return t.size;if(!("undefined"!=typeof FormData&&t instanceof FormData))try{return JSON.stringify(t).length}catch(e){return}}}},{}],11:[function(t,e,n){var r=0,o=navigator.userAgent.match(/Firefox[\/\s](\d+\.\d+)/);o&&(r=+o[1]),e.exports=r},{}],12:[function(t,e,n){function r(t,e){var n=[],r="",i=0;for(r in t)o.call(t,r)&&(n[i]=e(r,t[r]),i+=1);return n}var o=Object.prototype.hasOwnProperty;e.exports=r},{}],13:[function(t,e,n){function r(t,e,n){e||(e=0),"undefined"==typeof n&&(n=t?t.length:0);for(var r=-1,o=n-e||0,i=Array(o<0?0:o);++r<o;)i[r]=t[e+r];return i}e.exports=r},{}],14:[function(t,e,n){function r(t){return!(t&&"function"==typeof t&&t.apply&&!t[a])}var o=t("ee"),i=t(13),a="nr@original",c=Object.prototype.hasOwnProperty,s=!1;e.exports=function(t){function e(t,e,n,o){function nrWrapper(){var r,a,c,s;try{a=this,r=i(arguments),c="function"==typeof n?n(r,a):n||{}}catch(u){d([u,"",[r,a,o],c])}f(e+"start",[r,a,o],c);try{return s=t.apply(a,r)}catch(l){throw f(e+"err",[r,a,l],c),l}finally{f(e+"end",[r,a,s],c)}}return r(t)?t:(e||(e=""),nrWrapper[a]=t,u(t,nrWrapper),nrWrapper)}function n(t,n,o,i){o||(o="");var a,c,s,f="-"===o.charAt(0);for(s=0;s<n.length;s++)c=n[s],a=t[c],r(a)||(t[c]=e(a,f?c+o:o,i,c))}function f(e,n,r){if(!s){s=!0;try{t.emit(e,n,r)}catch(o){d([o,e,n,r])}s=!1}}function u(t,e){if(Object.defineProperty&&Object.keys)try{var n=Object.keys(t);return n.forEach(function(n){Object.defineProperty(e,n,{get:function(){return t[n]},set:function(e){return t[n]=e,e}})}),e}catch(r){d([r])}for(var o in t)c.call(t,o)&&(e[o]=t[o]);return e}function d(e){try{t.emit("internal-error",e)}catch(n){}}return t||(t=o),e.inPlace=n,e.flag=a,e}},{}],ee:[function(t,e,n){function r(){}function o(t){function e(t){return t&&t instanceof r?t:t?c(t,a,i):i()}function n(n,r,o){t&&t(n,r,o);for(var i=e(o),a=l(n),c=a.length,s=0;s<c;s++)a[s].apply(i,r);var u=f[v[n]];return u&&u.push([y,n,r,i]),i}function d(t,e){m[t]=l(t).concat(e)}function l(t){return m[t]||[]}function p(t){return u[t]=u[t]||o(n)}function h(t,e){s(t,function(t,n){e=e||"feature",v[n]=e,e in f||(f[e]=[])})}var m={},v={},y={on:d,emit:n,get:p,listeners:l,context:e,buffer:h};return y}function i(){return new r}var a="nr@context",c=t("gos"),s=t(12),f={},u={},d=e.exports=o();d.backlog=f},{}],gos:[function(t,e,n){function r(t,e,n){if(o.call(t,e))return t[e];var r=n();if(Object.defineProperty&&Object.keys)try{return Object.defineProperty(t,e,{value:r,writable:!0,enumerable:!1}),r}catch(i){}return t[e]=r,r}var o=Object.prototype.hasOwnProperty;e.exports=r},{}],handle:[function(t,e,n){function r(t,e,n,r){o.buffer([t],r),o.emit(t,e,n)}var o=t("ee").get("handle");e.exports=r,r.ee=o},{}],id:[function(t,e,n){function r(t){var e=typeof t;return!t||"object"!==e&&"function"!==e?-1:t===window?0:a(t,i,function(){return o++})}var o=1,i="nr@id",a=t("gos");e.exports=r},{}],loader:[function(t,e,n){function r(){if(!w++){var t=g.info=NREUM.info,e=u.getElementsByTagName("script")[0];if(t&&t.licenseKey&&t.applicationID&&e){s(v,function(e,n){t[e]||(t[e]=n)});var n="https"===m.split(":")[0]||t.sslForHttp;g.proto=n?"https://":"http://",c("mark",["onload",a()],null,"api");var r=u.createElement("script");r.src=g.proto+t.agent,e.parentNode.insertBefore(r,e)}}}function o(){"complete"===u.readyState&&i()}function i(){c("mark",["domContent",a()],null,"api")}function a(){return(new Date).getTime()}var c=t("handle"),s=t(12),f=window,u=f.document,d="addEventListener",l="attachEvent",p=f.XMLHttpRequest,h=p&&p.prototype;NREUM.o={ST:setTimeout,CT:clearTimeout,XHR:p,REQ:f.Request,EV:f.Event,PR:f.Promise,MO:f.MutationObserver},t(9);var m=""+location,v={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net",agent:"js-agent.newrelic.com/nr-963.min.js"},y=p&&h&&h[d]&&!/CriOS/.test(navigator.userAgent),g=e.exports={offset:a(),origin:m,features:{},xhrWrappable:y};u[d]?(u[d]("DOMContentLoaded",i,!1),f[d]("load",r,!1)):(u[l]("onreadystatechange",o),f[l]("onload",r)),c("mark",["firstbyte",a()],null,"api");var w=0},{}]},{},["loader",2,7]);</script>
<link href="//static.rnfrst.com/0850bfa99b358985adfe4f645b384dfbf8088420/application.css" media="screen" rel="stylesheet" type="text/css"/>
<script src="//static.rnfrst.com/0850bfa99b358985adfe4f645b384dfbf8088420/application.js" type="text/javascript"></script>
<meta content="authenticity_token" name="csrf-param"/>
<meta content="ejwifkJKbjzsAQXRkVsu+i5h+5V8QATGhw/rMOzB6NM=" name="csrf-token"/>
</head>
<body>
<div data-paste-pause-delay='300' data-punchclock-url='https://punchclock.rainforestqa.com' data-rdp-swf='/assets/Flashlight-a93d94c.swf' id='beak-env'></div>
<div class='notification-bar-holder'></div>
<div class='loading-holder'></div>
<div id='page'></div>
 
<script type="text/javascript">
!function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","group","track","ready","alias","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="3.0.1";
  analytics.load('dXNqhDHtzPNs80fjSw3ORQmF239XMvPq');
  analytics.page();

  if (document.cookie.replace(/(?:(?:^|.*;\s*)identified\s*\=\s*([^;]*).*$)|^.*$/, "$1") != 'true') {
    var expires = new Date(new Date().getTime() + 1 * 24 * 60 * 60 * 1000);
    document.cookie = 'identified=true;expires=' + expires.toGMTString() + ';';
    analytics.identify('A3QP3LRCVC20M0', {
      email          : 'A3QP3LRCVC20M0@turks.rainforestqa.com',
      turker         : true
    });
  }
}}();
</script>
</body>
</html>

**Comment by srsaurabh32** [comment]
@helloworld111gh @nerdatwork 

related screenshots 

![error 1](https://cloud.githubusercontent.com/assets/19935406/16715993/215e3be0-470d-11e6-9024-7585f5fdc0e8.PNG)

![error2](https://cloud.githubusercontent.com/assets/19935406/16715994/2adbc318-470d-11e6-9cb2-6d644fed6976.PNG)

![error3](https://cloud.githubusercontent.com/assets/19935406/16715997/3317c446-470d-11e6-8d9e-a1d788a44811.PNG)

![error4](https://cloud.githubusercontent.com/assets/19935406/16715998/3a0640f2-470d-11e6-9601-49cb314f9b3a.PNG)

**Comment by helloworld111gh** [comment]
that's not the one, scroll down, its near the bottom, it might as red text

**Comment by srsaurabh32** [comment]
@helloworld111gh 
I am at this page, where am i supposed to click now:

![where](https://cloud.githubusercontent.com/assets/19935406/16716023/4b07f610-470e-11e6-874f-291f9953a495.PNG)

**Comment by helloworld111gh** [comment]
in the table scroll down, look for the row that has "/api/1/jobs/get/..
<http://tester.rainforestqa.com/api/1/jobs/>." (near bottom), click on it,
go to "Response" and show whats there

**Comment by srsaurabh32** [comment]
@helloworld111gh 

can't find anything like this at the bottom

![cant](https://cloud.githubusercontent.com/assets/19935406/16716082/d94055ac-470f-11e6-8f44-41ebc1a56469.PNG)

**Comment by helloworld111gh** [comment]
Check the middle?

**Comment by srsaurabh32** [comment]
@helloworld111gh 

can't find it anywhere, see for yourself:

![nowhere1](https://cloud.githubusercontent.com/assets/19935406/16716101/894ffb32-4710-11e6-9cc2-5273bad4d38f.PNG)

![nowhere2](https://cloud.githubusercontent.com/assets/19935406/16716102/94b6c82a-4710-11e6-92cb-bd99c224be93.PNG)

![nowhere3](https://cloud.githubusercontent.com/assets/19935406/16716104/9c1217aa-4710-11e6-901e-a49ed3315538.PNG)

![nowhere4](https://cloud.githubusercontent.com/assets/19935406/16716105/a0fad662-4710-11e6-83b8-978d8945e872.PNG)

**Comment by srsaurabh32** [comment]
@helloworld111gh 
 i found what you are asking for but not with this job url that have browser=ie8 but browser=any

screenshot from browser=any?

![found](https://cloud.githubusercontent.com/assets/19935406/16716126/44caa39e-4711-11e6-9809-70ca59d3409c.PNG)

**Comment by srsaurabh32** [comment]
@helloworld111gh 

I am going to bed now, its too late now 02:50 AM, thanx for your help. We will continue later.

**Comment by srsaurabh32** [comment]
@nerdatwork  continuously getting this same error url with browser=ie8, cant do work, Please RF help me.

**Comment by srsaurabh32** [comment]
common RF at least try to understand this issue, in the whole day i get several errors; these errors. browser=ie8 and always it end up with a pink blank strip and nothing else. I dont know what to do so I just close the tab in hope that the next task would not disappoint me, but again the same thing happens and it happens continuously and for the whole day. Please look into this matter, because on the whole RF tester team I am the only one who is getting these errors, no one in my contact and on this forum has seen such error, please look into this matter, I am really very upset because of this. 

Desperately, waiting for solution.  @nerdatwork @pscohn @helloworld111gh

**Comment by srsaurabh32** [comment]
@nerdatwork problem resolved. Closing this thread. Thanks for the support. Happy working.
