### ISSUE TITLE
Rejections

### ISSUE THREAD

**Issue by ecliptica777** [rainforestapp/tester-chrome-extension#309]
<img src="https://pp.vk.me/c633229/v633229959/3db9c/j9hVeyBITIM.jpg" alt="Rejections" />

Why is the rejections here? Unfortunately Rainforest support is not responding. I have 2 rejections and the reason is unclear. Who have problems with rejections?

**Comment by kaytsu** [comment]
double check your math. 622 +709 does not equal 1341. It equals 1331.

**Comment by pscohn** [comment]
It looks like it's because you didn't go to the correct link at the start of the test. We'll work on adding this information to the rejections view so it's more obvious.
