### ISSUE TITLE
Extension may not be getting jobs for some users

### ISSUE THREAD

**Issue by pscohn** [rainforestapp/tester-chrome-extension#31]
https://rainforest.zendesk.com/agent/tickets/8644

One tester reported the extension not working for the last 3 weeks. I've also not been able to get a job myself (using the extension with Russ's account).

**Comment by Ranky2211** [comment]
It might be true.For me i noticed that it didn't work on Saturday,Sunday and Monday.Mostly i got oops or hit from Tuesday to Friday and it depend on luck also.Its so funny you couldn't.

**Comment by ukd1** [comment]
@pscohn any ideas why?

**Comment by gmadhavreddy** [comment]
I Have not received even single hit also after installing Chrome Extension. Any body having same problem.

**Comment by pscohn** [comment]
@gmadhavreddy is this still the case? what is your worker ID?

**Comment by gmadhavreddy** [comment]
Now problem solved.
Thanq

**Comment by pscohn** [comment]
Closing this as there are no confirmed cases that aren't linked to https://github.com/rainforestapp/tester-chrome-extension/issues/24
