### ISSUE TITLE
Job abandoned because of screenshot problem

### ISSUE THREAD

**Issue by persman** [rainforestapp/tester-chrome-extension#310]
Hi, I had a problem with Screenshot (Failed to report a screenshot) and I got (job abandoned) Because of this error. What should I do now?

**Comment by nerdatwork** [comment]
This happens to most of us. Its unfortunate but Rainforest is working on fixing it. If you get job abandoned, close the tab and wait for another job to load.

**Comment by persman** [comment]
thank you :)
