### ISSUE TITLE
30 Minutes of You Have Done The Maximum ! Affs :(

### ISSUE THREAD

**Issue by felipeinsanobr** [rainforestapp/tester-chrome-extension#311]
At 21h (Brazil) I am with 30 minutes with You Have Done The Maximum ! Almost every day is happening this with my ID

My ID: 38484087
Check Pliz

**Comment by ahmedofhell** [comment]
same here

**Comment by zfonck123** [comment]
same here id : 34044189

**Comment by tulko** [comment]
same here 29649019

**Comment by tulko** [comment]
I have the same problem in the present day, it is due to rejection? It was only in the sum test, could find another way to test anti bot. I'm tired of adding

**Comment by JrRandy** [comment]
#303 

Looks like the same issue.  @pscohn
