### ISSUE TITLE
  2 job without payment

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#313]
![image](https://cloud.githubusercontent.com/assets/19192312/16776833/22c4692c-4835-11e6-9a5f-183c92e182f2.png)

  2 job without payment

**Comment by philips13** [comment]
same problem

**Comment by nerdatwork** [comment]
Have you read this at the top of the HISTORY in your profile ?

"**NOTE: Bonuses are normally paid within 24 hours, usually less. Occasionally there are delays. If a bonus takes longer than 48 hours during Monday-Friday**"

**Comment by philips13** [comment]
the task appears as if we had not made ​​any steps. I understand that payments can take up to 48 hours and that is not the problem.

**Comment by zfonck123** [comment]
when i done this task, i get one problem " aplicattion offline" and realod and say send the job thx. later when check my perfil  have this error.

**Comment by MuhammadRafique182014** [comment]
@nerdatwork are you drunk LOL look at the Screen shots 
@zfonck123 yeah its a bug, same here but 1 hit

**Comment by nerdatwork** [comment]
@MuhammadRafique182014 How did you know I was drinking coffee ?

**Comment by MuhammadRafique182014** [comment]
@nerdatwork I got it with your comment LOL

**Comment by nerdatwork** [comment]
How very perceptive of you!

**Comment by Electroglitch** [comment]
Happened to me today also, for the first time ever to see this kind of bug,
i was on the last step and screenshot error appeared ,after trying 7-8 times (closing error message and clicking Yes) it looked like everything went just fine, submited test after that 
but in profile history saw situation just like in screenshot above
no submitting time no bonuses just "-" but time taken was present 00:05:43
very strange...

**Comment by nerdatwork** [comment]
Maybe those jobs are travelling through the Bermuda Triangle and lost track of time by the time they reached your profile :dash:  

Also on other hand, you took screenshot of your profile, pasted in paint and took screenshot of paint! You must really be frustrated.
