### ISSUE TITLE
Tired of adding

### ISSUE THREAD

**Issue by tulko** [rainforestapp/tester-chrome-extension#314]
I'm pretty tired of doing antibot sums. But when I make mistakes. It seems silly but when you do many tests you get tired and make mistakes. Could leave alone the robot, sandwich, pyramid, and find some other silly question for this test?

**Comment by nerdatwork** [comment]
You will get tired of other silly anti-bot questions too eventually. How often should you suggest to keep changing the anti-bot questions ?

**Comment by marius11** [comment]
> I'm pretty tired of doing antibot sums.
Tired of answering the easiest question in a task?

> It seems silly but when you do many tests you get tired and make mistakes.
You need to pay attention to details. If you're not patient enough to add two numbers, how can you solve the rest of the task?

> Could leave alone the robot, sandwich, pyramid, and find some other silly question for this test?
Adding other silly questions wouldn't make any difference.

**Comment by nerdatwork** [comment]
If it was up to me just to satisfy your curiosity I would make the anti-bot questions something like this

## ax + cy = p

Find value of b.

**Comment by JrRandy** [comment]
I'd be happy if the anti-bot questions just didnt take screenshots.  Nothing worse then getting "Are you a human" and then failing to take screenshot 7 times before it moves forward lol

**Comment by qpPykT** [comment]
I'm tired of "There are no virtual machines currently available. Please retry in a few minutes." :ghost:

**Comment by GreekGuy** [comment]
Who cares about these anti-bot questions when there is no work.... -.-

**Comment by tulko** [comment]
Perhaps it is a response to what I'm doing enough jobs, which is good. I can do sums, I'm practicing them without the calculator. I just feel frustrated by a rejection, by a bad sum with the mind
