### ISSUE TITLE
a very slow test

### ISSUE THREAD

**Issue by persman** [rainforestapp/tester-chrome-extension#316]
hi, 
there is a test that is very very slow  and I did it 2 times ( 11 steps and 10 steps) and in both of them I saw abandoned error. is it my problem? I don't have any problem with other tests. what can I do for this test?
best regards.  
I didn't tell the name of that test, because I think it is not legal (it is NOT NDA test).

**Comment by nerdatwork** [comment]
Taking a hint from the Title change I understand your problem but you didnt do anything wrong. That particular website is slow in the terminal. Many testers face that issue. Try your best to do it in time if not there is nothing else that you can do about it. Happy Testing ;)

**Comment by persman** [comment]
thank you for your quick answer. 
Is it dangerous for my account? I am new so I am scared of everything :S I don't want to be banned so I am asking everything from you.

**Comment by nerdatwork** [comment]
Your account is safe as long as you follow rules. Lots of testers face slow speed for that particular website.

**Comment by persman** [comment]
thank you very much. good luck :)
