### ISSUE TITLE
A security error occurred (Error #2048).

### ISSUE THREAD

**Issue by berkomay** [rainforestapp/tester-chrome-extension#319]
A security error occurred (Error #2048).
Please check you can connect to http://v061.ext.prd.rnfrst.com:843

**Comment by JrRandy** [comment]
If this was inside the terminal (Which it always has been in my experience) click "No" report issue, and move on to next job.  Please do not report issues inside the terminal on this github.  This is strictly for reporting issues with the interface/extension itself, and not issues that can be reported via the No button while performing tests.

**Comment by nerdatwork** [comment]
All errors inside the terminal **must be reported by clicking NO** and mentioning the details in the pop up that shows under NO. Please close this thread.
