### ISSUE TITLE
Job history gone & not credited for newly done jobs.

### ISSUE THREAD

**Issue by Ashok-Reddi** [rainforestapp/tester-chrome-extension#321]
This is my actual profile. 
![rainforest_ashok](https://cloud.githubusercontent.com/assets/20459671/16842070/ab5ba8ac-49f9-11e6-861e-aff6224e43c2.png)
but some thing has gone wrong and I got the different stats in my profile. pls check here.
![ashokrfnew](https://cloud.githubusercontent.com/assets/20459671/16842264/7d630746-49fa-11e6-9456-c8cdd4ecfd43.png)
Here are the job history with new profile with the listings which are not related to my jobs done. They are all someone else's list except the top 3 and the test jobs.
![jobsnew](https://cloud.githubusercontent.com/assets/20459671/16842283/8d8f1cea-49fa-11e6-9ce2-51ac5359779f.png)
And I am not getting paid to my eliteCF. Also is is showing some deducted amount in the notifications in my CF.

I raised the ticket but no response yet.

**Comment by JrRandy** [comment]
The tester link is different for the 2.  They look like 2 different profiles, not an updated profile.  Are you sure you used the right email?  It looks like at some point you made 2 profiles for whatever reason, and now have 2 accounts.

**Comment by Ashok-Reddi** [comment]
@JrRandy, I dont know how 2nd profile was created. suppose in this case how can I deactivate the second profile. Can you please let me know the process

**Comment by nerdatwork** [comment]
These are clearly 2 profiles. Did you take prior permission before opening up a new profile ? Having 2 Rainforest accounts is against the TERMS of use.

**Comment by Ashok-Reddi** [comment]
@JrRandy, I dont know how the 2nd profile was created. In this case can you please let  me know how to deactivate my second profile and continue with the first one?

**Comment by Ashok-Reddi** [comment]
@nerdatwork, Can you please suggest me what to do in my case. I just wants to go with my 1st profile ie., 55jobs completed profile. Whom do I ask to resolve this issue?

**Comment by JrRandy** [comment]
You can't deactivate an account to my knowledge.  You need to log in using the email address you logged in with on the 13th, and not the one you logged in with on the 14th.

**Comment by Ashok-Reddi** [comment]
@JrRandy, the 2 profiles are linked with same email. that is what the issue here. I dont know how it happened with out my notice.

**Comment by JrRandy** [comment]
If thats the case, then only the help desk via a ticket can assist.  Considering it doesn't appear that you logged into the first account now that I look again (Login button is still visible), I am guessing they are not attached to the same email and that you just had a link stored from 2 years ago when you started testing.  Try some other email addresses that you use, and you may find the actual login for that first account.

**Comment by pscohn** [comment]
It's likely that you have the same email addresses for both profiles. Please try logging into one profile,changing the email address, and see if you can log into the other one. If it works, please respond to the ticket you sent in as well. @Ashok-Reddi

**Comment by Ashok-Reddi** [comment]
@pscohn, Thank you so much bro. It worked perfectly. I got my history back. I just done a small job and it is showing in my profile too. waiting to check the amount to be credited. Thanks a lot @pscohn, it was a great help to me.

**Comment by Ashok-Reddi** [comment]
As it solved my problem now I am closing the issue. once again Thanks @pscohn.
