### ISSUE TITLE
new interface

### ISSUE THREAD

**Issue by tulko** [rainforestapp/tester-chrome-extension#324]
On several occasions I got an error "Failed to perform action on machine".
this was to take screenshot
I had to start over several times

**Comment by tulko** [comment]
at the end refresh, four times and I could not finish

**Comment by ilegalna** [comment]
"Unsuspected token" error on my side:

<a href="http://screenshot.net/jgvn5a0" rel="nofollow"><img src="http://screenshot.net/jgvn5a0.jpg" /></a>

**Comment by JrRandy** [comment]
@ilegalna Can you move your post to #328 as Tulko's error is different than yours.  328 is related to your issue (Error appears when taking screenshot)

**Comment by ilegalna** [comment]
Of course @JrRandy :)
