### ISSUE TITLE
New Interface Error

### ISSUE THREAD

**Issue by murilus** [rainforestapp/tester-chrome-extension#326]
@pscohn @ukd1 

I received a test on the New Interface, it showed me Loading, I've waited 5 minutes, it still showed me Loading, after 5+ minutes, I refreshed the link, it showed me Loading again, been waiting again like 2+ minutes, still the same, refreshed again, been waiting again, refreshed and received You've requested this job to often.

After that the extension gave me another link but I received the message 

You have reached the maximum number of unsubmitted assignments. So we are fair to other workers, we stop you doing too much for us at once. You can complete the other assignment(s) and refresh this page, or simply return this hit.

That was like 40 minutes ago, since then I refreshed the new link I received a few times, I still get this message...

My Worker ID is 34460763, if you could please check and see what's happening...

I don't think I'm the only one with this error...

**Comment by murilus** [comment]
Now I don't receive that error anymore and I just received a test, but I believe it's because 60 minutes passed since then, so I believe it's still an error...

**Comment by JrRandy** [comment]
From the portal:

Rolling Back the Update 2016-07-14 22:24:55 UTC, Paul Cohn
We're rolling back the update for now - we discovered a bug with some jobs that caused a long period of the "maximum unsubmitted assignments" message. Thanks to everyone who reported this problem!
