### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by NeoWorker** [rainforestapp/tester-chrome-extension#328]
I keep receiving this error. When I tryed to reload the page, I was getting only this message in the page.

Pic:

http://storage3.static.itmages.com/i/16/0714/h_1468533212_4983875_5b99a4489f.png

**Comment by GreekGuy** [comment]
I got it instead of screenshot error i believe.

**Comment by tulko** [comment]
I think it's the same error of taking a screenshot. wait a few moments and try again.

**Comment by ilegalna** [comment]
<a href="http://screenshot.net/jgvn5a0" rel="nofollow"><img src="http://screenshot.net/jgvn5a0.jpg" /></a>

**Comment by luisdanielvc** [comment]
At least this error was much better than the screenshoot one in the old interface.
