### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by nuevao** [rainforestapp/tester-chrome-extension#329]
greetings, very common error in my case in the new interface, after giving click to take the screenshot with the error image![image](https://cloud.githubusercontent.com/assets/16979522/16856974/1a6bf580-49eb-11e6-99e8-4b923c6fd3a8.png), besides presenting a delay in taking the screenshot. other so very nice, modern interface.

**Comment by JrRandy** [comment]
Please post in #328 and close this thread as they are for the same issue.

**Comment by nuevao** [comment]
@JrRandy  you are right, Closed
