### ISSUE TITLE
Cross connection. Terminals are shared

### ISSUE THREAD

**Issue by nerdatwork** [rainforestapp/tester-chrome-extension#33]
![image](https://cloud.githubusercontent.com/assets/15882196/11903900/83eb26d2-a5e2-11e5-93d0-6f1f6d800a01.png)

This is the second time today that my terminal was shared with another worker and this is absurd. This needs to be fixed asap

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx732a12-2d98-4b54-a6f2-89d2b7e5bac6&browser=any&hitId=3326957&sig=7b49be86810dbe8081d5b051209bbb581b7d94bffb3d175372a238c5a3f89894&turkSubmitTo=%2Fthanks&workerId=nerdatwork

This is the url and that image above shows what the other worker was doing. He was working on a totally different HIT but we were using same terminal

**Comment by BV25** [comment]
This is prevalent all day throughout today and is happening with every other HIT/terminal I get. It is really really distressing.

I'd like to point out some testers are also using abusive language in their native language and blackmailing us to leave the Terminal and get out. Such language is intolerable.

**Comment by qpPykT** [comment]
I have the same problem twice.

**Comment by mueller2511** [comment]
Almost all the hits which i had for Consumer affairs had the same problem and even after restating the same problem and after 4 time , request too often due to which now i am not able to do the job.

**Comment by pscohn** [comment]
We're looking into this ASAP.

**Comment by Genesis2015** [comment]
I have the same annoying problem! It's drive me crazy and i've lost lots of HITs :( I hope this problem will be resolved ASAP :)

**Comment by nerdatwork** [comment]
@pscohn Its prevalent mainly in Mac terminals and not restricted to Consumer affairs site HITS alone.

**Comment by mueller2511** [comment]
@nerdatwork was right, i just lost a 16 stepper hit due to the same issue which was Mac, but had the issue in windows as well on other hits.

**Comment by androwg** [comment]
Also i have this annoying problem Also today very increase in we have reached our maximum .
my accuracy in profile went below 70% i hope  not to be near to block :(

**Comment by mueller2511** [comment]
lost lot of hits today due to the shared user & Concurrent users issue , i hope it doesn't effect my account.

**Comment by ando100** [comment]
@pscohn   At least now- maybe you should eliminate the 4 tries rule, up to the point problem gets solved? If it`s not so big trouble. 
Kind of " Mice Cinema" from my point of view with most of tasks today. 
Reason- 4 tries- out.

**Comment by Ranky2211** [comment]
@pscohn Same here Lost so many HIT due to shared terminal or terminal is loaded Half then Something went wrong or max message.In some hit when i paste job url then someone erasing my url and putting theirs and when i again trying then someone close browser and shutdown the terminal.Its like someone trying to stop me doing HIT then connection lost.Refreshing give you requested this job too often please return to the work and there is no way to return to the work.Please do something about this.

**Comment by pscohn** [comment]
Just to clarify, have you all experienced this problem in the past, or has it started happening today?

**Comment by Ranky2211** [comment]
@pscohn All other problem i experienced in everyday testing except  other tester working on my terminal I experienced today.Its my first experience.Erasing url,closing browser,and shutdown the terminal.Firstly i don't understand what is happening in the terminal but later understand.

**Comment by Genesis2015** [comment]
I have experienced this problem in the past, but very rarely compared to today.

**Comment by ando100** [comment]
Just to clarify, have you all experienced this problem in the past, or has it started happening today?

in the past-yup- but rare, today- massive...Meaning all over.  Meaning- I just sit back and relax and enjoy. Mouse cinema...

**Comment by nerdatwork** [comment]
@pscohn I never experienced in the past just today.

**Comment by tetanus123** [comment]
this problem has happend to me in the past, and I know a lot of people also faced this, but after refreshing terminal was ok.
yesterday was crazy, lots of hits lost because I had to refresh HIT and every time someone else was there with me, had nice chat with few of them lol

**Comment by androwg** [comment]
AS tetanus123 SAID

**Comment by mueller2511** [comment]
Still having the same issue.

**Comment by nerdatwork** [comment]
Just now faced a shared terminal with windows and firefox environment.

**Comment by nihlathar** [comment]
It's still happening by the way. Maybe less than before, hard to say. Other jobs than the consumer affair ones (including internal/rfqa).

**Comment by mueller2511** [comment]
@nihlathar may be less for you , but its happening almost all the hits which i am getting just like friday.

**Comment by begsoon** [comment]
it is possible to do any hit
we have 4 times to refresh and again and again terminal was shared by someone
and then ''to often req'' 

this is serious issue

**Comment by Genesis2015** [comment]
The problem still persist to me :(

**Comment by androwg** [comment]
it is impossible to work in these conditions right now.

**Comment by tetanus123** [comment]
here we go again :dancers: 
I just hope we are not going to be baned for losing so much hit,  because as @androwg said, it is impossible to work

**Comment by mueller2511** [comment]
Don't know weather this has anything to do with the shared user terminal but in the last 2 hits i haven't see the issue but started to see the following error.

Connection error
dail tcp 67.221.170.49:80: i/o timeout

if you are a tester, please report this issue
Manchine ID: 8212641

and the page was not loading at all.

Thanks

**Comment by androwg** [comment]
Yes as mueller2511 said terminal cross connection is over for the last 2 hits  but first hit page no need to load at all and the second give Connection error dail tcp message.

**Comment by teteuc2** [comment]
The terminal features many problems after the latest updates. Back with our good please terminal. I need it to survive.

**Comment by Ranky2211** [comment]
Hi I had to report 7 Hit of connection error on first step.They are all consumer affair HIT.Connection error
dail tcp 67.221.170.49:80: i/o timeout with different machine id.

**Comment by teteuc2** [comment]
You could go back to the CF. The extension does not work right, absurdly bad terminal. Return everything as it was six months ago when everything worked normally for us testers. Please!

**Comment by androwg** [comment]
@pscohn Everything is ok now except increase in amount of we have reached our maximum which may consume the 5 refreshes.

**Comment by jbarber** [comment]
@teteuc2: The extension does nothing apart from show when jobs are available more rapidly than using CF/mturk - so you will see the same terminal errors whichever method you use to get jobs.

**Comment by pscohn** [comment]
To be clear @teteuc2 @jbarber - you will see the same terminal errors..until we fix them :)

**Comment by BV25** [comment]
@pscohn Hi, there's an urgent problem ongoing since past 30 mins, that of 'Failed to take screenshot' while working on any HIT. The Terminal loads properly, the Oops page also loads, but you can't work on any Step due to failed screenshot.
Generally this'd have resolved on its own normally within a few mins, but I'm conveying you as it has been more than 30 mins so requesting you to have a look, as it seems a little major issue.

**Comment by Ranky2211** [comment]
@pscohn Same here Screenshot is not working on first step.Its been more than 10 miniute what to do.I refreshed several time.

**Comment by sizika66** [comment]
Same here. All have a problem at the moment. This is general bug.

**Comment by pscohn** [comment]
@BV25 @Ranky2211 @sizika66 The screenshot error affecting tests this morning has been fixed, but please don't tack on unrelated bugs to an issue topic like this, as it just bloats the thread :)

**Comment by JPierreS** [comment]
@pscohn  Regarding the other users in terminal, this is not a new issue.  I noticed this in the more than 1 1/2 year I've been working on this task, however, it happened on an extreme rare occasion.  Lately it happened frequently, and now for a while now it seems to have stopped (for now) though at first I thought it was intentional that you guys want us to share terminals (share and share alike) sort of like a team work thing, you do steps 1-20 I'll do 21-72 ;-)

**Comment by ukd1** [comment]
@pscohn @jbarber @gallois - did we ever get to the bottom of this? Suggestion: lets put the ``machine-id`` visibly in the interface, so when we get screenshots we can track it back in the logs.

**Comment by qpPykT** [comment]
Today I had the cross connection bug again. The terminal was shared between the two testers.

**Comment by Genesis2015** [comment]
Me too few day ago.

**Comment by pscohn** [comment]
Haven't seen this reported in a while, so I'll close until there are new reports.
