### ISSUE TITLE
Another worker take my job 

### ISSUE THREAD

**Issue by josejecr97** [rainforestapp/tester-chrome-extension#331]
I have some troubles because when im finishing my job it says that somebody else finish my job... i have this error all the day .. i cant do anything .. is really unfair :( please fix :(

**Comment by pscohn** [comment]
@josejecr97 can you screenshot the error and provide your worker ID, and a job/assignment ID if possible?

**Comment by josejecr97** [comment]
Oh i dont see the post, sorry .. OK, i dont have any screen yet but i will post here when it happens again..

**Comment by Halcongris** [comment]
Tengo un problema cuando abro los trabajos me dice BAD GATEWAY 502

**Comment by Halcongris** [comment]
I have problems when I open the work tells me 502 bad gateway

**Comment by nerdatwork** [comment]
@Halcongris Stay with your thread, this thread is not for your issue. Use ENGLISH when you are replying.

**Comment by josejecr97** [comment]
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx7d6eef-471f-4966-a7cb-a62a7b14e0ae&browser=any&hitId=4375118&sig=c3336876a335f9e5acd7d317362de646149caddd97bf6ea3bd6586d36ac78631&turkSubmitTo=%2Fthanks&workerId=33601615    


i dont know whats the id.. so i post the link, @pscohn  i've doing job like 2 mins.. when i press yes to get another step it says that some one else have doed it ..not fair. 

http://oi66.tinypic.com/23sbu6d.jpg

worker id : 33601615
