### ISSUE TITLE
Problem with the url

### ISSUE THREAD

**Issue by srsaurabh32** [rainforestapp/tester-chrome-extension#333]
https://tester.rainforestqa.com/tester/assignment/aws/ie8?assignmentId=cx7ad4d3-e366-4470-8c24-989b1c350720&browser=ie8&hitId=2TFKNQY2RCJKNEV1PR8R8KUIQI33SI&sig=6378601f20452af391476fc7d097e987e8e2c8e11ad064272753a63b9d26a609&turkSubmitTo=%2Fthanks&workerId=A3QP3LRCVC20M0 

can anyone please tell me what is wrong with this url, it never lands me on a job page, instead I receive a blank pink bar only, I have reported this issue several times but it has never been resolved.

I am unable to do any jobs, please help me.

I also tried changing, browser=ie8 to browser=any as shown below but it showed an Error: the signature in the url is invalid. Like this:

https://tester.rainforestqa.com/tester/assignment/aws/any?assignmentId=cx7ad4d3-e366-4470-8c24-989b1c350720&browser=any&hitId=2TFKNQY2RCJKNEV1PR8R8KUIQI33SI&sig=6378601f20452af391476fc7d097e987e8e2c8e11ad064272753a63b9d26a609&turkSubmitTo=%2Fthanks&workerId=A3QP3LRCVC20M0

**Comment by nerdatwork** [comment]
Try opening the browser=ie8 link in Internet Explorer 8 and see if it works.

**Comment by srsaurabh32** [comment]
i have windows 10 and ie8 is not supported, i tried it on ie edge and same results; blank pink strip.

**Comment by tulko** [comment]
I call your attention id worker, usually a number, you have something alpha numeric

**Comment by srsaurabh32** [comment]
@tulko this worker id belongs to Mturk hence alphanumeric, your must be of some different platform. The problem is not the worker id, it is the browser, when the url contain browser=any, I am able to complete the job but when browser=ie8 nothing but a blank pink bar shows us.

**Comment by Devil3000** [comment]
I have same problem

**Comment by srsaurabh32** [comment]
@Devil3000 the same blank pink bar problem? browser=ie8? and since how long?

**Comment by nerdatwork** [comment]
@Devil3000 Your problem is not the same as this thread. Please stay in your thread a proper response will be given to you.

**Comment by srsaurabh32** [comment]
@nerdatwork what am i supposed to do now, no one has any idea how to deal with this problem.

**Comment by nerdatwork** [comment]
have you tried another computer ? I recommend windows 7 which can run ie8.

**Comment by tulko** [comment]
@nerdatwork you're administrator or something.?

**Comment by srsaurabh32** [comment]
@nerdatwork  yup i followed your advice, tried it on different machine, with windows 7 but the same problem, not only this, but i checked logging in on different machines but the same problem and as a matter of fact one of my friend who also work for RF, I tried working on his machine, there too I got the same error. My friend who also works for RF have never witnessed anything like this. I am the only one who gets browser=ie8.

**Comment by nerdatwork** [comment]
This is completely strange. Could you confirm the version of Rainforest extension whether its up to date.

**Comment by srsaurabh32** [comment]
@nerdatwork  Take a look:
![rainforrest](https://cloud.githubusercontent.com/assets/19935406/16915575/e6cb766e-4d15-11e6-92fb-38ec7476a96d.PNG)

**Comment by srsaurabh32** [comment]
@nerdatwork  this is the latest link that i just received 

https://tester.rainforestqa.com/tester/assignment/aws/ie8?assignmentId=cx718f14-1069-4024-9844-cc4764e7e2d0&browser=ie8&hitId=2TFKNQY2RCJKNEV1PR8R8KUIQI33SI&sig=391b6b034ac2f0f78e1dbf1b1c5287eaf9ee62dc677865ce9b40ab4d220673ba&turkSubmitTo=%2Fthanks&workerId=A3QP3LRCVC20M0

**Comment by srsaurabh32** [comment]
![enw](https://cloud.githubusercontent.com/assets/19935406/16915633/46ce29d0-4d16-11e6-8e55-722f326cab9f.PNG)

**Comment by nerdatwork** [comment]
Well this week there are company wide meetings so support will be limited. Have your fingers crossed. I hope you find a response because only Rainforest staff can help you now.

**Comment by srsaurabh32** [comment]
@nerdatwork ok lets wait then.

I have one more question: what platform do you use?

**Comment by srsaurabh32** [comment]
@nerdatwork guess what i took my friend's RF id and logged in using his id and worked on for 1 hour but did not receive the error once. This proves that problem is not on my side but it is on the RF's side.

**Comment by tulko** [comment]
@srsaurabh32 use neobux, I think it is the best option for all channels of payment and immediate payment. On one occasion I thought I'd switch to CF elite, but pay only for paypal. Neteller  have a card mastercard and withdraw my money with that plastic.

**Comment by srsaurabh32** [comment]
@tulko thanks for the suggestion. How much time does it take to switch from clixsense to neobux.

**Comment by nerdatwork** [comment]
Every reward site takes a % from what you get paid besides Elite. As of now you **CANNOT** switch accounts or create new accounts or close Rainforest account.

**Comment by tulko** [comment]
@nerdatwork  It was in response to a question from @srsaurabh32 
@nerdatwork  you are a moderator?
@srsaurabh32 in neobux they charge a%, but if you get "golden" of reintegrating 30% for every dollar you earn in CF, easily amortize the "golden" and recover the commission

**Comment by nerdatwork** [comment]
@tulko Dude check what he was asking. It was never about the payment just a question on which reward site I was using. You quickly jumped on to the payment aspect of it. 

@srsaurabh32 Wait for Rainforest to respond to your support ticket. I apologize on their behalf for the delay.

**Comment by srsaurabh32** [comment]
mturk does not charge a single penny. @nerdatwork  @tulko 

I contacted crowdflower regarding switching accounts but they denied any such thing, and asked me to consult RF if they can allow such change.

**Comment by qpPykT** [comment]
Dark :horse:

**Comment by edwardbass** [comment]
I have the same problem the url never load just a white page

**Comment by nerdatwork** [comment]
@srsaurabh32 Is your support ticket answered yet ?

**Comment by srsaurabh32** [comment]
@nerdatwork happy to announce that my problem is now resolved, i did a job recently that had browser=ie8. So happy to submit that job successfully. I'll close this thread now. Thanks for the support everyone specially @nerdatwork .
