### ISSUE TITLE
Website is offline | 525 : SSL handshake failed

### ISSUE THREAD

**Issue by Devil3000** [rainforestapp/tester-chrome-extension#334]
I have this problem since 2 days  

![2016-07-18_083309](https://cloud.githubusercontent.com/assets/19398759/16907256/3ea2d3ae-4cc2-11e6-8611-e77d69185c47.png)

**Comment by nerdatwork** [comment]
@Devil3000 Are you using the Chrome extension to get jobs ? Take a screenshot of whole screen including the URL and extension.

**Comment by Devil3000** [comment]
yes i using the Chrome extension to get jobs 
![2016-07-18_090052](https://cloud.githubusercontent.com/assets/19398759/16907749/6280f504-4cc6-11e6-8cfb-aa7c40af6462.png)
when i refresh this page turned to : 
![2016-07-18_083309](https://cloud.githubusercontent.com/assets/19398759/16907814/dff84316-4cc6-11e6-91fb-181e600481a9.png)
must be click on "Retry for alive version" to back me  "Another worker accepted the job before you! ... "

**Comment by nerdatwork** [comment]
If you see that error, you need to close that tab and not refresh it. Clear your Chrome cache by going to settings and history then clear all history/cache from "Beginning of time".
