### ISSUE TITLE
ERROR #2048

### ISSUE THREAD

**Issue by ladystoneheart** [rainforestapp/tester-chrome-extension#335]
PLEASE tell me what is this error! photo attach. and if i report this they haven't paid me for reporting as error! 
![error 2048](https://cloud.githubusercontent.com/assets/20522240/16924546/825d550e-4d28-11e6-9391-300c15f22416.png)

**Comment by nerdatwork** [comment]
All errors inside the terminal **MUST** be reported by clicking NO and mentioning the details in the pop up. If your payment is delayed, the official waiting period is 48 hours. After that you can file a support ticket.

**Comment by marius11** [comment]
> All errors inside the terminal MUST be reported by clicking NO and mentioning the details in the pop up.

You are aware that in this case reporting by clicking NO is impossible, right? I was disconnected 10 minutes into a 24 step test without any reason today. When you're disconnected like this, you **CANNOT** report using the NO button.

**Comment by rnfrst** [comment]
This is the kind of error that even you report, you won't be paid because you haven't even entered yet the initial url indicating that you have accepted the job. You should get a new terminal instead of reporting this.

**Comment by ladystoneheart** [comment]
@nerdatwork AS i said i report as error but no payment for this 
![error](https://cloud.githubusercontent.com/assets/20522240/16927673/33818842-4d37-11e6-89f7-5a032532a21c.png)

**Comment by ladystoneheart** [comment]
@rnfrst yes thanks for info.

**Comment by nerdatwork** [comment]
@ladystoneheart Wait for 48 hours if you still arent paid you can file a support ticket. When you get this message you can refresh the page to get new terminal but by the sheer amount of new testers we have the probability that the job is picked by someone else is very much HIGH.

@marius11 Did you refresh the HIT and were able to submit the job?

**Comment by limsanto** [comment]
I report this error long time ago.
RF respond is, there is nothing wrong with their system and asking me to check my internet security system, and now it seems RF can not get away from this error again with many others worker have the same problem.
RF please check your system security which maybe blocking the terminal connection with worker.
For worker, if you face this error problem, please refresh the hit with long time interval (1-2 minutes), usually 1-2 times refresh will fix that problem.
