### ISSUE TITLE
Something went wrong while getting a terminal

### ISSUE THREAD

**Issue by luisdanielvc** [rainforestapp/tester-chrome-extension#337]
I've been getting this a lot of times this day :(

**Comment by nerdatwork** [comment]
Check your internet connection. When you get this message it is safe to refresh the page till you get the terminal or you get an error message.

**Comment by MuhammadRafique182014** [comment]
LOL this is also a bug from RF side its not his Internet connection LOL

**Comment by hunt40** [comment]
their servers cant handle 1900+ tester hammered their servers at same time and this error happened with their own test.this is the problem,they have tons of problem and i dont see them fixed it anytime and with now tons of new testers coming everyday.....

**Comment by luisdanielvc** [comment]
It is not my internet connection and it is not safe to refresh while getting this error because the you have requested this job too often appears :(

**Comment by MuhammadRafique182014** [comment]
@luisdanielvc so sad :(

**Comment by sweeneyapps** [comment]
here's good tip.  when u see VM not available.. go ahead try refresh.   If still unavailable, you just wait for the Rainforest Plugin to turn Green (YES).   Hit refresh ASAP.    You'll get lucky or not.   It's highly likely that u'll still secure the job.

**Comment by sweeneyapps** [comment]
I worked on this today..   all of us will be cheering!!     tonight!!     This is only for Virtual Machine unavailability.   It'll increase your chance to grab the job before anyone else grab it.

here is it....   https://github.com/sweeneyapps/JobAutoReload
