### ISSUE TITLE
CHANGE MY worker ID rainfoster

### ISSUE THREAD

**Issue by MOHAMMEDAMRANI82** [rainforestapp/tester-chrome-extension#342]
MY ACCOUNT NEOBUX BE SUSPENDED 
AND I WANT TO CREATE A NEW ACCOUNT
IS CAN I CHANGE MY worker ID rainfoster FOR PAY THE GAIN IN NEW ACCOUNT or no 
AND THANKS

**Comment by nerdatwork** [comment]
Send a support ticket at tester@rainforestqa.com

**Comment by TheOneWhoKnock** [comment]
can i ask, is this posible?

**Comment by uqbiii** [comment]
@TheOneWhoKnock Check #392.
