### ISSUE TITLE
the job about "earth.paperlesspost.com" is a disaster!

### ISSUE THREAD

**Issue by bilelmz** [rainforestapp/tester-chrome-extension#344]
I got an job about this website: earth.paperlesspost.com
it's very very very slow!
I think because there is lot of images 
also, "failed to report screenshot" error happened many time
Five steps in half an hour, in the end, i clicked "NO" Because a bug, and the website refused to respond!
what a disappointment!

**Comment by hunt40** [comment]
yeah paperlesspost is the new attend,its like that since beginning

**Comment by luisdanielvc** [comment]
Rotagreek is another disaster, a lot of steps in a single one
