### ISSUE TITLE
71 steps, 30 minutes...job abandon ?

### ISSUE THREAD

**Issue by samballode6** [rainforestapp/tester-chrome-extension#345]
71 steps, 30 minutes...job abandoned ?
It's supposed 60 minutes, aren't they ?

**Comment by qpPykT** [comment]
@samballode6 

> It's supposed 60 minutes, aren't they ?

Now it's should be 90 min.


_"The time limit has recently been changed from 60 minutes to 90 minutes in order to accommodate tests that customers have a hard time making shorter. "_

**Comment by nerdatwork** [comment]
@samballode6 You were banned from Rainforest, is that correct ?

**Comment by samballode6** [comment]
@nerdatwork 
No...I am not banned from Rainforest, I am just fine now...
May I know. why do you ask ?

**Comment by thetodd1** [comment]
sambellende6 aka sigitsenyo , reported him for duplicate accounts, eventually he will be banned.

**Comment by samballode6** [comment]
@thetodd1 
I don't have duplicate accounts
I use just one now
Please understand, thank you...

**Comment by samballode6** [comment]
@qpPykT 
Thank you for your info, I appreciate that...

**Comment by thetodd1** [comment]
same type of avatar , same posting style writing long sentences ending in .....
even nerdatwork figured you out lol , waiting for a response from rf  about you .
enjoy your account while you can .

**Comment by samballode6** [comment]
@ thetodd1...
I think, this is not for your concern...
Please do you own business, not mine...
I did not do wrong thing with you...
What are you problems guys...
Who are you exactly ?
Are you human ?
