### ISSUE TITLE
Question about blocking policy

### ISSUE THREAD

**Issue by skoraatw** [rainforestapp/tester-chrome-extension#347]
I have one question
For example I have 2 rainforest profiles, one in clixsense and one in neobux, so my question is when I get 11 rejections in neobux and 11 in clixsense I get banned in all profiles, or if I make 21 rejections on neobux I get banned on neobux only

**Comment by helloworld111gh** [comment]
you are not allowed to work on two accounts

**Comment by skoraatw** [comment]
I mean when i used clixsense i have 11 rejections, then i claim my profile to neobux and start making tasks with neobux profile in rainforest

**Comment by nerdatwork** [comment]
You are violating Rainforest rules by using 2 accounts. You **MUST use only 1 account**. Pick either account and only use that account henceforth.

**Comment by nihlathar** [comment]
Having more than 1 account provides no benefit, they made it that way a long time ago. But you should stick to one, they can definitively ban all your accounts when they find out. 

Anyway, you should only get rejected sporadically, current system is fair and quite lenient therefore you should not get rejected unless you report 'no' in some bizarre part of the instruction, or, fail a test question

**Comment by maciejgryka** [comment]
@skoraatw What others said is exactly right - you can only do work using one profile.

@nihlathar a small note: we almost never punish people for clicking "no" (your work might not be accepted, but there will be no negative consequences). On the other hand we often block people who click "yes" in a wrong place. If you're ever in doubt, it's better to answer "No", or at least leave a comment.
