### ISSUE TITLE
Please Help with VM security error

### ISSUE THREAD

**Issue by henspear** [rainforestapp/tester-chrome-extension#348]
I very hopeless to find solution for this problem always occur when I got hit job to do from RF, I already tried all suggestion from here and clixsense furom but still no hope. Please help me guys to solve this kind of problem....

![rainforesterror](https://cloud.githubusercontent.com/assets/13687619/17168878/9947bcc4-5399-11e6-9634-8230a009dd69.png)

**Comment by nerdatwork** [comment]
Whenever  you face problem like this, you can refresh the page in order to get a new working terminal.

**Comment by henspear** [comment]
Still hopeless even I refresh it many time, I don't know what happen to this..,

**Comment by henspear** [comment]
Even in new update still I got this error.., too bad this error won't get away on me...

![rferror](https://cloud.githubusercontent.com/assets/13687619/17200463/5663d0a4-543a-11e6-87f7-e9fd173b079b.png)

**Comment by nerdatwork** [comment]
Try reinstalling chrome and the extension for Rainforest.

**Comment by henspear** [comment]
@nerdatwork: Thanks for replying, I did what you suggest but still this security error occurred.., I really don't know now what to do with this error..,

**Comment by qpPykT** [comment]
@henspear 
What kind of type internet connection do you use. Cable fiber or mobile like 2G-3G-LTE. Or something else.

**Comment by henspear** [comment]
@qpPykT: I use Cable Fiber, not the mobile type of connection. Does it affect with internet connection?

**Comment by uangonline** [comment]
@henspear Do you use proxies?

**Comment by henspear** [comment]
@uangonline: nope I don't use proxies, i don't know also how to use it.... :)

**Comment by uangonline** [comment]
@henspear Yes seems it's a bug since also encounter this once in a while, and i also doesn't use proxy.

**Comment by henspear** [comment]
Is there any way to resolve this bug? I wanna work with RF so many hits I already miss due to this error. please help me of this guys.

**Comment by nerdatwork** [comment]
@henspear Did you file a support ticket ?

**Comment by uangonline** [comment]
@henspear Most of the time just refreshing the job will do. If you encounter it again and again after refresh the job than i suggest to report it.

**Comment by henspear** [comment]
@nerdatwork: I already file a support ticket and its more than a week already but still no reply from them.

@uangonline: I never stop trying on refreshing the job even the error always appear again and again, but I feel wasted on all the hit job I miss.

**Comment by amerkurta** [comment]
Check the DNS settings, if still does not work, set the google dns on your computer (8.8.8.8) and you've solved the problem. Good luck!
