### ISSUE TITLE
New ERROR?? "Something bad happened"

### ISSUE THREAD

**Issue by MarinaCec** [rainforestapp/tester-chrome-extension#349]
I was testing well and now I'm stuck in this message... :(

**Comment by MarinaCec** [comment]
Aand now... You have reached the maximum number of unsubmitted assignments. So we are fair to other workers, we stop you doing too much for us at once. You can complete the other assignment(s) and refresh this page, or simply return this hit.

The update was good until a few minutes, faster terminal, shame that this error occurred, I hope that fix or that it does not last long.

**Comment by DrDejan** [comment]
Same thing with me. After "Loading" screen bar "Something bad happened" message appear. I refresh my browser only once and message "You requested this job too often" shows up.

**Comment by MarinaCec** [comment]
@DrDejan I'm thinking that this message is replacing "something get wrong"

**Comment by nerdatwork** [comment]
In the new interface you will  get some older messages and some new messages, its part of the update. Its not an issue as such.

**Comment by DrDejan** [comment]
nerdatwork, What is with message "You requested this job too often..."? Before new interface that message appear after 4 time refreshing browser and after that message was impossible to continue with task.

https://github.com/rainforestapp/tester-chrome-extension/wiki/Troubleshooting-&-Common-Errors-Explained 

"You have requested this job too often. Please return the work.

This message will appear if you have refreshed too many times - currently you can refresh a maximum of 4 times. If you request the job after that, you will see this message and have to close the tab and wait for a new job."

**Comment by nerdatwork** [comment]
@DrDejan You are correct, you can refresh a job a total of 4 times and only 2 times in 30 seconds.

**Comment by DrDejan** [comment]
nerdatwork, I know i am correct but.... 
Problem is: Loading bar is on the screen ( beginning of the new job, before starting terminal ) , suddenly loading bar disappear  and "Something bad happened" message appear on the screen. I refresh ( only one time ) browser and "You have requested this job too often. Please return the work." message appear.
This is not normal :-(
Is it a new rule or it is a BUG ?

**Comment by uangonline** [comment]
@DrDejan That's a new bug, All we can do now is wait until RF team fix this.

@nerdatwork You'r not a RF Admin right? Since most of the time your explaination make people got more confuse.

**Comment by nerdatwork** [comment]
@uangonline Thank you for your valuable feedback I have been waiting for this moment for years now.

@DrDejan In that case I think its a bug, please file a support ticket explaining your issue in detail and if you can add relevant screenshots that will be more helpful.

**Comment by uangonline** [comment]
@nerdatwork I know you mean no harm. Just read what other people say more carefully next time before you give help. It could be dangerous if other think you are a RF team Admin (which is i know you'r not) but give some confusing explanation.

**Comment by MarinaCec** [comment]
''This machine does not exist yet or this machine is incapable of having screenshots in it's state."

WHATS IS THAT????

**Comment by uangonline** [comment]
@MarinaCec It's mean "Failed to report screenshot". It same error/bug with different text message. But unfortunetly if you see this message in this new interface (unlike the old one) most of the time all you can do is refresh the job and start all offer again. I encounter this error several times and most of the time i must refresh the job.

**Comment by nihlathar** [comment]
Don't mind the errors. If terminal closed, or there's an issue just get a new one. If you can't because of some other red-text message, close the tab, and wait for new work (i recommend to reinstall the app periodically, helps with a lot of problems)
