### ISSUE TITLE
broblem in alot of task

### ISSUE THREAD

**Issue by awnosa** [rainforestapp/tester-chrome-extension#35]
today found url in a lot of test not work and very slow, in this case take screenshot of terminal and click next step and choose no or other is this right answer or not?, or the right should close test with take screenshot, what the correct answer in this case? and for this step pay 4c only.

![test](https://cloud.githubusercontent.com/assets/16338438/11937060/99def678-a81a-11e5-8249-6f1a8c314bd0.JPG)
.

**Comment by nerdatwork** [comment]
I do not think you are doing it right. You need to read the instructions carefully and then submit the task. All those 4 cents only shows you are not doing the Tasks properly. Please ready the instructions again and again.

**Comment by Ranky2211** [comment]
@awnosa I think all these hit are consumer affair hit with timeout error.

**Comment by awnosa** [comment]
thanks for reply me, but my question what the correct answer when the url in test not open, is the correct take screenshot and choose other or no button and type the problem or close test without screenshot

**Comment by Genesis2015** [comment]
@awnosa In your case - Other = Web Page Time Out

**Comment by awnosa** [comment]
ok thanks
