### ISSUE TITLE
new error, affter try take screemshoot

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#350]
![image](https://cloud.githubusercontent.com/assets/19192312/17214244/fb20f278-54a5-11e6-96ee-13efcff1746c.png)

**Comment by uangonline** [comment]
@zfonck123 Same error/bug but different text message. It's mean it's "failed to report screenshot". Try to do it again several times. If still failed, all you can do is refresh the job and start all offer again or you can tried until "connection lost" error appear.
