### ISSUE TITLE
problem to work

### ISSUE THREAD

**Issue by alfredolol** [rainforestapp/tester-chrome-extension#351]
hello I have a problem,when I have a job the page is blank and I do not get anything someone know wy? i try reinstall chrome extension but the problem continue, and i try reinstall chrome Navigator an the problen continue too

**Comment by nerdatwork** [comment]
Can you take a screenshot of the page whenever you encounter it as blank ?

**Comment by nihlathar** [comment]
It's a new problem that appeared when they introduced the new interface. It's probably fixed by now, if not, try to get a new terminal and if problem persists, report it through the 'no' option
