### ISSUE TITLE
another error, if try reload i will get job obten

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#352]
![image](https://cloud.githubusercontent.com/assets/19192312/17223383/51827e9c-54ca-11e6-9c61-373b696b6f56.png)

**Comment by zfonck123** [comment]
Could not get a osx_firefox machine.

**Comment by nerdatwork** [comment]
This error is specific and in detail than earlier message of "There are no VMs...". So you can safely refresh the page to get the terminal.

**Comment by zfonck123** [comment]
not is that error, i get a job affter 10seconds get error. but affter 5minutes and 2 refresh get my job again
