### ISSUE TITLE
Still can't see any vm performance improvement with this new interface.

### ISSUE THREAD

**Issue by uangonline** [rainforestapp/tester-chrome-extension#353]
Still can't see any vm performance improvement with this new interface. Still have a lot of bugs.

**Comment by nerdatwork** [comment]
List the bugs you found.

**Comment by uangonline** [comment]
@nerdatwork Same bugs as the old one.

**Comment by nerdatwork** [comment]
So you see absolutely no improvement in speed, performance, layout, total working of the terminal ?

**Comment by uangonline** [comment]
@nerdatwork Nope, No improvement what so ever with speed and performance and all the bugs that the old interface has, which is the most important to fix. So can you fix this?

**Comment by nerdatwork** [comment]
Thank you for your feedback.

**Comment by uangonline** [comment]
@nerdatwork Are you one of the RF team?

**Comment by kaytsu** [comment]
With the tasks that I have done using the new terminal I have still seen no terminal available, and someone else took the job the same amount. 

In the tests themselves I have gotten less "failed to report screenshot" (only once maybe?) and connection lost. (I don't think I've gotten any connection lost today) 

So in my opinion the new interface is better then the old one.

**Comment by nerdatwork** [comment]
Is it better "then" or better **"than"** ?? :)

**Comment by uangonline** [comment]
@kaytsu: I still encounter connection lost, Failed to report screenshots and other bugs.

@nerdatwork And why that so important? Great atitude you have there.

**Comment by tulko** [comment]
the new interface works very well. please do not remove.
same question @nerdatwork  you are a tester or RF staff
