### ISSUE TITLE
Typo in the new error messages

### ISSUE THREAD

**Issue by kaytsu** [rainforestapp/tester-chrome-extension#354]
![image](https://cloud.githubusercontent.com/assets/20136128/17224794/04ef854a-54c8-11e6-9694-e2125a7b0d4f.png)

**it's** is a contraction of it is or it has (It's time to test the website)
**its** is possessive (The tree has lost all of its leaves.)

The error message should just be its with no apostrophe. 

This machine does not exist yet or this machine is incapable of having screenshots in **its** state.

**Comment by nerdatwork** [comment]
I dont think there is any typo in the error message. It merely states that the machine in it's current state cannot take screenshots. Here the "it" is machine/terminal so machine's state is same as it's state. You have explained it earlier its = it is now if we use your logic the sentence would be "This machine does not exist yet or this machine is incapable of having screenshots in **it is** state." Here "it is" makes no sense.

**Comment by kaytsu** [comment]
http://www.grammar-monster.com/easily_confused/its_its.htm
This is from the website - you are the one that is incorrect. 
![image](https://cloud.githubusercontent.com/assets/20136128/17226539/9a7785ca-54cf-11e6-8430-8eb465ee875c.png)

Grammar dictates that a contraction has to have an apostrophe. So the contraction of it is becomes it's. The apostrophe takes the place of the removed letters in a contraction. 
its is not the same as it is. it's is the same as it is (just like I've is the same as I have and you're is the same as you are)

**Comment by nerdatwork** [comment]
Wow I stand corrected. Thank you for this lesson :)

**Comment by kristen-allie** [comment]
Thanks for reporting this! I'll share it with the team!

**Comment by luisdanielvc** [comment]
Connection lost everywhere
