### ISSUE TITLE
only is a question.

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#356]
in this moment, us have job with CF, or when open again for new members ? i remember two friends comming work withs us at 27 of june, but affter 4 july, i dont never see the job.

**Comment by luisdanielvc** [comment]
The last time i saw it was the 24th of July

**Comment by nerdatwork** [comment]
Here's a quick update on Rainforest testers! As of today, we've stopped accepting new testers until the need comes up in the future. We hope this will allow us to focus on providing better quality results to our customers, along with a better quality testing environment for all of you. That being said, welcome to all the new testers that have joined us recently! We're excited to have you! Keep up the good work, everyone!

**Comment by nihlathar** [comment]
Claim your rainforest profile, then you can get the work through the app (if you've done any tasks, recently, you should see a notification with the link here https://tasks.crowdflower.com/notifications)
