### ISSUE TITLE
Bug fixes (revisit issue)

### ISSUE THREAD

**Issue by sweeneyapps** [rainforestapp/tester-chrome-extension#357]
I did fix some serious bugs going on with your extension.

Here's list of bugs
- It dropped job and fail to open a new tab until the next polling cycle.
- polling too much (16 seconds is not good for the server)

I did submit pull request against the Master branch today and updated everything by bumping up version and fixing the test.  It should build without any problem thru CI then you guys could have updated the extension thru Google Chrome Store by today or tomorrow.     We will appreciate the faster updates cycle on bug fixes.   I know that 2.0 is underway, that's why I closed my pull request from last week due to disappointment that none of Rainforest staff are looking at it.    Then I realized that I couldn't leave it alone because we will never know when 2.0 will be out.  It's in process and probably requires some testing time before releasing it out in the wild.    

So that's why, I'm bringing this up here so I can get noticed and any of Rainforest staff can share this w/ the development team there.   

I already tested my code and it works great with getting job to the new tab.   You don't have to worry about closing tab after completing a job.   You'll not have to worry about the extension dropping job after one cycle.   It relaxes the server and for sure, the server will respond back every 20 seconds to let you know if there's job.   

Before the bug fix, the extension is asking the server for job every 16 seconds,  first request: no, 2nd request: no, 3rd request: stop it! too much request.  (we will never know on 3rd request if there's job or not).   so we lost 32 seconds in that process. (2 x 16 seconds) Or... even more than that because it takes time to process the request thru from extension to server.   

About the tab problem:  it's so silly if there's job and the extension just skip opening tab when it can't find the tab that it's asking for.  Of course, it can't find the tab because we closed it after completing a job.   The extension doesn't know that, we closed the tab and it won't know.  Then it will wait until the next time it ask the server again to see if there's job.   With that setup, we missed some chances to secure a job.   

Now I need your help..   SHARE THIS with the Extension development team.   Believe me, I did tag them on github and they never reach out to me at all.  I felt so invisible.

**Comment by nihlathar** [comment]
222
