### ISSUE TITLE
Rain closed again?

### ISSUE THREAD

**Issue by josejecr97** [rainforestapp/tester-chrome-extension#359]
Is rainforest closed again to new testers? i have some days without see the job in the crowdflower list

**Comment by nerdatwork** [comment]
If you are already registered then why are you looking for the job in CF list ?

**Comment by josejecr97** [comment]
refferals??

**Comment by nerdatwork** [comment]
As of today, Rainforest has stopped accepting new testers until the need comes up in the future. Thank you.

**Comment by josejecr97** [comment]
:O srsly? @nerdatwork where u read that?

**Comment by nerdatwork** [comment]
You will get a notification either in your email or in the CF inbox.

**Comment by josejecr97** [comment]
oh thanks!

**Comment by nerdatwork** [comment]
Update: Check this https://portal.rainforestqa.com/

**Comment by uangonline** [comment]
@nerdatwork Are you sure? There is nothing mention on not taking new member from the link you provide. So where do you read about this?

**Comment by luisdanielvc** [comment]
@uangonline It clearly says "As of today, we've stopped accepting new testers until the need comes up in the future."

**Comment by uangonline** [comment]
@luisdanielvc On what date?

**Comment by uangonline** [comment]
@luisdanielvc ah yes my mistake. Sorry.
