### ISSUE TITLE
Failed to report screenshot.

### ISSUE THREAD

**Issue by Unsubmitted** [rainforestapp/tester-chrome-extension#36]
Hi RF Team,

Not able to take screenshot even after multiple restarts on all hits.

Thanks

**Comment by jaspreet188** [comment]
same here  :(

**Comment by BV25** [comment]
Yes..it has been ongoing for over 30 mins. @pscohn

**Comment by Ranky2211** [comment]
@pscohn Hi RF team Same here on first step after pasting job url even after multiple restarts.

**Comment by NSPthakur** [comment]
getting the same problem.

**Comment by NSPthakur** [comment]
Getting same problem.

**Comment by AmaiaKao** [comment]
Screenshot failing, losing hits... :/

**Comment by qpPykT** [comment]
Same thing for me.

**Comment by sizika66** [comment]
Same.

**Comment by Genesis2015** [comment]
Same annoying situation here :(

**Comment by nihlathar** [comment]
same

**Comment by Katy112** [comment]
Same here.I restarted the hit several times,same error.I got another hit,but same screenshot error.

**Comment by AlexandruVerenca** [comment]
Yeah, having the same issue. I tried restarting the browser, reopened the window and it persists.

**Comment by kwimy** [comment]
Same here,2 hits lost due to this problem.

**Comment by Shatoth** [comment]
same problem!

**Comment by rajib9** [comment]
same here...failed to take screenshot...

**Comment by BonesKnows** [comment]
same here

**Comment by richiepurple** [comment]
same here

**Comment by awnosa** [comment]
same problem

**Comment by awnosa** [comment]
every task open find take screenshot not work any tester find this problem also  

![untitled](https://cloud.githubusercontent.com/assets/16338438/11981155/b11ac800-a9a8-11e5-928f-810b14f9787e.JPG)
![2](https://cloud.githubusercontent.com/assets/16338438/11981157/b1ed285e-a9a8-11e5-86d5-b8cd57aaff7c.JPG)

**Comment by helloworld111gh** [comment]
gettting 404 errors trying to send screenshot: http://puu.sh/m6anE/c431c5d9c9.png

**Comment by roko777** [comment]
I have exactly the same problem. Lost 3 test due to a problem with screenshots.

**Comment by MuhammadRafique182014** [comment]
its working now

**Comment by jbarber** [comment]
Hi guys, we've identified the issue and fixed it. Many apologies for the problems :(
