### ISSUE TITLE
2 Testers sharing same VM

### ISSUE THREAD

**Issue by sweeneyapps** [rainforestapp/tester-chrome-extension#360]
It's so funny!  I started on a job and then someone took over the screen and doing the work.  I'm like hey! I am working on this job!!  so then I went ahead refresh and finish the job without any problem.   I don't know if refresh did solve the problem but probably the other tester left the job.

**Comment by nerdatwork** [comment]
That is odd and that issue was resolved. Was it the only time this happened ?

**Comment by uangonline** [comment]
@sweeneyapps Yap i also encounter this 1 time. You should refresh the job to get a new VM, don't close the tab just refresh it.

**Comment by kristen-allie** [comment]
Thanks, all! I'm reporting this to the team.

**Comment by kristen-allie** [comment]
@sweeneyapps can you provide the job ID or your worker ID? The team can't see any evidence of this in the logs, so one of those might be helpful in tracking down the issue.

**Comment by nerdatwork** [comment]
@uangonline You can also provide with the job ID or worker ID to help Rainforest fix this issue asap.

**Comment by sweeneyapps** [comment]
@kristen-allie here's my worker ID A2IZF5P145XIE
 I think it was on job ID 7388308

**Comment by sweeneyapps** [comment]
as long, it's reported. :)  closing this..
