### ISSUE TITLE
good, I want to express my dissatisfaction with the closure to new people to RF.

### ISSUE THREAD

**Issue by jombere** [rainforestapp/tester-chrome-extension#361]
I wonder how long will this ?, I think it would be good to open the RF new people once a month.

**Comment by luisdanielvc** [comment]
It is good because the team can concentrate in solving the problems of the server, the more users on the system, the more problems we'll have. I know it's sad, i had like 4 referrals who wanted to start but there are a lot of people testing at the same time and the server cannot with that.

**Comment by uangonline** [comment]
@luisdanielvc Agreed, Fixing bugs is more important right now.

**Comment by josejecr97** [comment]
I think is really good the close, because there are many tester and is really hard to find any job...

**Comment by nerdatwork** [comment]
@jombere Your feedback is duly noted. Since this place is for posting issues testers face related to the chrome extension, please close this thread.
