### ISSUE TITLE
Unable to get the final rating page or thanks page

### ISSUE THREAD

**Issue by balajisekar** [rainforestapp/tester-chrome-extension#366]
Hi,

**Rainforest Job 7403168**

After completing all the steps, at the final step (12th step) job is not getting submitted. After final step, page is not redirecting to rating page. I got the same response after doing it 2nd time. If rating page doesn't came I didn't get payment for this job.

Please look into this issue and resolve this as soon as possible. Past week this happened to me for more than 3 hits.

**Note:** Attached is the screenshot of the hit, which captured at different timings.

![image](https://cloud.githubusercontent.com/assets/16969519/17275477/5d8db72e-5727-11e6-9fbc-57f37f1b8857.png)

![image](https://cloud.githubusercontent.com/assets/16969519/17275478/660dab84-5727-11e6-9306-3e5a01a101c2.png)

![image](https://cloud.githubusercontent.com/assets/16969519/17275479/6be6c8c4-5727-11e6-9b0d-4dc8bcfebea7.png)

**Comment by nerdatwork** [comment]
Have you filed a support ticket yet ?

**Comment by balajisekar** [comment]
Yes, I have filed a support ticket too.

**Comment by josejecr97** [comment]
hey i think is against the terms post work caps.... be care

**Comment by nerdatwork** [comment]
@josejecr97 : You are not supposed to post/discuss clients whose NDAs you have signed outside Rainforest Support other than that its ok to post screenshots. To protect your privacy I would recommend removing or blurring your email address. You can always discuss or mention them privately in the support ticket.

**Comment by macocha** [comment]
As @nerdatwork mentioned. Please do not discuss and especially post screenshots of jobs under NDA outside our Support channel.  

We removed screenshots from the original post and will close the issue, please take it further with our support.
