### ISSUE TITLE
rainforest tester notifier not working

### ISSUE THREAD

**Issue by luisdonner97** [rainforestapp/tester-chrome-extension#367]
I give the button to change the "off" to "no" and the extension does not work help me

**Comment by nerdatwork** [comment]
What do you mean it does not work ? Can you explain more ? If it says NO its working and will turn into YES when there is job.

**Comment by luisdonner97** [comment]
the "off" button I click and does not change "no"

**Comment by josejecr97** [comment]
try to reinstall the notifier

**Comment by nerdatwork** [comment]
Try reinstalling chrome and the Rainforest extension and see if that helps.

**Comment by nerdatwork** [comment]
If your issue is resolved please close this thread
