### ISSUE TITLE
Site stopped!

### ISSUE THREAD

**Issue by bilelmz** [rainforestapp/tester-chrome-extension#368]
I don't know what to say! 
With the recent improvements, I think that things are better, but... 
The picture says it all 
In step 26, site stopped!
The site have a lot of problems, especially in the many steps jobs
![sans titre](https://cloud.githubusercontent.com/assets/20234458/17305210/a684b3b2-5829-11e6-96bb-cbf14cb731e9.jpg)

**Comment by nerdatwork** [comment]
Did you try to refresh the HIT and complete the job ?

**Comment by bilelmz** [comment]
i try 3 time before!
Every time i get a problem
This is the fourth one

**Comment by zfonck123** [comment]
refresh the job 2 or 3 times is loss at time, and if refresh mroe of 4 times  u get job obten "loss at job" and block for 30min or more

**Comment by diabolic012** [comment]
Same problem here. Last 2 days experienced same problem 4 or 5 times. Refresh do not help.

**Comment by bilelmz** [comment]
I got the same problem again 
In the last step the site does not respond 
i did the job twice, but .... nothing! 
i send support ticket, but as usual, no response!
![sans titre](https://cloud.githubusercontent.com/assets/20234458/17405498/02894dde-5a60-11e6-8eb1-6a6237ac164b.jpg)

**Comment by nerdatwork** [comment]
@bilelmz You can hide your email address but keep the job id so its easier to diagnose the issue.

**Comment by bilelmz** [comment]
@nerdatwork thanks
this is the job id: 7504735
i didn't get a reply for this support ticket, and for the Previous tickets

**Comment by pscohn** [comment]
When this happens, can someone screenshot the javascript console and/or the network console? There may be some error showing that will help us diagnose.

**Comment by nerdatwork** [comment]
@bilelmz You can **press F12** on the job page to show the different options and choose **Network tab** for the screenshot. This is what @pscohn meant. In case you dont know how to see network console.

**Comment by bilelmz** [comment]
@nerdatwork @pscohn thanks
I'll do that next time

**Comment by bilelmz** [comment]
this happened few minutes ago
I completed the job after refresh
![02](https://cloud.githubusercontent.com/assets/20234458/17410614/c569952a-5a74-11e6-9af2-23527e23e258.jpg)
![03](https://cloud.githubusercontent.com/assets/20234458/17410631/cf059fc0-5a74-11e6-8582-ac27913d471b.jpg)

**Comment by pscohn** [comment]
I don't see anything that might be related to this bug in the screenshots, so I'll look into this some more.

**Comment by uangonline** [comment]
@pscohn I think it's not complitly stop. I think i've encounter this type of error before with this new interface. It just took longer time to show an error than the old one. I have to waited full 3 minutes to see the error message. But not always though.

**Comment by pscohn** [comment]
@uangonline what error did it show?

**Comment by uangonline** [comment]
@pscohn I think "Something Bad Happen" and " Fail to perform..." This 2 kind of error that i saw when that happen.

**Comment by uangonline** [comment]
@pscohn One more thing, can you please change the way the error message display? It just add a new error message below the old message and close the "YES NO" button, if we tried to click "YES NO" button before the old one diseppear.

**Comment by bilelmz** [comment]
It's happened again
in the last step, Step 24!
so frustrating!
![01](https://cloud.githubusercontent.com/assets/20234458/17424064/9ca200f4-5ac0-11e6-9ffe-00bb8ed055b9.jpg)

**Comment by A1xx** [comment]
Hi everyone! I have the same problems several times. Yes No buttons are disabled and I can not do anything. I am so disappointed, because it happens at last step((( Maybe there is any way to make buttons enabled? Think about such function. Something like reconnect button 
![errror](https://cloud.githubusercontent.com/assets/17779557/17450823/960e40b4-5b73-11e6-81a7-c6cadf9f6427.jpg)

Here is url of this job: https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx84b061-dd2b-4370-aeaf-728702a6b62b&browser=any&hitId=4277134&sig=b76461780315c5b7b69573e31ffd56bf9428cc54209e648d9ab307c0c65f301c&turkSubmitTo=%2Fthanks&workerId=31233917

**Comment by bilelmz** [comment]
@A1xx OMG 58 step!

**Comment by diabolic012** [comment]
Already 2 jobs like that today. Job done, no payment....

**Comment by qpPykT** [comment]
@A1xx 
You signed NDA. Your screenshot has a part of NDA site.

**Comment by uangonline** [comment]
@A1xx It's disabled before you click the button or after?

**Comment by A1xx** [comment]
@uangonline After I pressed the button. And I can tell you for sure that the site didn't stop. I had one more job with such problem. The terminal worked, the site worked it didnt freeze. I waited and got "Job abandoned". So I think that somehow after pressed the button at last step I just wasn't redirected to confirmation page.

**Comment by bilelmz** [comment]
happened again!
in last step!
so frustrating
next time, when i see a job like this, with many steps, i'll close the page simply
![sans titre](https://cloud.githubusercontent.com/assets/20234458/17503617/82bb4694-5df1-11e6-954b-67fe5e927e2d.jpg)

**Comment by diabolic012** [comment]
It seems better not to do jobs with more then ten steps. 16 steps for me few minutes ago and nothing after I press on "DONE" at the end of the job.

**Comment by pscohn** [comment]
This is our top priority to fix right now, though it's a little hard to debug/reproduce. We're going to release a log feature soon that will hopefully help us debug - you can just click to copy the log after something goes wrong and then send it to us for debugging.

**Comment by bilelmz** [comment]
@pscohn
thanks
hope this problem fixed soon.

**Comment by nerdatwork** [comment]
@bilelmz Please remove the NDA client screenshot from your post. **You should NEVER discuss about NDA clients outside the Rainforest ticket support system**. Also are you using any Chrome extensions like **AdBlock Plus** or **GreaseMonkey** or **TamperMonkey**?

**Comment by pscohn** [comment]
The copy log feature is now available. When this happens again to someone, please save it in a text file and you should be able to upload it here.

**Comment by bilelmz** [comment]
@nerdatwork 
what is "NDA client screenshot" ?
yes i use AdBlock

**Comment by diabolic012** [comment]
This is log from my last job which didn't go through.
[New Text Document.txt](https://github.com/rainforestapp/tester-chrome-extension/files/410125/New.Text.Document.txt)

**Comment by nerdatwork** [comment]
@bilelmz In the most recent screenshot you posted, you can see **Sighten** which is our NDA client. 

@diabolic012 Thank you for posting the log file.

**Comment by sweeneyapps** [comment]
When you go to Rainforest Profile page, you signed the NDA (non-disclosure agreement) which you promised to not reveal their website to the public or tell anyone about it.   This forum is public.   The reason I'm explaining here because I think that any of you might doesn't understand what NDA means.

Here's what it looks like on the NDA page..   below

Qualifications
You can qualify for more jobs by completing short forms, such as signing a website's non-disclosure agreement.

Current Available Qualifications: 
There are no new qualifications at this time.

Completed Qualifications:
Consumer Affairs NDA
Emailage NDA
Lutron Privacy Policy
Sighten NDA

**Comment by diabolic012** [comment]
Another log from 36 steps unsuccessful job

[10.08.2016.0725CEST.txt](https://github.com/rainforestapp/tester-chrome-extension/files/410371/10.08.2016.0725CEST.txt)

**Comment by pscohn** [comment]
Thanks for the logs @diabolic012 . It will also be helpful if someone can capture it, to have the network tab open BEFORE doing the last step (it can be popped out in a separate window), and then if the bug happens to screenshot the end of the network request list.

**Comment by bilelmz** [comment]
Another one
I pressed "NO" in step 21 for a bug
[Rainforest Job 7693920.txt](https://github.com/rainforestapp/tester-chrome-extension/files/412049/Rainforest.Job.7693920.txt)
![sans titre](https://cloud.githubusercontent.com/assets/20234458/17569842/3e74bd76-5f4a-11e6-8b90-2470ff088566.jpg)

**Comment by bilelmz** [comment]
And another one!
[Nouveau document texte.txt](https://github.com/rainforestapp/tester-chrome-extension/files/412209/Nouveau.document.texte.txt)

**Comment by bilelmz** [comment]
I refresh and get the same result again!
[Nouveau document texte.txt](https://github.com/rainforestapp/tester-chrome-extension/files/412225/Nouveau.document.texte.txt)

**Comment by pscohn** [comment]
@bilelmz merci. do you see any network errors when this happens?

**Comment by bilelmz** [comment]
@pscohn For the third time, same result
![sans titre](https://cloud.githubusercontent.com/assets/20234458/17573709/7a54f34e-5f5c-11e6-8236-0d11267eca02.png)

**Comment by pscohn** [comment]
@bilelmz you have to open the network tab before you get to the step, otherwise it won't start logging the requests. I'm sorry this is still happening though.

**Comment by bilelmz** [comment]
@pscohn I'll do it next time.

**Comment by bilelmz** [comment]
@pscohn Another one
![01](https://cloud.githubusercontent.com/assets/20234458/17601869/77499570-600a-11e6-849d-450df542f14d.jpg)

**Comment by pscohn** [comment]
@bilelmz that screenshot is helpful, thank you

**Comment by pscohn** [comment]
@bilelmz do you have adblock enabled?

**Comment by bilelmz** [comment]
@pscohn when i did this job,i disabled it
sometimes even if the adblock enabled, the problem not happened

**Comment by A1xx** [comment]
@pscohn I have installed AdBlock, but it is diabled on rainforest sites. I had about 10 jobs with this problem.

**Comment by bilelmz** [comment]
The problem still exists

**Comment by nerdatwork** [comment]
@bilelmz Remove Adblock extension and restart the browser. The Abdlock extension might be interfering with the normal working of the terminal. Even though you might have it disabled on the Rainforest page there are always some scripts that might be blocked. You have already spent lot of time and HITs for this error so give this a shot and I am very sure this would resolve your issue :) (fingers crossed)

**Comment by pscohn** [comment]
@nerdatwork's suggestion could work, please try it and let me know if it solves the problem. I can't find any problem in the code that would be causing it, and the vast majority of jobs seem to have no problem.

**Comment by bilelmz** [comment]
@nerdatwork @pscohn I'll try it. I'll remove Adblock completely.
I think that the problem is related to the number of steps. It's not exist in the jobs with a few steps.

**Comment by diabolic012** [comment]
Problem is not in Adblock, I removed  him and still have same issue with ten stepper 2 minutes ago.

**Comment by nerdatwork** [comment]
@diabolic012 Could you open this in chrome "chrome://extensions/" and post a screenshot ?

**Comment by diabolic012** [comment]
Here is a video, cannot take screenshot.
https://vimeo.com/178695080

**Comment by qpPykT** [comment]
@diabolic012 
Are you have been trying to disable or remove all of your plugins except rf? Have a such bunch of junk it's not a good idea.

**Comment by diabolic012** [comment]
Will try....

**Comment by diabolic012** [comment]
No, problem is not in extensions,  I tried using only RF extension on a clear chrome browser and still same problem happened on 15th stepper.

**Comment by bilelmz** [comment]
It happened again.
Although i removed Adblock completely.
Any job containing 15 or more step, the problem appears!
please fix that problem.
![sans titre](https://cloud.githubusercontent.com/assets/20234458/17675920/3d62cc58-632c-11e6-9197-281dcf80ef09.jpg)

**Comment by uqbiii** [comment]
You should try to complete a HIT in incognito mode, if you have allowed any of your extensions to run in incognito mode then stop them for a while for incognito and if you do, close the original windows for a while, or try to complete a HIT in any other but updated browser.

**Comment by bilelmz** [comment]
@uqbiii I'll try it.
But i think the problem is related to the number of steps, like i said, any job containing 15 or more step, the problem appears!

**Comment by uqbiii** [comment]
@bilelmz Maybe, but it's working fine for me, i completed some jobs with more than 15 steps yesterday and today but not faced such kind of problem. Hope it will be resolved soon.

**Comment by bilelmz** [comment]
I completed a job with more than 15 steps, Adblock was removed and all extensions were disabled.
Now, i try with some extensions and see what happen.

**Comment by bilelmz** [comment]
Now, confirmed that this problem is not related to extensions!
The same problem with a job of 15 step, Adblock removed, ALL extensions disabled.
It's clear that the reason related to the number of steps, more than 15 = get problem!

**Comment by nerdatwork** [comment]
@bilelmz Can you try using a different computer ?

**Comment by bilelmz** [comment]
@nerdatwork Frankly, tired of trying.
I don't know, if i get this problem again, i'll close the window.

**Comment by nerdatwork** [comment]
I understand but can you at least try.

**Comment by A1xx** [comment]
@nerdatwork I had this problem on two different computers (one at home, one at my work). 
About one week I don't have it anymore. Only once I had something like this. Done Button got disabled, but this time, after few minutes I got error message, two red lines came up on the page with text. It was something about fetch. When I made screenshot the error message had gone. Button got enabled. I pressed it again, it became disabled, waited and got Job abandoned this time. 
Here is my screen, maybe it will be helpfull.
![333331111111](https://cloud.githubusercontent.com/assets/17779557/17829011/d8dde5a0-66b0-11e6-995a-5d51a7944ffe.png)

**Comment by nerdatwork** [comment]
@A1xx Next time when you get that red error message click the "Reconnect" button and try again. It should work.

**Comment by qpPykT** [comment]
@nerdatwork 
Reconnect button just refresh flash inside the terminal. How it will be help with "yes" "no" or "done" buttons. It's not affecting on buttons outside the terminal.

**Comment by uqbiii** [comment]
@A1xx The image you uploaded have two **unusual** things, first the link was bookmarked(not a problem) and HIT id is 4277331 and currently this figure is around 77***** which shows it's an old link, 2nd, there are two tabs opened for HITs, there may be some conflict, i am not sure but this could be the reason. When you get a new HIT with new HIT id, check if you face the same problem or not, and also when you get a HIT, don't open other tabs related to HIT. I am not sure about these things, but currently these 2 seems to be the reason of this problem.

**Comment by A1xx** [comment]
@uqbiii Thanks for reply, I opened second tab after I got error, usualy I don't open second tab with HIT. I just didn't now what to do with this buttons disabled, so I tried different stupid things))) I copied the job's url in new tab. 
About old link. Should hitId in the url and Job be the same value or near it? Few minutes ago I got new job, hitid in url is 4277311 and Job is 8013092. Got other job 8012743 and the hitid the same - 4277311. And everything was fine,  there was no problem with buttons.

**Comment by uqbiii** [comment]
I just checked and found that all of the my previous history contains the same HIT ID, so there is no problem for this and my assumption was wrong, sorry for that. But it's very strange scenario you are facing. I completed 15+ today without zero error, even when i started typing this comment, i got 1 and completed successfully, "Done" button works perfectly and i am still thinking whats going wrong at your side.

**Comment by A1xx** [comment]
@uqbiii I had 10+ jobs with disabled buttons at last step(((. But for last week it happend only once. And now everything seams to be fine. I hope it whould not happened again.

**Comment by nerdatwork** [comment]
@A1xx I hope it works well. Have you tried reinstalling chrome and the extension before ?

**Comment by bilelmz** [comment]
@uqbiii you said: "Put the same url in firefox or any you prefer and try to complete the HIT. Maybe this works?" 
Is it acceptable? and what about the original window in Chrome Do I have to close it?

**Comment by bilelmz** [comment]
@pscohn where are you?
The problem still happened to me, this time with just 13 step.
I removed chrome and install it again, NO Adblock NO extensions, but .......
![sans titre](https://cloud.githubusercontent.com/assets/20234458/17834996/08666dbc-6759-11e6-9107-9e8b6dba1043.jpg)

**Comment by uqbiii** [comment]
**browser=any** in the link means that you can use any. When RainforestQA tasks were started, they will ask for a specific browser but the real concern was VM's browser so they changed it to any, and Chrome by default because the extension is only available to chrome users.

**Comment by sweeneyapps** [comment]
@uqbiii Actually, browser=any means what kind of assignment do you want.  It's only related to the VM assignment.  It's set to any so you can have the opportunity to grab any jobs that are available.   If you set it to browser=chrome then you are limited to Chrome VM testing only.  That will limit your opportunity and miss a lot of jobs.

**Comment by helloworld111gh** [comment]
@sweeneyapps This is false, uqbills answer is correct. Back in the day you did the hit in your own browser, not via VM. So you had to be testing in the browser that the HIT needed. 

 @bilelmz Next time this occurs, in the network tab, click on "answers" and screenshot the stuff that pops up. Then click on "Timings" or something similar and screenshot what pops up there.

**Comment by sweeneyapps** [comment]
@helloworld111gh I am correct.  Your old day is different and currently, it's related to VM.

**Comment by uqbiii** [comment]
@sweeneyapps Maybe i am wrong, but still i think completing a HIT in browser other than Chrome is not a problem, they are also web browsers and are as good as Chrome. @sweeneyapps What's your opinion?

**Comment by sweeneyapps** [comment]
I would suggest to stay w/ Chrome and make sure it's updated.   Because Rainforest developers expected you to be on Chrome because of the Chrome extension.

**Comment by bilelmz** [comment]
This time with just 10 steps!
![sans titre](https://cloud.githubusercontent.com/assets/20234458/17981454/1ea0be26-6b04-11e6-9c57-622fb9acb79d.png)

**Comment by pscohn** [comment]
@bilelmz are you still doing the jobs with no extensions installed? are you using an incognito window? do you have any other software or firewalls that might be blocking connections?

**Comment by A1xx** [comment]
Yesterday I had one more job with this problem. During this job on diferent steps I had error "Something bad was happened" 2 times. And at the last step I got disabled buttons((( 
![test2508_2](https://cloud.githubusercontent.com/assets/17779557/17982797/93d3cb3c-6b1a-11e6-9d1f-5ae274e60483.png)

Why 2 times I got disabled buttons for a wile and then got error message and buttons enabled again, but at the last step it did not happened?

**Comment by bilelmz** [comment]
@pscohn I removed Adblock, the other extensions are disabled. No i'm not using an incognito window currently, but i try it before with no change. I have kaspersky installed on my computer.

**Comment by A1xx** [comment]
@pscohn The internet connection could be the reason of this?

**Comment by bilelmz** [comment]
The same thing again, what a waste of time!
@pscohn .........................
![sans titre](https://cloud.githubusercontent.com/assets/20234458/18007902/2f0a011c-6ba6-11e6-9f66-a1a47b1c8de6.png)

**Comment by helloworld111gh** [comment]
Next time this happens, do "Network" > "answers" > "Timings" > Screenshot
and post results

**Comment by pscohn** [comment]
@bilelmz can you do what @helloworld111gh suggested, and can you also try disabling kaspersky during your jobs to see if that helps?

**Comment by bilelmz** [comment]
@pscohn @helloworld111gh I'll try.
It's ok disable kaspersky after the job start?

**Comment by pscohn** [comment]
@bilelmz if that somehow steps the network request when finishing the job, I think that's ok.

**Comment by bilelmz** [comment]
@pscohn Happen again.
Kaspersky was enabled, because i completed a job before like that.
I noticed that when the terminal slow. and there is errors such as (something bad happened) the problem happen.
Also, why this problem happen just for the jobs containing 15 step or more?
Can i try to complete a job in another browser (firefox ...)? in this case, Do I have to close the original window in Chrome?
Please fix that problem.
![sans titre](https://cloud.githubusercontent.com/assets/20234458/18166536/0a2afc20-704c-11e6-8536-e600be4ae0f5.png)

**Comment by bilelmz** [comment]
Another one!
![sans titre](https://cloud.githubusercontent.com/assets/20234458/18169669/7fe84dd2-705b-11e6-92c3-95250d2a7c83.png)

**Comment by pscohn** [comment]
@bilelmz my question isn't whether you can complete a job with kasperspy enabled - it's whether you ever get the error with it disabled. Can you disable it for every job and let me know if it solves the problem? It may have to do with the amount of data in the request that kasperspy could be blocking for certain jobs (with a lot of steps) and not others.

**Comment by bilelmz** [comment]
@pscohn I'll try.
What about the other question: Can i try to complete a job in another browser (firefox ...)? in this case, Do I have to close the original window in Chrome?
Is it possible that the problem related to Internet connection (DNS ...)?

**Comment by bilelmz** [comment]
@pscohn This time, Kaspersky was disabled.
I restarted the job and completed it.
![sans titre](https://cloud.githubusercontent.com/assets/20234458/18180270/61fe861c-7086-11e6-9913-e585874bd054.png)

**Comment by bilelmz** [comment]
@pscohn The same again!
Kaspersky was disabled.
So frustrating!
![sans titre](https://cloud.githubusercontent.com/assets/20234458/18214007/2c61df84-714b-11e6-8a16-a324d6c6830a.jpg)

**Comment by pscohn** [comment]
@bilelmz I'm sorry you're still getting this, I'm not really sure what the cause is. Do you have any other software or extensions that might be blocking network requests?

**Comment by bilelmz** [comment]
@pscohn All extentions are disabled, i removed Adblock completly.
I have only Kaspersky.
I had many times the security errors (#2048, #2031) related?
Can i try to complete a job in another browser (firefox ...)? in this case, Do I have to close the original window in Chrome?
Is it possible that the problem related to Internet connection (DNS ...)?

**Comment by pscohn** [comment]
@bilelmz you can try in firefox, and probably close the chrome tab before opening it. If you have access to a different internet connection, or even computer, it's worth trying to see where the problem is.

**Comment by bilelmz** [comment]
@pscohn I think this problem is related to these errors: 
An IO Error occured: ioError, Error # 2031
A security Error ocurred (Error # 2048)
Because it show when the problem occurs.

**Comment by bilelmz** [comment]
@pscohn Hi, it's a month since the last replay!
- The problem still happen to me, but rarely.
- I removed Java (don't know if this is why the problem happen fewer than before)
- I tried in Firefox several time, it works fine, no problem with it. (maybe the problem related to Flash player plugin inside Chrome?)
- If you cancel the possibility to refresh the job page, then i can't work with Firefox!
I hope this problem get fixed soon, thanks.

**Comment by bilelmz** [comment]
@shosti @pscohn Why this topic closed?! my problem still happen, as you see in my last reply.
please fix that problem, it's not happen never in Firefox, why just Chrome?! so frustrating.

**Comment by helloworld111gh** [comment]
Non-extension related support got moved, ask for help here: forum.rainforestqa.com

**Comment by bilelmz** [comment]
@helloworld111gh I'll try, but i don't think i'll get a response from the RF team, as what i see in the forum.

**Comment by jbarber** [comment]
We've closed the issue because it's not related to the extension, I'll follow up in the forum.
