### ISSUE TITLE
error in click to take screenshot 

### ISSUE THREAD

**Issue by awnosa** [rainforestapp/tester-chrome-extension#37]
every task open find take screenshot not work any tester find this problem also  

![untitled](https://cloud.githubusercontent.com/assets/16338438/11981155/b11ac800-a9a8-11e5-928f-810b14f9787e.JPG)
![2](https://cloud.githubusercontent.com/assets/16338438/11981157/b1ed285e-a9a8-11e5-86d5-b8cd57aaff7c.JPG)

**Comment by nerdatwork** [comment]
This has already been covered in #36

**Comment by pscohn** [comment]
Also covered in https://github.com/rainforestapp/tester-chrome-extension/issues/7
