### ISSUE TITLE
A lot of issues today

### ISSUE THREAD

**Issue by mijorojas** [rainforestapp/tester-chrome-extension#370]
What is happening today? I have got a lot of problems when clicking YES or NO in a test.

**Comment by uangonline** [comment]
@mijorojas Alot of "Something bad happened" error message today.

**Comment by luisdanielvc** [comment]
And problems with the screenshot as usual

**Comment by euparkeria** [comment]
Something very weird happened to me today. I couldn’t login because the username and password was incorrect so I answered “No” and gave a report of the error but the test did not end and It continued to ask me the other questions(are you human, add this and that number)… Very weird.

**Comment by huynhxuanvinh** [comment]
Lost conection many times. If previously I have terminal after refreshing 1-3 times, now I can't have one even refresh 4 times and finally have to abandon job. So frustrating.

**Comment by kaytsu** [comment]
@euparkeria That is a normal test for that site. It is testing the login system. (making sure the right messages show up when it is wrong)
