### ISSUE TITLE
@pscohn My ticket, please check. Thank YOU.

### ISSUE THREAD

**Issue by myIssue** [rainforestapp/tester-chrome-extension#372]
Hallo Mr.

I want to you check my ticket #12839 for my issue detail. Till now it hasn't been resolved yet.
Thank YOU for your help.

**Comment by nerdatwork** [comment]
@myIssue How long ago was the ticket submitted ?

**Comment by myIssue** [comment]
@nerdatwork  since 27 June

**Comment by kutch1** [comment]
I submitted also alot of tickets and there are no replies on them !

**Comment by pscohn** [comment]
Responded to your ticket
