### ISSUE TITLE
@pscohn I submitted 2 tickets long time ago and i had no response

### ISSUE THREAD

**Issue by kutch1** [rainforestapp/tester-chrome-extension#373]
Can you please check ? #14328 and #13604 ! 

Thanks in advance

**Comment by nerdatwork** [comment]
When did you submit the ticket ?

**Comment by kutch1** [comment]
July 11th and the other one is 5 days ago .

**Comment by josejecr97** [comment]
yes.... it takes a long time... i dont know why..
