### ISSUE TITLE
Suddenly appear Job abandon

### ISSUE THREAD

**Issue by djux90** [rainforestapp/tester-chrome-extension#374]
Today i got two job abandon, and says that i waited too long, but jobs just appeared, or it says no VM and when refresh, just got that job abandon message

**Comment by nerdatwork** [comment]
Please read this : https://github.com/rainforestapp/tester-chrome-extension/wiki/Idle-Policy

**Comment by djux90** [comment]
I know that, and that is because i post this. It is all diferent from that, like i said, it is suddenly, just appeared, i was there, waiting for job, and just got that

**Comment by nerdatwork** [comment]
Does it happen to all jobs or you encountered one job with this issue ?

**Comment by djux90** [comment]
no, that was just for yesterday, and it seems now it is ok

**Comment by nerdatwork** [comment]
If your issue is resolved please close this thread.
