### ISSUE TITLE
Brand New Tester

### ISSUE THREAD

**Issue by Fallingsoul86** [rainforestapp/tester-chrome-extension#375]
Good Day Rainforest Team!

First of all, thanks for the good work, keep the improvement...

I have something to ask, I started to work with a help of a friend on August 1st, I already claim the profile and have a lot of work done and bug finded, but, the payment don't reach Crowdflower, please, can you help with this issue?

Thanks in advance!.

**Comment by nerdatwork** [comment]
Please give your worker id and did you file a support ticket for this issue yet ?

**Comment by Fallingsoul86** [comment]
Thanks for the quick reply Nerdatwork, My Id for Crowdflower is "38597628", and I didn't fill a support ticket yet, I only write a mail to "tester@rainforestqa.com" last Thursday.

**Comment by nerdatwork** [comment]
While writing the email did you mention your worker id shown in the Rainforest profile.

**Comment by Fallingsoul86** [comment]
![image](https://cloud.githubusercontent.com/assets/20804914/17520304/42aa88a4-5e1d-11e6-8a3b-1c294eb4c7f5.png)

![profile](https://cloud.githubusercontent.com/assets/20804914/17520334/5f7e9a38-5e1d-11e6-8d05-49a2992c7bb7.PNG)

That is my profile and History, my ID worker is the "38597628" that can be see on the History tab.

**Comment by Fallingsoul86** [comment]
Requester Javier Araque Created Today at 07:33 Last activity Today at 09:01
Id #14566 Status open Worker ID 38597628 I need help with... New Tester Job Id —

**Comment by Fallingsoul86** [comment]
Ticket created

**Comment by nerdatwork** [comment]
Great now wait for Rainforest to reply to your ticket.

**Comment by Fallingsoul86** [comment]
Please Paul Cohn @pscohn do you can see something about this issue please, I already have 1 Week waiting for some reply, thanks in advance and sorry for disturb.

**Comment by sweeneyapps** [comment]
I noticed your profile and I don't think it's possible.. because you have been member since Aug 2016 and Rainforest stopped accepting new tester on July.   How is that possible?   That's might reason why they are not paying you.

**Comment by Fallingsoul86** [comment]
It's fair enought, I know and understand the situation, I'm just asking for a opportunity to be working on your team... thanks in advance.

**Comment by TheOneWhoKnock** [comment]
@sweeneyapps may be he was not claim his profile immediately

**Comment by zfonck123** [comment]
@sweeneyapps  i think can give one oportunity to coming to team. not is a "bad tester"  80/3 is soo good

**Comment by TheOneWhoKnock** [comment]
@zfonck123 yep my acc is 90/2 but cf ban my acc without explain@@ RF should open for woker like us to change id.

**Comment by zfonck123** [comment]
@TheOneWhoKnock but CF is at CF, and RainForest is another.   only u can change id with another chanel example gifhunter club, elite,neobux cliksense ect, u need waiting for reopen new tester and get a job nivel 1 "rainforest" y think the  old name is " test a web application with any browser" with a new chanel.

**Comment by TheOneWhoKnock** [comment]
@zfonck123 yeah but it can take a long time  till re-open :))

**Comment by nerdatwork** [comment]
@TheOneWhoKnock Rainforest **does not** change worker ids. I understand your situation but there are already enough testers and when new testers are allowed to join, you can try to claim another profile but till then there is nothing you can do besides waiting.

**Comment by TheOneWhoKnock** [comment]
@nerdatwork yep i know. but it so sad :(

**Comment by Fallingsoul86** [comment]
@sweeneyapps Something more that can be said?

**Comment by sweeneyapps** [comment]
sorry, I was just surprised.  I hope thing will work it out for you with Rainforest staff.

**Comment by zfonck123** [comment]
@pscohn any updated about that ?

**Comment by Fallingsoul86** [comment]
It's hard to be in this way =/.
