### ISSUE TITLE
job abandoned after 60 minutes

### ISSUE THREAD

**Issue by huynhxuanvinh** [rainforestapp/tester-chrome-extension#376]
Rainforest staff please change the limit time to 90 min or more, please  because I just got the first 90-step hit and get the abandoned message at the the step 78. All my work in 60 minutes is gone. Please increase the limit of time or each test, or at least change the limit time depend on the length of test.

**Comment by nerdatwork** [comment]
The time limit has already been increased to **90 mins**. If you spent more time on the hit, naturally it will show you job abandoned.

**Comment by huynhxuanvinh** [comment]
No, I have just done that test 5 minute before I wrote this topic and I also have count the time I spent, and it's exactly 60 minutes since I accepted the job. I have also read Idle policy in the wiki again and it also said the same 
"Your job will be aborted in the following cases:

If you do not start the job within 10 minutes after accepting it.
If you do not show progress on the job for 15 consecutive minutes after starting.
If you do not complete the job within 60 minutes of accepting the job.
If you disconnect (close the page or internet down) for 5 minutes"

**Comment by IceCreamCake** [comment]
I have same problem, the fist time i reach 87 steps job. And after working  just 50 minute. Connection lost.  After few times try to click Reconnect, then "Job abaddon". So, that "The time limit has already been increased to 90 mins" is lie, i guess.
