### ISSUE TITLE
No connection in the test browser

### ISSUE THREAD

**Issue by roko777** [rainforestapp/tester-chrome-extension#38]
All evening this problem (((![default](https://cloud.githubusercontent.com/assets/16417121/11986028/99fc6efa-a9d3-11e5-95df-1869247679f4.jpg)

**Comment by Genesis2015** [comment]
Same here :(

**Comment by Ranky2211** [comment]
I face this connection error with only consumer affair hit and this is with their website problem and to be reported.Problem is not with test browser.i checked the browser.It has connection.

**Comment by jbarber** [comment]
Thanks for letting us know, but as @Ranky2211 suspected this was a problem with the server.
