### ISSUE TITLE
Another tester was on my VM.

### ISSUE THREAD

**Issue by euparkeria** [rainforestapp/tester-chrome-extension#380]
So I got a HIT and a terminal opened but after I pasted the URL I noticed the mouse cursor started moving on itself and someone else was also connected to the VM and tried to paste the URL. After fighting for control for a moment I decided to confirm my suspicion and typed “Who Are you” in the browser address bar and the other user answered something on the lines of “I don’t know what’s going on”. I decided to restart the HIT and refreshed the page but unfortunately got “you have requested this job too often”.

**Comment by nerdatwork** [comment]
Please give the Job ID or your Worker ID so Rainforest can better understand what actually happened.

**Comment by uangonline** [comment]
@euparkeria Yap, that's a bug. Don't worry just refresh the job to get a new VM.

**Comment by warpten09025** [comment]
It happened to me half year ago

**Comment by nerdatwork** [comment]
@euparkeria We cannot help you if you cant provide your worker ID or Job ID for this issue.

**Comment by JPierreS** [comment]
This is a rare issue where more than one tester shares the same terminal.

Do not try to complete the job.  Your only option at this point is to RESTART the HIT (refresh in your own browser) this will get you a fresh new VM.  Keep in mind if the other party refreshes first, you will see a terminal disconnect.  never attempt to complete the job inside a shared terminal, only 1 person can get paid, not both :D

**Comment by jbarber** [comment]
Hi, we thought we'd nailed this problem a while back, but it looks like it's back. I think I've got a fix which we'll deploy in the next couple of days.
