### ISSUE TITLE
Is it ok to to job when you got exceed message

### ISSUE THREAD

**Issue by djux90** [rainforestapp/tester-chrome-extension#381]
i got message rate exceed for exidentaly refreshed 2 times fast, but job appeared when i again clik on refresh instead on close. Is it ok for me to do it?
To explain it better. i accepted job, and got message that cannot get browser, i refreshed it and got rate exceed (probably refreshed two times), then aplication error came out. I refreshed it again and finish job. Is that ok? I couldn't find anything for explaining that situation

**Comment by uangonline** [comment]
@djux90 Yes, that's fine.

**Comment by JPierreS** [comment]
Not a problem, when you get a live HIT it means it is now assigned to you.  The refresh limit is hard coded internally so if you were able to get through it means that you were within limits.

**Comment by nerdatwork** [comment]
If your issue is resolved please close this thread.
