### ISSUE TITLE
Get Something bad happen everytime get a new job.

### ISSUE THREAD

**Issue by uangonline** [rainforestapp/tester-chrome-extension#383]
Get Something bad happen everytime get a new job, refresh on the page once and boom you request this job to often. It just getting worse by the day.

**Comment by JrRandy** [comment]
They changed the refresh rate to 2 every 50 secs instead of 2 every 30 secs in hopes of reducing this I believe.

**Comment by uangonline** [comment]
@JrRandy Yes i hope so.

**Comment by qpPykT** [comment]
@JrRandy 
The load is still there. This is the fourth consecutive day, almost at the same time.

![metrics](https://cloud.githubusercontent.com/assets/4960092/17600439/2e42f194-600c-11e6-90cb-f6e6ac9ebace.jpg)

**Comment by uangonline** [comment]
@qpPykT I see a better performance for now, but something bad happen still appearing most of the time when we get a new job. Also i notice that even though we already get a VM we still sometimes redirect to something bad happened page.

**Comment by uqbiii** [comment]
I think, the real purpose of this change is to reduce the status code: 400 request. After the change, extension turns to Yes more than before, no matter i got HIT or not and this error is happening to all of testers, so wait and see what will happen.

**Comment by JPierreS** [comment]
I do not believe this has anything to do with server load.  I work the night shift and I see some stats here, even with less than 600-700 workers, more than 1/2 less than day time, there are similar issues with "something bad happened" or other issues.  These issues are separate problems such as transient issues with hosting or application errors / local issues (non Heroku) 

So those errors, slow downs, etc, I get even during night time.

As far as requests, prior to extension , the way to get jobs was through CrowdFlower.  Now as more and more people use extension (thousands) compared to the past, this means the number of "requests" has likely increased exponentially, so this could be the reason why they are addressing this.

Back in the days the requests were hard coded at 6 seconds at API level, then 8, and there were far less issues than now, but probably also less requests across the board.

I do not think this will resolve the transient issues, hosting issues, errors, this is a different ball game.  There are days when I see 2x number of runs and workers online and all is running smoothly.

You will not get less jobs from polling at 2/50 than you would 2/35 or any figure, since the limit is set for everyone.

**Comment by JrRandy** [comment]
There is likely something else going on.  The server should be able to handle the requests being thrown at it.  1500 users at 15 secs per request is only an average of 100 requests per second.  That is nothing compared to computing power nowadays.  It is always around the same time, and last for a few hours.  Its likely as @JPierreS stated.

**Comment by begsoon** [comment]
@JPierreS I totally agree with you.

**Comment by Elizabesita10** [comment]
I've had this problem almost all day today I have completed a few job

**Comment by uangonline** [comment]
@Elizabesita10 Yes, today, by far, is the worst day in RF testing history lol.

**Comment by huynhxuanvinh** [comment]
for the last 6 hours I have gotten 8 hits and can you believe, all of them gone with "another worker..." message. I never meet this situation before when I can get 5/8 number of hit. Don't know what's happening but I think the add-on rainforest or the server has an error. So frustrated when a new open and got that message all the time.

**Comment by uangonline** [comment]
@huynhxuanvinh No, that's normal. Annoying? yes, nut normal. It's just you'r not fast enough to get the job.

**Comment by uqbiii** [comment]
Got 23 so far in 10 hours, but today lots of error showed up then before.

**Comment by uangonline** [comment]
@uqbiii NICEEEEE!!! 5 so far in 3 hr.

**Comment by huynhxuanvinh** [comment]
@uangonline  no, got some of them is normal but get that message all the time is not normal. I even can get the hits this morning but now have passed 14 hits and 14 are gone with "another worker" message. It's very strange when I lost 100% number of hits. My computer have core i7 processor and 8 GB ram and my internet speed is 80 Mbps so it had to have something wrong. My ID worker is 33676548 so if you are staff of RF and have read my post please check it. Thanks.

**Comment by uangonline** [comment]
@huynhxuanvinh lol, I'm NOT RF staff. I just an ordinary tester like you. Try to ping tester.rainforestqa.com and tell me the time you get.

**Comment by huynhxuanvinh** [comment]
@uangonline  it's 55 ms.

**Comment by uangonline** [comment]
@huynhxuanvinh  Well that's normal if your not from USA.

**Comment by uqbiii** [comment]
Take a look at mine, not as good as yours.  Minimum = 213ms, Maximum = 233ms, Average = 224ms. I think you should try a clean installation of extension, if still persist then reinstall chrome, I also uninstalled and reinstalled my extension yesterday.

**Comment by uangonline** [comment]
@huynhxuanvinh Hope get a better luck next time though.

**Comment by uangonline** [comment]
@uqbiii I don't that will help with his situation, he still got a hit from extension.

**Comment by huynhxuanvinh** [comment]
My friend also confirm the problem as me. If this can happen to Vietnam so it can happen to another country which is far from the server. But till this morning I still could get hits without problem but now is so frustrating. I have installed again my extension but can't change anything. I will wait until tomorrow before reinstall my browser. Really sad if one day I can't get hit to do.

**Comment by uangonline** [comment]
@huynhxuanvinh Sorry i can't give you much help. Hope you will find solution for your problem.

**Comment by huynhxuanvinh** [comment]
@uangonline  thank you. I will try to find out the problem and hope everything will be better tomorrow.

**Comment by uqbiii** [comment]
vinhvip: I hope tomorrow will be better than today. Good Luck

**Comment by huynhxuanvinh** [comment]
@uqbiii thank you. time to sleep after a hardworking day. I do not have only rainforest job so try do do many things in the same time make me tired. By the way, try my best to catch the target of this month.

**Comment by qpPykT** [comment]
@uqbiii 
Ho-ho. Tomorrow will be weekend days and it's not so good for getting a lot of hit.

**Comment by uqbiii** [comment]
apart from HITs there will be no one to solve all these ongoing problems, and "no vm" message increases in weekend so it will be hard to get a vm with all these problems and it looks like Monday is not much good.

**Comment by MilaZj** [comment]
Worst week ever.

**Comment by normensstounss** [comment]
I completed 25 hits ( but I never sleep) and yes many bad errors.

**Comment by uangonline** [comment]
@normensstounss Never sleep? What are you? A robot? lol

**Comment by MilaZj** [comment]
Are u a human? lol

**Comment by uqbiii** [comment]
@normensstounss I think you are this guy "neotaruga" or maybe his brother, btw got 25 as well.

**Comment by normensstounss** [comment]
I'm kidding, I sleep. lol :smiley:

**Comment by normensstounss** [comment]
@uqbiii No I'm not "neotaruga"

**Comment by qpPykT** [comment]
@normensstounss 
Are you just Neo :D :japanese_ogre:
