### ISSUE TITLE
Jobs with hundred steps and lost connection

### ISSUE THREAD

**Issue by CharlieSpock** [rainforestapp/tester-chrome-extension#384]
Why clients send jobs with too many steps like a 110 steps?. The system expels testers within an hour of the VM's. My experience a job with 110 steps when i do the step 87 a connection lost message appear, i try to reconnect using button on the VM not get connected again and lost all the job. When i refresh the page a message say that all jobs are sumited. Should recommend to customers who do not make job's with too many steps.

**Comment by uangonline** [comment]
@CharlieSpock I think steps is not an issue here. I'v finished jobs with many step without problem. The most important issue here is how to make sure that VM will not disconnected when tester doing a job. Jobs with many steps help a lot.

**Comment by CharlieSpock** [comment]
@uangonline yes thats right! maibe the capacity of server and the many users online on certain time of day make some diference on performance of VM's

**Comment by sweeneyapps** [comment]
I would recommend rainforest to save snapshot every 25 steps.  So that way, we get paid for doing every 25 steps on an one big job (unlimited steps)...   If it's feasible for them to do that.. then that would be great..

**Comment by uqbiii** [comment]
I also completed one with 107 steps, it was very easy so no problem occurred and completed in 45 minutes, but i thought that if job with that much steps with a slow website appears to me, i will simply close the tab instead of wasting 60 minutes. They should make a system, like if someone is clicking yes or no and passing steps the time for him will increase accordingly, what if a website owner makes a test with 200 steps, no one can complete it in 90 minutes as well.

**Comment by uangonline** [comment]
1 Big thumb up for @sweeneyapps.

**Comment by uqbiii** [comment]
@sweeneyapps waiting for your update on jobautoreload, i installed it yesterday and they changed the limit.

**Comment by sweeneyapps** [comment]
i'll update the limit..

**Comment by uangonline** [comment]
@sweeneyapps Why not give an option popup to change the timer, so you don't need to update it everytime rate limit change.

**Comment by sweeneyapps** [comment]
@uqbiii For now, I set it at 30 seconds..   because I'm editing off github website.   when I have time tonight or this weekend.   I'll add the option popup like @uangonline suggested.  that would be great.     Any of you..  don't be afraid to leave Issues on my github and I'll follow up on it.

**Comment by uqbiii** [comment]
That's Great!!! Thank you for the update and for the upcoming update as well. From now i will post on your own github for help related issues.

**Comment by samizle** [comment]
I have also had a frustrating experience doing a job with +80 steps from Sighten NDA, not to mention that my connection was a little slow. While I was on the very last steps of the task, i lost connection forever of the VM and timed out! I cannot tell how much disappointing that was as you lose time and energy for granted. I suggest that it would be much better to divide tasks with multiple steps into parts of 25-30 or so. As soon as one finish the first part and rate it, the VM will automatically load the following part. I am not sure if this one is feasible or not, but it would be like a chained task.

**Comment by huynhxuanvinh** [comment]
@uqbiii where can I get that job auto load program. Link to install, please

**Comment by uqbiii** [comment]
@huynhxuanvinh https://github.com/sweeneyapps/JobAutoReload
