### ISSUE TITLE
still no notifications

### ISSUE THREAD

**Issue by vrr123** [rainforestapp/tester-chrome-extension#387]
Hello.
I confirmed 2 tasks (id 930309, 919467) and I have not received any notification. I can't claim my profile...
Support service is not responding.   my last ticket #13893

**Comment by nerdatwork** [comment]
What do you mean you cant claim profile ? When did you submit your ticket ?

**Comment by vrr123** [comment]
there is no message with a link to my profile after I confirmed the task from RF - https://tasks.crowdflower.com/notifications

the ticket was created on July 19.

**Comment by nerdatwork** [comment]
When did you complete the task ?

**Comment by vrr123** [comment]
11 June and 8 July.
![default](https://cloud.githubusercontent.com/assets/19910901/17665187/f72a4894-6301-11e6-9687-bb28eae8ea4f.png)

**Comment by qpPykT** [comment]
@vrr123 
I think if all goes well the notification with a link to claim your profile is sent on same day when the task was done.
Did you were previously registered in the rainforest?

**Comment by vrr123** [comment]
I was doing   tasks before, but I was not registered in the RF.

I was doing tasks of RF in 2015. But I did not confirm my profile at the time. All messages and notifications came and preserved.  But NOW these old links do not work, and it is impossible to confirm the user's profile.

**Comment by uqbiii** [comment]
that's not possible, even if you are an old tester, you still receive a message about claiming profile, and if you are trying to get your 2nd account with the same contributor id, that may be the issue.
