### ISSUE TITLE
Please also put restart job button in "Something Bad Happened" and "Application error" page.

### ISSUE THREAD

**Issue by uangonline** [rainforestapp/tester-chrome-extension#391]
Hello @ukd1 @pscohn, can you please also put restart job button in "Something Bad Happened" and "Application error" page? That would be nice feature.

**Comment by uqbiii** [comment]
How awesome if they remove these errors,  Sounds Great!!!. 
Give them some time and they will remove them as well.

**Comment by uangonline** [comment]
@uqbiii I'm sure they will, but before that's happen, i think put the button is necessary.

**Comment by TheOneWhoKnock** [comment]
not relate, but is there anything to push a sound when a job is comming and a new tab popup? guys? thanks

**Comment by uangonline** [comment]
@TheOneWhoKnock They not give that feature, but you could add it your self to the script though.

**Comment by TheOneWhoKnock** [comment]
@uangonline how to do it ? or u know any extension with same funtion?

**Comment by helloworld111gh** [comment]
Theoretically, good design would have the tester interface automatically
retry if it got an error.
I'm sure there will be less complaints about server issues if there is auto
retry (just keep showing the loading bar).

**Comment by TheOneWhoKnock** [comment]
@helloworld111gh yeah i found a extension to do this, u guys can try cola tab extension :D

**Comment by uangonline** [comment]
@TheOneWhoKnock Just put "var audio = new Audio('any audio folder/any audio.wav');" below "var _ravenJs2" and "audio.play();" below "if (resp.work_available) {"

@helloworld111gh Agreed.

**Comment by uqbiii** [comment]
i am using tempermoneky with a java script which is working really good.

**Comment by TheOneWhoKnock** [comment]
@uangonline thanks mate but, i need to learn code fist :))

**Comment by uangonline** [comment]
@TheOneWhoKnock Well i also new in Javascript lol.

**Comment by androwg** [comment]
@uangonline  hi in witch file can i found "var _ravenJs2" ?

**Comment by helloworld111gh** [comment]
@androwg It is impossible to manually edit the extension unless you are
willing to learn advanced JS and command line tools in order to compile and
install edits.

**Comment by androwg** [comment]
@helloworld111gh Hoped that i have time to learn other things :)

**Comment by uangonline** [comment]
@androwg Like @helloworld111gh  said.

**Comment by sweeneyapps** [comment]
@TheOneWhoKnock  @helloworld111gh 

 I wrote some tamperMonkey script here..  at my gist page..  [https://gist.github.com/sweeneyapps/9a74def901420422dafd30415a7057b2](url)
and also added  new job sound feature on my JobAutoReload github page at [https://github.com/sweeneyapps/JobAutoReload](url)

I hope those are helpful.  :)

**Comment by TheOneWhoKnock** [comment]
@sưeeneyapps thank you but link not work bro pls fix :D

**Comment by sweeneyapps** [comment]
@TheOneWhoKnock  @helloworld111gh 

 I wrote some tamperMonkey script here..  at my gist page..  https://gist.github.com/sweeneyapps/9a74def901420422dafd30415a7057b2
and also added  new job sound feature on my JobAutoReload github page at
https://github.com/sweeneyapps/JobAutoReload

I hope those are helpful.  :)

**Comment by TheOneWhoKnock** [comment]
@helloworld111gh @uangonline @androwg @uqbiii can u show me how to use the gift from Mr. @sweeneyapps , thank you :+1:

**Comment by TheOneWhoKnock** [comment]
@sweeneyapps it worked :D thank so much bro

**Comment by sweeneyapps** [comment]
lol, I'm glad you figured it out and be able to select your own sound.

**Comment by uqbiii** [comment]
@sweeneyapps It's working really good, but don't you think that using a sound from our computer is much better, as you can see the sound @TheOneWhoKnock uploaded is 75kb, and everytime it rings, it will use your 75kb (i am not asking to save data,), and this 75kb is more important for TAB instead of extension.

**Comment by sweeneyapps** [comment]
@uqbiii I did some updates....  but logically, once sound is loaded from the internet, it's cached on your computer locally.

**Comment by TheOneWhoKnock** [comment]
@sweeneyapps  @uqbiii i think so :D it respond very fast

**Comment by RnkSts** [comment]
@sweeneyapps I try your JobAutoReload app and It's fully working C: Thanks so much for sharing it! I could not leave here without thank you for this amazing help :smile:

**Comment by sweeneyapps** [comment]
no problem!   I had much fun today playing Forza Motorsport 6: Apex Beta while waiting for Rainforest job.  :)   It's free on Windows 10.   Something to keep you busy.

**Comment by uangonline** [comment]
@sweeneyapps Spoiler alert!!! lol.

**Comment by androwg** [comment]
@sweeneyapps Can you adjust it to give a sound when we get a real work not just a another work or there is no vm messages ?

**Comment by samizle** [comment]
The worst scenario happened to me twice now. +50 steps job and on the very last moment I received "application error" message yesterday when the task already rated and the submit button clicked. it took me like 35 minutes to get it done. What a frustration! I reloaded the page and I was taken back to the start page. I hold back my anger and disappointment and proceeded with the job again, but I kept receiving errors like "something bad happened" and "connection lost, error # ...something" and finally "this assignment is marked as complete...."!! ah-h!!
Please, guys, help us out and make that SAVE button for tasks +30 steps or so, at least we get paid for what we worked for. Thanks everybody for the hard work!

**Comment by uangonline** [comment]
Finally implemented thanks.
