### ISSUE TITLE
2-3 step jobs

### ISSUE THREAD

**Issue by priggy** [rainforestapp/tester-chrome-extension#393]
Today, whole day, i received around 12 tasks and bunch of red message hits (either another worker took my  job or something bad happened). Those 12 jobs I managed to get in had 2, 3 or at most 4 steps... Anyone having same trouble?

**Comment by srsaurabh32** [comment]
yup same issue...

**Comment by Dolazim** [comment]
This is not issue jobs is jobs even if he have 2-3 step...

**Comment by uqbiii** [comment]
1st, RainforestQA employees can't do anything about this topic, it's upto the website owner.
2nd, it's not an issue to discuss further and we should work as a tester not as a moneymaker. Our priority is to give best of our work. What if you get a 100 steps HIT and had to report it in the 1st step? What will you do, and it you feels? If you work as a tester you will fell good but you feel really bad in other case.

**Comment by andrianr** [comment]
It is a good job.. You will be sure you 100% won't see "Lost connections" :)

**Comment by marius11** [comment]
> Anyone having same trouble?
That's not an issue. You should close this thread.
