### ISSUE TITLE
black area above and below browser 

### ISSUE THREAD

**Issue by androwg** [rainforestapp/tester-chrome-extension#394]
Please fix this problem 
![untitled](https://cloud.githubusercontent.com/assets/15823279/17740466/fc126826-6498-11e6-8931-d0c7d0744caa.png)

**Comment by luisdanielvc** [comment]
Yeah, the terminal looks very small but it's not a big problem

**Comment by nerdatwork** [comment]
This is an issue with the HD version of the terminal and Rainforest is working on fixing it. Thank you for notifying.
