### ISSUE TITLE
CF is killing spree-Can RF open to swap RF account one for one?

### ISSUE THREAD

**Issue by TheOneWhoKnock** [rainforestapp/tester-chrome-extension#395]
yesterday i has been got ban for task.cf account so might be i can't get paid throught over elite.cf.
Many friend of mine is have same problem, so why RF don't open to us to swap one for one  RF account (old acc will be delete or disable) so i continue work with u, this is not mean accept new worker, i am old one :(
 thank you 
ps;that is so sad, i got ban just because i fail in a job in Cf :(

**Comment by qpPykT** [comment]
@TheOneWhoKnock 
Bans are not handed out to all and sundry. If you're doing your job badly there then what can we say about other places. You can solve your problem with CF if you got the ban unfairly.

**Comment by TheOneWhoKnock** [comment]
it was unfair (i just do the quiz then out) but u know CF it take some month or never to process your ticket.

**Comment by uqbiii** [comment]
It must be a sentiment job, and i hate them, never tried a single one in 3-4 years, and my account is going well. Btw, it's not good to discuss cf ban here, try to find there phone number and call them, that may work!, otherwise wait for 5-6 months for their reply.

**Comment by TheOneWhoKnock** [comment]
it was not sentiment job :( just find info and i did not make money on that job at all just do the quiz and quit :(( so unfair, i mean that can RF can make a change for people like us. open to swap one for one RF (at good status at all)

**Comment by nerdatwork** [comment]
@TheOneWhoKnock This place is discussing issues with Chrome extension and not CrowdFlower bans. You should contact CrowdFlower since this is not related to Rainforest in any way. Please close the thread.

**Comment by TheOneWhoKnock** [comment]
@nerdatwork no i mean CF was ban my acc in task.cf.com but acc in elite.cf.com is not baned. So when it happen i still can receive cash from RF but CF will not pay for me and i want RF can swap acc for me so i can continue work on RF

**Comment by helloworld111gh** [comment]
No.
Please close this thread, Rainforest are notified of everything posted here
and hey will likely block your account after finding out your CF account
was banned.

**Comment by nerdatwork** [comment]
@TheOneWhoKnock I understand your problem now. Your account is banned in some reward site and you want to change your worker id. As of now Rainforest cant help you to change your worker ID.

**Comment by TheOneWhoKnock** [comment]
ok thanks for all your comment :+1:

**Comment by nerdatwork** [comment]
Please close the thread if you got a satisfactory response to your issue.

**Comment by TheOneWhoKnock** [comment]
ok I forgot. sorry
