### ISSUE TITLE
Could not get a ie11 machine.

### ISSUE THREAD

**Issue by nummuss** [rainforestapp/tester-chrome-extension#396]
Could not get a ie11 machine. Same with firefox.
assignmentId=cxe7456d-ef14-468b-89c9-6ac5d612c08b
workerId=30073888
Too often today.

**Comment by nerdatwork** [comment]
There is no need to report this issue here. It simply means the extension was unable to get an Internet Explorer version 11 machine. You can safely refresh the page when you see this message.
