### ISSUE TITLE
Account Blocked

### ISSUE THREAD

**Issue by xvmmc20x** [rainforestapp/tester-chrome-extension#397]
Good people my account was blocked because * Reason for block: You have failed to follow instructions on too many jobs * How I resolve this ??

**Comment by qpPykT** [comment]
@xvmmc20x 
Blocks are permanent for everyone and mean you cannot do tasks with Rainforest in the future on the blocked account or any other account you create.

**Comment by xvmmc20x** [comment]
Yes I read that , really dont any form to resolve this?.. Really I know that could happend

**Comment by qpPykT** [comment]
@xvmmc20x 
You can create a ticket but it is likely that your account has been blocked by the admin and cannot be unlocked.

**Comment by uqbiii** [comment]
How much rejection has you received in last 30 days? Or it is banned without rejections?

**Comment by xvmmc20x** [comment]
Yes I receive a rejections, but really man , I think they can send a email saying me hey look a lot rejection take care etc etc, but I really dont know that could be happend

**Comment by rnfrst** [comment]
High number of rejections is in the Wiki and that is linked to your portal, there is no way you could miss it unless you ignore it.

**Comment by xvmmc20x** [comment]
Thanks everyone well If I blocked nothing to do .. this piss me off .. but well, thanks a lot!

**Comment by nerdatwork** [comment]
@xvmmc20x Please close this thread if you got a response to your satisfaction.
