### ISSUE TITLE
You have reached the maximum number of unsubmitted assignments.

### ISSUE THREAD

**Issue by GreekGuy** [rainforestapp/tester-chrome-extension#398]
Almost one hour with this error after finishing a job.

**Comment by uqbiii** [comment]
Have you tried restarting your browser. Whenever this happens to me, i simply close that tab because refreshing that tab will show the same error, you should close all tabs related to HITs, restart your browser, restart your extension and i hope you will never see this again.

**Comment by GreekGuy** [comment]
I ve tried it and i also reinstalled the extension but nothing..
