### ISSUE TITLE
Somethign bad happened

### ISSUE THREAD

**Issue by priggy** [rainforestapp/tester-chrome-extension#399]
it is not that something bad happened.... it is HAPPENING.... continuously.... 5 jobs in a row, from 7 to 12 steps... each had to end at 1st... due to something bad happened message after few steps... restarted each job multiple times, same bug on same step... then it started messing up at the beginning not even taking initial screenshot...

**Comment by MarinaCec** [comment]
all day, every time refreshed

**Comment by djux90** [comment]
yes, for me to. Hope they will fix that soon
