### ISSUE TITLE
Mac OS Safari/Firefox are unresponsive

### ISSUE THREAD

**Issue by BV25** [rainforestapp/tester-chrome-extension#40]
Hello @pscohn  @jbarber 

This is with regards to the Mac OS platform and HITs on Safari Terminal.

The Terminal is 
- extremely slow
- is unresponsive. 
- It also freezes mid-way in a HIT.
- Left-click does not work, when you click, you get right-click options.
- While taking screenshot or moving cursor inside Terminal, the Terminal blinks a lot almost like a white screen - thereby prohibiting proper monitoring of work performed. 
- It actually takes more than 30 minutes to complete a single HIT due to this fallacy.  This is unacceptable. This problem is ongoing since a week.

I urge you to kindly rectify this serious problem which hinders the smooth execution of HITs at an earliest. Thanks.

**Comment by Genesis2015** [comment]
Same situation here :(

**Comment by nerdatwork** [comment]
Its a known issue with Mac terminals. Hope they fix it soon its been pending for too long

**Comment by BV25** [comment]
It's pre-existing but it was never so bad. It is now impossible to work. Left-clicks now do not work, if you click, it shows options as if you had right-clicked. Is there any way to fix this, please? This is deplorable.

**Comment by jbarber** [comment]
@BV25 I don't see any of the problems your seeing. What is your desktop environment, browser and Flash version?

**Comment by BV25** [comment]
I'm using Windows 10 and Google Chrome and my Flash version is 20.0.0.267. I've recorded two video highlighting this issue for your perusal so that it can provide a better insight :) But I'm unable to upload it here as GitHub shows an error that it does not support video format files to be attached. 
Is there a way I can attach or send you the video recordings?

The problems highlighted are 
- 1st video shows constant blinking  while performing a HIT (Specifically illustrated at 24 seconds - 38 secs and 01:06 secs), and extreme slow/lag issues. (this is common to all testers and others have reported this issue many times). 

- 2nd and 3rd video show how despite me using left-click on my mouse, the Terminal identifies it as if I have right-clicked and re-attempts are unsuccessful. The only option is to refresh Terminal, and this generally happens mid-way. This is detrimental in case you have a long stepper HIT which are 10-15+ steps.

I appreciate your timely intervention and reply that you gave. Thanks.

**Comment by helloworld111gh** [comment]
I can partially agree with the fact that Mac terminals are worse than Windows terminals. OSX Firefox/Chrome are only slightly worse or on par as Windows, but the Safari terminal is extremely bad. Copy and paste can paste incorrectly 25% of the time, and the terminal is also extremely slow.

**Comment by jbarber** [comment]
@BV25 upload to google drive / dropbox and share it?

**Comment by BV25** [comment]
https://drive.google.com/folderview?id=0B0reExMNiMLmVzI5RTJPMlM3OWM&usp=sharing

**Comment by BV25** [comment]
@jbarber Were the videos helpful? Any updates appreciated! The problem still persists.

**Comment by helloworld111gh** [comment]
When will this problem be solved?

Right now Safari terminals are so terrible that it is possible that webpages take up to a minute to render the CSS/JS! That is unacceptable!

**Comment by Unsubmitted** [comment]
The Safari terminals are really slow lately , RF Team do something to solve the slowness and especially copying the url in the address bar has became pain lately.

Thanks

**Comment by hunt40** [comment]
tell me about it i completely lost just  20 min ago,when i work on just 5 step rainforest hit,safari going completely mad,i have to refresh terminal 3 times,for a 5 step hit i spend 14 min for complete,its ridiculous bad , unresponsive ,slow ,truncated links everytime when i paste,i have to paste god knows how many times with this last hit at least 8 times.i am going completely mad.

**Comment by SantVzlaC** [comment]
I share the same problem with the Mac OS platform on Safari terminal. :/

**Comment by hunt40** [comment]
17 step zenefits right after 14. step lost connection with mac terminal,ill become cancer for this mac servers,what kind of QA company have this kind of bad quality i have no idea,this is beyond terrible,i am so mad right now,cant even paste the .... url to browser,always some words missing,this is nothing but a huge joke.now i ahve to start all over agaian cant copy the ..... url.

**Comment by androwg** [comment]
@jbarber yes Safari hits are very very slow and time consuming i hope you find a solution.
