### ISSUE TITLE
Do i need to report if on vm says problem loading page?

### ISSUE THREAD

**Issue by djux90** [rainforestapp/tester-chrome-extension#400]
It says that, but VM works well, opening all links, that is just in begining, i couldn't find answer on wiki, so i don't know do i need to report that, 
![1111111](https://cloud.githubusercontent.com/assets/20422665/17792875/69b02bb8-659b-11e6-9f4d-9b7b20c05cd0.JPG)

**Comment by kutch1** [comment]
No i don't think so because you still didn't do the 1st step at all .Also you enter a link then you take a screenshot so that doesn't count .

**Comment by nerdatwork** [comment]
If you are not getting any error messages or pages after pasting the link in first step then there is no need to report this error page because you have **NOT** started working yet
