### ISSUE TITLE
Member classification

### ISSUE THREAD

**Issue by Profica** [rainforestapp/tester-chrome-extension#401]
Good day, Is it possible to see list of members, or just for me classification of how good am I or others doing the job? Am I fair, sloopy or something third...

**Comment by nerdatwork** [comment]
If you are reporting the jobs that need to be reported and following the rules to the letter then of course you are doing an awesome job. We need more testers like you that are doing their best to give best results :)
:+1:

**Comment by Profica** [comment]
For this month I have 2 rejections, last month I had 4, sometimes happens that I report something but, number of bug stay the same. Do You count those reports as something bad?

**Comment by nerdatwork** [comment]
Bug count increases when other testers spot the same bug. Read the instructions carefully to avoid rejections. 20 rejections and your account is permanently banned.

I hope that helps.
