### ISSUE TITLE
ping 400+  something bad happened error

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#402]
![image](https://cloud.githubusercontent.com/assets/19192312/17811266/d7ee5100-65ef-11e6-9551-8e9e1a3d27f6.png)

**Comment by nerdatwork** [comment]
Yes the response time is really bad but its getting better now :)

**Comment by bilelmz** [comment]
I get the same job again!
With 28 step this time, but i simply closed the window, my nerves cannot afford more fatigue.

**Comment by zfonck123** [comment]
![image](https://cloud.githubusercontent.com/assets/19192312/17816643/38cad3a0-6608-11e6-9257-60bc4b261177.png)
![image](https://cloud.githubusercontent.com/assets/19192312/17816645/3aa7a73e-6608-11e6-839e-1a2a1222e163.png)

**Comment by marius11** [comment]
A thread addressing the same issue has already been opened here: https://github.com/rainforestapp/tester-chrome-extension/issues/399
