### ISSUE TITLE
This is second time, 53 step Job Abandon after work on 35 minute mark. (83 steps job in recently time)

### ISSUE THREAD

**Issue by IceCreamCake** [rainforestapp/tester-chrome-extension#403]
How can i work, when just submit the answer yes/no already take almost 30s-1 minute, and then Lost connect - Job Abandon on 35 minute????

**Comment by zfonck123** [comment]
the server have error in this moment :( :(

**Comment by uqbiii** [comment]
got a HIT at 06:11pm PST and now 06:56pm but still no hope to complete it, it has just 7 steps, but the combination is really bad, browser is edge with a website related to digital post and rf current stat is very bad. I just struggling to complete it because i don't want to abandon, as i already got 2 times "you have requested this job too often.

**Comment by nerdatwork** [comment]
@uqbiii I feel your pain. The response time for the terminal is really very bad and we are all facing the delay. I hope it gets better.

**Comment by IceCreamCake** [comment]
I hope the system can let tester choose "Saved work or not" when Job Abandon, that's will give more fair to us.

**Comment by uqbiii** [comment]
Completed now, and after completing, got 1 HIT which shows "too ofter". Will there be any problem if we abandon too much jobs, i mean their system abandon jobs on testers behalf???
![untitled](https://cloud.githubusercontent.com/assets/16700973/17812585/2445aac0-6641-11e6-80ca-b3d0523f0b68.png)

**Comment by j1menezz** [comment]
I was doing a hit with 107, in the step 45 (after 34 mins) the hit show me the connection lost error and Job Abandoned? Its rlly annoying!!!!!..

**Comment by TheOneWhoKnock** [comment]
be happy because u can keep working with RF :( i done because shit CF

**Comment by IceCreamCake** [comment]
It make my feeling turn very bad. and guess what, the admin come to this topic and response the others?? i really don't know what to say.......

**Comment by uqbiii** [comment]
@TheOneWhoKnock I feel really sorry for what happened to you, and please don't be disappointed, they have lifted bans a few weeks ago from accounts which were suspended unfairly and they given a 2nd chance to all of them, i hope you will get your account soon.

**Comment by xakep99** [comment]
@ nerdatwork:

No need to feel someone else's pain and don't hope for things to get better. Instead, stop assigning new jobs that can't be finished and fix the things that should got better.

I had 39-stepper and after 40 minutes I was on step 27. In remaining 20 minutes only 6 screenshots could be taken - more than 3 minutes for a single screenshot.

Then, I got 107-stepper and got abandoned after 1 hour and 92 steps. Two hours of work and zero compensation for that.

**Comment by nerdatwork** [comment]
@IceCreamCake Saved work concept seems good but the current process is not designed to work like that. FYI **I am not the admin**

@uqbiii When did Rainforest lift bans and where did you read that ? Could you tell more about this ?

We are all facing the same situation like you @xakep99 showing empathy is **not** a bad thing. If you are giving up hope of things not getting better then that is a problem. Rainforest has improved the overall performance a lot compared to few months back. There is more work for everybody.

**Comment by uqbiii** [comment]
@nerdatwork You should read everything carefully, it will help you in the future and now check this thread again #395 . His account was not suspended by Rainforest, CF suspended his account.

**Comment by TheOneWhoKnock** [comment]
@uqbiii thanks mate :+1: i send a ticket with hopeless :(  my acc at RF is very good i got more 20 hits a day and 5-6 of them have more 35 step. biggest is 116 st. money and money.

**Comment by IceCreamCake** [comment]
@nerdatwork Glad to receive response. Sorry, i thought u r admin or staff of RF. And i just think maybe just have  "Saved work" when Job(with many step) Abandon to resolve current issue, not in normal job. But..... so  just waiting till it's fixed is the option.

**Comment by uangonline** [comment]
@All Don't loose hope... I'm sure sooner or later The RF team will fix all the errors. Just be patient.

**Comment by xakep99** [comment]
I hope I will be compensated for two hour work but it's definitely not gonna happen. Hope is that much useful in these matters.

**Comment by uangonline** [comment]
@xakep99 Try to send support ticket with your word and job ID, and screenshot of your work if it available. Hope you get a best of luck.

**Comment by xakep99** [comment]
Hope, empathy and luck are philosophical categories and they just don't have anything to do with 0's and 1's which is what we talk here. If I count on luck I would buy a lottery ticket (**hope** to win and expect **empathy** if I don't).

**Comment by tulko** [comment]
these days I've had problems like everyone else. Although not sending tikets because I do not get answers. Directly I hope to solve the problem. Pokemon Go this weekend :dash:

**Comment by huynhxuanvinh** [comment]
Hello, I have a question but don't want to open a new topic because I think I can find answer here. If we abandon too many hits, how can it affect our account? I mean, our account can be suspended or some thing else if we abandon too many jobs? I turn my computer on all time and go for lunch for a while because  very few hits appear at this time, but when I come back, bump, "job abandoned". Really hurt due to missing one available hit but I'm scare this can lead my account to bad situation, really want to ask you for safe.

**Comment by nerdatwork** [comment]
@huynhxuanvinh Job abandoned will not affect your account. You are safe.

**Comment by huynhxuanvinh** [comment]
@nerdatwork let real blocking policy again:
Examples of bad behavior that will result in a block:

Clicking "Yes" when the answer is clearly "No," or when you run into errors or are unable to complete the test.
Clicking "Yes" for every step without performing the steps,
**Accepting a job with a working terminal and failing to start in a timely manner.**
I wonder if "accepting a job" is when we click on "I understand" button, the third rule is really confused to me. :(
