### ISSUE TITLE
Job with "Choose No but TOTAL FOUND BUGS not increase"

### ISSUE THREAD

**Issue by IceCreamCake** [rainforestapp/tester-chrome-extension#404]
This job always have this question when close to last tep:
 "Have history activities update ......... with time at today (08/22/2016)?"
But the time show up always is yesterday. Like 08/21/2016 with today. Or if the job is yesterday (08/21/16), time show up in the page is 08/20/2016.
I report as bug already 3 time for that kind of job but the Found Bugs not increase, so should i keep reporting it, or simply choose Yes and move to next step.

**Comment by uqbiii** [comment]
I also reported several jobs for the same reason at the same step, but don't know why they are not fixing these things, and you can say they are just wasting their money on tests as they are not willing to fix these problem. I also reported this error in T**Con***t job.

**Comment by IceCreamCake** [comment]
Exactly, also i worries about is it have some kind of affected to my account, i'm not sure i should keep reporting it or not... so confusing@@

**Comment by uqbiii** [comment]
Keep reporting, otherwise they can reject you on the basis of screenshots, but if you reported, then they can't reject your work at all.

**Comment by IceCreamCake** [comment]
Got it, thank you my fr :)
