### ISSUE TITLE
Too Long Jobs

### ISSUE THREAD

**Issue by uqbiii** [rainforestapp/tester-chrome-extension#407]
@pscohn  RainforestQA should create some limits for steps in a single HIT. In 60 minutes how can one complete 135 stepper HIT and have to click 2-3 times in some stps to pass the step and move forward. If RainforestQA devs can? I would love to watch that video but please don't increase Time Limit for yourself.
![88fb8b37079e42eaba4b243aa384b618](https://cloud.githubusercontent.com/assets/16700973/17868884/3528a424-68ca-11e6-9943-9846ee104583.png)

**Comment by nihlathar** [comment]
It never happened to me that I arrived even at a half of a long task so I don't think it's a real problem. You ought to find errors sooner, most of the time

**Comment by huynhxuanvinh** [comment]
It happen to me too. I think they should increase to 90 minutes for each job or limit number of steps of each test. What if I do on step 80th at minute 59 and can't find any bug? I will lost all my effort in 60 mins if I don't report. Hope the team will take a look at this problem.

**Comment by uqbiii** [comment]
They should remove the 3rd policy from Idle policy and trun it to this.
As you click Yes or No to proceed, 45/60/120seconds are added on your side for that step.
Even 45 seconds are enough if they add them. With that policy we get a total of 75minues for a 100 stepper and 15 minutes for their policy no. 2. 60 is best, you get 100 minutes+15minutes. And time increases according to the situation. Or else, they should stop website owners from creating bigger HITs.

**Comment by qpPykT** [comment]
@uqbiii 
"gold diggers" will be happy to click it. About 60 min limit. Now it's should be 90 min but I'm not sure about it. Answer on that was in the [last AMA](https://paper.dropbox.com/doc/July-2016-AMA-Shared-with-Testers-CEDDg1Zp99tRLn2aE3bf3). 
Recently I had one of bigger hits. I spent about 1 hour on it and had done 67 steps out of 110. Next was connection lost error not the job abandoned. In future if I will be have one of big hits (more than about 60-70 steps) I just will not do it thats all.

**Comment by uqbiii** [comment]
But #403 is the proof that time limit is still 60 minutes and Wiki also shows 60 minutes as time limit. When something bad happened shows to gold digger at 99, they may broke their machines too. It seems like they are not testing their websites they are testing our mental capabilities, believe me after completing even a 60 stepper, you need at least 10 minutes to get back to the normal condition.

**Comment by qpPykT** [comment]
@uqbiii 
In Wiki maybe just forgot update it if they changed limit. 
About 403 issue he's told 35 min not 60 or 90min it can be just a some bug. I was spent about 60-65 min when I was doing big task.

**Comment by marius11** [comment]
I received the same job and it's impossible to solve it in 60 minutes. I had to report it at step 79 and politely asked them to reconsider the number of steps in their tests.

**Comment by uqbiii** [comment]
@marius11 Now they updated the idle policy and time changed to 90 minutes, i hope it will help us in completing long jobs.
