### ISSUE TITLE
Change to Crowdflower from MTurk

### ISSUE THREAD

**Issue by farookabubakker** [rainforestapp/tester-chrome-extension#408]
Hi,
First I did the Rainforest job with Clixsense through Crowdflower. Later I didn't use CF but my account still active. I use Mturk over 3 months. One day I hit rainforest job. since I did that job My contributor ID change to Mturk. I couldn't do job with Crowdflower. Is there any option to change from Mturk to Crowdflower?

**Comment by helloworld111gh** [comment]
Try changing your MTurk account email to a different one (that you
control), then login with your Crowdflower account details.
Note that you should stick to just one channel, and not switch between
channels. MTurk should pay the best, you should stay there.

**Comment by farookabubakker** [comment]
Thank you. I'll do it. I can stay Mturk. But the problem is I'm from India and I cannot disburse my funds to my Bank Account. I ask them. But bullshit reply. I have only one option to transfer funds to amazon gift card. If I purchase from amazon.com, shipping is too difficult. The shipping charge, customs clearance. For example, If I purchase mobile of 65 USD, shipping and customs is about 45USD. No use to buy with amazon.com. I can buy only on Amazon.in. But I can't use Amazon.com gift balance there. This is the reason to change my Account. CF do the best with clixsense. They have the option to redeem with Paypal account. This one is more convenient for me. Otherwise I won't change MTurk.

**Comment by sweeneyapps** [comment]
How do I receive payment in Indian Rupees?
If you are a Worker in India, you may get an option to transfer your earnings to your local bank account. You will need to provide your birth date and a scanned copy of your Permanent Account Number (PAN) card to be eligible to transfer to your bank account. Once submitted, it may take up to 7 days to verify your card information. After we've verified your PAN card information, you'll be able to provide your bank account information for verification. This will enable you to transfer your earnings to your bank account. You will receive instructions on the Earnings page when this transfer option is available to you.

**Comment by farookabubakker** [comment]
Dear sweeneyapps, 
Thanks for your comment. I have birth proof and PAN data. But I don't know how to send them. I ask amazon.com regarding this. They reply as this option is under processing.

**Comment by sweeneyapps** [comment]
i was looking around for answers..   All answers pointed to earning page or account setting page.   I would suggest you to look around your Account Setting to find out how to enable your bank account on your account..  Because there should be instruction somewhere on how to send your scanned PAN data etc..    I hope you work it out.
