### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by Ashok-Reddi** [rainforestapp/tester-chrome-extension#409]
I am getting the Application Error now a days very frequently 3 out of 10 jobs I am getting this error. Does anyone facing this issue? What could be the reason for this? 
I am also facing the other issue like "Another worker accepted...", "No virtual machines are available at this time...."
I am using 10MBPS net connection. Do I need to increase my internet speed? Does this solve the issue or these all issues are from RF side only?

**Comment by marius11** [comment]
You will get that message quite often when there are many testers online at the same time. A better (faster) Internet connection will not solve your issue. I have a 1000Mbps plan, but I still get application errors from time to time.

**Comment by uqbiii** [comment]
I have a wireless connection, its speed varies from time to time, currently it's around 2.5Mbps, maximum i have seen is 6 Mbps, so speed doesn't matter. When you get this message, don't refresh too quickly, wait for 20-30 seconds, then refresh, You are not alone in getting this error, everyone is facing the same issues.

**Comment by Ashok-Reddi** [comment]
Thank you all for the clarification.
