### ISSUE TITLE
blank payment!

### ISSUE THREAD

**Issue by ladystoneheart** [rainforestapp/tester-chrome-extension#410]
i don't understand what's happening here but all my jobs done was with blank payment...
![untitled](https://cloud.githubusercontent.com/assets/20522240/17900905/dfc621be-6969-11e6-9aa6-ad8ee867fdf2.png)

**Comment by kutch1** [comment]
I think these are the training jobs if you are a new tester . If you are an old one try contacting the support .

**Comment by nerdatwork** [comment]
Did you successfully submit the jobs till the last step ?

**Comment by ladystoneheart** [comment]
@nerdatwork yeah i finished and  did submit all of it, and the worst part it added to my rejections.

**Comment by ladystoneheart** [comment]
@kutch1 i did write to support and  im still waiting

**Comment by nerdatwork** [comment]
All of them were rejected ? Could you show the "public Profile" data from your profile ?

**Comment by madeuser** [comment]
I have the same issue, it seems that we received training missions and I don't know why because in my case I'm a 2 year old member. Thanks!
<img width="598" alt="rain" src="https://cloud.githubusercontent.com/assets/21203252/17902978/55cb2320-6972-11e6-9816-416e51130998.png">

**Comment by ladystoneheart** [comment]
@madeuser yeah right this was the jobs, but i thought it will be ok to done this jobs.

**Comment by ladystoneheart** [comment]
@nerdatwork this was 5 this morning and after i do that jobs becomes 11
![untitled1](https://cloud.githubusercontent.com/assets/20522240/17903241/6b394452-6973-11e6-8aa7-afcc6c9f6066.png)

**Comment by nerdatwork** [comment]
Ok when did you submit your ticket and what is the ticket number ?

**Comment by helloworld111gh** [comment]
In order to get paid, you must do the jobs according to the rules.
Rainforest reserves the right to not pay jobs that are not done according
to the rules and instructions.

**Comment by nerdatwork** [comment]
@helloworld111gh Even rejected jobs are paid but she isn't getting paid.

**Comment by ladystoneheart** [comment]
@nerdatwork ticket #15010

**Comment by helloworld111gh** [comment]
@nerdatwork the job type they are trying to complete does not pay money if
the job is rejected

**Comment by nerdatwork** [comment]
@helloworld111gh I see it now, it's training job.

@ladystoneheart When was this ticket submitted ? Also "training jobs" as you see in the screenshot do not pay.

**Comment by ladystoneheart** [comment]
@nerdatwork thanks, so next time when i see training jobs i shouldn't make it? i am not a new tester. just today after i saw that payment is blank.

**Comment by nerdatwork** [comment]
@ladystoneheart You wont get real jobs unless you complete training jobs but do them carefully.

**Comment by ladystoneheart** [comment]
@nerdatwork ok thanks! :)

**Comment by madeuser** [comment]
@nerdatwork sorry for busting in but how many training jobs do we have to do? I completed 24 already and I still receive them and the jobs keep on repeating. They are the same training jobs...

**Comment by helloworld111gh** [comment]
@madeuser rainforest automatically determines the number of training jobs
you do based on your performance.
testers who are found to follow the rules and instructions will very
quickly leave training

**Comment by qpPykT** [comment]
@madeuser 
Training consists of a number of jobs which you have to answer correctly to continue.

**Comment by madeuser** [comment]
@helloworld111gh I know that and I followed the rules and answered all of my 26 training jobs correctly, I did not receive any rejections. I remember that I had to complete 4 training jobs when I started working with rainforest two years ago. Another questions, why did we receive training jobs if we did our jobs correctly? Today I completed over 20 payed jobs, correctly!

**Comment by nerdatwork** [comment]
All jobs that have the title "Training jobs" do not pay and you need to pass them to get real jobs. All other jobs will pay.

**Comment by helloworld111gh** [comment]
@madeuser there were was less training tasks 2 years ago as the rules were
more soft at that time
answering the questions correctly is not the only factor rainforest uses in
determining if you followed the instructions

**Comment by madeuser** [comment]
@nerdatwork As I said in my last message, until 16:28 pm all of my jobs were normal, I was payed and suddenly I received a lot of training jobs without no reason. Maybe someone is testing something and forgot to tell us? It does not bother me to work on 100 training jobs if I have to, but I would really appreciate if someone would tell me if there is a problem with the servedr and the server just sends me and other testers training jobs because it is a bug... or not! :)
<img width="743" alt="jobs" src="https://cloud.githubusercontent.com/assets/21203252/17904745/3bb50a08-6979-11e6-81ca-416de388a656.png">

**Comment by ladystoneheart** [comment]
@madeuser we are the same just this morning i received payable jobs and now i got many training jobs.

**Comment by madeuser** [comment]
I just received a normal job, it seems that the issues is fixed! Happy testing! :)

**Comment by kristen-allie** [comment]
Hey all! And @ladystoneheart -- looks like these are training jobs, which you don't get paid for. Older workers receive training jobs when their work indicates they need to be retrained.

**Comment by alncssk** [comment]
they started to leave again......

**Comment by luisdanielvc** [comment]
@kristen-allie I've seen people with more than 3000 jobs getting this, they don't have rejections so that couldn't be possible

**Comment by rnfrst** [comment]
There are also other kind of rejections that testers do not see.

**Comment by ladystoneheart** [comment]
@kristen-allie @rnfrst  but how come i still receiving training jobs even i got this message that i have completed the training jobs.

Your training is complete! Hi ladystoneheart, Great news: your training is complete! You will now be able to do regular work for us! Happy testing! Rainforest QA Team p.s. view your profile here: https://portal.rainforestqa.com/.... Get our Chrome plugin here: https://chrome.google.com/webstore/detail/immdjpjbcikbffjifkbncgfbohbjicpo ref: 6793

**Comment by ladystoneheart** [comment]
@madeuser hey did you really reciev

**Comment by nerdatwork** [comment]
@ladystoneheart You got 11 rejections so far, you are only 9 rejections away from getting blocked hence you are receiving training jobs, in my opinion.

**Comment by ladystoneheart** [comment]
@nerdatwork yeah i know. but i saw my rejections. can you review them? there are rejections i think that i have done correctly but they are rejected.
![a](https://cloud.githubusercontent.com/assets/20522240/17919565/3489edbc-69d7-11e6-965f-3436ef9552c2.png)
![b](https://cloud.githubusercontent.com/assets/20522240/17919564/34894cea-69d7-11e6-9261-fc2e5c7c833b.png)
![c](https://cloud.githubusercontent.com/assets/20522240/17919566/348ccab4-69d7-11e6-89af-9000f5d7967e.png)

**Comment by madeuser** [comment]
@ladystoneheart here is a screenshot with the normal jobs (payed) after the training day ended for me. 
<img width="841" alt="trainingday" src="https://cloud.githubusercontent.com/assets/21203252/17921434/73ffac2e-69e2-11e6-8321-304beb1cad42.png">

I received only one rejection and it's ok because I was not paying attention, I was rushing because I was frustrated for receiving all of those training jobs without knowing the reason why I was getting them. In the future I'll keep my eyes peeled and I'll try to be more patient when I'll receive training jobs.
Here is a print screen with a new normal job that I just received.
<img width="842" alt="newtask" src="https://cloud.githubusercontent.com/assets/21203252/17921791/6ebdae4e-69e4-11e6-984e-c5a1b6b8b677.png">

Good luck! :)

**Comment by ladystoneheart** [comment]
@madeuser yeah thanks i got my also :)

**Comment by madeuser** [comment]
@ladystoneheart well done! glad to hear that! :)

**Comment by nerdatwork** [comment]
Check this:[Why Training jobs ?](https://portal.rainforestqa.com/)

**Comment by sweeneyapps** [comment]
I asked on other issues..    any of you get paid for the training jobs?    let me know.
