### ISSUE TITLE
Why Training job?

### ISSUE THREAD

**Issue by slrojasc** [rainforestapp/tester-chrome-extension#412]
Anyone can guide me about it, I just activated training jobs, I've done 10, not all are paying, is a system error? or have to go through a new phase of training, I have more than a year doing the test a web and are now more 6700

**Comment by luisdanielvc** [comment]
I have some friends that cannot work either, they get training and they're getting a lot of rejections, the system is crazy

**Comment by qpPykT** [comment]
@slrojasc 
Why you cannot read two previous issue and created another one :-/

**Comment by nerdatwork** [comment]
@slrojasc Can you take a screenshot of your profile ?

**Comment by Ssamfisher** [comment]
Same problem since yesterday 
![perfil](https://cloud.githubusercontent.com/assets/21204433/17922468/6fb9cd32-69df-11e6-9be9-fa8a8e61ad17.PNG)

**Comment by nerdatwork** [comment]
Check this:[Why Training jobs ?](https://portal.rainforestqa.com/)

**Comment by slrojasc** [comment]
![perfil](https://cloud.githubusercontent.com/assets/21203991/17932273/3545252c-69dd-11e6-864d-c9c70bfac3e0.jpg)

**Comment by slrojasc** [comment]
Since last night comes into training again, the same thing this morning

**Comment by nerdatwork** [comment]
@slrojasc Did you read the link I posted above ?

**Comment by slrojasc** [comment]
After 15 training, including one last night, and I get normal jobs ... I have understood that it is a kind of evaluation for those with low performance, but I have more than 16 months making "test a web" (one just over 6700) and rejections fail to 1.05%), then I do not think it's for "low performance"

**Comment by irishclouds** [comment]
For me after more of 40 training jobs nothing changed, 3 notice on the RF desk that i can make normal jobs and training is ended but nothing changed really. Also 2 rejections for unfair question after 1 year substantially without rejections.

**Comment by qpPykT** [comment]
@slrojasc 
How many "total found bugs" do you have?

**Comment by marius11** [comment]
> Hi <insert your name here>. We have various ways of evaluating your performance. Since yesterday we’ve increased our quality threshold, which means that being given paid jobs is more difficult than previously. If we see your performance isn't meeting our expectations, you will only be given training jobs until we're sure your work can be trusted (this may take a long time, depending on your history!) Even when we trust your work again, we will continue monitoring your submissions and might put you back in the training sandbox if we detect poor performance. A very small percentage of our testers fall into this category, so as long as you keep up the good work, you have nothing to worry about!
