### ISSUE TITLE
you have reached for more  1hour

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#413]
ID 34044189    
![image](https://cloud.githubusercontent.com/assets/19192312/17932798/ae3150bc-69df-11e6-97d0-12b3058bf81d.png)

**Comment by uqbiii** [comment]
Try clearing Cache, Cookies and History, restart Chrome and start the extension, don't open previous links realted to HITs, this always works for me and i get new jobs in 5-10 minutes if available, and always try to complete your HITs.
