### ISSUE TITLE
 Since yesterday only appear training works .

### ISSUE THREAD

**Issue by renangloor** [rainforestapp/tester-chrome-extension#414]
Since yesterday , so I get a lot of TraInIng jobs that do not pay anything when they fix this bug , I go to regular work ..
To help still had 2 unfair rejections doing these workouts, did more than 20 .

**Comment by madeuser** [comment]
Read this... https://portal.rainforestqa.com/

**Comment by renangloor** [comment]
Another 30 training ?, all but 2 are still frowned upon and is training , since I proved I can do the work , that this grossly unfair .

**Comment by madeuser** [comment]
@renangloor try not to get any training jobs rejected. This is the only advice that I can give you. I was in the same situation, received training jobs without no reason (I believe, maybe I did something wrong). Rainforest introduced a new QC system yesterday and some users have to do training jobs. Don't worry, be careful at the task and questions and you will succeed! Good luck! :)

**Comment by GersonTavare** [comment]
I did 74 training jobs and It appeared until now. This message that they would like to see our performance don't make sense. This trainings have a lot of unfair corrections, and my last 40+ I don't get any rejection and still continue receiving it. Almost 24 hours without receive anything but training hits and not being paid for it.

The support doesn't answer the tickets. I hope someone can tell us what to do...

Cheers

**Comment by renangloor** [comment]
exactly

**Comment by GersonTavare** [comment]
@madeuser how much trainings you do before come back to normal hits?

**Comment by renangloor** [comment]
Here he did not return, and I have no idea when vae back .

**Comment by madeuser** [comment]
@GersonTavare about 40 hits.

**Comment by renangloor** [comment]
He returned at last.

**Comment by GersonTavare** [comment]
@renangloor What did you do?

**Comment by renangloor** [comment]
@GersonTavare  kept doing the training , the whole was about 45 , there 's nothing began to appear normal work ..

**Comment by eudy66** [comment]
hello good day, I took more than 50 tests and nothing to leave me normal yet, aside that last that have turned out I miss as it should and me is placing as bad made with which I am losing several.
