### ISSUE TITLE
The signature in the URL is invalid.

### ISSUE THREAD

**Issue by ellmirr0001** [rainforestapp/tester-chrome-extension#416]
Does this mean that we can only get job through chrome extension and no other way because i am getting few jobs with extension from 5 to 10 in one day.

**Comment by javicocuba** [comment]
the same problem

**Comment by rnfrst** [comment]
Shouldn't it be like that, via the chrome extension?

**Comment by zfonck123** [comment]
same problem

**Comment by pscohn** [comment]
You can only get jobs through the Chrome extension currently.
