### ISSUE TITLE
Getting only Error message on the hits from extension

### ISSUE THREAD

**Issue by Unsubmitted** [rainforestapp/tester-chrome-extension#42]
Hi RF Team,

From the last 1 hour i am only getting 

ERROR: Something went wrong on our server, sorry about this. Please reload and try again.

or 

Application error message on the hits which are opened from the extension.

Please look into the issue.

Thanks

**Comment by qpPykT** [comment]
I have the same problem.

**Comment by BV25** [comment]
Same here

**Comment by Genesis2015** [comment]
Same annoying problem here :(

**Comment by pscohn** [comment]
This may have been a transient problem, is anyone still getting this for every job?

**Comment by Unsubmitted** [comment]
@pscohn its fine now , we are not encountering the problem.
