### ISSUE TITLE
when will trainer test end 

### ISSUE THREAD

**Issue by awnosa** [rainforestapp/tester-chrome-extension#420]
when will trainer test end

**Comment by nerdatwork** [comment]
When you are trained properly to get real jobs.

**Comment by zfonck123** [comment]
@nerdatwork @pscohn  Your training is complete! Hi zfonck, Great news: your training is complete! You will now be able to do regular work for us! Happy testing! Rainforest QA Team p.s. view your profile here.. i get this message in the night.... now in the morning get again training jobs...

**Comment by zfonck123** [comment]
![again](https://cloud.githubusercontent.com/assets/19192312/17970778/f3ddaa36-6aa5-11e6-86c7-d06b2e997728.jpg)

**Comment by zfonck123** [comment]
![image](https://cloud.githubusercontent.com/assets/19192312/17971567/574b5642-6aa9-11e6-9d7f-65eebfd491a2.png)
  again ?

**Comment by nerdatwork** [comment]
can you take screenshot of your profile ?

**Comment by zfonck123** [comment]
![image](https://cloud.githubusercontent.com/assets/19192312/17971676/d2f87630-6aa9-11e6-8808-8f03c2394ca3.png)
![image](https://cloud.githubusercontent.com/assets/19192312/17971685/e08f14de-6aa9-11e6-9fbb-be17636229ff.png)
![image](https://cloud.githubusercontent.com/assets/19192312/17971694/e7ecc2e4-6aa9-11e6-9ca0-950dbd6d3670.png)

and again training

![image](https://cloud.githubusercontent.com/assets/19192312/17971710/f539fa5c-6aa9-11e6-9513-236420979b3e.png)

**Comment by zfonck123** [comment]
I think is a bug, Again training, affter training complete 
![image](https://cloud.githubusercontent.com/assets/19192312/17972088/8f1e9d98-6aab-11e6-95e9-caab07625f11.png)

![image](https://cloud.githubusercontent.com/assets/19192312/17972098/9b564b06-6aab-11e6-9556-30916281d12a.png)

**Comment by mimimar** [comment]
Same thing with me. But I have a three notification that I passed the training.
![index notifications 1](https://cloud.githubusercontent.com/assets/21242801/17972831/787df9c8-6ae0-11e6-90d6-36c0552bf9e4.png)
![index notifications 2](https://cloud.githubusercontent.com/assets/21242801/17972837/80284afc-6ae0-11e6-9c4c-46ba21b61d42.png)
![index notifications 3](https://cloud.githubusercontent.com/assets/21242801/17972847/88e243e6-6ae0-11e6-91b1-9ca819e62278.png)

**Comment by zfonck123** [comment]
me too i have 3 and maybe in 5-10 min get the four... :(

**Comment by zfonck123** [comment]
4 with it
![image](https://cloud.githubusercontent.com/assets/19192312/17973300/ea85b6ea-6aaf-11e6-93b1-1846cb6f7aef.png)

**Comment by maciejgryka** [comment]
Hi all, the message you receive after training is out-of-date (we're changing it right now), but the behavior is not a bug. Depending on your history, you might need to complete unpaid training several times before your work meets our new quality standards and you can do real work again.

**Comment by mimimar** [comment]
Finally passed, no more training, I received "another worker..." and hit with real job. I hope that you too soon :)

**Comment by zfonck123** [comment]
@maciejgryka  ok. but is very strange, because complete the training 4-5 times  and each with 7 training lesson.  . i will go to finish training and try get a real job.   Thanks for ur answer.

**Comment by awnosa** [comment]
@mimimar can you tell me how many msg say "your training is complete! You will now be able to do regular work for us! Happy testing!" before you received a real job

**Comment by zfonck123** [comment]
@mimimar  yesterday only 1  today 4

**Comment by awnosa** [comment]
that mean i will received real job after 5 times of this msg

**Comment by qpPykT** [comment]
They don't want learn need more training tasks :)

**Comment by irishclouds** [comment]
For me, after 2 days without any rejections and normal jobs, now i have training jobs...i think it's impossible to understand it :(

**Comment by qpPykT** [comment]
@irishclouds 
Rejections are not the main indicator for the training tasks.

**Comment by irishclouds** [comment]
Ok, but they are changing between real jobs and training jobs within 3 minutes...really i don't understand the new system.

**Comment by sweeneyapps** [comment]
same here..   got into Training SandBox for no reason.

**Comment by zfonck123** [comment]
training mode again ?
![image](https://cloud.githubusercontent.com/assets/19192312/18067272/10d1e2b2-6e0a-11e6-9eff-7a52c1dededf.png)

**Comment by zfonck123** [comment]
2 rejection with this job, i dont understand what is my wrong in this :( 
![image](https://cloud.githubusercontent.com/assets/19192312/18067635/9fd8a292-6e0b-11e6-8f57-f18036806796.png)
![image](https://cloud.githubusercontent.com/assets/19192312/18067678/ca7b9504-6e0b-11e6-8a92-2da7e433ce39.png)

**Comment by zfonck123** [comment]
i am so very sad :(   anyone can explain me ? for dont get a wrong again please :( i dont wanna loss my account for this :(
![image](https://cloud.githubusercontent.com/assets/19192312/18067806/79ee2f9c-6e0c-11e6-977e-9bc6df7a5b8f.png)

**Comment by IceCreamCake** [comment]
Honestly, i @#%@ hate that dog.....
ps: i keep in & out trainning job too

**Comment by pscohn** [comment]
@zfonck123 you need to check carefully for images to check that no 2 are the same in that training.

**Comment by pscohn** [comment]
We periodically will retrain or give random trainings to all testers, not just ones who are performing badly.

**Comment by helloworld111gh** [comment]
@pscohn Seeing as you're here, can you define what a "scroll" is for this job, and how much is one? The instructions do not specify how big a scroll is, and we can't just reject the job because it's training

**Comment by dollydol** [comment]
@zfonck123 maybe I am wrong (probably since I got a rejection too on this horrible dog) but in the first of your rejection, the dark background one, it could be it was not a grid? there are blank spots so maybe that or the pics don't load, there is something wrong in the pictures arrangements to me. But still VERY UNCLEAR instructions.
