### ISSUE TITLE
Changes: They help or hinder the testers?

### ISSUE THREAD

**Issue by teteucalifornia2** [rainforestapp/tester-chrome-extension#421]
Good morning everyone!
In recent days we are getting many trannings, and that consumes at least 40% of testadores.Além time that he is presenting the training unfair rejections.
These latest changes are good for the tester?
Lately, it is also happening many mistakes "Something bad happened '', among other mistakes that hurt us a lot.
When released for new testers, our quality has dropped a lot. I ask you to be understanding with our work.
You could make a simple and good change for us. Place an audio alert when there came a new extension work. And do not let the extension be '' off '' alone, without anyone having clicked on it.
Let's change for the better Rainforest? What do you think?

**Comment by marius11** [comment]
Rainforest recently announced that they increased the quality treshold for testers, so these training hits are necessary if you do not meet the quality treshold Rainforest wants.
Also, the extension should go OFF if the user behind it is inactive, or AFK. It wouldn't be fair for active workers to have jobs taken by someone who is AFK.

**Comment by teteucalifornia2** [comment]
@marius11 Yes, I agree that training is needed. But they are coming in large quantities and often unfair rejections. And what about the mistakes that often comes up?

**Comment by qpPykT** [comment]
@teteucalifornia2 
If you think that these rejections are not fair it does not mean it's true. Learn all rules and do tasks more carefully. Errors always was there and before the last update.

**Comment by ellmirr0001** [comment]
how many jobs do u get via chrome ext, im getting really low like 5 to 10 in one day and that's not even 5$

**Comment by teteucalifornia2** [comment]
@qpPykT 
It is unfair not only to me but to many people . So if the errors were already before the update , we can not improve ? Beautiful thought friend!!

**Comment by sweeneyapps** [comment]
@ellmirr0001  by the way, the extension have little bug,  it stopped checking for job after an network error.   I am trying to pinpoint the error but I didn't have the log enabled for that.

**Comment by ellmirr0001** [comment]
@sweeneyapps tnx for the info, hope it'll be fixed soon.

**Comment by qpPykT** [comment]
@teteucalifornia2 
Ok, if you think you are right you can submit a support ticket.

**Comment by teteucalifornia2** [comment]
@qpPykT ok

**Comment by GersonTavare** [comment]
These trainings are ridiculous. I do more than 100 (one hundred) in the past 3 days, and still receiving. And unfortunately there is no support to help when you send email, only serves to give copied answers...

**Comment by MarinaCec** [comment]
After the new testers came, earnings fell lot, $3(day) not buy a mcdonalds sandwich, lamentable...

"Place an audio alert when there came a new extension work. And do not let the extension be '' off '' alone, without anyone having clicked on it.
Let's change for the better Rainforest? What do you think?"  I agree...

**Comment by MarinaCec** [comment]
Some people here accept mistakes, accept being harmed by the mere fact of being "Ass Kisser". It is fair to give our point and report to them that something is not this right or not good. No one is disregarding or disrespecting the rainforest, but simply giving advice of something that could improve to the testers, since every update get worse and never better.

**Comment by teteucalifornia2** [comment]
@MarinaCec Exactly. Together Rainforest can improve in all aspects .

**Comment by GersonTavare** [comment]
@MarinaCec it's ridiculous, rainforest gets worse every update. 

- They reduce our work - long tiime ago we can do 4 hits at the same time. 
- They change the layout just to upgrade the errors - now it's more than the old one. 
- Constantly we lost a day (or a few) because some internal problem - the new one is the training hits. 

Unfortunately don't seems like Rainforest values the work of each one here. It seems like they just want numbers without caring about quality.

It's not because we work for them that we have to accept everything, smiling as if nothing had going

Sad, very sad. 

Who works on RF for over a year knows how things were bad...

Some months ago, I see an article that says that Rainforest have plans to replace workers by robots. It seems like we already facing changes.

I hope to be wrong.

Cheers, friends.

**Comment by zfonck123** [comment]
affer google chrome extencion alot errors, bugs, 1 job for time... i remember in november and december 2015 easy do 100 jobs more in one day.   today only can do 20-40 jobs... but i remember to only 400 online,, now is 1800+

**Comment by MarinaCec** [comment]
Sometimes I get the feeling they want to humiliate us, like "It will be our way and end, your opinion doesn't count".

At the beginning I was feeling like part of the team, cause our job is important to rainforest too,  don't feel it anymore. Sad.

**Comment by marius11** [comment]
@GersonTavare @MarinaCec That's simply not true. I have noticed an increase of number of tests in the last 2-3 weeks and new websites appeared that I've never seen before. It quite clear that Rainforest has more and more customers using their product, hence why they increased the quality threshold by delivering training tasks to those who don't have good results.

If you have problems or issues, report them here, send a ticket or an email. Baseless ranting won't get you anywhere.

**Comment by kaytsu** [comment]
I like the extension turning off when I don't click it. It senses that my computer is idle and will turn off instead of giving me a task which ends up abandoned because I am AFK cooking dinner or watching my nephew outside.

**Comment by playpin** [comment]
Yes sometimes its useful as we do not end up abandoning task . otherwise it annoys me when i am reading something in same browser and it goes "off"

**Comment by zfonck123** [comment]
@kaytsu  if u are not old member, u dont  know nothing.    last year we can we 100 jobs or more daily.  but affter app "december" is at imposible get 100 jobs or more, for won the 20% bonus

**Comment by sweeneyapps** [comment]
@zfonck123 yeah... I did 98 jobs in 24 hrs.   I took the challenge..and failed miserably.  :(    So I am recommending 500 steps for 20% because not all jobs are equal.   You'll see my recommendation on the next upcoming AMA.

**Comment by sweeneyapps** [comment]
@ellmirr0001  I fixed the bug and waiting for RF to merge my code.  :)

**Comment by zfonck123** [comment]
@sweeneyapps excellent :D
