### ISSUE TITLE
"This email address is already in use" when restart a job

### ISSUE THREAD

**Issue by bilelmz** [rainforestapp/tester-chrome-extension#423]
This error happen if the job containing a "sign up step", and for some reason, i had to restart the job. when i do the same step again (sign up) the website says: "this email address is already in use" or something similar.
Please fix that.

**Comment by qpPykT** [comment]
@bilelmz 
In that situation you should to report it as "no" and add explanation.

**Comment by Electroglitch** [comment]
Unfortunately only thing you can do is to report it and write explanation
and hope terminal wouldn't misbehave when doing another similar test with sign up :)

**Comment by nerdatwork** [comment]
@bilelmz The only thing you can do is click NO and explain that you had an error and you had to restart the job and because of this you see "This email address is already in use" message on the page. You will not be penalized for that.

**Comment by bilelmz** [comment]
I get this again!
The data that is entered, it is supposed to be deleted when restart the job?!
