### ISSUE TITLE
 complete 8x ? why ? 

### ISSUE THREAD

**Issue by Jonashp** [rainforestapp/tester-chrome-extension#424]
![test](https://cloud.githubusercontent.com/assets/21248961/17984532/f91c4498-6ae7-11e6-9c7b-f95e85dc8565.PNG)

**Comment by Electroglitch** [comment]
Check this #420

**Comment by GersonTavare** [comment]
There's no way to know, my friend. Rainforest don't answer the emails, and the post on portal don't make sense. I complete more than you, I think about 12 times, and until now I'm receiving it. 

Hope they fix it soon.

**Comment by Jonashp** [comment]
More 4x complete,same problem .-.
