### ISSUE TITLE
All kinds of unfair rejections

### ISSUE THREAD

**Issue by jsslng** [rainforestapp/tester-chrome-extension#427]
Since this "training tests" stuff started, i'm getting a lot of unfair rejections and that is ruining my profile stats, i had like 3 rejections tops, and now i have 8 and the training jobs don't stop because of the rejections, it's an endless loop.

![captura de tela 2016-08-26 as 14 38 01](https://cloud.githubusercontent.com/assets/17452854/18014750/bfcb4cd0-6b9a-11e6-9e5e-b5a1200741b8.png)
![captura de tela 2016-08-26 as 14 37 45](https://cloud.githubusercontent.com/assets/17452854/18014751/c1d18d64-6b9a-11e6-9fd6-08387f8a5903.png)

**Comment by uangonline** [comment]
@jsslng From your own screensshot i can say the rejection was **FAIR**! You could just put the email or password wrong between step 1 or 3. That's why you got Incorrect email/password error message at step 3. Be more carefull next time.

**Comment by ladystoneheart** [comment]
look at this also.
![untitled](https://cloud.githubusercontent.com/assets/20522240/18026000/02ea9270-6c43-11e6-84f0-944e904fd4f1.png)

**Comment by farookabubakker** [comment]
First I did 7 training test 3 months ago. I qualified and did the jobs. Unfortunately contributor gave me training test again. Like you I had one rejection. Totally I did 8 training tests including that rejection. I don't know why I asked for training again. I mailed them but replied rejection could not be reviewed individually. So keep doing the training again and again until they mail your mailbox your test has been completed. All the best.

**Comment by Rafaelde** [comment]
Like I have two rejections in similar tasks, but can not see where is the error.

It would be helpful if clear where the bad.
![raiforest](https://cloud.githubusercontent.com/assets/21296796/18036614/9001f022-6d3d-11e6-9fe1-23dd7bb1ba08.png)

**Comment by uangonline** [comment]
Please read [https://github.com/rainforestapp/tester-chrome-extension/wiki/Guide-Rules:-Confusing-Scenarios](url)

**Comment by Rafaelde** [comment]
The link does not work

**Comment by HW71** [comment]
Hmm, this one should work:
https://github.com/rainforestapp/tester-chrome-extension/wiki/Guide-Rules:-Confusing-Scenarios
