### ISSUE TITLE
No hits or Oops  from extension 

### ISSUE THREAD

**Issue by Rainforestuser790** [rainforestapp/tester-chrome-extension#43]
Hi Rainforest Team,

i have noticed from last week there are very less hits from the extension even though it changes to Yes  it doesn't open any hits and today it is always in the No mode and not a single hit  even though its not weekend.  Normally during this time frame we usually get  hits but there is not a single hit opened or any Ooops from it.

Just wanted to check whether there are any issues going with the extension which is preventing it from opening hits or is it me having issues

Thanks

**Comment by AlexandruVerenca** [comment]
I get some hits from time to time, but it's significantly less work than usual and I still get more Oops than work.

**Comment by hunt40** [comment]
i seen it too its turn to yes but not open any window if its open its already all gone,first come first serve who have fast connection grab hits before then other people.

**Comment by Genesis2015** [comment]
Same here :(

**Comment by mukikuki** [comment]
i have fast connection, good latency and bandwidth  , latency 7-10 ms, but still , oops messages. when the extensions opens a hit it is loading for more than 40 seconds  and sometimes even more than 1 min and then the oops message. But some times it works like  a charm , fast loading and opens the hit but this is rare

**Comment by erdeminofff** [comment]
![last](https://cloud.githubusercontent.com/assets/8877357/12520723/e28f94ac-c14e-11e5-9ca4-2aff04537bd1.gif)

**Comment by helloworld111gh** [comment]
The rate limit is at 15 seconds while the extension is at 8 seconds. You
can change the rate of checking to 15 seconds and there won't be rate limit
errors.

**Comment by JPierreS** [comment]
@helloworld111gh 
Are you sure about this mate ?  8 seconds is the polling interval in the extension 1.0.1 (from 2 to 8).  Where did you get this 15 seconds rate limiting feature, this is not the case, or did you mean 15 per minute.  Rate limiting is measured in number of refreshes of minute.  If rate limiting is at 15, it means minimum 4sec refreshing allowed, if it,s at 30, it means minimum 2sec refreshing allowed etc.

**Comment by helloworld111gh** [comment]
I have tested it myself, I do not get rate errors at 15 sec (4 requests per
min). And I do at 10/12 sec.

I have no idea why RF set it to 8 seconds. Maybe they plan on setting it to
8 seconds soon.

**Comment by Rainforestuser790** [comment]
Hi @pscohn,

Can you please get my account verified once as i am not getting hits opened most of the time as the extension says only No or even if it changes to yes it doesn't open a hit. Previously it use to work fine and open hit when ever it changes to green but not now. From last 2 weeks onward the problem started.

Following is the id: 34408790

Thanks

**Comment by pscohn** [comment]
@Rainforestuser790 I don't see any problem with your account, and it appears you've done several hits recently through the extension.

**Comment by Rainforestuser790** [comment]
Thanks @pscohn for getting my account verified, i am not saying i am not getting hits at all but the ratio of hits slowed down drastically and the main issue was the extension changes to yes but doesn't open a hit like it use to open before , i just saw the time was changed from 2 seconds to 8 seconds for the extension to check for hits may be it has some issue.

Thanks

**Comment by Rainforestuser790** [comment]
@pscohn during the time when i see the extension changing to yes but not opening the hit in the extension console i could see the following messsage where it is fetching the assignment but not opening the tab.

RESP: Object {error: "Too many requests"}
main.js:155 RESP: Object {work_available: true, url: "https://tester.rainforestqa.com/tester/assignment/…d8ff14b2&turkSubmitTo=%2Fthanks&workerId=34408790"}url: "https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cxe03abf-4fac-45f5-8854-d614b263529f&browser=any&hitId=4601661&sig=3b329687d31dadef152b55d9cb072a288c106a900adce47c38039ac0d8ff14b2&turkSubmitTo=%2Fthanks&workerId=34408790"work_available: true__proto__: Object
main.js:105 No tab with id: 149.


but the tab never opened with the assignment which is shown. 

Thanks

**Comment by L4kshmi** [comment]
@pscohn Hi!
Any comments about of NEW TESTERS? I wanna work in RF

**Comment by pscohn** [comment]
@L4kshmi see https://github.com/rainforestapp/tester-chrome-extension/issues/24 - short answer is we're working on a new onboarding system, and should see a fix in the coming weeks.

**Comment by pscohn** [comment]
@Rainforestuser790 this may be a new bug - can you open a new issue for it if it continues to happen?

**Comment by Rainforestuser790** [comment]
Sure @pscohn , i could still the problem happening , i will open a new issue for this.
