### ISSUE TITLE
Unfair blocked ! 

### ISSUE THREAD

**Issue by samballode6** [rainforestapp/tester-chrome-extension#430]
Unfair blocked ! 

http://oi67.tinypic.com/zl3z94.jpg

http://oi63.tinypic.com/1xxvlg.jpg

http://oi68.tinypic.com/99m1w2.jpg

**Comment by samballode6** [comment]
Unfair blocked !
![blocked 02](https://cloud.githubusercontent.com/assets/19857030/18020229/94336cd6-6c0a-11e6-91e1-6d6b2e961d5a.png)
![blocked 021](https://cloud.githubusercontent.com/assets/19857030/18020236/9cd5f214-6c0a-11e6-95da-250bd3681ad1.png)
![blocked 022](https://cloud.githubusercontent.com/assets/19857030/18020243/a3853570-6c0a-11e6-9be7-b1937c714fc7.png)

**Comment by helloworld111gh** [comment]
You will not be unbanned, you have cheated Rainforest many times, as
explained in your block reason. People like you are the reason why the pay
for tasks are offers are so low, and why Task Authors are trigger happy on
rejecting legit users.

**Comment by thetodd1** [comment]
ayylmao sigitsenyo
proof here use google translate  
https://www.neobux.com/forum/?/22/574619/Test-Applications-For-Rainforest-Qa/1/&vl=EF1605696B1AE3A8D2F12EA092E8AF9B

if you dont wanna read the whole thread , see here
http://imgur.com/a/mK2B9
