### ISSUE TITLE
Poorly written instructions

### ISSUE THREAD

**Issue by xakep99** [rainforestapp/tester-chrome-extension#431]
..."you should NOT pass a test with poorly written instructions that you can't clearly follow"...

Who's gonna judge whether I understand instructions?

Are test authors gonna be introduced to 5 Principles of Testing at least and asked to follow them?

It's interesting to see use of rule of text in quotes with number. I could see all possible wrong variations but correct ones could be seen very seldom. Authors are weak link, not testers. 

Other priority should be fixing the application. 

Fixing these two problems will incredibly improve testing results and all parties involved will benefit from that.

If prompt actions on these two issues are not taken soon, rainforest can make delicious dinner out of golden goose they have now.

**Comment by kaytsu** [comment]
If the directions are unclear to you and you click NO they won't reject your work. You just need to add the note that the directions were unclear. You can simply say "On step X I didn't understand the directions. They were confusing and I couldn't follow them" 

I've had some where the question was worded like this "The user will see this and this and this?" They are still clear enough to follow the directions but I make sure to add a tester note about writing it as a question "Do you see this and this and this?"

**Comment by playpin** [comment]
I tried going through this "user will..." Test
But on last step instructions got too complicated due to "user..." Thing
So i reported but no bug+

**Comment by xakep99** [comment]
@kaytsu Somehow I don't share your opinion and that is the reason I have started this topic.  And guess what? It happened. Somebody took over divine duties and rejected my work because of poorly written instructions I couldn't understand.

User will does clicked on the blue button link green colored ...

Why these HITs are even assigned for working?!?

If task authors stick to the basis principles of testing which we see every time we are supposed to start working on task, it would cut volume of problems in half and for the benefit of everyone involved.
