### ISSUE TITLE
After choose NO, do i have to provide the report note again for survey.

### ISSUE THREAD

**Issue by IceCreamCake** [rainforestapp/tester-chrome-extension#432]
Some bug is very simple, only thing i can provide for the survey note is the same when i report bug. So i wondering what should i do, rewrite that note again or just submit the job.

**Comment by djux90** [comment]
yes, if some admin can say something about this, i am interested about it to, if i choose no and give the reason why is it no, why should i write that in again in survey?

**Comment by pscohn** [comment]
The survey at the end has nothing to do with the bug in the test - it's for evaluating the job overall as far as the terminal (VM), instructions, and job interface. You can leave any extra feedback you have about those things in the survey, but don't have to write anything about the bug or website you were just testing.
