### ISSUE TITLE
I have 121 total jobs completed pending by paid

### ISSUE THREAD

**Issue by jzanotto** [rainforestapp/tester-chrome-extension#433]
Hi Team,

I have 121 total jobs completed and I don´t have received payment of any.

Please, Can you help me???

I attach files with my profile and job history

![job history](https://cloud.githubusercontent.com/assets/20929891/18028146/a9e11684-6c44-11e6-964a-f2bc26f3b7a2.JPG)
![profile](https://cloud.githubusercontent.com/assets/20929891/18028147/aa11cb94-6c44-11e6-912d-e721a7b12bed.JPG)

**Comment by begsoon** [comment]
![image](https://cloud.githubusercontent.com/assets/16007586/18028211/c51bfd18-6c78-11e6-9518-21476a457110.png)

**Comment by qpPykT** [comment]
@jzanotto 
What is your payment channel neobux, clixsense and ect. Look at your worker ID maybe you claimed another ID on payment channel.

**Comment by Dolazim** [comment]
How you get 121 job in one day?

**Comment by zfonck123** [comment]
august "29 days" for the moment. him dont say 121 jobs in one day lol. and training maybe 30-50 xD i do 50 training for get real job again

**Comment by nerdatwork** [comment]
@jzanotto Have you sent a support ticket ? If yes can you give your support ticket number.

**Comment by uqbiii** [comment]
@nerdatwork why you are asking for ticket number, please explain in details, because there is no badge on your profile with "RainforestQA Member", what will you do to this number :smiley:.

**Comment by qpPykT** [comment]
@uqbiii 
I think he's one of the...

**Comment by jzanotto** [comment]
I am a new tester since August 1st and I want to konw when I'll be part of the team rainforest.
I have shown that I can do this job.

**Comment by qpPykT** [comment]
@jzanotto 
Registration for new testers was closed on 29 July. When the registration will be open again, nobody knows.
