### ISSUE TITLE
i cant Reset my password

### ISSUE THREAD

**Issue by asdoo** [rainforestapp/tester-chrome-extension#435]
i request to rest my password and there is no thing happen

**Comment by GreekGuy** [comment]
you should check cloudflower messages.

**Comment by prpiro** [comment]
I have a problem like this, I ask for password reset but the messages never arrive to my crowdflower account message board, i am unable to work because I cant run the app if I am not logged...

**Comment by nerdatwork** [comment]
Whenever you reset your Rainforest password the email is sent to your email provider like gmail or yahoo or hotmail. Make sure to check your spam folders too.

**Comment by prpiro** [comment]
Thanks for your contribution, neither they have arrived to gmail

The situation is that I have two Contributor IDs (one in use and the other abandoned but active) and I mistakenly changed the first Id's profile email into the second's one, (now both account are linked to the same email) after this I wasn't able to login and an error showed: "Invalid email and/or password" . I tryed to reset the password but the message never arrived to my crowdflower account message board or to Gmail, it is more like if the email is not yet valid.

**Comment by helloworld111gh** [comment]
try logging in with your first accounts password (or second accounts
password, if you are currently using your first)
once you have logged in, you can change your email of that account back

**Comment by prpiro** [comment]
(thanks again for your support,) I'd tryed this already too....
