### ISSUE TITLE
Is there a limit af IPs that i can use?

### ISSUE THREAD

**Issue by mimsura** [rainforestapp/tester-chrome-extension#437]
I have 3 different PCs in 3 different locations with different IPs. Will it be a problem if I work NOT at the same time ofcourse but for example in 1 day from 2 IP enteries ?

**Comment by JPierreS** [comment]
So long as you are not sharing accounts or working through multiple Rainforest accounts you should be fine. You are allowed to work only from ONE Rainforest account.

However, you MAY have issues with CrowdFlower and/or the channel you work from as they might detect the 3 different IPs and location as suspicious and flag your account.  It would be safe to let the channel you are working from know about this as well as with CrowdFlower and keep your support interactions on record.  If you are working "offers"  (surveys, etc.) in a channel, the change of location will eventually get you flagged.

**Comment by mimsura** [comment]
thanks a lot for your answer it really helped me :)

**Comment by nerdatwork** [comment]
If you are satisfied with the response you got please close this thread.
