### ISSUE TITLE
Could not get a X machine error

### ISSUE THREAD

**Issue by sweeneyapps** [rainforestapp/tester-chrome-extension#438]
this error showing "Could not get a X machine" where X is name of machine such as Chrome, etc.  has been happening repeatedly this morning (PST) when accepting a job.    I closed those jobs because it's pointless to continue refreshing.   Then guess what I'm in training sandbox for no reason.  :-1:

**Comment by uangonline** [comment]
@sweeneyapps Why not refreshing every 2 or 3 minutes? It works for me.

**Comment by uangonline** [comment]
@sweeneyapps I'm also in training sandbox now :-1: .

**Comment by ellmirr0001** [comment]
same problem too :/

**Comment by sweeneyapps** [comment]
nobody deserve this. I have done like 14 training jobs after doing nothing wrong. No rejections even no rejections on training jobs task. So I decided to turn off my chrome extension for the day and hopefully by tomorrow, I am getting paid job. Again, nobody deserve this at all. Also in USA, we do pay our workers on their training day. So Rainforest needs to go back to the drawing board and figure out to do this the legal way. And compensation all of us. Thank you for ur time to hear me out.

**Comment by sweeneyapps** [comment]
random testing...   and this error is probably just nothing.
