### ISSUE TITLE
Unfair rejections ... AGAIN

### ISSUE THREAD

**Issue by josejecr97** [rainforestapp/tester-chrome-extension#439]
@maciejgryka 
@qpPykT
https://i.gyazo.com/1c680a3613b60d17e547934a527004e1.png
https://i.gyazo.com/fc27a74a6606a281405b0f6c7e094fb7.png

I'm AGAIN in training mode and get the same JOB x2 times ... i did everything and i still dont know what is wrong with this......., please do something  i did everything it says !

**Comment by irishclouds** [comment]
same for me, one day on job mode, the next in training mode, without rejections...i can't understand this system, no sense on it

**Comment by priggy** [comment]
i have same problem.... first they start testing me after i have done more than 1000 hits without one single rejection.... then they reject my testing hits... and they test me like 5 times in a row, all rejected!

**Comment by Yhenko** [comment]
Same training jobs, SAME REJECTION.
https://gyazo.com/04c18a1c9e5279d2cd2d35a3335f5643

Another UNFAIR REJECTION ¬¬, can solve this please? 3 unfair rejections last week, 1 today

**Comment by hackyyy** [comment]
I have the same problem, just reported the bug to the help desk, this is unfair.

**Comment by helloworld111gh** [comment]
@Yhenko no one can determine if you are right if you don't post the
screenshots they provide
same message to everyone else with unfair rejection, you need to post the
screenshots they provide to determine if you are right

**Comment by luiscl32** [comment]
training, 1 free unfair rejection  bug :/ , 
https://i.gyazo.com/4bd75ac1797b4881b93eafb2354fc224.png
https://i.gyazo.com/5c07186bc6b769b8ac7e50bac289f8a1.png

**Comment by crieli** [comment]
same problem, thousands of hits without rejections and now on training mode.

**Comment by josejecr97** [comment]
@helloworld111gh  we are posting screenshots ?¿?¿? i dont understant what do u mean

**Comment by AndyARB** [comment]
Same here!
Why? JOB IDS: 8332166, 8331963, 8331788.
Fix please!

**Comment by Yhenko** [comment]
@helloworld111gh Okey, lets see.
1- https://gyazo.com/04c18a1c9e5279d2cd2d35a3335f5643
2- https://gyazo.com/692da793f1f5ef48313ae979376db550
3- https://gyazo.com/943a24f572314c820dcea3b56f1e9857
4- https://gyazo.com/66bea39869c32c2c6d777816c5381013

**Comment by hackyyy** [comment]
I have two others like that: :)

![unfair 5](https://cloud.githubusercontent.com/assets/2355915/18067654/5fbfff6c-6e46-11e6-9b13-23ce14c4bb06.png)
![unfair 1](https://cloud.githubusercontent.com/assets/2355915/18067653/5fbecbe2-6e46-11e6-8d76-3fbb01aa20a1.png)
![unfair 2](https://cloud.githubusercontent.com/assets/2355915/18067652/5fbe95b4-6e46-11e6-9aed-076a724b6b75.png)
![unfair 3](https://cloud.githubusercontent.com/assets/2355915/18067655/5fd8c3c6-6e46-11e6-9c60-a3aa57123c30.png)
![unfair 4](https://cloud.githubusercontent.com/assets/2355915/18067656/5fdaae16-6e46-11e6-8174-2c27f02cbc36.png)

**Comment by Rodolfo2709** [comment]
Same for me, the same training of google twice and two unjust rejection...  Please fix it  T.T

**Comment by priggy** [comment]
apparently, when they ask to click on a "clipboard icon" make sure IT IS VALID clipboard icon, not just a random square or scissors (in second and third try they gave me those icons) then I reported the job saying there is no clipboard icon... result: NO REJECTION... however, next was again training test, but other with different tasks and steps... pay a little more attention and maybe you will pass.... learned it the hard way

**Comment by AndyARB** [comment]
So, we can report it because this job have unfair questions, and unfair rejections!

**Comment by priggy** [comment]
just click NO instead of YES, same as you are reporting the bug on regular testing page... BTW... last 10 minutes, no tests popping up

**Comment by ilegalna** [comment]
Same here. My ID is 29166275.

**Comment by helloworld111gh** [comment]
@hackyyy the rejection was correct in your case, remember to follow the
rules to the letter at all times.
please remember that not following the rules will result in training hell.
please remember that not following the rules will cause significant
reputation penalty, causing you to require potentially hundreds of training
job to resolve

**Comment by majulink** [comment]
same here 3 jobs = 3 rejections  (wrong rejections )

**Comment by AndyARB** [comment]
Maybe the job is removed. Now, how to remove the unfair rejections? ._. I can't report it because they send me an email that say: Hello,
Due to the amount of tickets we receive, we are not able to look into individual training job rejections. We're so sorry! We will be adding clearer feedback about training job rejections in the future.

**Comment by zfonck123** [comment]
2 rejection with this job, i dont understand what is my wrong . any can help me found what is my error please ?
![image](https://cloud.githubusercontent.com/assets/19192312/18067635/9fd8a292-6e0b-11e6-8f57-f18036806796.png)
![image](https://cloud.githubusercontent.com/assets/19192312/18067678/ca7b9504-6e0b-11e6-8a92-2da7e433ce39.png)

**Comment by josejecr97** [comment]
@AndyARB  anyway , help desk never solve our troubles.. i've send allot of tickets and they never answer

**Comment by ellmirr0001** [comment]
@zfonck123 i have same problem like u with this job

**Comment by AndyARB** [comment]
@josejecr97 You're right, we hope.

**Comment by regi92** [comment]
same here !!
https://i.imgsafe.org/4a838869f8.png
https://i.imgsafe.org/4a8346c927.png

**Comment by teteucalifornia2** [comment]
Here also is unfair rejections in excessive training. For God's sake , fix it. I can not work right due to these changes.

**Comment by stamos551** [comment]
yeap, same for me here..
6 rejections
They said they are gonna fix it tommorow sooo I guess they will

**Comment by AndyARB** [comment]
Calm down.

> We're getting a lot of tickets about training job rejections. It will take a while to go through them all, but we'll look at them tomorrow and post an update if we've found a bug in them. Thanks, everyone!

**Comment by hunt40** [comment]
i got 1 unfair rejection too after 4 training job,also for mail,yes they never check training job rejections thats same answer i got 4 months ago ,so dont hope for anything just pray there will be no more training jobs.

**Comment by laga407** [comment]
6 rejection on training job, for the google training answer no when ask for click Icon, now for the upload file don't no i miss..

**Comment by MarinaCec** [comment]
4 unfair rejections on training job

**Comment by mariaelite** [comment]
Rainforest has the cheapest labor in the world.
Based on that ....
Does it seem right, whatever is happening?

**Comment by mariaelite** [comment]
I have no new rechazon and I have no idea how many workouts take
