### ISSUE TITLE
 4 rejections in one short time in training Rainforest

### ISSUE THREAD

**Issue by Elizabesita10** [rainforestapp/tester-chrome-extension#441]
Hello is happening, these are very simple work and do it all well, just are 4 steps, and has repeated the same job 4 times and continuous, but it will not hold them, all give me rejections, it is going all right with rainforest? acomulo first time that so many rejections
![sin titulo](https://cloud.githubusercontent.com/assets/20981036/18068378/45887ce8-6dfe-11e6-8bf7-77a555423c26.png)

**Comment by ellmirr0001** [comment]
#439 #440

**Comment by khristianjose** [comment]
I got the same right now, two rainforest trainning jobs, i did those very well and it counts to me as rejected, what? Anyone knows why?

**Comment by JrRandy** [comment]
If people gave you the correct answer on a training job, it would defeat the purpose of the training jobs.  I have completed the above training job and passed it.  So it is not "broken".  Pay attention, and read carefully.

**Comment by Elizabesita10** [comment]
sorry, and I realized my mistake, I did not give cicboard click the icon that is the scissors, sorry, I must pay more attention

**Comment by JrRandy** [comment]
You should edit that to not provide hints or answers to other members.  I am glad you found your error.  As I said, have to read carefully :)
