### ISSUE TITLE
BAD REJECTIONS

### ISSUE THREAD

**Issue by khristianjose** [rainforestapp/tester-chrome-extension#443]
Hi, i got 2 BAD REJECTIONS right now on trainning jobs, anyone knows whats happening?  
![sin titulo](https://cloud.githubusercontent.com/assets/17553414/18068680/a36f383a-6e10-11e6-973a-5e47ab5f2dfa.png)
![sin titulo3](https://cloud.githubusercontent.com/assets/17553414/18068681/a37a2f10-6e10-11e6-93f5-89b37bab4011.png)

**Comment by josejecr97** [comment]
#439

**Comment by MarinaCec** [comment]
4 unfair rejections for me...

**Comment by sweeneyapps** [comment]
nobody deserve this. I have done like 14 training jobs after doing nothing wrong. No rejections even no rejections on training jobs task. So I decided to turn off my chrome extension for the day and hopefully by tomorrow, I am getting paid job. Again, nobody deserve this at all. Also in USA, we do pay our workers on their training day. So Rainforest needs to go back to the drawing board and figure out to do this the legal way. And compensation all of us. Thank you for ur time to hear me out.

**Comment by teteucalifornia2** [comment]
@sweeneyapps I hung my extension as well. It is impossible to work that way.

**Comment by maciejgryka** [comment]
Hey - we've just posted an update to our news portal about yesterday's training jobs: https://portal.rainforestqa.com/. Please close this issue if it answers your question.
