### ISSUE TITLE
Training job

### ISSUE THREAD

**Issue by diabolic012** [rainforestapp/tester-chrome-extension#444]
I got several training jobs and all passed, but still got messages:
 "You passed a training lesson! Hi R... C..., Congratulations, you completed your last training lesson successfully! If your course is complete, you should get another email shortly. "

And all that after 5000+ jobs and 2 rejections till now. To me it's look like some bug in Rainforest system.

**Comment by josejecr97** [comment]
#439

**Comment by zfonck123** [comment]
me too  erros alots errors with this new method of training ...

![image](https://cloud.githubusercontent.com/assets/19192312/18069171/38acef8a-6e13-11e6-8ca9-d1877d09433e.png)
![image](https://cloud.githubusercontent.com/assets/19192312/18069174/3e9be900-6e13-11e6-9d8e-a2839a11bbb8.png)

**Comment by MarinaCec** [comment]
4 unfair rejections...

**Comment by sweeneyapps** [comment]
nobody deserve this. I have done like 14 training jobs after doing nothing wrong. No rejections even no rejections on training jobs task. So I decided to turn off my chrome extension for the day and hopefully by tomorrow, I am getting paid job. Again, nobody deserve this at all. Also in USA, we do pay our workers on their training day. So Rainforest needs to go back to the drawing board and figure out to do this the legal way. And compensation all of us. Thank you for ur time to hear me out.

**Comment by maciejgryka** [comment]
Hey - we've just posted an update to our news portal about yesterday's training jobs: https://portal.rainforestqa.com/. Please close this issue if it answers your question.
