### ISSUE TITLE
Training job and scroll

### ISSUE THREAD

**Issue by dollydol** [rainforestapp/tester-chrome-extension#446]
As many of you I got a rejection on a training job regarding the dog job.
Now my question is if instructions ask to scroll 3 times, how much a scroll is? Because after a single scroll of my mouse the page did not load any more dog pictures, that's why I failed the job and got a rejection.
So my question is: 3 scroll, how much is that? Because in a long scroll website like tumblr or facebook or twitter if after the first scroll the page does not load anymore there is a problem.

**Comment by xakep99** [comment]
The same with me. I reported unclear instructions and some divine creature decided that they were clear.

I have announced that the other day in the separate topic but not to many people bothered to read and think about it. There's too much mystery around rules and everything else. Why is that?

**Comment by dollydol** [comment]
I searched for this issue but I haven't found your message, good that I am not the only one fool enough to actually count three scrolls :) I reported it as bug but I don't think I will ever get a useful answer.

**Comment by slrojasc** [comment]
I sended this for Bug:
Someone else happens this?
There is an inconsistency with the evaluation of the jobs described below, the six works referred to are the same job. In previous jobs identified with  ID: (8348616, 8348891, 8350908, 8351038, 8352263), I answered "YES" to all questions and were rejected.
With the latest work identified with ID: 8351869 I answered "NO" in the last question, and was also rejected, indicating the feedback the following: ". Everything on this page was correct - you shouldnt Have Reported a bug" if everything is correct, why the first 5 were rejected ?.
Sincerely

Silverio Rojas

P.S. thats jobs say in first step: " Look at the page.
Does it say "Go to http://google.com"? "

**Comment by xakep99** [comment]
@ dollydol
Just the other day it was strongly advised to report unclear instructions. 

Anyway, they can do it just because they can. That's not in mysterious set of rules.

@ slrojasc

They slightly alter the task after rejected work. You should pay attention on that.

**Comment by dollydol** [comment]
@xakep99 Exactly, they even sent an email about it, but maybe it works only if it's not them !

@slrojasc I did the Google task once and it went fine but I don't remember it how tricky it was.

**Comment by ivasadzakov** [comment]
I understood that by scrolling down, the pictures should load more and more when you get to the bottom, like it is case for example on Google image search. In my case, the images did not load more, and I answered fairly  (my answer was No, they did not load) and by my opinion correct. The images in this question remain the same as on the first "Take screenshot" and nothing new loaded anymore. On every of these 11 jobs I waited for about 3-4 minutes for images to load, thinking the browser may be slow, and it takes time to load new images. As these jobs were popping out one following other, I did not pay attention to Job Rejection page or Crowdflower notifications, so I did not realize I was doing anything wrong. Instructions unclear, my opinion. I am blocked!!! :(

**Comment by nuevao** [comment]
this I just happened to me. Only reports the fault, it turns out that you have to guess which is the failure to find they want to continue. too bad this.

**Comment by Electroglitch** [comment]
Guys remember that training tasks have expected answers , so if task is programmed like let's say that you must click on some icon or link and at that moment page didn't load properly and you can't see it so you report it,
well... sadly it will be rejected.
This is just the tip of the iceberg with this poorly planned and executed idea.
So despite you are doing what you're suppose to be doing you'll be penalized.

**Comment by euparkeria** [comment]
Got a rejection on this test too. It’s improperly worded, no extra images “load” when scrolling down.

**Comment by xakep99** [comment]
@Electroglitch We understand that and it's OK. Unfair, too.

They could refer us to sources (online, hard press, whatever...) when we can learn about mouse scroll measurements. It's good thing to know for the future efforts.

**Comment by someone1x** [comment]
I agree with my colleague above , task with the dog is not correct ( scroll 3 times). If you need to talk honestly do not scroll half way: 
![1](https://cloud.githubusercontent.com/assets/21322993/18071312/7cb8adb4-6e5d-11e6-8c40-60562937627b.PNG)

**Comment by nuevao** [comment]
It is that that test had already done and in 3 scrolls appeared new images, but I sent her again, and this see the second scroll was not charged more images. I hope reconsider this....

**Comment by dollydol** [comment]
@xakep99 Yes! If they had some rules you can learn, mistakes will be on you, but they haven't. You should be provided with enough lessons to pass the tests without mistakes. Bad thing is even if they will eventually strike this job out because of a bug, rejections will remain. It's just like the attention check "are you using a computer?" which was very misleading when you were working on a mobile VM, in the end it was replaced but those rejections have remained.

**Comment by bilelmz** [comment]
In this job, Whether you answer yes or no = rejection!!!!!!
Look at this: 
https://github.com/rainforestapp/tester-chrome-extension/issues/440 
Some testers answer "yes" and get rejections!

**Comment by dollydol** [comment]
@bilelmz  Just for the record, before the rejection I had already done a dog task, where the three scrolls were not mentioned and it was not rejected. So I don't really know what bugs are they looking for.

**Comment by someone1x** [comment]
I got this job two times , the second time, I answered "yes" and there was no problem ...

**Comment by Electroglitch** [comment]
@dollydol check this thread at the bottom #420

**Comment by xakep99** [comment]
@ bilelmz: As I said they slightly alter repeated tasks and although they look the same they are not.

What we discuss here is bad instructions problem which is

**Comment by mobradovic** [comment]
> What we discuss here is bad instructions problem which is

What you discuss here mostly is poor understanding of basic English. Instructions (especially training ones) are as clear as can be.

**Comment by dollydol** [comment]
@mobradovic so if they are as clear as can be, can you please explain (no sarcasm I am dead serious) the 3 scroll measure? If you say scroll, it's ok I do it and see pictures loading. If you say scroll three times and I get to the bottom of the page in half a scroll, what am I supposed to think?

**Comment by euparkeria** [comment]
@mobradovic This is not true when comes to this particular task. This task is incorrectly worded. There are no images “loading” when scrolling down the page. If the question had been “Do images *appear*”, then that’s a completely different matter but “loading” is something quite specific when it comes to web pages. The instructions give the impression that more images will load and extend the page, similar to what google is doing with their images. I am a web developer and know what “loading” means.

**Comment by nuevao** [comment]
@mobradovic these instructions confused, What esla clarity? if you say "Scroll down three times to load more images."
and then you ask: As you are scrolling down the page, do continue to load new images? but you see that get to the bottom and not continuous loading more images after two Scroll. What is supposed to be the answer? I do not understand

**Comment by mobradovic** [comment]
> can you please explain (no sarcasm I am dead serious) the 3 scrolls measure?

No I can't (no sarcasm also), because it defeats the purpose of the test, and would be outright cheating, right?

Also, this whole discussion is totally inappropriate here, since this should be a place to talk about the extension, and extension alone... (hope someone will tidy up a bit).

**Comment by someone1x** [comment]
difficult to explain to Serb  "polyglot" :)

**Comment by mobradovic** [comment]
> I do not understand
And that's the key-phrase for all this fuss.

> Serb "polyglot"
Totally irrelevant, and kinda proves the point...

**Comment by xakep99** [comment]
So, you know whole lot about scrolling but you wouldn't tell us?

**Comment by Electroglitch** [comment]
Hey people! One guy said it's just matter of poor understanding of basic English,
so there was no problem after all, close the thread and let's all go home!
Man! I sure hope my understanding of basic English and application testing gets better tommorow.

**Comment by xakep99** [comment]
No. In fact it's the problem of understanding poorly written English.

Anyway, you can go home any time you want. We are not obliged to follow you.

Concerning your understanding of basic English, you are right. Take a break and see if it gets any better.

**Comment by Dani-Vase** [comment]
Same happened with me too. 
Under my opinion, there won't be any changes in the rejections. They will remain in the history until it is restarted (after a month). 
I just hope there won't be any penalties.

**Comment by bilelmz** [comment]
Latest News
Training Jobs 2016-08-30 01:04:53 UTC, Kristen Hohenstein
Hi, everyone! Random training was enabled today. I didn't know ahead of time or I would have sent an email letting you know. I apologize for the inconvenience! This doesn't necessarily mean that bugs got released with the training, however. If you think you got unfair training rejections today, please send in a support ticket categorized as "Other" and provide the jobs IDs in your message. Please start the ticket with the sentence, "Potential unfair training rejections." If you are rude or use bad language, you will be blocked from Rainforest. We will be looking into these tickets tomorrow after the AMA. Thanks for your patience! If you already submitted a ticket, submit one again using the above language, but add "I sent in a ticket earlier." This way I can easily locate all of your tickets and solve them accordingly. Thank you!

**Comment by Electroglitch** [comment]
@xakep99 Can't you recognize sarcasm?
And i really don't know why are you insulting me i thought we're on the same side concerning this,
meh...

**Comment by xakep99** [comment]
Sorry, I didn't notice that. I apologize.

**Comment by maciejgryka** [comment]
Hey - we've just posted an update to our news portal about yesterday's training jobs: https://portal.rainforestqa.com/.

**Comment by dollydol** [comment]
They just sent an email about the scroll jos that says they're gonna go through rejections for that and fix it because the training job was too difficult. So I'm going to close this issue and hope my rejection will go in the end :)
