### ISSUE TITLE
Accidentally unsubscribed

### ISSUE THREAD

**Issue by prpiro** [rainforestapp/tester-chrome-extension#447]
I inadvertently sent the Unsubscribe link in a RainForest message, Does anyone know how to undo this?

**Comment by nerdatwork** [comment]
You mean you clicked "unsubscribe" link inside the email ?

**Comment by JPierreS** [comment]
@prpiro 
If you are referring to the STATUS updates you receive by e-mail, then please visit the following:
https://status.rainforestqa.com/

On the top right, click on "SUBSCRIBE TO UPDATES" and enter your e-mail.

--------------

In regards to the tester notification you receive from Rainforest (NOT the status updates)
then you can configure this through your rainforest profile, under "edit profile" and NOTIFICATION SETTINGS.

Cheers

**Comment by prpiro** [comment]
Thanks JPierreS, !
