### ISSUE TITLE
I cant claim my profile

### ISSUE THREAD

**Issue by duda72** [rainforestapp/tester-chrome-extension#448]
Hello
I am sorry for the late reply to your message.
i still have no access to my account,I am not sure if I forgot my email or my password.
Since then,I can't check my work or my potential Rejections.
I would appreciate if you could resolve my issue as soon as you can,because I am afraid of getting banned due to potential errors while doing your tests.

Thank you in advance

**Comment by nerdatwork** [comment]
Have you submitted a support ticket ?

**Comment by duda72** [comment]
Yes I wrote went on biopsy forgotten mail or password, and never got
instructions for resetting passwords

2016-09-01 10:11 GMT+02:00 nerdatwork <notifications@github.com>:

**Comment by duda72** [comment]
For months, I can not go in on my profile because I forgot password

2016-09-02 11:13 GMT+02:00 Dusica Jocic <dusicajocic2@gmail.com>:

**Comment by nerdatwork** [comment]
Please remove your email address from the previous post.

**Comment by duda72** [comment]
Ok

2016-09-02 13:02 GMT+02:00 nerdatwork <notifications@github.com>:

**Comment by duda72** [comment]
Ticket number: 16150

2016-09-02 21:16 GMT+02:00 Dusica Jocic <dusicajocic2@gmail.com>:
