### ISSUE TITLE
no hits

### ISSUE THREAD

**Issue by hades00** [rainforestapp/tester-chrome-extension#45]
i claimed my profile and installed my rf extension a week ago and didnt get any hit ,i always keep the extension in NO position but this issue remains, what do i do??can anyone help me 
![aaaaaaaaa](https://cloud.githubusercontent.com/assets/16840796/12530977/c8978022-c1d6-11e5-958b-a09cda81dc43.png)

**Comment by pscohn** [comment]
@hades00 what is your worker ID?

**Comment by hades00** [comment]
**this is my work id 27694255 **

**Comment by pscohn** [comment]
It appears you haven't completed a job with us directly through CrowdFlower recent enough to be able to get paid through the extension - this is issue https://github.com/rainforestapp/tester-chrome-extension/issues/24. When that is fixed, you'll be able to get a new hit from CrowdFlower and then begin using the extension.

**Comment by hades00** [comment]
pscohn do you know when this issue will be fixed?

**Comment by pscohn** [comment]
@hades00 I don't know have an exact date as it will be fixed alongside an overhaul of some code, but it should be sometime in February.
