### ISSUE TITLE
Leave the page alert in wrong place

### ISSUE THREAD

**Issue by sweeneyapps** [rainforestapp/tester-chrome-extension#452]
After completing a job, "Leave the page" alert came up.  silly right?  

http://imgur.com/a/g5KbA

**Comment by RnkSts** [comment]
Same problem(_?_) here. Any info? :U
![screenshot_3](https://cloud.githubusercontent.com/assets/20311303/18104531/7e4885f2-6ec9-11e6-85e9-f31d627b0344.png)

**Comment by GreekGuy** [comment]
Just Check the prevent this page.. click Leave and bye bye pop up.

**Comment by NeoWorker** [comment]
I believe it's because of this:

https://github.com/rainforestapp/tester-chrome-extension/issues/292

**Comment by pscohn** [comment]
This will be fixed shortly.

**Comment by sweeneyapps** [comment]
@pscohn thanks

**Comment by zfonck123** [comment]
i think is a good, because for error u can leave the page :P

**Comment by playpin** [comment]
its fixed i guess
this is useful if we refresh the page by mistake in middle of the job

**Comment by sweeneyapps** [comment]
yeah.. fixed..    :)
