### ISSUE TITLE
time for task

### ISSUE THREAD

**Issue by awnosa** [rainforestapp/tester-chrome-extension#453]
I got task 155 step but can't finish in 60 minutes is each task max 60 minutes to finished?

**Comment by marius11** [comment]
You now have 90 minutes instead of 60.

**Comment by awnosa** [comment]
@marius11 every task 90 minutes

**Comment by nerdatwork** [comment]
Read this : https://github.com/rainforestapp/tester-chrome-extension/wiki/Idle-Policy

**Comment by awnosa** [comment]
@nerdatwork thanks alot

**Comment by nerdatwork** [comment]
You are welcome. If you are satisfied with the response please close this thread.
