### ISSUE TITLE
Security error

### ISSUE THREAD

**Issue by hupapa** [rainforestapp/tester-chrome-extension#455]
Hi all.

I´m trying to do a HIT but all of the sudden I get a " An IO error occured: ioError, Error #2031 " error.
I looked into the Wiki and refreshed the HIT but now the VM wont even load and the same error appears.
Refreshed a 3th time and same thing.
The HIT itself doesnt have the option to refresh sending feedback to RF about the error and the Reconnect option gives the same error...
Should i just abandon the HIT?

**Comment by zfonck123** [comment]
u need only clik and button restar job and reporting the error inssue vm

**Comment by hupapa** [comment]
Thanks for your response.
Like i said, that button was not there. There´s was just the " Reconnect " button and that one didn´t work either.

**Comment by nerdatwork** [comment]
Did it happen to just 1 HIT or all the HITs ? A refresh should have given you a new terminal without the error message but in some rare instances the error persists.

**Comment by hupapa** [comment]
Today happened again but when i refreshed went back to normal...
Seems that yesterday was just a rare case.

**Comment by nerdatwork** [comment]
That is great. If you are satisfied with the response please close this thread. Happy testing :)
