### ISSUE TITLE
Problem with do jobs You have reached... bug in my account

### ISSUE THREAD

**Issue by suplazam** [rainforestapp/tester-chrome-extension#456]
In this afternoon I had a problem with the jobs. The jobs says "You have reached the maximum number of unsubmitted assignments". After a while it seems off and the extension gives me a link without work. I refresh the job but then for no reason I get the same and I can not perform work . Please help me with this problem.

**Comment by nerdatwork** [comment]
Try clearing your cache and history from Chrome. If it doesn't work. Re-install Chrome and Rainforest extension.

**Comment by marius11** [comment]
@nerdatwork You should stop advising people to reinstall Chrome. It doesn't make any sense, at all.

**Comment by uqbiii** [comment]
This never happens to me, like when i am facing the "You have reached...", no new HIT opens until the HIT i missed got abandoned, after that if i get a link it doesn't contain this statement, but if you open a previous saved link from history, it will show the same error until the missed job got abandoned, there is nothing to worry about, it takes 10 to 15 minutes mostly, in this time don't open any links of HITs and wait for the extension to say "Yes".

**Comment by mijorojas** [comment]
Just wait for some minutes and everything will be normal. It has happened to me several times.

**Comment by uangonline** [comment]
@suplazam It seems you have the same problem as @Levendy, are you the "friend" he is talking about? read #457 and try the solution writen there. Hope thats help.
