### ISSUE TITLE
Stuck IDs in diferent IP address, locations and ISP

### ISSUE THREAD

**Issue by Levendy** [rainforestapp/tester-chrome-extension#457]
Last week a friend stayed at home for the weekend and brought his work with him, since then, when He has an open Job, my chrome extension gives me only "no" or "You have reached the maximun number of..." and viceversa, as if the ID stuck togeder. Is this temporary?, if not... Can be Undo this?

**Comment by uqbiii** [comment]
You should take a look here [https://github.com/rainforestapp/tester-chrome-extension/wiki/Troubleshooting-&-Common-Errors-Explained#you-reached-maximum-of-unsubmitted-applications](url) before sharing internet.
If you are still using the same internet connection, you have to stop sharing to get rid of these messages.

**Comment by Levendy** [comment]
Thank you for answering uqbiii. Certainly we share internet for 2 days but when my friend returned to his house arose the problem I described in the previous comment. My question is: we must do to fix this? we try to reinstall the chrome extension and delete cookies but continue our stuck accounts.

**Comment by sweeneyapps** [comment]
@Levendy, have you tried logging out and log back in?

**Comment by uangonline** [comment]
@Levendy If your ISP use dynamic IP, Try to turn off your modem for 10 minutes to get the new IP. If thats not help and you have another computer that never used for RF job, try to login with that computer.
NEVER user same computer for different RF ID.
Hope that's help.
