### ISSUE TITLE
Answer of this test

### ISSUE THREAD

**Issue by awnosa** [rainforestapp/tester-chrome-extension#458]
any one got this test what's Answer today and yesterday 0.00 of EST.WAGES

I am not found today where in this pic? Found yesterday only sometimes answer yes and no

![untitled](https://cloud.githubusercontent.com/assets/16338438/18203564/a3a1afb8-70cc-11e6-8887-56ec2e2a824d.png)

**Comment by marius11** [comment]
The value for today is right under "EST. WAGES".

**Comment by awnosa** [comment]
@marius11 but under EST. WAGES say "yesterday"

**Comment by uqbiii** [comment]
"vs" is the main thing to understand, which is before yesterday, yesterday is past, and we can't think about future is EST. WAGES, then what is before vs, its present, and present is today, it's a little tricky question but not difficult.

**Comment by marius11** [comment]
@awnosa It says in big bold characters **$0.00**. That's the value for today. Under it, you find the value for the day before.

**Comment by awnosa** [comment]
@marius11 @uqbiii  Thanks a lot I am understand now.
