### ISSUE TITLE
Too many Training jobs daily

### ISSUE THREAD

**Issue by ddiiego1** [rainforestapp/tester-chrome-extension#459]
Hi, i'm worker 38569716, since like 5 days I've been receiving a lot of training jobs daily (I have passed it all), and it is not allowing me to earn anything.
I know that there was an problem with the platform the past days (I read the portal news daily) but you said that it was now fixed up, but I still having this problem and cant work because of this.
Please take a look and help me.
![14249181_1299560580062756_801249491_n](https://cloud.githubusercontent.com/assets/19738677/18216256/4353287c-711b-11e6-922c-05acfce8cf34.jpg)

**Comment by nerdatwork** [comment]
How many rejections have you gotten in the past few days ? The whole point of training jobs is for you to get trained. If you keep on making mistakes you will NOT be taken out of the sandbox and made to do training tasks till you get perfect.

**Comment by ddiiego1** [comment]
I have 4 rejections, but since like 1 week (because of the bug in the training jobs), but in the past few days I had not got any rejections and I pass all my training jobs correctly. Thats my problem.

**Comment by Angelituss** [comment]
I have the same problem for days

**Comment by Angelituss** [comment]
I still have between 15 and 20 tests training every day
