### ISSUE TITLE
Why so many instructions under one step in Attend hits?

### ISSUE THREAD

**Issue by akshithaaravi** [rainforestapp/tester-chrome-extension#46]
There are at least 6 to 8 instructions given in each step, its very tedious and confusing...! always results in reporting the issues.

**Comment by SantVzlaC** [comment]
Totally agree

**Comment by qpPykT** [comment]
A little practice and you will be able to do these tasks with your eyes closed.

**Comment by marius11** [comment]
Although you shouldn't. You are supposed to treat every task as if you haven't done it before. Also, more worried about 502 Bad Gateways errors in Attend tasks.

**Comment by Genesis2015** [comment]
I haven't see any hits from Attend since end of November! What could be the reason? :(

**Comment by PSamanta** [comment]
Since November? You probably got banned from doing Attend I guess !! :-(

**Comment by hunt40** [comment]
exaclty every step is like a 4 step worth of work with attend

**Comment by mall2307** [comment]
ya It is very slow to open attend task and so many instructions in each step

**Comment by PSamanta** [comment]
Always Slow, so many work (like 5 steps) in a step!! offffffff... Tired of this. Really disappointing!!

**Comment by pscohn** [comment]
This GitHub issues page is only for issues related to our (Rainforest) platform, not our customer's. I'm closing this issue but I will pass on your complaints.
