### ISSUE TITLE
Count total cent make today on portal

### ISSUE THREAD

**Issue by warpten09025** [rainforestapp/tester-chrome-extension#462]
I think the portal need to display the total cent that tester make on the latest day.
So I managed to write some jquery code to do this .
The code is very bad because i'm just a student.
I will post this code on youtube if this is legit :+1: 
![image](https://cloud.githubusercontent.com/assets/15846336/18225843/fa482ab6-7227-11e6-8d91-a3b7541c8ace.png)

**Comment by sweeneyapps** [comment]
it doesn't work that way.  Javascript can't do stuff like this because it will only count the total on each page only.   If you did more than 25 jobs on that day, you will get the total wrong.    What Rainforest can do is write code on their server-side (SQL/NoSQL) to display the daily earning total on the page.

**Comment by warpten09025** [comment]
You're right . This is much more easy if  it was on server side . 
my code only work on one page so you need to go to page 2 or even page 3,4,5 and just need to do it again ( If page 1 sum is $3 , page 2 sum is $2 then you make $5 on that day)

**Comment by JPierreS** [comment]
@warpten09025  Unless Rainforest allows to change the value of per page entries (25, 50, 100, 500, etc)
or export the history :D  
I'm not too experienced in JS  but I could have a stand alone app do this and much more such as total time taken for all jobs, calculated $/hr, total earning, type of browsers, etc :dancer: 

Of course the best method would be server side, but then again it probably is not a priority ATM ;)

Keep in mind that unless you are working through CF Elite, these would be gross earnings, so perhaps a local script to automatically calculate and display the net values (based on your channel).

**Comment by GreekGuy** [comment]
@warpten09025  download notepad++ ;)

**Comment by JrRandy** [comment]
This type of thing is done for both Swagbucks, and MTurk (And I am sure many other sites), so it is possible.  There likely just isn't enough people caring for someone to invest the time and effort to make it happen.
