### ISSUE TITLE
Add sound support

### ISSUE THREAD

**Issue by shosti** [rainforestapp/tester-chrome-extension#466]
Steps:

- [x] Add an options page to enable/disable (#470)
- [ ] Add sound notification that plays if the option is enabled

@sweeneyapps

**Comment by sweeneyapps** [comment]
I got some questions,   should I follow your pattern with chrome extension requiring me to create separate html file such as options_dev.html etc?   I’m testing a method where we could use react.js on options.js and having it built via npm.

while working on it, I want to see if I’m going into the right direction.

here’s what I did.    I created an “options” directory inside "src" directory.    I added some lines to package.json:

"build:options": "browserify src/options/index.js -d -o build/options.js -t [ babelify --presets [ react ] ] -p [ minifyify --map options.js.map --output build/options.js.map ]”

and updated this line:   "build": "npm run build:browser && npm run build:module && npm run build:options”

so options.js will be on the server-side if I’m doing this correctly.   It worked in the development environment but not sure if you re doing it differently on server-side.

I followed your pattern by doing  options-dev.html, options-staging.html, and options-prod.html along with script src = options.js on specific server url you had on your index’s pattern also updating *_manifest.json files.

I will create a module inside src/options directory that will listen to chrome.storage changes and creating a reducer for options alone.  Making it easier for future updates if we need to add anything to options page.

Also I noticed that you didn’t use index-prod.html in the production_manifest.json.

**Comment by sweeneyapps** [comment]
(repost for this discussion) 
@shosti checking to see if I'm on the right track.. can you check out my branch at https://github.com/sweeneyapps/tester-chrome-extension/tree/localDev
if possible, can u test it out.

**Comment by shosti** [comment]
Hmmm, since the options page requires change to manifest.json I actually think it should be part of 2.0 (assuming you're using  [this API](https://developer.chrome.com/extensions/optionsV2)). We don't want to have to redeploy the actual extension for the foreseeable future. I'll look into adding the basic options framework and then the sound stuff can be built on top of it.

**Comment by shosti** [comment]
Actually looking at this again, I think we should forego an options page and instead have an "extension settings" section in the tester portal (since we already handle auth that way). I'll open up an issue there.

**Comment by sweeneyapps** [comment]
that's good idea and that would be easier that way.

**Comment by shosti** [comment]
(btw I made a quick boilerplate options page: https://github.com/rainforestapp/tester-chrome-extension/pull/346/commits/950883f4db6bf9ad03fbf0e0cb74a4a835f2edfd)

**Comment by sweeneyapps** [comment]
yes, i saw...   it's perfect.    Making it easier for all of us.    btw, it was my first time doing react and redux but good experience for me and I'll continue study more documentation on that.

For sound file, we can convert it into base64 format.    Audio() API will accept data uri ("data:audio/mp3;base64,T2dnUw.....") or url from internet source.

**Comment by shosti** [comment]
@sweeneyapps once https://github.com/rainforestapp/tester-chrome-extension/pull/573 ships this should be really easy I think. The options page will set `state.plugin.options.soundNotificationUrl` which we can use for the audio notification. Sound reasonable?

**Comment by shosti** [comment]
The only other thing is that some people wanted sound repeating or something like that. Not sure of the details, but something to consider.

**Comment by sweeneyapps** [comment]
Yeah, it does sound reasonable.   If testers are able to customize sound by providing their own url to sound then we wouldn't need sound repeating options because they could find a sound url that play longer.

**Comment by shosti** [comment]
Oh to start I think we'll just host a few options. Allowing people to enter their own audio notifications is also a possibility for the future if people really want it.

**Comment by shosti** [comment]
@sweeneyapps OK options framework should be GTG. Feel free to make a PR when you can. (If you don't think you can this week, let me know and I'll handle it.)

**Comment by sweeneyapps** [comment]
@shosti sure thing, it'll be first thing on my mind tomorrow morning.
