### ISSUE TITLE
Rainforest tester notifier problem

### ISSUE THREAD

**Issue by DarrE9o** [rainforestapp/tester-chrome-extension#467]
When i turn him ON, if he dont find job in 7,8  minutes, he automaticly goes on off...So i must watch all day in that green leaf...Any recommendations ?

**Comment by nerdatwork** [comment]
Yes that is how it is supposed to work. If you are not active the extension will turn off so it can allocate jobs to testers that are active.

**Comment by qpPykT** [comment]
> Any recommendations ?

Read read and again read if you want to know something about rainforest. 
You can start with [Wiki pages](https://github.com/rainforestapp/tester-chrome-extension/wiki)
