### ISSUE TITLE
A Security Error (help required)

### ISSUE THREAD

**Issue by SHAFIQUETUP** [rainforestapp/tester-chrome-extension#468]
From yesterday to till now every hit comes to me following error occurred "A security error occurred" (Error#2048). Kindly guide me how can i get rid off this problem.

**Comment by shrestha15207** [comment]
Restarting the terminal may help. i had that issue before. wrote couple of support tickets as well, but it will go by itself. nothing we could do. u may try updating ur flash or temporarily disabling firewall.

**Comment by RnkSts** [comment]
When I get this message, i usually click the **Reconnect** button and problem it's solve, but sometimes the error it's recurrent and I have to click Restart Job, and select _"Issue with VM"_ and explain, copy/paste the error message in the input box. After that I can work without problems.
