### ISSUE TITLE
PLEASE HELP! Profile blocked becuse of "dog" job rejections

### ISSUE THREAD

**Issue by ivasadzakov** [rainforestapp/tester-chrome-extension#469]
I sent 2 support tickets about this, but my profile is still blocked. I can not work for 8 days now, can you please unblock my profile because I am blocked due to 10 rejections on same "dog" job which came one after another in one hour. I think it is useless to send another support ticket because you have them too much. I wasn't automatically unblocked. If anyone from the Rainforest is reading this, please help me, I want to work! My worker ID is 17981759.

**Comment by nerdatwork** [comment]
I will let the right people know. Sorry for the delay.

**Comment by maciejgryka** [comment]
You should be unblocked now @ivasadzakov.
