### ISSUE TITLE
rainforest extention package is invalid could not load extension icon

### ISSUE THREAD

**Issue by yoges9** [rainforestapp/tester-chrome-extension#47]
i am using window 7 and chrome shows package is invalid could not load extension icon png

i am unable to add rainforest extention

**Comment by PSamanta** [comment]
Upgrade to latest version of Chrome and try again.

**Comment by yoges9** [comment]
i have latest chrome 49.0.2623.28 Beta but unable ?

**Comment by yoges9** [comment]
error is here : package is invalid. detail: could not load extension icon/icon38.png

**Comment by MuhammadRafique182014** [comment]
they are saving their steps usage LOL!

**Comment by nihlathar** [comment]
Having the same problem, reinstalled chrome (x64, latest beta), gives the error yoges9 gave.

**Comment by nihlathar** [comment]
I fixed the problem by switching to x86 chrome stable version, should work for you too

**Comment by yoges9** [comment]
Thanks to nihlathar i installed chrome 32 bit and it works.. thanks..

**Comment by ukd1** [comment]
@yoges9 fyi, this is fixed - you'll need to update to ``1.0.2`` which was released ~1m ago.

**Comment by yoges9** [comment]
Thanks
