### ISSUE TITLE
Handle options for extensions

### ISSUE THREAD

**Issue by shosti** [rainforestapp/tester-chrome-extension#470]
You should be able to customize certain aspects of the plugin (such as sound notifications). We can set that up the options page in the tester profile, after which we can just add it to the workers reducer (should be pretty straightforward since we already listen for auth in the same way).

**Comment by mariaelite** [comment]
Sorry. Google translator does not help.
This is a future or is already active?

**Comment by shosti** [comment]
@mariaelite if an issue is open it's always in the future (issues are closed once they're active).
