### ISSUE TITLE
i can't claim my profile 

### ISSUE THREAD

**Issue by moneymanagain** [rainforestapp/tester-chrome-extension#471]
Hello,  I received an invitation on 27th May 2015 to create a profile for RainforestQA. The problem is that when I click on the link provided by them for the activation of my profile it sends me to the site, but I cannot activate my profile because the claim my profile button doesn't work..I also have a ticket #14770 that i got for them for an support about this problem but no one response and the issue was sent in 16 August  .Best regards

**Comment by ando100** [comment]
@moneymanagain Hey, with all the respect- have a look at the calendar, 09/2016 now :)
Your only option at the moment- when RainforestQA invites new members- to do the task and claim a profile again..

**Comment by moneymanagain** [comment]
Well only in 16 August this year i saw in notification tab of my crowdflower menu the invitation and i didn't got an alert that i got this message last year . I tried to see if i can join but when i want to claim my profile  nothing happens and  it's not showing  a message like the invitation has expired.

**Comment by ando100** [comment]
@moneymanagain that link is expired.. Don`t lose your hope though, keep an eye on- when new invites are released and you can start doing the tasks again.

**Comment by bilelmz** [comment]
@moneymanagain I had the same problem. I emailed the support, and after a while, they give me a link to claim my profile, but they said that i can't work with it until they open new registrations again.
You must have did at least one job with this ID, and be patient, support will reply.

**Comment by moneymanagain** [comment]
Thanks guys, i will just have to be patient and wait for an response from the support team.
