### ISSUE TITLE
not under stand this step

### ISSUE THREAD

**Issue by awnosa** [rainforestapp/tester-chrome-extension#472]
Enter activation code: "as456-pouy9-ABC34asdfwre".
User is restricted after 15 characters i.e., "as456-pouy9-ABC34"??

**Comment by uqbiii** [comment]
Some text fields are restricted to specific number of characters, this code field is restricted to 15 characters, but the activation key contains 22, now they are asking you if you put a code of more than 15 characters, will all of them show or the text field show only first 15 and rest of them automatically disappear? Answer "Yes" if you see 15 means this "as456-pouy9-ABC34" and "No" if you see "as456-pouy9-ABC34asdfwre" or any code which contains more than 15 alphabet and digits.

**Comment by awnosa** [comment]
@uqbiii I am understand, thanks.
