### ISSUE TITLE
Couldn't load plugin

### ISSUE THREAD

**Issue by dmjohnson12** [rainforestapp/tester-chrome-extension#473]
Yesterday and today, I have been having issues getting a terminal.  The message says "Couldn't load plugin."  I try Reconnect, Restart, and refreshing the screen, nothing works.

**Comment by nerdatwork** [comment]
Could you take a screenshot of the page to get a clear understanding of the issue ?

**Comment by uqbiii** [comment]
Make sure you are using the latest version of Flash Player. type chrome://components and check if pepper_flash is up to date. Never experienced this issue, maybe the problem is just on your side.

**Comment by dmjohnson12** [comment]
I have attached a screen print here.  It says my pepper_flash is up to date.  Is it possible that this is because I am on Windows XP?  
![couldn t load plugin](https://cloud.githubusercontent.com/assets/22036204/18313284/04080772-74dc-11e6-96b3-d7eae3a2f002.JPG)

**Comment by nerdatwork** [comment]
It is not related to your operating system. It should work fine regardless of whether it's Windows XP/7/8/10. Something is blocking the script to load flash. Can you try reinstalling Chrome and the Rainforest extension ?

**Comment by dmjohnson12** [comment]
I have reinstalled Chrome and the Rainforest extension.  I am still getting the same result.

**Comment by nerdatwork** [comment]
Do have Adblock plus installed or any other extension besides Rainforest ? Also which antivirus are you using ?

**Comment by dmjohnson12** [comment]
I have disabled all extensions except Rainforest.  It had ASK and Playfizz enabled.  I am using AVG Free 2016.

**Comment by nerdatwork** [comment]
Ok. Try this . Go to **C:\Users\(YOUR USERNAME)\AppData\Local\Google\Chrome\User Data\PepperFlash** go inside the folder starting with the version number of pepperflash maybe 22.x.x.x and rename pepflashplayer.dll to **pepflashplayerC.dll**

Close chrome if it's open and open it again. Try to see if the job loads this time.

Happy Testing ;)

**Comment by dmjohnson12** [comment]
That worked - thank you so much!
