### ISSUE TITLE
Failed to fetch error spam!

### ISSUE THREAD

**Issue by khristianjose** [rainforestapp/tester-chrome-extension#475]
![image](https://cloud.githubusercontent.com/assets/17553414/18330503/f6bb6776-7526-11e6-9eb6-6117863267c6.png)

im getting this msg error on every job i get

**Comment by cookin2** [comment]
@khristianjose  I'm sorry that you're getting this error :(

But when I first saw it, I didn't know if it was computer-speak like "sandbox" or not.  It made me LoL because it sounds just like my dog - failed to fetch!

**Comment by AmaiaKao** [comment]
Having the same issue since 5-6 hours ago. Not a single hit since then. I can see 'another worker' or no vm, but when it's a live hit since the 'Test note' button is visible, it suddenly goes 'Failed to fetch'. Sent ticket about this too. :(

**Comment by noel4657** [comment]
Got the same issue with @AmaiaKao, missed 11 hits already.

**Comment by khristianjose** [comment]
Im still getting the same error on all the jobs i get, cant work, whats happening?

**Comment by AmaiaKao** [comment]
everyone here kindly send tickets so Kristen will know it's not just one who's having trouble but few of us 
:(

**Comment by khristianjose** [comment]
It shows the modal but when you think its going normal it shows FAILED TO FETCH, frustrating.

**Comment by AmaiaKao** [comment]
yea, you can see even the test note button when it's a live HIT but doesn't load fully and changed to 'failed to fetch'. Happened to me almost the same time this thread was created. 

Any idea about this @pscohn thank you!

**Comment by khristianjose** [comment]
Well i cant work, would be nice if we receive an answer about this problem, im losing time :/

**Comment by khristianjose** [comment]
@maciejgryka  Any help?

**Comment by kristen-allie** [comment]
Hey @khristianjose , we're looking into this now!

**Comment by khristianjose** [comment]
@kristen-allie Thanks.

**Comment by kristen-allie** [comment]
@khristianjose @AmaiaKao @noel4657 can you send in a support ticket with your worker ID? Please make the first sentence "Failed to fetch - worker ID" so I can locate them easily. Hopefully this will help us figure out what's going! Sorry about this :(

**Comment by khristianjose** [comment]
I just did it now.

**Comment by khristianjose** [comment]
This is happening since yesterday, i was working normal at all, but then i receive a lot of those errors, and its a nonstop of failed to fetch

**Comment by JPierreS** [comment]
Just one suggestion, those who have the failed to fetch, on the same tab, right click anywhere on the page, click inspect and go to the network console, would the text in this area possibly help RF in finding the cause of this ?
Could be that for whatever reason some specific users cannot establish a network connection with the terminal ?

**Comment by pscohn** [comment]
@JPierreS that would be helpful (or it might show up in the javascript console), but we've reverted an offending code change so it shouldn't be happening anymore.

**Comment by AmaiaKao** [comment]
yes working normally now thanks a lot. I also sent the console error to Kristen.

**Comment by zfonck123** [comment]
i get same error, when my internet conecction down @khristianjose
