### ISSUE TITLE
You have reached the maximum number of unsubmitted assignments. So we are fair to other workers, we stop you doing too much for us at once. You can complete the other assignment(s) and refresh this page, or simply return this hit

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#476]
You have reached the maximum number of unsubmitted assignments. So we are fair to other workers, we stop you doing too much for us at once. You can complete the other assignment(s) and refresh this page, or simply return this hit..    this week alot time with this  about more 10-30minutes, . very rare very strange

**Comment by zfonck123** [comment]
maybe for app error, and hight ping this night ? 
![image](https://cloud.githubusercontent.com/assets/19192312/18334057/75fd2a5e-7542-11e6-8414-a25feb58adfb.png)

**Comment by nerdatwork** [comment]
Did you read this ? [You have reached the maximum ... ](https://github.com/rainforestapp/tester-chrome-extension/wiki/Troubleshooting-&-Common-Errors-Explained#you-reached-maximum-of-unsubmitted-applications)

**Comment by zfonck123** [comment]
no, thx for the info
