### ISSUE TITLE
COPY button didn't work?

### ISSUE THREAD

**Issue by ladystoneheart** [rainforestapp/tester-chrome-extension#477]
Am I the only one experiencing this one? when I clicked it copied the paste in the terminal didn't work. look my screenshot to know what I mean. I have experienced this many times, so I have to type whole link in the terminal. 

ps. even I click CTRL+C and CTRL+V

![a](https://cloud.githubusercontent.com/assets/20522240/18337812/95ca9d4e-759c-11e6-9350-504eabfaa7c0.png)
![b](https://cloud.githubusercontent.com/assets/20522240/18337813/95cd5cb4-759c-11e6-9df5-907bb6f41d48.png)

**Comment by uqbiii** [comment]
You need to press Ctrl+v to paste copied text into the terminal.

**Comment by JPierreS** [comment]
Copy and pasting is working fine.  When the item you are copying from is OUTSIDE the terminal area, you must use CTRL-C or the copy button is available in the instructions and then use CTRl-V to paste in the terminal.

If you are copying and pasting items inside the embedded terminal area, then you must right click and use the copy / paste from the context menu inside the terminal area.

From OUTSIDE terminal to INSIDE terminal -   CTRL-C / CTRL V
From INSIDE terminal to INSIDE terminal - context menu (right click) copy / paste from within terminal.
