### ISSUE TITLE
Anyone have any idea why this happens?  "Rate limit exceeded, you may do 2 ..."

### ISSUE THREAD

**Issue by MiguelAbrams** [rainforestapp/tester-chrome-extension#481]
All hits that I receive through the addon give me the message:
"Rate limit exceeded, you do May 2 every 50.0 seconds requests. Do not refresh the page More Often Than This. This limit May change."
The message format is the old format: not with the background color.
I have two users, only it happens with one of them. The other works well.

**Comment by nerdatwork** [comment]
What do you mean by having 2 users ?

**Comment by zfonck123** [comment]
this fix, u can refresh each 30s , if not u get rate limit exceeded

**Comment by MiguelAbrams** [comment]
Thank you zfonck123
When the hit emerge beforehand shows the message. I have yet not  refreshed.

**Comment by sweeneyapps** [comment]
@MiguelAbrams btw, rate limit is for 1 IP address.  If you have 2 computers behind 1 IP address then it'll mess up with rate limit.

**Comment by MiguelAbrams** [comment]
sweeneyapps:
Thanks. I am using an only computer however your comment remember me the problem starts when I installed the Rainforestqa addon in my other machine. I uninstalled the addon in my other computer but I continue with the same problem.

**Comment by MiguelAbrams** [comment]
nerdatwork:
If you work for several PTC you should be able to have one user for each PTC.

**Comment by nerdatwork** [comment]
I understand but do you have 2 users connected with Rainforest account ?

**Comment by MiguelAbrams** [comment]
No, I connect one user at a time. You cannot connect 2 or more users at a time.

**Comment by Dolazim** [comment]
Nope I also get this message some time I not have two acc I have only one no one close to me work this...

**Comment by MiguelAbrams** [comment]
Dolazim:
Have you write to support team? Have you installed the addon in 2 or more computers?
I thank you for your intervention.

**Comment by shosti** [comment]
No longer relevant.
