### ISSUE TITLE
Invalid email and/or password

### ISSUE THREAD

**Issue by Levendy** [rainforestapp/tester-chrome-extension#483]
Hello Friends, I can not log in to the Rainforest Portal, because I had to change my email in Edit Profile, accidentally mistyped the new email and saved the changes, now I have no way to know what email is was saved in my Profile, please if anyone can help me, I can not get the Chrome extension and my job is stopped. Thank!

**Comment by nerdatwork** [comment]
Did you send a support ticket about this ?

**Comment by Levendy** [comment]
I did't send a ticked yets!

**Comment by nerdatwork** [comment]
Do it and reply with your support ticket here.

**Comment by Levendy** [comment]
Ok I will, Thanks for the help!
