### ISSUE TITLE
Doubts regarding matching texts inside quotes. 

### ISSUE THREAD

**Issue by pat87** [rainforestapp/tester-chrome-extension#488]
I know there was a thread recently about texts inside quotes and what needs to be reported. I had a few extra questions.

Is there any official word on how much needs to be matched, before or after the text inside quotes in the instruction. How many sentences do we match when something is inside quotes? and when do we stop?  **_Basically. How much do we look to match before and after a sentence when quotes have been used in the instructions? One whole sentence formation, along with any punctuation, makes perfect sense. Other sentences before and after the one in the instruction are in the grey zone for me and I cant decide how much we have to match._** 

I mean, consider the following scenarios.

**Instruction** : Does the page says "Thank You!"

**Page** :  Thank You! You will get an email shortly.

The page says  "Thank You!". Do we report it because there is another line after it.
what if the page said the second sentence in a different line?

**Page** : Thank You!
                You will get an email shortly.   
Is that ok?

My understanding was that we needed to match the texts inside quotes to the page .. and look for differences within that sentence(part of the sentence). So if the step said
**Instruction** : Do you see "Thank You"
**Page** : Thank You!

I would report because the **!** is a part of the sentence.

But if the page said
**Page**:  Thank You! We will get in touch. 
I would pass because there is an exact match and the rest is additional content from another sentence. 

----- part 2--

Also, there was a update in the guide 
"If the instruction says Click on the button which says something like "Run tests" and the website says "Run test", answer No. The test author is using quotes inappropriately. If they didn't want you to worry about looking for the exact phrase, they should not have used quotes around "Run tests".Them saying something like beforehand doesn't change the rule."

Which I understand .. Another variant of this, used in rainforests own website hit, is 

**Instruction**: Do you see an error beginning with "Error some of the tests couldnt be" 
But the page starts with that and there is more content in the same sentence. There is no placeholder "_" in the step instruction. Do we report this too.. 
The page does start with the text inside quotes.. But quotes have been used incorrectly as well. 

**eg: do we report this as incorrect use of "quotes" or proceed.** 

![rfdoubt](https://cloud.githubusercontent.com/assets/17265000/18406292/d90e4696-7718-11e6-81df-609dec754557.PNG)

**Comment by Zunami007** [comment]
I would pass it, because the heading **begins** with "Current Issue", but if the instruction says: Scroll down the homepage to the heading "Current Issue" I would say NO, because the correct instruction would be"Current Issue_". That is what I would think .. hopefully I am right .. ^^

**Comment by clessweapon** [comment]
and how about this case? "Sign up" and Not a member? Sign up
![clipboard01](https://cloud.githubusercontent.com/assets/22085655/18412794/5c1da18a-776e-11e6-9c43-cdc528d56771.jpg)

**Comment by marius11** [comment]
Is "Not a member?" a green link? I don't think so. The instructions are very clear.

**Comment by sweeneyapps** [comment]
hopefully Tester's Forum will be open to all testers for this kind of issues.

**Comment by sweeneyapps** [comment]
let close this issue..  I think ya all get it.
