### ISSUE TITLE
Extension shows "YES" but no job received

### ISSUE THREAD

**Issue by ahmedofhell** [rainforestapp/tester-chrome-extension#49]
Hello,

Somthing wrong with the extension, Extension Status Changed to Green YES But without received any job.

Turn the extension to OFF and NO again didn't solve the problem.

I must Remove it from chorme and Add it again after every Hit I complete in order to get the next job.

**Comment by nuevao** [comment]
It is true, that happens to me too, but it is not something new, some time ago has been happening, suddenly so long that is green you get a test, or else simply placed in "NO" again and do not assign tests.

**Comment by Genesis2015** [comment]
That think happens to me too. Some times switchng off and then on resolve the problem.

**Comment by warpten09025** [comment]
Like Genesis2015 mentioned above , I think the best solution is just switching off and on ! 
Source :My Experience  !

**Comment by Unsubmitted** [comment]
switching off and on is not working and even removing the extension and installing also is not working for me.

Rainforest Team is there any update on the issue.

**Comment by ahmedofhell** [comment]
Now Extension **NOT** shows "YES" at all, I must Remove it from chorme and Add it again after every Hit I complete in order to get the next job.

**Comment by ukd1** [comment]
@ahmedofhell you have to remove the whole extension? can you email us your worker ID, I'll take a look a the logs.

**Comment by ahmedofhell** [comment]
@ukd1 Thanks for your help.
Extension Works somehow Better now, But It's still very slow.
If you can do anything to resolve this problem.

Thanks again

**Comment by masterpeing** [comment]
same here.. Start with Yes but a error close the job.. :(

**Comment by nerdatwork** [comment]
The problem still persists

**Comment by khristianjose** [comment]
Same problem here, Show YES, but then in the page OOPS
