### ISSUE TITLE
TypeError Failed to fetch

### ISSUE THREAD

**Issue by shosti** [rainforestapp/tester-chrome-extension#491]
https://sentry.io/rainforest-1/tester-chrome-extension/issues/157680409/

```
TypeError: Failed to fetch
  at None (chrome-extension://immdjpjbcikbffjifkbncgfbohbjicpo/index_prod.html)
```

**Comment by shosti** [comment]
According to https://stackoverflow.com/questions/39393909/how-do-i-handle-javascript-fetch-errors , this is how chrome reports `fetch` errors (way to go Chrome!). We should handle better somehow...

**Comment by MarinaCec** [comment]
The message failed to fetch is coming when we are inactive??? I don't understand it yet
