### ISSUE TITLE
New Extension update

### ISSUE THREAD

**Issue by MarinaCec** [rainforestapp/tester-chrome-extension#494]
It get worse, failed to fetch all the time :(

**Comment by MarinaCec** [comment]
and it turns off (grey) in less than 5 minutes, it does not make noise only, got worse

**Comment by prpiro** [comment]
It is hard to differenciate the greyish-green color tone versus the grey tone for the elder people, please give it more contrast

**Comment by MarinaCec** [comment]
@prpiro do you think is coming less work after the upgrade? because I am

**Comment by shosti** [comment]
@MarinaCec have you successfully gotten any work? Would you mind posting any error messages you're getting?

**Comment by MarinaCec** [comment]
@shosti had one job now and only... the message "Failed to fetch" is coming a lot

Versão 54.0.2840.16 beta-m (64-bit)

**Comment by djux90** [comment]
I am little confused with this new extension. I got 2 or 3 hit, extension sometimes show word work (even if it is grey or turned off), and sometimes not. When i got works, it doesn't writed work on extension.

**Comment by shosti** [comment]
@MarinaCec would you mind posting a screenshot of the error message?

**Comment by djux90** [comment]
when i see it again, i will screeshoot it.  And it can be turned on little more time, very fast is going to off

**Comment by Cocapesi** [comment]
@shosti
If you have the extension green (ON) and you run a program as administrator our extension disable automatically with this message: "We noticed you were idle so we stopped checking for work"

This is a bug or is good? 

Thanks

**Comment by shosti** [comment]
@Cocapesi it's supposed to turn off if you're idle in chrome for 3 minutes (maybe we should increase to 5). Are you saying that it's turning off immediately?

**Comment by Cocapesi** [comment]
@shosti Yes, is turning off immediately if you open any program in your pc as administrator.

**Comment by shosti** [comment]
@Cocapesi hmmm that sounds like a bug in chrome. Can you make a separate Github issue and I'll investigate next week?

**Comment by Cocapesi** [comment]
@shosti Done!

**Comment by MarinaCec** [comment]
@shosti 
![asd](https://cloud.githubusercontent.com/assets/18725046/18406897/4b3f3e3a-76da-11e6-895a-efb8e1f1f32d.png)

**Comment by MarinaCec** [comment]
can't complete the hit with this error

**Comment by shosti** [comment]
Oh that's actually unrelated to the plugin and is a problem with the console.

Cc @pscohn

**Comment by sweeneyapps** [comment]
@shosti  I'm working right now..    so far..  doing 5 jobs without any problem..    polling is great and icon is rendering correctly.     Much better than 1.2  :+1:

**Comment by begsoon** [comment]
@shosti No errors right now.All works perfect(maybe because its only 1000 online testers).

**Comment by djux90** [comment]
i didn't have errors too, all going good for now. Just, you can little increasae time for extension to be on. And here is what was confused me:

![xxx](https://cloud.githubusercontent.com/assets/20422665/18407123/897c0556-7708-11e6-86de-83c3bc2441b5.JPG)

![c](https://cloud.githubusercontent.com/assets/20422665/18407124/897e8ace-7708-11e6-98ac-434a990b011b.JPG)

**Comment by ikjt** [comment]
I would have to agree with prpiro about the colors. Could you please make them bit brighter, so it's easier to distinguish between green and gray? Thanks.

**Comment by mariaelite** [comment]
@shosti Please remove this feature off.
I work on my computer.
You can not be enslaved only to Rainforest.

Use google traslator.

**Comment by srsaurabh32** [comment]
the new extension turns off within seconds.....i am not getting any work.

**Comment by qpPykT** [comment]
Caught six tasks works fine. Some problem with updating icons it's updated but very slowly after some time.

**Comment by farookabubakker** [comment]
I suggest the colours:
Red for turned off
Grey for idle
Green for Work!!!

**Comment by teteucalifornia2** [comment]
Unfortunately another change that does not improve anything for testers :/

**Comment by MarinaCec** [comment]
The message failed to fetch is coming when we are inactive??? I don't understand it yet
