### ISSUE TITLE
"We noticed you were idle so we stopped checking for work"

### ISSUE THREAD

**Issue by Cocapesi** [rainforestapp/tester-chrome-extension#498]
If you have the extension green (ON) is turning off immediately if you open any program in your pc as administrator with this message: "We noticed you were idle so we stopped checking for work"

Please check it @shosti 

Thanks

**Comment by mariaelite** [comment]
It is exasperating that turns off all the time

**Comment by qpPykT** [comment]
Same thing after opening any program on pc. 
![turn-off](https://cloud.githubusercontent.com/assets/4960092/18409342/6019113c-774d-11e6-8e2d-58c18b356205.jpg)

**Comment by justsux** [comment]
I vote for removing this new "feature". 

I used to watch movies/series while waiting for new work to come.
Which means my mouse and keyboard are idle. Yet, I'm not.

**Comment by marius11** [comment]
@justsux I'm not sure if your vote will help, but you should either watch your movies, or complete tests.

**Comment by justsux** [comment]
@mariaelite As they say: Don't teach me what to do and I won't say you where to go.

**Comment by sweeneyapps** [comment]
@justsux  It's not new feature.  The old extension already have idle checking feature and if you re watching a movie, the old extension (1.2.*) will turn u off anyway.

**Comment by shosti** [comment]
Dup of https://github.com/rainforestapp/tester-chrome-extension/issues/522 (we upped the limit to 6 minutes for now).
