### ISSUE TITLE
Notification sounds when new work is found

### ISSUE THREAD

**Issue by ukd1** [rainforestapp/tester-chrome-extension#5]

**Comment by ando100** [comment]
Russ, checked- no sound came in?

**Comment by ukd1** [comment]
@ando100 this is an enhancement request, not a bug - it doesn't exist yet

**Comment by ando100** [comment]
Cool, thanks !

**Comment by balajisekar** [comment]
Notification sound is not came, when new work is found

**Comment by Genesis2015** [comment]
It could be a very useful feature!

**Comment by LimitMan** [comment]
Fast solution for sound when {work_available: true}:
1. Change manifest background section to:

`   "background": {
      "page": "background.html"
   },
`

2. Create background.html in root with next code:

`		<script src="js/howler.min.js"></script>
		<script src="js/main.js"></script>
`

3. Download howler.min.js  from https://github.com/goldfire/howler.js/ and put it in js folder (howler is free for any type of distribution, modification etc.)

4. edit js/main.js on line 160 after

`        open_or_focus_tab(resp.url);
`

insert 

`		var sound = new Howl({
			urls: ['sound.mp3']
		}).play();
`

5. Download and put in extension root  file https://www.dropbox.com/s/m2l2oq0sulaep79/sound.mp3?dl=0 (this is just example file. It's opensource mp3 so it can be used for redistribution) 

Load extension and try :)

**Comment by helloworld111gh** [comment]
Playing sounds doesn't require a big library and can be done in vanillaJS
without editing background.html with 2 lines of code.

Fast solution for sound when {work_available: true}:
1. Change manifest background section to:

"background": {
"page": "background.html"
},

   1. Create background.html in root with next code:

<script src="js/howler.min.js"></script>
<script src="js/main.js"></script>

   1.

   Download howler.min.js from https://github.com/goldfire/howler.js/ and
   put it in js folder (howler is free for any type of distribution,
   modification etc.)
   2.

   edit js/main.js on line 160 after

open_or_focus_tab(resp.url);

insert

var sound = new Howl({
urls: ['sound.mp3']
}).play();

   1. Download and put in extension root file
   https://www.dropbox.com/s/m2l2oq0sulaep79/sound.mp3?dl=0 (this is just
   example file. It's opensource mp3 so it can be used for redistribution)

Load extension and try :)

—
Reply to this email directly or view it on GitHub
<https://github.com/rainforestapp/tester-chrome-extension/issues/5#issuecomment-181060234>
.

**Comment by LimitMan** [comment]
@helloworld111gh I suggested change to background.html so howler and script can be in different files. I agree that this can be done with many other libraries or even without them, but I found this is very simple way to do it without messing with writing extra code. Also, I don't find howler.js robust and resources consuming... But that is my opinion ;)
I guess developers of extension would appreciate any idea and workaround so You are welcome to write it.

**Comment by androwg** [comment]
@LimitMan @helloworld111gh  can any one of you generously upload the whole extension with the sound because a lot of people here and sure me don't understand these codes Thanks in advance

**Comment by LimitMan** [comment]
i would love to, but only if @ukd1 agree with this method...

**Comment by helloworld111gh** [comment]
@androwg here you go: https://github.com/helloworld111gh/tester-chrome-extension
i also added a notification for good measure

**Comment by androwg** [comment]
@helloworld111gh amazing it works Thanks a lot

**Comment by ando100** [comment]
@helloworld111gh thanks, it works, hope this is ok with Russ

**Comment by ChrisRaven** [comment]
It could also be useful to blink the browser tab on taskbar, when a job is ready. Especially, it would be good for those, who don't use Chrome as their default browser and keep it opened in the background only for the tests.
Something like this should do the job:

`chrome.windows.update(-2, {drawAttention: true});`

"-2" represents current window.

**Comment by androwg** [comment]
@helloworld111gh will we need to update your extension manually or it is like the official one it updates automatically when a new version is present? and when it updates to the new version will the sound works again?

**Comment by androwg** [comment]
@helloworld111gh will we need to update your extension manually or it is like the official one it updates automatically when a new version is present? and when it updates to the new version will the sound works again?

**Comment by ando100** [comment]
@androwg    I`m pretty much positive it does not update automatically:) 
leave it as is and it does it`s job. Also check the readme file - disclaimer @helloworld111gh added recently. And I assume the official version will have the sound alert in very near future.

**Comment by androwg** [comment]
@ando100 Thanks lets hope @helloworld111gh  add the sound to the new version when it comes and lets hope @pscohn  hear our voice to add the sound to the official release.

**Comment by ukd1** [comment]
@helloworld111gh wanna do a PR?

**Comment by androwg** [comment]
@helloworld111gh I think your new version has a problem because it doesn't want to turn to "on" instead of "off" after clicking on the extension.

**Comment by androwg** [comment]
@helloworld111gh it stays like this with no or off option 
![untitled](https://cloud.githubusercontent.com/assets/15823279/13223698/0e2bb06c-d98e-11e5-8212-e16fcd220b31.png)

**Comment by LimitMan** [comment]
@androwg Check if developer mode is enabled, restart your browser, and if chrome asks you to disable plugins say NO!

**Comment by androwg** [comment]
@LimitMan did all of that but in vain official version is working great but helloworld111gh one gives this pic with no option of on or off
![untitled](https://cloud.githubusercontent.com/assets/15823279/13233622/3280552e-d9bd-11e5-9bd3-4c4e11059d82.png)

**Comment by sweeneyapps** [comment]
that's easy..  I'll add to my pull request to add this feature.   My sound file will say, Job Found.

**Comment by sweeneyapps** [comment]
I closed my pull request due to 2.0 is underway..    anyway..   what I used was basically base64 format on audio..    (data:audio/mp3;base64) using Audio().   Good luck w/ 2.0.. hopefully u guys get everything patched up.

**Comment by sweeneyapps** [comment]
PR https://github.com/rainforestapp/tester-chrome-extension/pull/599 addressed this issue. :) @ukd1

**Comment by macocha** [comment]
@sweeneyapps that took a while 😄 
Closing.
