### ISSUE TITLE
Update extensión

### ISSUE THREAD

**Issue by mariaelite** [rainforestapp/tester-chrome-extension#500]
Goodnight Rainforestqa
The extension is off all the time
I do not understand why putting on this function when it is much better to add a sound.
With a sound, not lose jobs.
Shutting down all the time is exasperating to work with this update.

**Comment by coyoteazul** [comment]
Hi. It's not the ideal solution, but this script adds a sound
https://openuserjs.org/scripts/coyoteazul/CoAzRainNotification_(alt)

**Comment by mariaelite** [comment]
@coyoteazul Hola Coyote. Gracias yo instale tu scripts hace tiempo y es maravilloso. La cuestión es que he de suponer que ellos colocan q la extensión se apague para que haya menos puestos de trabajo abandonados y para mi, esa no es una solución viable, mientras que colocarle un sonido si lo es. Es imposible que las personas que no somos del área de la informática o cibernética nos las pasemos pegados a la PC nada mas para que la extensión no se apague. Por ejemplo, yo soy tejedora y gracias a tu scripts puedo seguir tejiendo y el sonido me avisa cuando me sale un rain y todo bien, pero ahora con este problema de la actualización, ya no puedo hacerlo y bueno perderé más rain de los que agarraré.

**Comment by sweeneyapps** [comment]
@mariaelite  they will add sounds on future update.   For now, working on to get rid of all the bugs on new extension then we can move forward for more new features.  :)

**Comment by shosti** [comment]
Sound support is #466. Closing as dup.

**Comment by mariaelite** [comment]
@sweeneyapps Google translation does not help me much.
I understand that this achievement will improve, besides placing a sound in future updates.
If I understood well, excellent. Thanks Rainforestqa.
