### ISSUE TITLE
New Extension Issue:  Stops polling after attempt to pass work leads to "oops"

### ISSUE THREAD

**Issue by JrRandy** [rainforestapp/tester-chrome-extension#501]
After job is "found" when polling, new window open with "Another worker....."  - Expected Behaviour
Upon CLOSING the "Another worker....." window, the extension keeps the word "Work" on it, and no longer polls.   

Inside the developer tools, the last fetch attempt was when it found work.  It has since been 15 mins, and not 1 fetch attempt has been completed.

**Comment by JrRandy** [comment]
*Note*  Turning extension OFF and then back ON does not lead to any polling.  Appears to be stuck perhaps waiting for the work you did not receive to be completed?

**Comment by f-ms** [comment]
Once the extension polls (gets a hit) and say we get "Another worker....", the extension remains in "WOR", does not go back to normal ON status. This is happening everytime it goes to "WOR". It does not come back to normal ON state.

The only way to get it to normal ON state is to uncheck and check the extension in chrome settings.

**Comment by diabolic012** [comment]
Same here, seems like a bug.

**Comment by f-ms** [comment]
Okay... Just got a hit and the extension remained as "WOR" till I submitted the hit. As soon as i submitted the hit it got back to normal green state without I having to uncheck-check at the chrome extension settings.

But when I get a potential hit, meaning when the extension says there is a hit but the hit is still not assigned to you and then the "Another worker..." message comes, that time the extension remains as "WOR" and does not return to normal green state. One needs to uncheck-check the extension in google chrome extension settings to get it back to normal green state.

**Comment by JPierreS** [comment]
This is a bug and could be fixed - meanwhile it is not an issue, you can refresh your oops until it converts to a HIT and once your hit completes it will starts polling again - the extension could be modified for it to check if you closed the oops tab - it would just add more checking, however this is essential in case someone decides to close the oops tab and wait for a live hit instead.

**Comment by Zunami007** [comment]
refreshing the addon does not work for me, I have to close the browser and reopen it, anotherwise the "Work" message won't disappear. 

Even when the addon turns off after 3 minutes, it is still there

![unbenannt3](https://cloud.githubusercontent.com/assets/22084629/18409917/a6623572-7754-11e6-8970-3513f22b8937.jpg)

**Comment by farookabubakker** [comment]
Anyone upload the screenshot for the new Extension??? How much it is better than older one???

**Comment by sweeneyapps** [comment]
if this happen, don't uninstall it,  just disable and enable it.   It'll work again.

I wrote about why this happened and suggestion for this bugfix at https://github.com/rainforestapp/tester-chrome-extension/issues/508

**Comment by shosti** [comment]
Dup of #508.
