### ISSUE TITLE
New extension isn't working

### ISSUE THREAD

**Issue by gusttest** [rainforestapp/tester-chrome-extension#502]
_Since I updated the extesion to the new version, I come not getting more jobs,when I click the plugin button, it is ON for a few seconds and then it makes getting OFF, he would not have to be ON (green) all the time?
Already I uninstalled / reinstalled and still the same.
I do not know if this is normal, I would help.
Thank you._

**Comment by srsaurabh32** [comment]
I am having the same issue mate....no work.

**Comment by noel4657** [comment]
No hits for almost 7 hours since this new version installed.

**Comment by kutch1** [comment]
Its the weekend i think there are less hits nowadays .

**Comment by vali12543** [comment]
neither green nor ON/OFF, all I can see is just grey button. nothing else. not a single HIT from the update, not even training job.

**Comment by hamosa2002** [comment]
me The same issue

**Comment by renangloor** [comment]
This horrible here too, they want to improve and ended up making that mistake horrible , only worse , hopefully agreeing soon , not to further damage the weekend .

**Comment by warpten09025** [comment]
Bring back old version please

**Comment by ladystoneheart** [comment]
hey guys its working, just remember it is Saturday today maybe there are no RAINS coming hehe

**Comment by warpten09025** [comment]
I know it's working but when i have no job it still display "WORK" which is a bug similar to "YES" when you have no job in older version

**Comment by warpten09025** [comment]
For my eye , It is hard to detect whether the leaf is green or grey

**Comment by AmaiaKao** [comment]
I guess I have the same error, it doesn't stay green. Yes extension is working for more testers but some testers are having the issue. Yes it's weekend but the fact that it doesn't stay green (no matter your actively clicking)  means there's an error.

**Comment by noel4657** [comment]
I've never got a hit until now.  Before even on weekends I still can get 10-15 hits.  @pscohn here is my worker ID 34223271

**Comment by farookabubakker** [comment]
So, soon we get the version 2.1!!!

**Comment by martinmay1985** [comment]
when I give a click to the extension:
you not logged in

but I'm already logged

**Comment by shosti** [comment]
See comment in #511.

(Closing as dup.)
