### ISSUE TITLE
error after error

### ISSUE THREAD

**Issue by gammarus64** [rainforestapp/tester-chrome-extension#504]
after the failure to start work in the icon WORK and does not allow new tests, and does not disappear
![09-10-2016-gammarus](https://cloud.githubusercontent.com/assets/22114100/18409354/06c2d100-7756-11e6-9f3c-186fadc57d3a.png)

**Comment by nagabhyru** [comment]
Yes I to have the same problem. If we unable to start the work due to errors or "Another worker accepted". the work in the icon is not disappearing and not getting new jobs. 

@gammarus64 try reinstalling the extension. Then it will work.

**Comment by RnkSts** [comment]
Same problem here... This bug happen to me every time the message "_Ops, another worker ..._" appear. I need to reinstall the extension after that, to continue receiving jobs. Hope this will be fixed soon :hammer:

**Comment by nagabhyru** [comment]
@RnkSts Close the browser and reopen it. Then it will work fine again.

**Comment by RnkSts** [comment]
@nagabhyru That's a good idea, Thanks,  but I have another important tabs opened in the same browser, so is easier to me to just reinstall the extension :disappointed: . Thinking on separate work in different browsers now.

**Comment by uqbiii** [comment]
Disable/Enable extension instead of closing browser, that works perfectly. I am doing the same thing.

**Comment by RnkSts** [comment]
@uqbiii Most of the time, even disabling and re-enable, the extension still in the same state. So i need to click the trash icon next to it :disappointed:.

**Comment by sizika66** [comment]
Hi! What about this: WOR icon is red. It should be green, right?
![extens4](https://cloud.githubusercontent.com/assets/16043846/18409671/a684ed76-774d-11e6-8e42-de5e4fd00be5.JPG)
![extens](https://cloud.githubusercontent.com/assets/16043846/18409674/a68911c6-774d-11e6-837e-9c710c2a9d98.JPG)
![extens2](https://cloud.githubusercontent.com/assets/16043846/18409672/a6857e26-774d-11e6-9d06-bc0c25a7d488.JPG)
![extens3](https://cloud.githubusercontent.com/assets/16043846/18409673/a688c7d4-774d-11e6-8e26-12698f5c2c7b.JPG)

**Comment by uqbiii** [comment]
@RnkSts You are right, but after disbale/enable it takes only 3-5 seconds to start working. btw Working fine here.

**Comment by ellmirr0001** [comment]
The extension works fine for me, didn't encountered any error messages so far.

**Comment by nagabhyru** [comment]
Extention is working fine than its previous version but it has only one issue. When we get an error (Something bad, No VM's...) or missed a job (due to "Another worker....") it did not go back and pool for the new job.  It stuck there. Rest of the things are fine.

**Comment by Paolick** [comment]
Hello, I am presenting the same problem, when an error icon is with the word work and does not allow me to receive more task occurs, wrote a message from my account / help section, I imagine and some will have done well, any new'll call for now uninstall and install the extension to avoid having to close the browser.
Thank you

**Comment by Paolick** [comment]
anyone know if even say the word I can keep getting work task? or while work say I can not get any work, as there are people leaving them in red and one in green, one knows the reasons.
Thank you

**Comment by sweeneyapps** [comment]
Temp fix for this...    if WOR still on after u re not working.   You'll have to disable and enable the extension.    Then it will start polling again.    This is good until next rolling update.

**Comment by AmaiaKao** [comment]
The extension doesn't stay green since the new update was released. It goes back to grey after few seconds. Uninstalled/reinstalled, logout/login account, disabled/enabled on extension tab, still the same result. :(

**Comment by shosti** [comment]
Closing as dup of #508.
