### ISSUE TITLE
Still polling too soon. (Too many Request)

### ISSUE THREAD

**Issue by sweeneyapps** [rainforestapp/tester-chrome-extension#505]
it is still getting "Too many requests" error (400), after every 2 requests.

**Comment by uqbiii** [comment]
Just checked a few seconds ago and it's working the same way as before, nothing resolved and a few new problems added into system. If DEV's don't mind, they need some training the same way as we(testers).

**Comment by sweeneyapps** [comment]
@uqbiii   I'm not worried.   Thing will get better.   2.0 is much better than 1.2.

**Comment by uqbiii** [comment]
@sweeneyapps I just used stopwatch to check the interval for new request and it was 20s, but a few days ago it was set to 25s if i am not wrong, maybe that is the reason for Too many requests" error (400).

**Comment by sweeneyapps** [comment]
@uqbiii yes, I'm aware of 20 seconds..   RF extension 2.0 handles polling differently because when a tester is working, it stops polling until they finished working.   So I can assume that they planned to lower the server's polling rate for this.  More likely, they will add API to check server's polling rate so extension will be aware of server's polling rate.

**Comment by shosti** [comment]
@sweeneyapps curious, how are you seeing the "Too many requests"? Is it in the console? (It should be ignored in the UI--if not let me know.)

@uqbiii Rate limiting is an unfortunate necessity for our current work assignment system; a new work assignment system will be rolled out over the next month or so that should make it unnecessary.

**Comment by sweeneyapps** [comment]
@shosti it is in the console (network tab) via managing extension then "Inspect views: index_prod.html"

**Comment by JPierreS** [comment]
It appears to be still hard limited at around 2:55 - Setting polling at 28s should fix this.
Any setting that is not 1:1 with API will waste requests, and during this wasted cycle you cannot get jobs.

**Comment by MarinaCec** [comment]
The message failed to fetch is coming when we are inactive??? I don't understand it yet
