### ISSUE TITLE
More time for extension to be ON

### ISSUE THREAD

**Issue by djux90** [rainforestapp/tester-chrome-extension#506]
Extension is too short turned on. I think it would be better if extension can be on for 10 min.

**Comment by playpin** [comment]
Gray leaf is of no use 
Red "Off" was more visible

**Comment by Genesis2015** [comment]
@playpin Yeah, it's hard to define if it's grey or green. Red and green is better combination for me  :)

**Comment by sweeneyapps** [comment]
https://github.com/rainforestapp/tester-chrome-extension/issues/522
