### ISSUE TITLE
doubts could help with the extension

### ISSUE THREAD

**Issue by jacobcortes** [rainforestapp/tester-chrome-extension#507]
Recently I change the extension.
I wonder a few things
If someone could help

What is the meaning of this?
For the word (WOR) is red in my browser and other users is green see in (https://github.com/rainforestapp/tester-chrome-extension/issues/504)
<a href="http://es.tinypic.com?ref=fp9oco" target="_blank"><img src="http://i66.tinypic.com/fp9oco.png" border="0" alt="Image and video hosting by TinyPic"></a>         <a href="http://es.tinypic.com?ref=2eeieyu" target="_blank"><img src="http://i65.tinypic.com/2eeieyu.png" border="0" alt="Image and video hosting by TinyPic"></a>

When a new hit arrives and ends in any of this you messages
	Another worker accepted the job before you! It doesn't look like there is any more work for any of our hits; please try again shortly - you can refresh this page, or close and wait for a new job.

	There are no virtual machines currently available. Please retry in a few minutes.

	You have reached the maximum number of unsubmitted assignments. 

	something bad happened.

	Too many requests.

How long the extension mode (WORD) before returning to its initial state?
<a href="http://es.tinypic.com?ref=fp9oco" target="_blank"><img src="http://i66.tinypic.com/fp9oco.png" border="0" alt="Image and video hosting by TinyPic"></a>              <a href="http://es.tinypic.com?ref=28gwbx2" target="_blank"><img src="http://i64.tinypic.com/28gwbx2.png" border="0" alt="Image and video hosting by TinyPic"></a>

During the time that this extension mode (WORD) are not assigned new job?

What is the period of inactivity for the extension is off?
 <a href="http://es.tinypic.com?ref=28gwbx2" target="_blank"><img src="http://i64.tinypic.com/28gwbx2.png" border="0" alt="Image and video hosting by TinyPic"></a>      <a href="http://es.tinypic.com?ref=2l8btkp" target="_blank"><img src="http://i67.tinypic.com/2l8btkp.png" border="0" alt="Image and video hosting by TinyPic"></a>

I would appreciate any information

**Comment by sizika66** [comment]
Hi! I have the same issue. Hi! It can not be right: WOR icon is red. It should be green, right?
![extens3](https://cloud.githubusercontent.com/assets/16043846/18412558/ddeffdde-7791-11e6-810e-f3a2f2be826f.JPG)
![extens](https://cloud.githubusercontent.com/assets/16043846/18412559/ddf3e908-7791-11e6-8627-b4809a824663.JPG)
![extens2](https://cloud.githubusercontent.com/assets/16043846/18412557/ddeff384-7791-11e6-88a5-f3278a48fa02.JPG)

**Comment by sweeneyapps** [comment]
@jacobcortes  I'll explain how it works.  

WOR is WORK.  Chrome cuts off the "K".  

When Icon picture is Green:  you are connected and waiting for work.
When you get "WOR":  you are working!!!
When Icon picture is Gray:  you re not connected.

The extension will go Gray (OFF) if you are away from the computer, more than 3 minutes.  (that can  be changed if RF decided to increase the idle setting)   Hopefully 5-10 minutes.   We will see.

I posted on https://github.com/rainforestapp/tester-chrome-extension/issues/508 
with suggestion on how to fix the "WOR" bug.

**Comment by jacobcortes** [comment]
Paul, thanks for the info
You have any idea of red or green in the word (WORK)
will have some meaning

**Comment by marius11** [comment]
@jacobcortes @sizika66 Update your Chrome browsers.

**Comment by sizika66** [comment]
@marius11 thank you! I can not update my Chrome browser because I'm still using windows XP.

**Comment by sweeneyapps** [comment]
@jacobcortes Nothing inside extension coding does the red color on "WORK"  It's probably Chrome bug.

**Comment by sweeneyapps** [comment]
@shosti  I tested on my test extension and what I discovered that red is the default color when text is set without setting color.

**Comment by shosti** [comment]
The red background thing must be a bug with certain versions of chrome.

Also annoying that some versions only display 3 characters for the badge. I'm open to suggestions for a message that's clearer than "WORK" (we considered "YES" and "IN P", for "in progress", but they seemed less clear).

**Comment by sweeneyapps** [comment]
@shosti  how about "WRK"..

**Comment by sweeneyapps** [comment]
btw "work" will show.

**Comment by sizika66** [comment]
@shosti thank you!

**Comment by ikjt** [comment]
"JOB" may also be fairly clear and it shouldn't cause the cut off issue.
