### ISSUE TITLE
Today I start claim profile, but it blocked, can anyone help me ? 

### ISSUE THREAD

**Issue by mueller01** [rainforestapp/tester-chrome-extension#509]
![start claim](https://cloud.githubusercontent.com/assets/22122367/18413438/3f1fb19a-77d2-11e6-9485-17104f8c189f.png)

**Comment by helloworld111gh** [comment]
You can know the reason of the block by reading the block reason.
Any particular reason you are blocking part of the block reason with
another window? Are you trying to hide something?

**Comment by mueller01** [comment]
![start claim 2](https://cloud.githubusercontent.com/assets/22122367/18413744/4bbd1442-77dc-11e6-8948-e8fe221ee739.png)

Reason for block: You have failed to follow instructions on too many jobs
But I did not do any job with this profile ?
When I claim it already blocked ?

**Comment by sweeneyapps** [comment]
this is wrong place to talk about it.     On your profile page, click Help and submit your support ticket.    You'll hear from Rainforest as they catch up with all support tickets.

good luck!
