### ISSUE TITLE
You're not logged in. You don't seem to be logged in to Rainforest, click here to go to your profile and login

### ISSUE THREAD

**Issue by cockfutu** [rainforestapp/tester-chrome-extension#510]
Dear RainforestQA admin,

Please help me to set default to my ACTIVE profile.

I have issue with new version of Tester Notifier yesterday.

I logged in to RF portal, it show my OLD profile: 
16458c0b-b0d3-4e4c-8baa-44b6aa68b65c (linking Neobux channel). This profile  is blocked 2 years ago.
![image](https://cloud.githubusercontent.com/assets/22123348/18413959/34172fba-77e3-11e6-9607-c29d6ceca4a2.png)

But I have ACTIVE profile e3633c09-f30f-40a0-b475-7119c0999a55 linking CrowdFlower Elite channel - Contributor ID 34689758). This profile is ACTIVE and I'm working well and have about 5000 total completed jobs.

![image](https://cloud.githubusercontent.com/assets/22123348/18413957/2874b9de-77e3-11e6-9731-7991b82f77e0.png)

![image](https://cloud.githubusercontent.com/assets/22123348/18414034/129dc71a-77e6-11e6-8b5f-75ce30ce42a2.png)

I cannot do RF jobs from new version appear yesterday with this issue. When i click grey icon, message appear:
You're not logged in 
You don't seem to be logged in to Rainforest, click here to go to your profile and login

Please help to fix my problem.

Many thanks

**Comment by JrRandy** [comment]
Once you are blocked, it is against the TOS to create a new profile.  User:  34689758 should never have been created.  Prehaps Rainforest caught this and have disabled your 2nd account?

**Comment by helloworld111gh** [comment]
we can't help you with this, you must contact rainforest support with the following details:
1. your old profile link
2. your new profile link
3. your contrib. id's
@kristen-allie

**Comment by qpPykT** [comment]
The old skeletons in the closet...

**Comment by cockfutu** [comment]
ticket is submitted but no answer from RF!!!

perhaps they are so busy to solve ton of ticket.

Waiting ....

**Comment by sweeneyapps** [comment]
yeah its weekend..   it ll take awhile.

**Comment by cockfutu** [comment]
Just read Frequently Asked Questions
https://github.com/rainforestapp/tester-chrome-extension/wiki/Frequently-Asked-Questions

My case in here
"
I can’t sign into the correct portal profile.

Each account on CrowdFlower is tied to one Rainforest Portal account. You may have the same email address tied to multiple accounts (this behavior has been fixed), so you’ll have to log in to one of the accounts and change the email address associated with it. If you’re not sure what your email address is on the account, you can see it while doing a job on the respective CrowdFlower account.
"

Hope they'll fix soon.

**Comment by qpPykT** [comment]
@cockfutu 
This would be your case if you did not had previously blocked account.
