### ISSUE TITLE
Suddenly Connection lost

### ISSUE THREAD

**Issue by RnkSts** [rainforestapp/tester-chrome-extension#512]
Well, I lost all the progress in this job, restart it is something annoying because it's a 'registration' job, so I sure get the "email already taken" or something, so I restart it to report that I can't continue in the registration step, because of this. Something that is _useless_ for both the tester and the costumer I guess.

The point of this is report this cases, a tester can lost to much work, in the case of a 30+ steps job. And we do not have an explanation for these errors (_or yes?_). So I have to say that we need an optional 'button' or something in this cases (_something like get new data to enter after restart_), because we can't click "_NO_" and finish directly.

The VM suddenly lost connection,  It was working perfectly before this, and the "**IO Error**" appear after clicking the reconnect button.

![screenshot_3](https://cloud.githubusercontent.com/assets/20311303/18414443/e79cc21e-7795-11e6-87b4-7daf79001294.png)

**Comment by warpten09025** [comment]
For me , i would click reconnect button more times until the machine works again , or at least restart job.
