### ISSUE TITLE
'Work' in green box, though there is no work or work has been completed.

### ISSUE THREAD

**Issue by sakadu** [rainforestapp/tester-chrome-extension#513]
At the start there is a round green leaf icon when you start the browser.
Then when you get some tasks there is a green work box with a text 'work' appears over round icon.
![screenshot 2016-09-11 17 20 27](https://cloud.githubusercontent.com/assets/17096478/18417141/280b4f64-7845-11e6-8314-e34487a8d95a.png)

Then you either finish the task or get message 'No virtual machines are available' or similar.This work icon will never disappear.
You have to restart the browser to disappear it.

**Comment by janrit** [comment]
The same happens to me.

**Comment by tulko** [comment]
I was not so concerned with the "wor" when there is nothing. I would not know if remain so stuck "wor" will come new jobs.

**Comment by playpin** [comment]
New work will not come if "wor" is displaying 
remove n add the Rainforest extension (from manager)to get rid of "wor"

**Comment by sweeneyapps** [comment]
close this..  same topic on https://github.com/rainforestapp/tester-chrome-extension/issues/508

thank you..
