### ISSUE TITLE
How do the "Options" work

### ISSUE THREAD

**Issue by playpin** [rainforestapp/tester-chrome-extension#515]
When i click "options" in RF extension menu it redirects me to my profile page 
but there are no options on profile
Can someone help me with this

**Comment by nerdatwork** [comment]
[Rainforest Options for profile](https://portal.rainforestqa.com/profile/edit)

What exactly do you want to do ?

**Comment by sweeneyapps** [comment]
@playpin   the options on RF extension menu is new add-on to 2.0.   We planned to add sound notification option on the profile page.   RF have not updated it's profile page to support options yet.  It's in work.

**Comment by playpin** [comment]
Thank u
