### ISSUE TITLE
New Version of the Tester Notifier...... 

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#517]
WORK BUTTON STUCK, dont get a job, and the app offline or online, say work....

![1 worl stuck](https://cloud.githubusercontent.com/assets/19192312/18420005/48d3834c-7836-11e6-9c91-3f5c7cd73998.jpg)

**Comment by nerdatwork** [comment]
There is already a thread about this #508 post your reply there and close this thread.
