### ISSUE TITLE
Taking screenshots is slow

### ISSUE THREAD

**Issue by nuevao** [rainforestapp/tester-chrome-extension#52]
menu of steps, slow.

step house lasts about 5 minutes, not because it is very long activities, but because every time you want to go to the next step:

Selection is approximately 30 sec remains white.
Then a message appears stating that "screenshot has failed, try again" appears. This situation can be repeated up to 3 or 4 times until it passes the following instructions.

I imagine this usually occurs when there are too many running tester.
![menulento](https://cloud.githubusercontent.com/assets/16979522/12861224/112335d6-cc34-11e5-8ed2-29c6b6ec149d.JPG)

**Comment by ukd1** [comment]
thanks @nuevao 

@jbarber @gallois we should really move the screenshots to go direct --> vcontrol, not proxy via vmanager. Thoughts?

**Comment by helloworld111gh** [comment]
Can't you guys just do a video of the terminal while testers are working,
and note when the step buttons are pressed?

You guys can remove cheaters easier and test authors can know how real
humans navigate their site (easy way to make the authors pay more $$$)

**Comment by marius11** [comment]
@helloworld111gh Just image the bandwidth usage if you were to record many concurrent testers...

**Comment by ukd1** [comment]
@nuevao @helloworld111gh we're actually working on that right now, which will make screenshoting much easier.

**Comment by yoges9** [comment]
same as mine was with 26 step total of 29 but failed to take screenshot and conection out, terminal was very slow waste my one hour.

**Comment by jbarber** [comment]
@yoges9 did you resubmit the response? This retakes the screenshot.

**Comment by yoges9** [comment]
time was out bcauze of very slow terminal and was not able to submit

**Comment by jbarber** [comment]
I don't understand. How does the terminal being slow (by slow I guess you
mean it was laggy?) prevent you from submitting?

On 12 February 2016 at 09:09, yoges9 <notifications@github.com> wrote:

> time was out bcauze of very slow terminal and was not able to submit
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rainforestapp/tester-chrome-extension/issues/52#issuecomment-183244238>
> .
>



-- 
Jonathan Barber

**Comment by marius11** [comment]
I haven't had any problems with the terminal being slow, but in the last week, taking screenshots was very slow or impossible. For example, I received a hit testing the tester's guide modal, and moving to the next step took 10-15 seconds before receiving "Failed to take screenshot".

After several tries, the message would appear the next second I clicked a button. I had to refresh the whole hit to have it completed and submitted.

**Comment by yoges9** [comment]
slow means late responsive, page were opening very late..

**Comment by warpten09025** [comment]
There are two types of "slow" :
1/  Failed to take screen shot -> prevent popup on the page -> press yes/no again about 20 times to get to the next step
2/ Laggy terminal , mouse move very slow and sometimes it freeze .

**Comment by warpten09025** [comment]
"Just improve bandwidth and connection speed" ( if you guys can )  then everything will be done :dancers:

**Comment by JPierreS** [comment]
@helloworld111gh   They don't need to record video of our terminal session, what you are referring to already exists.  Through an admin view, they can see your full interaction inside the terminal on a step by step basis, and can easily spot those who just click buttons vs. those who actually follow instructions and interact, and could spot those who do not interact properly or tamper with objects on the site (example, is a step asks if switch is off and it is on, but user manually turns it off before taking screenshot.).

**Comment by masterpeing** [comment]
same jpierres , iam having low terminal speed and fail screenshoots multiple times.... thanks for share your experience.
