### ISSUE TITLE
any can help me ?

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#521]
Hello,
This job was rejected because you answered "yes" to some steps, but we detected that you didn’t follow the instructions exactly:

    Observe the Page
      Do you see some Snacks selected along with their Price and quantity??

    Observe the Page
      Do you see  "VI ...1000"  under "Payment info"?

    Observe the Page once its refreshed
      Under "Shipping address" section, do you an address starting with  "Test Membership" , and the first line of the address starting with  9775 Pascale Curve ?

You should never answer a step without performing the instructions. This will always result in a rejection. I hope this helps!
Regards,
![i check that](https://cloud.githubusercontent.com/assets/19192312/18422383/408af274-7868-11e6-919a-0e46d09e72f8.jpg)

**Comment by JPierreS** [comment]
Answering YES even if the answer is correct is not enough.  If you answered too quickly  / just clicked YES, it is hard to prove to an admin that you followed instructions.  When an admin checks a job they don't only check the answer you clicked on but your interaction with the terminal.  Let the mouse cursor be your eyes, even if you know what you are seeing take your time on these steps, move your mouse to each respective area.  This will provide solid proof that you did what was asked - an admin checking your job would see that there is mouse movement activity around those areas and acknowledge that you did actually look and not just click yes.  This goes for any hits, if just clicking YES but no mouse, key, click, etc activity associated with it, will more likely lead to getting your job rejected.

**Comment by zfonck123** [comment]
but that is soo bad, if i see, .. for the news tester, its normal take more time, but for old teste who doing more of 4000jobs. doing jobs more fast.

**Comment by JPierreS** [comment]
@zfonck123  Indeed, but the age of the account is NOT taken into consideration, your work is judged by whether you are following the instructions exactly and properly interacting with terminal as explained above.

For example, when I complete hits, I use my mouse cursor as my eyes - When I am asked for instance on a hit to click "add to cart" then check the cart icon area if the number increased, I move my mouse pointer to the cart area and hover around the number that increased.  When an admin checks that job, they would see that a click was registered at the right position AND that mouse moved to the cart area, so it proves that I followed instructions before clicking YES.   Correct answer and proper interaction = job well done.
No matter if a tester is new or 3 year tester the same applies for all.

**Comment by zfonck123** [comment]
i think is a unfair rejection... but now  them , i will take more time to do jobs  :( i dont like this rejection T_T

**Comment by JPierreS** [comment]
@zfonck123 :  You may have done your work correctly by looking at the area in question but you need to provide proof in the form of interaction, it's not just a question of speed but also your interaction with the site, even if it is obvious :)

**Comment by zfonck123** [comment]
thx.

**Comment by qpPykT** [comment]
@zfonck123 
This is called karma.
