### ISSUE TITLE
@pscohn All are running well now. Thanks..

### ISSUE THREAD

**Issue by myIssue** [rainforestapp/tester-chrome-extension#523]
But as an OLD MEMBER, i still need job starter to get my bonuses.
My ticket ID : #16603

Thank YOU for your help.
Regards,

**Comment by mueller01** [comment]
My ticket ID : #16684
My ticket ID : #16685
Thank YOU for your help.

Regards,

**Comment by marius11** [comment]
This thread is usually used for discussing about the extension.

**Comment by myIssue** [comment]
Right here waiting...
