### ISSUE TITLE
Sign In error in Extension...

### ISSUE THREAD

**Issue by farookabubakker** [rainforestapp/tester-chrome-extension#526]
When I click the Grayed Icon in extension, it turns Green. But within 5 second it turns back to gray and signed out. Please fix this issue guys...

**Comment by shosti** [comment]
It would be useful if you could do the following:

1. Go to chrome://extensions/
2. Enable "Developer mode"
3. Click "Inspect view: index_prod.html" for the plugin (or something similar)
4. Look in the console for error messages and post them here if you see any

**Comment by pvenkat7** [comment]
i also have similar situation. when follow your instructions. it says 

5 https://bouncer.rainforestqa.com/1/testers/f60f09c5-b553-44d0-8ed1-f7c049fb…22email%22:%22prk.infos@gmail.com%22,%22id%22:%22103174993915567266658%22} Failed to load resource: the server responded with a status of 403 ()

**Comment by pvenkat7** [comment]
i also have similar situation. when follow your instructions. it says

2https://bouncer.rainforestqa.com/1/testers/f60f09c5-b553-44d0-8ed1-f7c049fbb421/work_available?info={%22email%22:%22%22,%22id%22:%22%22} Failed to load resource: the server responded with a status of 403 ()

Please help me

**Comment by shosti** [comment]
hmmm it looks like there's a problem with requiring CAPTCHAs. If you follow one of those links directly do you see a CAPTCHA page?

If that does fix it, I'll try to look into an automated solution.

**Comment by khristianjose** [comment]
I have the same problem too.

**Comment by pvenkat7** [comment]
No! when i click it redirects to a page texted with {"work_available":true,"url":"https://tester.rainforestqa.com/tester/...............................}

**Comment by khristianjose** [comment]
i have only the leaf icon and when i activate it it turns off after like 5 seconds

**Comment by khristianjose** [comment]
https://bouncer.rainforestqa.com/1/testers/994f0175-057b-4e4c-bc43-414fe191b42f/work_available?info={%22email%22:%22%22,%22id%22:%22%22} Failed to load resource: the server responded with a status of 403 ()

**Comment by khristianjose** [comment]
handlePolling.js:39 GET https://bouncer.rainforestqa.com/1/testers/994f0175-057b-4e4c-bc43-414fe191b42f/work_available?info={%22email%22:%22%22,%22id%22:%22%22} 403 ()

**Comment by shosti** [comment]
what version of chrome are you running?

**Comment by khristianjose** [comment]
Versión 53.0.2785.101 m (64-bit)

**Comment by shosti** [comment]
@khristianjose can I get your contributor ID? Would help debug the issue...

**Comment by pvenkat7** [comment]
53.0.2785.101 (updated version) 

When i click on above link it redirects to a page with " {"work_available":false,"url":""} " 
If i reload that page until "work_available":true " i can use that to get work. But my extension not able to do it automatically. 

My contributor ID is 33801308

**Comment by khristianjose** [comment]
ID: 34040816

**Comment by khristianjose** [comment]
Any update about?

**Comment by khristianjose** [comment]
Yes im 100% sure, it turns green for a few seconds but then it turns gray again

**Comment by shosti** [comment]
OK this is turning out to be rather tricky to debug, so I'll need some help if that's OK. In the console (following the instructions above), put in the following: `DEBUG = true`. You should see some output; I'm particularly interested in the "worker" and "socket" ones (if you need to click an arrow to see more info from them, do).

Unfortunately the data will include some authentication stuff so you shouldn't post it here. But if you can take a screenshot and email it to emanuel@rainforestapp.com that would be very helpful.

**Comment by khristianjose** [comment]
Already sent the image to your mail.

**Comment by khristianjose** [comment]
@pscohn Any idea about this error? please.

**Comment by shosti** [comment]
@khristianjose I'm still looking into it, I think I'll need a few more things to be able to debug properly. Thanks for your patience!

**Comment by shosti** [comment]
@khristianjose sorry to make you do this, but would you mind following the debugging steps again and sending me another screenshot? Also make sure you click the extension a few times before sending it.

**Comment by khristianjose** [comment]
Check your email.

**Comment by shosti** [comment]
OK I think I found the problem--thanks for your help! Fix should be shipped soon.
