### ISSUE TITLE
The 'WORK' on extension icon may not disappear when new tab opens for work but you do not get work.It'll disappear when you finish the task.

### ISSUE THREAD

**Issue by sakadu** [rainforestapp/tester-chrome-extension#528]

**Comment by nerdatwork** [comment]
There is already a thread about this #508 . Dont make duplicate threads for same issue

**Comment by luis1leal** [comment]
I spend something similar.
And to work again I completely close the browser.

**Comment by JPierreS** [comment]
This is normal behaviour and intended.  Whenever you receive work, the extension will go into standby mode and stop polling / checking for work, as you can only work on one instance at a time.  Once you complete the hit and submit, and once the work is flagged as received, "WOR_" will disappear and the extension will resume polling.   In regards to receiving no_vm or another worker link, you can just refresh that until it converts to a hit, and a fix for the stuck work mode without a live hit is something they are fixing.   A fix for the stuck work mode without a live job is to toggle disable/enable in your extension panel, this will reset the ext.  (not from the actual extension leaf itself).
