### ISSUE TITLE
No VM's error all the day

### ISSUE THREAD

**Issue by nagabhyru** [rainforestapp/tester-chrome-extension#529]
Again we are getting "No VM's" error. In past this error was there but in recent times this was solved. Again today I am getting this error for almost all the jobs. 

I think we are getting this because of extension.

**Comment by Taruga** [comment]
"No VM´s..." , "Too many requests...", websites not redirecting/loading webpage, etc.... All working fine, lots of free time to myself  today ;)

**Comment by nagabhyru** [comment]
I think rainforest is testing its error messages today.

**Comment by hunt40** [comment]
i got every possible error today amazing day for who like to spend their time for NOTHING,great job once again

**Comment by Paolick** [comment]
recently i have a problem with VM and the following test

"Connection Error
dial tcp 40.84.156.68:443: i/o timeout
We were unable to connect to the website. If you are a tester, please fail this test.
Machine ID: 18557157

Anybody can help me?

**Comment by Paolick** [comment]
Hello, I recently has been presenting an error in jobs, with respect to the VM as it never loads the page and generates the following error me.

"Connection Error
dial tcp 40.84.156.68:443: i/o timeout
We were unable to connect to the website. If you are a tester, please fail this test.
Machine ID: 18557157"

Do not know how to fail the test, I've been closing the tab but do not think is the right way, if they could help me really appreciate it.
Thank you

**Comment by begsoon** [comment]
@Paolick That's error message is on consumer end.You should report it with ''Connection error''.

**Comment by Paolick** [comment]
Really thanks you for your answer, for the next time i apply

**Comment by uqbiii** [comment]
Few minutes ago, i was working on PaperLessPost and then every error appears which appears during a HIT at 9th step. How bad these steps are, can't explain in words 😞 .

**Comment by nagabhyru** [comment]
One new error I got today- "Could not get chrome machine". After reloading the job couple of times I got the same error and end with "You have requested this job too often. Please return the work."

**Comment by Paolick** [comment]
sorry to ask, but I can not button or otion that says '' Connection Error ''. where I find this option or button?
Thank you

**Comment by nagabhyru** [comment]
So far I got following error
1, No VM's
2, Something bad
3, Application error
4, Unable to perform action in the machine.
5, Unable to fetch chrome machine- end with "You requested this job too often."
6, Unable to fetch office 2013 machine-Same ending.
7, Another worker accepted.... (Not an error but got couple of times)
8, An IO error.
9,Too many requests.

**Comment by Zunami007** [comment]
it is very annoying getting the whole day the "No VM" message, and it is also annoying to have to disable and enable the extension after VM error happens .. Today I can refresh this tab twice, then "Too many requests" appears. 
I turn this thing OFF now, for me it is just a timewaste at the moment

**Comment by uqbiii** [comment]
All error are working at their best. HATS OFF 👎.

**Comment by regi92** [comment]
![download](https://cloud.githubusercontent.com/assets/21320924/18445243/9409f218-7914-11e6-8425-1cfefa778f39.png)

**Comment by Taruga** [comment]
New extension available V2.0.2

**Comment by Paolick** [comment]
corrections have this new version?

**Comment by JPierreS** [comment]
BTW, the NO VM errors have nothing to do with the extension.

Yes indeed I have seen this error far more frequently it is getting worse.  I see this day and night, even with only 400 testers online.  It's now a competition between another worker and no vm, and NO VM is coming back with vengeance lol - but the good news at least no worker and no vm can both be refreshed until they convert to hits - sort like second chance ;-)
