### ISSUE TITLE
Too Many Oops! Messages Since 04 Feb 16

### ISSUE THREAD

**Issue by Deepak0988** [rainforestapp/tester-chrome-extension#53]
On an average, I was able to complete about 8-10 tasks everyday (Mon-Fri), but after 04 Feb 16 (When server got down), There are a lot of Oops! messages and the average hits for me went down to 1-2 per day. Is there any Issue with the extension ???????? My worker ID is 32687648

**Comment by akshithaaravi** [comment]
Me too, I have had only one hit after the outage, all I am getting now is ooops...

**Comment by hunt40** [comment]
same here ,today i got my first hit after 3 day and its zenefits on mac and pages not loading.

**Comment by Genesis2015** [comment]
Same here :(

**Comment by normensstouns** [comment]
Same here.

**Comment by GreekGuy** [comment]
Same here and not only that, i get so many Server [errors](http://prntscr.com/9ziupf) and application [errors](http://prntscr.com/9zivh0) and it takes so much to load..

**Comment by ukd1** [comment]
@GreekGuy thanks; when you get these it's super helpful if you can record the url and paste here, so we can track it back and fix it. /cc @pscohn

**Comment by qpPykT** [comment]
I caught only two tasks today. So bad :(

@ukd1
Got the error "ERROR: Something went wrong on our server, sorry about this Please reload and try again.."
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cxd6cb75-0c00-42cc-88c3-c3f66fb5aa64&browser=any&hitId=4527956&sig=e8cccd6a4475734bfe2d4cc5453f944a3c42e060a2d716fb9ee6b239ea0ca4d9&turkSubmitTo=%2Fthanks&workerId=31275106

**Comment by marius11** [comment]
@ukd1 Here are a couple of URLs:

- https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx458df6-4fa7-4827-9d23-df9302df5d8b&browser=any&hitId=4473732&sig=849d270bb7999324df245111b31ce1e58c2205184cafd2a5d4a32a9648abbc03&turkSubmitTo=%2Fthanks&workerId=12160415
- https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx9f7faf-a5db-4f6f-9f56-d83fd193340c&browser=any&hitId=4401683&sig=d8c5cd9dbf6455a53f2471c31097cd9171d31f761ceb53465232c1431f1b3ae9&turkSubmitTo=%2Fthanks&workerId=12160415

**Comment by helloworld111gh** [comment]
Getting large amounts of app errors and screenshot errors.
This problem seems to affect all URLs, so I'll give me worker ID: 12219174

**Comment by GreekGuy** [comment]
Application error here [link](https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx6afb77-29e1-4903-b0c9-8fba81c21e2f&browser=any&hitId=4620827&sig=802a337200cecf638a11c4a2fedda8547ca8e6d7300cec0a34496cf40944d4d3&turkSubmitTo=%2Fthanks&workerId=28212973)

[screenshot](http://prntscr.com/a0pbqb)

**Comment by RezwanulHaque** [comment]
Same here, not getting task like before, If get, Ooops ........is coming-
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cxffbecd-279c-425b-9da3-6317b5431120&browser=any&hitId=4412020&sig=ba7542d2ef9455a57de3f3631510cd914193655eac04390b13430a59fc2df7d2&turkSubmitTo=%2Fthanks&workerId=31933957

**Comment by marius11** [comment]
I can post more links if it helps because this issue is still present. I'm getting hit after hit and they are all Ooopses or server errors.

**Comment by hunt40** [comment]
this last hour nothing but ooops and couple of server errors,then i find the solution and turn off the plugin otherwise i will lose my sanity.

**Comment by manishflyboy** [comment]
same here ,today i got my first hit after 3 day and its zenefits on mac and pages not loading.

**Comment by Sateesh85** [comment]
Today I got Ooops messages. one of them below 

[Link Here](https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx2947df-f361-4bbe-8acb-56e3a3e43530&browser=any&hitId=4623384&sig=cb30456ac5adbdbe8ea089cb1d867543fdcf94d2a7276c9c43b288361c99a5b4&turkSubmitTo=%2Fthanks&workerId=34784545)

**Comment by masterpeing** [comment]
+1 same here

**Comment by nerdatwork** [comment]
Covered in #22 Please check

**Comment by manishflyboy** [comment]
getting too many oops msgs.
