### ISSUE TITLE
The word "WORK" still there after the job finished

### ISSUE THREAD

**Issue by bilelmz** [rainforestapp/tester-chrome-extension#533]
After I finish the job, "WORK" still on the extension icon.
I have to deactivate the extension and reactivate it, so this word disappear.

**Comment by shosti** [comment]
The WORK indicator will stay until the previous job has been fully processed (you can't get more work until that's done in any case).

Closing for now; re-open if you finish a job and the WORK indicator stays on for an unusually long amount of time (> 10 min).

**Comment by djux90** [comment]
I have that problem when i got message no virtual machine... or another worker...
Chrome is updated. And i have verry little jobs since extension updated. I hope they will fix that soon

**Comment by qpPykT** [comment]
There was new update today 2.0.2

**Comment by uqbiii** [comment]
@qpPykT Thanks for the info, just installed now, let's see how it's different from 2.0.1.
