### ISSUE TITLE
Extension opens many tabs.

### ISSUE THREAD

**Issue by qpPykT** [rainforestapp/tester-chrome-extension#535]
Extension opens many tabs. Until the hit has not been caught.

**Comment by uqbiii** [comment]
4 in 2 minutes, Strange scenario.

**Comment by qpPykT** [comment]
@uqbiii 
I have 10 it's like a monster :)

**Comment by djux90** [comment]
yea, me to. But finaly got one work :D atleast they trying to fix it :D
![adasdsasd](https://cloud.githubusercontent.com/assets/20422665/18450742/7dd7817a-7934-11e6-83fe-7faeb45b26dc.jpg)

**Comment by shosti** [comment]
To clarify: are these for multiple cases of failing hits, and then one for a successful hit? Or are there multiple successes?

**Comment by djux90** [comment]
for me it is multiple cases of failing hits, and then one for a successful hit. But still to many no VM or another worker and very little jobs

**Comment by shosti** [comment]
OK I"ll work on a fix.

**Comment by djux90** [comment]
ok, thanks. I think extension seems to be stabile very soon

**Comment by MarinaCec** [comment]
Extension opens many tabs is good, this is not a problem

**Comment by MarinaCec** [comment]
3 hours without any work, congratulations
