### ISSUE TITLE
After failing test: Extension 2.0.2 still get stuck in "WORK" mode...

### ISSUE THREAD

**Issue by HW71** [rainforestapp/tester-chrome-extension#539]
Hi all,

just updated to Extension version 2.0.2 but after working on a HIT and failing this one because of a bug the extension didn't switch back to polling. Instead it stayed in "WORK" mode and I had to disable and re-enable it.

The good thing, though: while typing this bug I got a new HIT and this time received "Another worker" message. After that the state switched back to "polling" mode! => Looks like one problem solved... ;-)

Thanks & Cheers, Erik

**Comment by HW71** [comment]
Just had to fail another test and this time the extension switched back to "polling" as expected...
Maybe the original issue was related to the fact that I saw multiple "Something bad happened" messages after I clicked the "No" button? I tried three times or so and finally was able to proceed with the "survey" at the end of the test. 

I will have a look on that in the upcoming days and if this doesn't happen again I'll close this issue...

**Comment by uqbiii** [comment]
I think this problem is now fixed, the problem you have faced is this that extension was showing "WORK" after submitting the work and this "WORK" appears until the HIT is not counted in your personal Portal. As soon as the extension turns to normal, means your HIT is counted(submitted) in portal.

**Comment by HW71** [comment]
Thanks for the hint... Yes, maybe that's the reason... But just to make sure: it took quite some time (we're not talking about "some seconds" or so). 

=> Closing for now, but will keep an eye on that... ;-)

**Comment by uqbiii** [comment]
Just found a good answer for your query, check #533 shosti's comment.
