### ISSUE TITLE
They are accepting new tester in rainforest?

### ISSUE THREAD

**Issue by lgiovanni** [rainforestapp/tester-chrome-extension#540]
I've been going to enter rainforest tester, and I econtrado who are not applying new tester, I wonder if anyone knows when to accept new since I am very interested

**Comment by ellmirr0001** [comment]
Rainforest has recently recruited new testers so until they need more. There won't be a job like that in CrowdFlower anytime soon.

**Comment by lgiovanni** [comment]
:( ok thanks really, i am really interesting but I will wait to rehire

**Comment by nerdatwork** [comment]
@lgiovanni Please read this: [Is Rainforest hiring new testers ?](https://portal.rainforestqa.com/?page=6)

If you are satisfied with the response I recommend closing this thread.
