### ISSUE TITLE
Restart Job button and disabling refreshing

### ISSUE THREAD

**Issue by ikjt** [rainforestapp/tester-chrome-extension#541]
@pscohn

Paul, first thanks for the Restart Job button. It's great to have it when something happens to the VM.

I have a concern about disabling refreshing, though. Here is the case that concerns me. It has happened quite a few times that after clicking Restart Job button, there is an error (something bad happened, couldn't get safari machine, too many requests, failed to fetch, application error etc). In case of any of those errors, the page gets redirected to the specific error page. That means we have no longer access to the Restart Job button. If we can no longer refresh those error pages, the jobs will get abandoned, sadly. I would have lost around 5 jobs yesterday/today if refreshing was not allowed. Luckily, thanks to the remaining refreshes, I was able to get a working VM and not lose the jobs.

Perhaps, it would be possible to display all those error messages on top of the testing interface page? So we wouldn't be redirected from that page and we still have access to the Restart Job button. In case of the screenshot, io, security errors, they are all displayed on top of the testing interface page, so perhaps that would also be possible in case of the errors that we'll encounter when clicking the Restart Job button?

Also, could you please clarify at what point is the job considered in-progress. There are times when the testing interface page is loaded and only terminal is still loading, but if the terminal fails to load, we are once again redirected to the error page (something bad happened,couldn't get ... machine, too many requests, failed to fetch etc). Is that already considered as job in-progress since the job was allocated to us, even though we were not able to start it? If it is, those jobs will also be lost if we can't refresh the error pages.

Thank a lot.

**Comment by JrRandy** [comment]
Agreed.  There are instances where the Restart and report leads to a forced refresh.  Forcing us to abandon those jobs does not seem like a fair direction to take.

**Comment by helloworld111gh** [comment]
Agreed, why not just give you back your old VM (or a new one if you don't have one/the old VM fails to load) if you refresh?

**Comment by JPierreS** [comment]
I agree, disabling refreshing job is a bad idea as it is required for instances where a restart job alone would not work, mainly for external errors or fatal errors that are not recoverable without restarting job by refreshing (external).

With this new change it means we will lose more hits.

**Comment by pscohn** [comment]
Would a restart button on the error page (the one that removes the vm and
all other content) solve this problem?

**Comment by JPierreS** [comment]
There is only one way to find out lol.

Perhaps the external refreshing method goes through a different process of resetting and linking back.
If the restart job outside the terminal behaves the same way I don't see how it will be any different,
though one would have to try to see if it works.  Sadly, lately, I have to restart job several times because I don't get a properly functioning terminal VM the first time - either the terminal is stuck in the Vagrant page, locked up, or a windows / mac loading page stuck even after minutes waiting, or a terminal without network or terminal that does not accept keyboard entry, in such instances the restart JOB is very helpful.  But for unrecoverable errors only an actual job restart resets things - if there was a button that resets the state the same way the hard refreshing does, then that would be good, and providing we get rid of this "job requested too often please return work" nightmare error lol.

**Comment by helloworld111gh** [comment]
It would help for most of the terminal issues, but there could be things
like tab/browser crashes that would require a refresh regardless.
Maybe allow only 1-2 refreshes would be the best solution.

**Comment by JPierreS** [comment]
1-2 ? 4 is not enough, often when we hard refresh we get something bad happened or no vm, concurrent workers, application error, cannot get a Chrome machine, or other similar errors, 1-2 would make it worse

**Comment by JrRandy** [comment]
As long as the restart button is available on the red bar error page, that should solve 99% of the reasons why a refresh happens.

**Comment by JPierreS** [comment]
They will test it on us one way or another so only then can we know if this is working on not  ;)

**Comment by Electroglitch** [comment]
Well there's this thing called Application Error and sadly nothing but regular refresh can't fix it,
also i'm pretty sure it's bigger than 1% :)

**Comment by ikjt** [comment]
Restart button on error pages should help in number of cases, but it wouldn't help in every situation.
With the significant increase in all kinds of errors in last month or so, as JPierreS mentioned, we now often have refresh two, three, four times to get a working VM. Would the restart button work with all the refreshes we need to do?

And then, as mentioned by others, there are application errors that happen quite often, also tab and browser crashes at times. Currently, we have a chance to recover from those and restart the job. But once the tab gets closed and we are not allowed to reload the job in new tab, or if we are not allowed to refresh the current tab in case of application errors or website offline errors etc, the job will be abandoned.
And I know in my case, the last thing I would want to do is to abandon a job. This happens too often already due to the server errors that we are not able to recover from (for example, something bad happened and right on the first refresh a message that you have requested the job too often). 

And just as I was typing this, I got Something bad happened error followed by an Application error. 

It does seems like as long as all those errors keep happening all the time, taking the refresh away will only increase the number of abandoned jobs.

**Comment by jackqc** [comment]
Today the following happened to me: job started, everything went find, after 2 two steps, there was a red error message "something bad happened" on an otherwise blank page, no way to use the restart job or reconnect button as the terminal the instructions and the buttons were all gone. I managed to recover my job by reloading the browser page, restarting the job. If reloading means would mean abandoning the job in future, I might as well have closed the tab.

**Comment by ikjt** [comment]
I have had the situation jackqc described above happen previously also. After getting the job and completing one or two steps already, the page suddenly gets redirected to the Something bad happened error page. Sadly, things like that happen too often recently.

**Comment by ikjt** [comment]
@pscohn

Thanks for the Restart Job button on the error pages, Paul. 
I have had to use it few times during the in-progress jobs when I got redirected to the Something bad happened error page, and it worked well.

Before closing this, I would like to clarify couple of things. 

Is the Restart Job button also present on Too many requests, Failed to fetch, Couldn't get _ machine pages? Luckily, I haven't seen those error pages during the in-progress jobs this and last week, but weeks before that, those error pages did appear also during the in-progress jobs.

Also, I assume there is nothing that can be done for the Application Error page? If we happened to get redirected to the Application Error page while using the Restart Job button, we have no other choice than to abandon the job after the refreshing has been disabled for in-progress jobs? Is that correct?

Thanks again.

**Comment by JrRandy** [comment]
I can confirm that the restart job button IS on the "Couldn't get _ machine" error (and works nicely I might add), and NOT on the "Too Many Requests" error page.  I have never seen the "Failed to fetch" so cannot provide any insight into that.

**Comment by ikjt** [comment]
Thank you, @JrRandy. That's good to know.

I have seen both "Too Many Requests" and "Failed to fetch" error pages in the past few weeks during the in-progress jobs, but maybe they are less frequent now since I haven't seen them this week and last week if I remember correctly. 

"Too Many Requests" error happens quite a few times every day when the extension opens a new job link, but that's a different situation and does not fall under in-progress job case, as I understand.

**Comment by ikjt** [comment]
Lots of Couldn't get _ machine errors today, but the Restart Job button has worked fine so far.
I will close this issue since the button is working on error pages. Thanks @pscohn :)
