### ISSUE TITLE
Invalid State

### ISSUE THREAD

**Issue by irj9** [rainforestapp/tester-chrome-extension#55]
Has any body else had this issue? The terminal takes an age to load, and once it does I am unable to paste the job url in the browser as every time I do, the terminal just replaces it with the original url. Again, again and again.
After several dozen attempts and much patience all I get is an error message on the terminal saying "Invalid State".
It's frustrating! I try to refresh the hit, but eventually I get the "This assignment has been completed"  so now I have a uncompleted hit on my record.

**Comment by RezwanulHaque** [comment]
It seems like when you were trying, in the mean time job has been done by someone.

**Comment by Deepak0988** [comment]
@irj9 this issue is mostly with the Terminal with safari browser. Next time if you have this issue try opening the url in new tab it will surely resolve your problem of url replacing.

**Comment by Gulbagh** [comment]
yes you have to start the hit within 10 minutes otherwise you will get invalid state....

**Comment by irj9** [comment]
> this issue is mostly with the Terminal with safari browser. Next time if you have this issue try opening the url in new tab it will surely resolve your problem of url replacing.

Thank you  @Deepak0988, I will try that :)
