### ISSUE TITLE
There was a problem with the Request problem Extension

### ISSUE THREAD

**Issue by khristianjose** [rainforestapp/tester-chrome-extension#553]
When i put the extension to work it says this and then when i click the message it says this and the extension stay on but im not getting jobs at all.

![sin titulo](https://cloud.githubusercontent.com/assets/17553414/18477747/bd58c404-799c-11e6-9ece-dd2bdfe4ed22.png)
![sin tituloeff](https://cloud.githubusercontent.com/assets/17553414/18477748/bd6047ce-799c-11e6-8056-077196ff813b.png)

**Comment by khristianjose** [comment]
@pscohn Any update about this error?

**Comment by khristianjose** [comment]
![eeee](https://cloud.githubusercontent.com/assets/17553414/18479866/9b4d2df2-79a4-11e6-80e7-2d55a98b4452.png)

**Comment by khristianjose** [comment]
@shosti

**Comment by gusttest** [comment]
I also still with the same error.

**Comment by shosti** [comment]
Have you tried clicking the notification?

**Comment by khristianjose** [comment]
![fffffffff](https://cloud.githubusercontent.com/assets/17553414/18482107/d6374c2e-79ac-11e6-8e04-8dc52ea28378.png)

**Comment by khristianjose** [comment]
That happens when i click the message.

**Comment by khristianjose** [comment]
I dont know but since you guys released that new plugin update there are too many errors that i cant even work, im stuck with this since saturday.

**Comment by shosti** [comment]
Unfortunately this is an issue with our CDN and there's not that much we can do about it other than notifying you. (The old plugin had exactly the same issue.) It will still keep polling and a certain percentage of requests should go through. If you try refreshing the page a few times you may get a CAPTCHA to fill out--unfortunately beyond that there's not a ton we can do on our side.

**Comment by khristianjose** [comment]
But i wasnt having those problems with the old plugin, why now i cant even get a single job, anything, its frustrating.

**Comment by shosti** [comment]
Really not much has changed w.r.t. CAPTCHA handling in the new version, so it's likely that the problem is network-related. Unless @pscohn has any ideas, unfortunately there's not much else that we can do.

**Comment by khristianjose** [comment]
I get this message when i click the notification, but sometimes i get true and a link, the link is the job that i should receive without opening that, i just done one job like that 
![sin titulo](https://cloud.githubusercontent.com/assets/17553414/18487112/fa2e78d6-79c1-11e6-9848-762b8c9f2c2b.png)

**Comment by khristianjose** [comment]
when i reload the page too much it shows this 
![sin titulo](https://cloud.githubusercontent.com/assets/17553414/18487285/a279ff6a-79c2-11e6-86ac-c3ac5706d57b.png)

**Comment by khristianjose** [comment]
If i follow that link i have the chance to get the job, the problem is that the process isnt happening well 
![sin titulo](https://cloud.githubusercontent.com/assets/17553414/18487440/443aa138-79c3-11e6-8cdb-292886e26969.png)

**Comment by shosti** [comment]
@khristianjose I understand that it's frustrating, but I think the best thing for now is just to dismiss the notification and let the plugin run. You should still get work (because it looks like it's failing sporadically).

**Comment by ponpit31** [comment]
i get the same problem..,  from sunday i never get one job

**Comment by khristianjose** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/17553414/18519205/0326effe-7a71-11e6-8cc9-8b02eb9c2086.png)

**Comment by khristianjose** [comment]
i see this when i click the red link upthere but i cant complete the captcha it doesnt let me click the submit button 
![sin titulo](https://cloud.githubusercontent.com/assets/17553414/18519430/ea886332-7a71-11e6-94a2-4d76b12f6fa4.png)

**Comment by khristianjose** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/17553414/18520105/7004e2ae-7a74-11e6-9d4c-b9460f302a1f.png)

Only fetch types
