### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by sweeneyapps** [rainforestapp/tester-chrome-extension#554]
keep in mind, extension keep on loading jobs repeatly after many errors.   It came up w/ "Too many requests" often..     I never refresh or do anything to it.

![image](https://cloud.githubusercontent.com/assets/7229364/18483866/dcdf77a2-799a-11e6-8ad9-f9d1f7b0200e.png)

Also I saved the HAR data and if u need it..  let me know.

**Comment by shosti** [comment]
CC @pscohn (this is probably due to the new rate-limiting code).

**Comment by sweeneyapps** [comment]
just noting this error..  so it's documented.     so far, everything fine now.

**Comment by djux90** [comment]
Yes, it always keep pooling for job, i got this too. But extension work good for me.
![rate](https://cloud.githubusercontent.com/assets/20422665/18488805/51e4fe68-79fb-11e6-89c2-3c6ecaaee23e.JPG)

**Comment by Taruga** [comment]
I'm having a lot of "Too many requests" today

**Comment by hunt40** [comment]
too many request then application error and then another worker got it while i am sitting on application error.

**Comment by shrestha15207** [comment]
i disabled extension, refreshed 'Another worker accepted the job before you!' page and got 'too many requests' and again waited 1/2 minutes, refreshed again, still got too many requests. why??

**Comment by JrRandy** [comment]
yeah, the "Too Many Requests" is becoming the new "No Virtual Machines".  Something is wrong with the config or the rate limiter.

**Comment by VeryDisappointedTester** [comment]
At least when you get "Too many requests" you know that something is going on. In most cases extension don't open window with this message but you are in "Too many requests" mode. This is much bigger problem. 
![extension](https://cloud.githubusercontent.com/assets/22333356/18747116/ac9fe418-80cb-11e6-8e7e-37cd6d01e3dc.png)
![extension 2](https://cloud.githubusercontent.com/assets/22333356/18747229/6b01eece-80cc-11e6-8409-da152a42d939.png)

**Comment by sweeneyapps** [comment]
I think this has been handled..  so I'm closing this.
