### ISSUE TITLE
Constant WIP

### ISSUE THREAD

**Issue by coyoteazul** [rainforestapp/tester-chrome-extension#557]
Hi. Today I noticed this new state on the notifier, WIP (I assume it means work in progress).
Whenever there's a problem with a job i get stuck in WIP and I receive no more jobs.
Closing the tab is not enough to force a reset (I have 2 tabs with 2 different chrome users and the extension is only in one of them). I have to close all of chrome's windows (basically, kill chrome's process)
![e1aa8f5ebcb8420eb4d434e0314ad1a3](https://cloud.githubusercontent.com/assets/15698371/18490554/e0cd0008-79d8-11e6-97dc-b52044f1fa5e.png)

**Comment by j1menezz** [comment]
Same happened to me too. After several mins the WIP disappeared but the icon turned grey.

**Comment by shosti** [comment]
K looks like a genuine issue. Will look into it...

**Comment by JrRandy** [comment]
It occurs on Application errors.  If you refresh the page to get a normal redbar error, the WIP goes away and it begins polling again.

**Comment by sweeneyapps** [comment]
@shosti   The extension does appearly work well.    When I get this Application Error page.     I see that I'm still on WIP status.    So I went ahead refresh and on first try, still Application Error.. then I waited awhile to refresh again.   I got the job page loaded and now working on it.

**Comment by shosti** [comment]
Yeah the issue is that the tester terminal sends a message to the extension to clear WIP when when there's an error loading the job. But if there's an error before the terminal is even started, it won't get cleared.

Proposed solution: clear WIP if the work tab has closed and the job hasn't started (see referenced PR).

**Comment by nagabhyru** [comment]
WIP is not disappearing for the following errors like Application error or In middle of the test if we got an error like something bad etc. For the rest of the errors WIP disappears and pooling for the new work. 

I think extension is working fine.

Again No VM's and Another worker messages are increasing. Do something to reduce as much as possible.
