### ISSUE TITLE
"Too many requests" at any time.

### ISSUE THREAD

**Issue by TyroneSt** [rainforestapp/tester-chrome-extension#558]
Why "Too many requests" error is appearing in random situations. Sometimes while refreshing for getting a VM and wait less than 30 seconds since my last refresh it appears and other times (its supposed we have 50 seconds for 2 attempts) it does not. The same happen when for any reason I wait more than a minute or a longer time to refresh the "Too many requests" appears again and other times it does not, even the worst is when I get a new hit after more than an hour since my last job was submitted the page loads some seconds and suddenly "Too many requests" again. Please can anyone tell me the purpose of such error message (and how can I avoid it)  because it doesnt have a pattern and each time it appears the hit is 100% lost.

**Comment by shosti** [comment]
Dup of #554. Please search for similar issues before reporting it as a new issue.
