### ISSUE TITLE
The Rain falls mainly in spain....

### ISSUE THREAD

**Issue by JPierreS** [rainforestapp/tester-chrome-extension#561]
Turns gray and stops polling completely, even after several attempts to re-install, enable/disable, uninstall/reinstall portal refresh, logging off and back in.

// Keeping an eye on this if issue recurrent

Restart of PC fixed for now but this was never a problem in previous versin.

**Comment by Electroglitch** [comment]
@JPierreS Thanks man for this info!
Similar thing happened to me, out of the blue sky.
 it was working normally and then  just fetch errors one after another ,
and just Restart of PC was able to fix it ,strange...
