### ISSUE TITLE
Starter Job (especially for old tester who pass in training session)

### ISSUE THREAD

**Issue by myIssue** [rainforestapp/tester-chrome-extension#564]
1. WIP always red even though i able doing hits, what does it means? ***SOLVED***
2. And also my bonuses are still pending till now.

**Comment by qpPykT** [comment]
@myIssue 
Update your browser. Red or green color WIP it's same.
Do you have all of your bonuses still pending or some of it?

**Comment by myIssue** [comment]
@qpPykT

In the past , all of them are still pending

**Comment by qpPykT** [comment]
@myIssue 
Have you received any money for completed tasks or not?
When you join to rainforest?

**Comment by myIssue** [comment]
@qpPykT

Last received bonus 05-05-2014. I joined since April 2014.
Last reply from RF said that i will be paid when RF recruite new tester again. But i'm still doing them even though with pending bonuses. So what should i do, stop it or continue?

Hmmm, confused+frusta*d....

**Comment by qpPykT** [comment]
@myIssue 
Oh, man. I understood you. You may try but I don't know. You need to claim your profile when registration will be open again.

**Comment by sweeneyapps** [comment]
@myIssue I would do something else to make money.   Because it's not fair for another testers if u took their job away from them and you re not being paid for it.

**Comment by myIssue** [comment]
I hope RF will give job starter soon...

**Comment by JPierreS** [comment]
Hopefully not mate - I hope they fix the cheating problem and revamp the acceptance process and use skilled, proven, trusted crowd only moving forward.
I agree 1000% with @sweeneyapps it is not fair to do this task potentially taking work from someone else, if you are not paid. what if they don't re-open any time soon, you cannot know this so why continue doing a task - what if they don't reopen for any near future ?

**Comment by myIssue** [comment]
@JPierreS

Thanks for your respon.

But of course, my account is valid and verified also.
I have successfully claimed my profile and everything running well. There is no errors, mistakes or something like that in my account. I passed in training session, so that's why i able to get hits. In other words, they still give me chance for their job. Thank You.

Please note that i **DIDN'T** do any cheating in this case. They **CAN** check my account or everything else.
I just wait **JOB STARTER** from them to get my pending bonuses.

Hope they give it soon...

**Comment by uangonline** [comment]
@myIssue Are your CF account still active? It really confused me. If you have Active CF, RF and any CF Channel partner account, and able to get RF job hit, you should get paid. Unless you get BAN in one of the account i mention.

**Comment by myIssue** [comment]
@uangonline 

Yes, it's still ACTIVE and NO one account banned.
All are running well, BUT hmmmmmmmmm..........

Still waiting...

**Comment by rnfrst** [comment]
@myIssue I guess you claimed your profile from a dormant account that needs to be reactivated. Unfortunately, the only way you can reactivate your account is by doing rainforest job from crowdflower.

**Comment by qpPykT** [comment]
@myIssue  Why are you always trying to break the system. You know what the result will be in the future :)

**Comment by helloworld111gh** [comment]
why are you trying to do rainforest for free?
but anyways, you can do work for rainforest assuming no bans or blocks. you just won't be paid, which sort of takes away the whole point of doing rainforest.
what was the job is of your last message (bonus/message/news, doesn't matter)?

**Comment by myIssue** [comment]
@JPierreS

Thank you for your explanation.
And I still hope there is an exception in this case, **especially** for old testers who are pass in training session.

**Comment by qpPykT** [comment]
@myIssue And you forgot one more thing who has not been blocked before.

**Comment by myIssue** [comment]
> And you forgot one more thing who has not been blocked before.

@qpPykT Ooops, yeah. I'm still expecting RF.

**Comment by myIssue** [comment]
Hmmm, i think patience is needed in this case.
Hopefully God help me soon...

**Comment by qpPykT** [comment]
@myIssue 
> Hmmm, i think patience is needed in this case.
> Hopefully God help me soon...

He will help you be blocked for the third time? Why are you so grrrrpphjjj... I don't have a words.

**Comment by myIssue** [comment]
> He will help you be blocked in the third time? Why are you so grrrrpphjjj... Sorry I don't have a words.

NO, I never be blocked but miss their last job only.

**Comment by qpPykT** [comment]
@myIssue  Yeah, never give up. You can change your ip - but change your self it's not so easy.

**Comment by myIssue** [comment]
Hopefully i can joint with a huge of active testers soon.
