### ISSUE TITLE
The algorithm waiting for delivery of a job is very short and is affecting countries where the internet is a bit slower

### ISSUE THREAD

**Issue by jjooeellkkaarrrr** [rainforestapp/tester-chrome-extension#567]
Today 70 jobs Another 60 were Worker, Who can help me please? Before the changes I was going well but after the last change I lost more than 80% of the work.
A million thanks

I think the time algorithm time waiting for delivery of a job, it fell to affect countries where the internet is a bit slower.

**Comment by TyroneSt** [comment]
I think the system is sending notifications of jobs that were already taken. Thats why most people is receiving Another Wor.. message all the time even more times than we used to receive hits few days ago. I prefer to receive a possible hit each hour than 10 messages that other worker received the job in the same hour. Just my guessing because some hits load immediatly just to show me Anothe..

**Comment by IceCreamCake** [comment]
same here, everything ok in old platform but now, all i have is Another worker.... (9/10 time)

**Comment by federicoall** [comment]
Same here no vms another worker aplication error to many resquest and no resfreshing anynithing.

**Comment by DrDejan** [comment]
Same problem here, no vm, another worker..., aplication error, to many resquest and no resfreshing anynithing.

**Comment by JPierreS** [comment]
I honestly don't understand how some people are able to get 70-80 let alone 100+ links daily from extension, whether a HIT or another worker it is a link.  I have completed 20 !!! 2 year tester, super tester, trusted crowd and I get 20 links, so I am puzzled.  

I don't see what the fuss is about the "another worker" - it is normal behaviour.  There are far too many testers IMO.  It is normal - the amount of work available is never 1:1 with the amount of testers, hopefully one day (if people stop cheating and follow the bloody rules) maybe a miracle can happen and we can all get work 24/7 non stop !  

For now, there are many testers competing for work.   The extension is just polling the API using your credentials and asks if there is work, if there is work it passes the URL it receives - work is actually not reserve to you yet until you open that URL, so someone out there will likely get the job first.  If there is another assignable job you will get what's available, if no assignable job at the time, you will get this error.  You can just switch off your extension and refresh the another worker link until it converts to a hit, OR close tab and let the extension pass you another link but you are likely going to get another "another worker" lol so you might as well refresh the link you receive.  Until the new system is into play and jobs are assigned and reserved, you will have to be patient.  All depends on the amount of tests circulating, some days there can be far less tests and more people competing for work so more "another worker" links.  The older or newer extension is polling the same way.

Yes the majority of links I get are another worker, I just close extension and refresh it, and it always converts to a hit eventually, so I don't see much of an issue.  There are more of these lately and more "no_VM" links as well, let's hope things get better and we get more hits, but to be honest I think it is a 2 way street, not only from RF but the CrowdSourced community as well and whether people submit QUALITY results, I think this has an impact too.

**Comment by f-ms** [comment]
You are right JPS.
Those 157 steps are those where the instructions are wrongly formulated and should have been reported. But alas that is not happening. Usually on those 157 step hit one usually finds faults by 20 to 30 step, at times even earlier, so it makes me wonder how people go about finishing the full hit upto 157 step.

**Comment by GreekGuy** [comment]
I believe the problem is the Propagation delay between the server and the clients if you are closer to the server you ll get more jobs.

**Comment by nagabhyru** [comment]
I am also facing the same issue since yesterday. When ever a job is open either we get No VM's or Another worker message. It happens 9 out 0f 10 times. I am hardly able to do 10 tasks in the span of 15+ hours that hardly getting me 1 to 2 dollars. In past we used to get decent number of jobs. Lets hope for the best, that's all we can do. 

Any one has an update about RF forum. They last said testing is going on. At least if we have a forum we can discusses these issues easy and RF can know the issues easily.

**Comment by JPierreS** [comment]
@GreekGuy  I don't believe the speed has to do with the amount of hits.  The requests the extension makes are so small in terms of transfer and only require few bytes, even a dial-up can handle that (I am referring to the actual bandwidth and speed required to acquire the link not the actual speed of working on a job.)

I have single to low digit latency between me and RF and that certainly does not increase my jobs, in fact I see a sharp decline.  SO unless your latency is so severely bad compared to the average, I don't see it being an issue at all in terms of frequency of jobs received, so unless there is some major bottleneck somewhere and your requests are significantly delayed, it is a non issue.

Some of my colleagues have 400ms and get just as many hits ;))
