### ISSUE TITLE
what is wrong with trainig jobs

### ISSUE THREAD

**Issue by berkomay** [rainforestapp/tester-chrome-extension#577]
Hello i am working with rainforest more than one year and done about 800 900 tasks. However about last 2 3 days i am received only training jobs and i have done about 30 40 training task. It seems it keeps coming. Is it a bug or is it supposed to happen?Thank you

**Comment by nerdatwork** [comment]
You are put in a training sandbox until you are trained properly. If you check through other posts here you will learn many other testers have been through your situation and have actually gotten real HITs after training. I wish you good luck.

**Comment by abozizo72** [comment]
me is the same

**Comment by kristen-allie** [comment]
This happens to testers who are performing poorly on tests, which is why it doesn't happen to everyone. Very few of our testers get put into this sandbox.

**Comment by cookin2** [comment]
I just got a training hit!  I'm so upset.  Then I got 2 regular hits, and then another training hit.  While I was doing the 2nd training hit which came from refreshing an error, another hit popped up from the extension.  After I finished the training hit, I went to the hit from the extension and it said "job abandoned".  As I was typing this, I got a regular hit.  I really don't know what's going on.  Have I done something wrong to be put into the sandbox?  If you're in the sandbox, can you do regular hits too?

**Comment by begsoon** [comment]
Training Jobs 2016-09-19 17:46:20 UTC, Kristen Hohenstein
Hey all! We've enabled random training for 100 testers in our continued effort to test out the feature before enabling it for everyone. So if you happen to receive a training job and don't know why, this is probably the reason :)

**Comment by cookin2** [comment]
I hope it's random!  It worried me and then I read Kristen's post above and panicked!  I may make a mistake her and there, but I really try to do good work.

Thank you @begsoon, I hadn't read that yet... whew, relief lol

**Comment by zjavierjz** [comment]
I'm like, today I received only hits of training, in the morning I barely got three normal hits, paid, but even now I keep getting hits test and I have ragalado four rejections, not because, because all my answers they are correct and in the description, or even appears because where is the error in the only marks, an "X" in step ... but obviously this well what I answered.

Yesterday spend all day that I did not load the VM, but today I open all alone in trainings. :(

**Comment by javicocuba** [comment]
que porquería

**Comment by HW71** [comment]
Hmm, "training jobs" have been explained in detail [in the FAQs / Wiki](https://github.com/rainforestapp/tester-chrome-extension/wiki/Training-Tasks) - hence I'd suggest to close this issue.

But maybe it would be a good idea to update the Wiki with the latest information concerning "Random Training" - just to make sure to have it up2date with current process.
