### ISSUE TITLE
Extension on two computers (same IP)

### ISSUE THREAD

**Issue by ivasadzakov** [rainforestapp/tester-chrome-extension#581]
I have two computers in the same house, on the same IP address. Is it allowed to have two extensions installed on both of these PCs, because sometimes I use one, sometimes the other one. Currently I have extension installed on only one computer and I think it is better to ask before I install it on other one. Thank you :)

**Comment by uqbiii** [comment]
There will be no problem if you want to install on both PC's until you use one Rainforest account. It's better to put it ON in one pc only.

**Comment by shosti** [comment]
Once https://github.com/rainforestapp/tester-chrome-extension/pull/576 has been shipped then you will only be able to use the extension on one computer (it will automatically disconnect from others when you log into one).

**Comment by ivasadzakov** [comment]
Thank you guys <3
