### ISSUE TITLE
Elite payment

### ISSUE THREAD

**Issue by mariaelite** [rainforestapp/tester-chrome-extension#589]
Hello Rainforest.
I wanted to know that Elite tell them regarding the payment owed to us.
Until this day, in my case, it's been five weeks they do not pay me what they owe me and do not answer.
I dread each week that I will collect and return me to steal.
I want to know that you know about it to know if I continue using Elite or not.

Excuse my bad English :-)

**Comment by JrRandy** [comment]
Please post in #568 The issue has been discussed there

**Comment by mariaelite** [comment]
JrRandy Thank you.

**Comment by Electroglitch** [comment]
@mariaelite Can you close this thread now as it's duplicate?

**Comment by mariaelite** [comment]
Electroglitch Ok.
