### ISSUE TITLE
Ooops Something Went Wrong

### ISSUE THREAD

**Issue by Deepak0988** [rainforestapp/tester-chrome-extension#59]
@ukd1 This is for your needful action.

1. Ooops Something Went Wrong Link :https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx1b6e8b-0661-4587-8b96-30e24bdcc01d&browser=any&hitId=4475569&sig=4f9e026ac05afef557dd21df680f34b9d2e03df827ffd3a561fb18dcc59e6c09&turkSubmitTo=%2Fthanks&workerId=32687648

2. Application Error Link:
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx1b6e8b-0661-4587-8b96-30e24bdcc01d&browser=any&hitId=4475569&sig=4f9e026ac05afef557dd21df680f34b9d2e03df827ffd3a561fb18dcc59e6c09&turkSubmitTo=%2Fthanks&workerId=32687648

**Comment by marius11** [comment]
There is already a thread for this problem:

https://github.com/rainforestapp/tester-chrome-extension/issues/53
