### ISSUE TITLE
There was a problem with the request

### ISSUE THREAD

**Issue by Lagstyle** [rainforestapp/tester-chrome-extension#590]
I have  a problem with "rainforest tester notifer" plugin.I have not get automatically work near week or more
![1](https://cloud.githubusercontent.com/assets/22318615/18666886/d628dd9e-7f36-11e6-913d-347cec984066.png)
![2](https://cloud.githubusercontent.com/assets/22318615/18666889/d855f002-7f36-11e6-9202-242866522b92.png)

**Comment by uqbiii** [comment]
Same happens to me every time i start Chrome, have installed extension about 25 times till now, yesterday posted screenshots of Network tab but no one is willing to take any action. Post a screenshot of Network tab, maybe they look into this problem. I hope it will looks like this.
![](http://image.prntscr.com/image/1a13023af69b4c3aa5fed186eaf1e122.png)

**Comment by erdeminofff** [comment]
They was applying some changements in server. Now servers back to online and seems they added Restart Job link in error notification page. 
![new bitmap image 20](https://cloud.githubusercontent.com/assets/8877357/18679190/38d47982-7f67-11e6-8005-e2e59efc8d2a.png)

Don't forget, After take a job if necessery, use Restart Job link instead of page refresh. Otherwise test will be abandoned

**Comment by sweeneyapps** [comment]
@uqbiii  get in touch with @shosti ..  he will instruct you on what to do for debugging on net:ERR_FILE_NOT_FOUND errors.

**Comment by shosti** [comment]
We've changed some network settings, which should hopefully help with the issue for now. Can you try again and see if it's improved?

**Comment by Lagstyle** [comment]
still not work
![2](https://cloud.githubusercontent.com/assets/22318615/18686915/71c56ebc-7f86-11e6-8e12-8e2c8ba30f14.jpg)

**Comment by cookin2** [comment]
I'm doing OK now, but I don't know if its the improvements or my "new" ritual.

Sign out of my portal
Uninstall the extension
Sign into my portal & get another extension from there and install
Extension tells me I'm not logged in
Log out & back in

That does fix it.  It's either that or no work, err_ messages and fetch.

**Comment by shosti** [comment]
@Lagstyle OK how about now?

**Comment by Lagstyle** [comment]
No errors and window with captcha for now

**Comment by Lagstyle** [comment]
Yeah!!!.Thanks all and Shosti.All work now
![111](https://cloud.githubusercontent.com/assets/22318615/18688472/3b0bc770-7f8d-11e6-99c1-39cd5eafc930.png)
