### ISSUE TITLE
About hits from Raiforest addon: Most of the hits I receive from Rainforest addon shows the following message:  "Rate limit exceeded you may do 2 request every 50.0 seconds. Don't refresh the page more often than this."

### ISSUE THREAD

**Issue by MiguelAbrams** [rainforestapp/tester-chrome-extension#597]
Hello.
 My ticket is # 15475 dated 09/05/2016. I have not had any response.

**Comment by MiguelAbrams** [comment]
The hits show the message, without having to refresh the window

**Comment by MiguelAbrams** [comment]
Please help me

**Comment by shrestha15207** [comment]
extension opens "too many request" page. whats going on??

**Comment by nerdatwork** [comment]
Most testers are experiencing these issues and a solution is on the way. Thank you for being patient.

**Comment by MiguelAbrams** [comment]
Thank you nerdatwork:
You are investigating !, it is nice to know.
This is very important to me. Rainforestqa is my only income.
Perhaps it might be useful know for your research a couple actions I did just before this problem is presented:

1. I changed the email account in my profile
2. I installed the extension on another pc of my property and with the same IP. The extension was probably connected on both a PC as on other PC at the same time but for very short time.

 If you need my colaboration in order to do proofs I am disposed to work hard with you.

Thank you

**Comment by aleksasf** [comment]
After 3 weeks of solving same old problems, that are present after 3 weeks i think i dont belive you :smile:

**Comment by MiguelAbrams** [comment]
Why this issue has not any response. This issue is ignored Why?

**Comment by cookin2** [comment]
@MiguelAbrams It isn't an issue anymore, there is no longer any refreshing of links.

**Comment by MiguelAbrams** [comment]
Thanks **@cookin2**. I'm already working. I am going to close this post.
