### ISSUE TITLE
ERROR: Something went wrong on our server, sorry about this. Please reload and try again.

### ISSUE THREAD

**Issue by LifeIsCod** [rainforestapp/tester-chrome-extension#60]
Getting lots of this error now a days
![screencapture-tester-rainforestqa-com-tester-assignment-crowd_flower-any-1455125192224](https://cloud.githubusercontent.com/assets/7995790/12955551/989477a0-d049-11e5-889e-06bc9d1f2954.png)

**Comment by marius11** [comment]
There is already a thread opened addressing this issue: https://github.com/rainforestapp/tester-chrome-extension/issues/53
