### ISSUE TITLE
New job when there is already a Job [error] tab opened

### ISSUE THREAD

**Issue by RnkSts** [rainforestapp/tester-chrome-extension#601]
When I get a new job, and this ends in an error (like '_There are not machines ...'_ '_Another worker ..._', etc.) and the job window remains open, sometimes it is replaced by a new job.

As you know the extension looks for work when the "**WIP**" is not present, this is good for when we receive a "_Another worker ..._', but when the job is received end with the typical error "_There are not machines bla bla bla..._" sometimes we need to click the reload button a few times in a time interval to get a VM, and maybe it gets replaced if there are more job available.

So here is my question: **This is normal?**

I think that most of the jobs that are replaced end up being taken by another worker, as I have tried to **disable** the extension when this happens, and 8 out of 10 times the job ends in '_Another worker..._'.

Plus: Here is a short video of what happens (The error message was 'There are not machines available at the moment', so I leave the tab open to click the reload button in a few moments later) Ignore the tab change. http://es.tinypic.com/r/5yc0z/9

This is sometimes annoying, because occasionally it happens so fast and often that I ended up getting 'Rate limit exceded' or also 'You have Reached the maximum number of ...'.

Another thing is that sometimes when a job is completed the "**WIP**" remains active. But that is another know issue.

Thank you if you read this long issue, lol. And sorry bad english?

**Comment by uqbiii** [comment]
I don't have answer to all of your questions but some can be answered.
The tweak i am using to avoid such situation is when i receive a HIT link with an error, i turn my extension to OFF, by this extension stops polling and no new links open. As soon as i get the HIT, or Another worker, i turn it ON
If you see "You have reached the maximum..." after automatic closing of current tab and opening a new Tab, open the link which is closed automatically, Ctrl+Shift+T is an easy way to open.
"WIP" remains active until your job is not submitted to the system, or you can say, it won't disappear until your Total Jobs Completed counter increases to +1. Sometimes it will disappear immediately and sometimes take a minute because of the load on the system. Not a big problem to worry.

**Comment by RnkSts** [comment]
@uqbiii Turning OFF the extension it's what I gonna do for now. The problem is when I'm not in front of the PC, or if i get distracted for a moment, this can happen. It has happened to me a couple of times I'm doing something else outside the PC and I hear the Job alert Sound several times in a short time period, before I can check what's happening. o.o

**Comment by uqbiii** [comment]
Well, for this scenario, this feature is very useful. It only closes Tabs if there is no HIT in the Tab unlike the previous versions, which doesn't open any new HIT links until you close the tab related to HIT if there is one open, no matter if error is showing. For such occasions, you can call this extension an auto refresh extension. If you are away from your PC means you cannot refresh it from that place and manual refresh needs your attention, with you don't have to close error pages and extension do it for you and when it finds work it will stop opening new links, so if extension do it for you, its really great. To me, this is a great feature.

**Comment by RnkSts** [comment]
Yeah it would good, unless they make you exceed the limit :(. But it is not something that always happens.

**Comment by uqbiii** [comment]
Exactly, at least not happened to me, and when we are away, we should not worry about rate limit exceed, it will back to normal without any loss.

**Comment by f-ms** [comment]
@RnkSts 

> It has happened to me a couple of times I'm doing something else outside the PC and I hear the Job alert Sound several times in a short time period, before I can check what's happening

Does the extension now come with the sound feature. meaning are we notified with sound if a hit/ Another worker/error comes up.
How are you able to get Job alert sound?

**Comment by RnkSts** [comment]
>Does the extension now come with the sound feature. meaning are we notified with sound if a hit/ Another worker/error comes up.
How are you able to get Job alert sound?

@f-ms There are other external plugins that can give the sound feature while this it's not included in the official extension. I use this (**https://github.com/sweeneyapps/JobAutoReload**) from sweeney. It's a job reloader, with sound support when you get a new job (Error or no). But we don't need the autoreload now, because the new Reload button. But I still use it for Job Alert :smiley:

**Comment by f-ms** [comment]
@RnkSts .... Thanks for the info
