### ISSUE TITLE
My Rainforest Tester Notifier

### ISSUE THREAD

**Issue by abbalight** [rainforestapp/tester-chrome-extension#602]
My Rainforest Tester Notifier does not work. It always stay in OFF state and it does not switch on.
How to solve this probelm?
Thank you

**Comment by nerdatwork** [comment]
Have you tried to reinstall it ?

**Comment by abbalight** [comment]
yes, many times, also disable and enable it

**Comment by JrRandy** [comment]
Is your account listed as active in the profile?

**Comment by JPierreS** [comment]
Assuming your profile is "ACTIVE", could you try logging out from profile and logging back in, then refreshing the profile page, try switching your extension on now, does it work ?

**Comment by abbalight** [comment]
It worked!!!
Thanks for the advice!
Regards

**Comment by JrRandy** [comment]
Excellent.  Can you please close this thread?
