### ISSUE TITLE
two job abandoned for that :(

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#603]
![image](https://cloud.githubusercontent.com/assets/19192312/18716920/714c81ee-7fec-11e6-9767-23de6e1a8624.png)

**Comment by zfonck123** [comment]
![image](https://cloud.githubusercontent.com/assets/19192312/18716964/9d347f0a-7fec-11e6-9e0e-f726076d7863.png)

**Comment by nerdatwork** [comment]
Your Email address is showing, hide it.
