### ISSUE TITLE
what happen today ?

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#604]
9am to the same time, alot errors, lag, virtual machine, something bad happened,aplication error. omg imposible working

**Comment by zfonck123** [comment]
terminal stucking loading :/

**Comment by CharlieSpock** [comment]
same on this side. Tabs open but only a white screen shows

**Comment by JrRandy** [comment]
They had some performance issues, and changed the polling time to 2 in 75 seconds as a resolution method I believe.

**Comment by nuevao** [comment]
still it appears to be performance issues at this time the tester not charge me
![captura](https://cloud.githubusercontent.com/assets/16979522/18730573/118353f8-8025-11e6-9a68-c7b3f218ee39.JPG)

**Comment by RnkSts** [comment]
**https://portal.rainforestqa.com/**
![p](https://cloud.githubusercontent.com/assets/20311303/18732457/578bce6e-8031-11e6-9f19-8fb1dd2ed29e.png)

**Comment by mariaelite** [comment]
That slowdown, That is a problem are experienced? or something you are testing.
I have not done anything today :-(
The terminal charge.

**Comment by RafaelBelmontes** [comment]
Same problem.

![image](https://cloud.githubusercontent.com/assets/22337927/18733852/7f35b4ec-803c-11e6-84d6-0d28cf340a1b.png)

![image](https://cloud.githubusercontent.com/assets/22337927/18733863/95c08c96-803c-11e6-924a-475a30e5d3c3.png)

**Comment by ukd1** [comment]
locking this as the slowdown has passed and this is going off topic.
