### ISSUE TITLE
Confusing scenarios

### ISSUE THREAD

**Issue by zulauf1** [rainforestapp/tester-chrome-extension#605]
What should I do with these hits? It does not say "click log in" I inform you that it is not clear .

**Comment by RnkSts** [comment]
> - If the instructions are intentionally vague and general, follow them as closely as you can. You should report any errors that show up and anything that prevents you from completing the task.

**https://github.com/rainforestapp/tester-chrome-extension/wiki/Guide-Rules:-Confusing-Scenarios**

**Comment by ukd1** [comment]
@zulauf1 do not post images of your work here.
