### ISSUE TITLE
really think that is a problem ?

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#606]
Rate limit exceeded, you may do 2 requests every 75.0 seconds. Don't refresh the page more often than this. This limit may change.

**Comment by RnkSts** [comment]
Due to performance issues maybe the polling time was changed to 2 request in 75.0 seconds as a temporary solution, I think.

**Comment by zfonck123** [comment]
that solution always time.... of 10 second to 15,   15 to 20,  25, 30,50, now 75... that not is a solution

**Comment by zfonck123** [comment]
![image](https://cloud.githubusercontent.com/assets/19192312/18733069/f9fd42d2-8035-11e6-88ad-b00a5bfacc11.png)
stuck loading, i will loss the job for job abandoned...

**Comment by zfonck123** [comment]
terminal vs server maybe is the conection, plataform, i dont know. but that inssue have alot time, affter create the app extencion

**Comment by zfonck123** [comment]
and have more problem, affter reopen for new tester in may to august

**Comment by ukd1** [comment]
we rate limit as some testers automate requests. if you go over the limit by modifying the extension, it will penalize you and take longer to get back to actual requests.
