### ISSUE TITLE
The signature in the URL is invalid. Another new bug???

### ISSUE THREAD

**Issue by uangonline** [rainforestapp/tester-chrome-extension#607]
Another new bug and error message?

**Comment by JrRandy** [comment]
Same issue

**Comment by Electroglitch** [comment]
Yes started like 5 -7 mins ago. One after another extension is serving links with error message.
I turned it off for now...

**Comment by st53stefanov** [comment]
Same here

**Comment by JrRandy** [comment]
Sure hope rainforest hasnt gone home for the night lol

**Comment by zfonck123** [comment]
same bug

**Comment by jguerrero2** [comment]
Same here, I had to turn off the extension!

**Comment by MarinaCec** [comment]
same

**Comment by helloworld111gh** [comment]
Look's like Rainforest broke something in their validation code...
Maybe Rainforest should use RainforestQA, a trusted QA service, to test
their tester interface before pushing it live...

**Comment by JrRandy** [comment]
Looks like they cranked the polling acceptance now.  Every window is popping with "You can only do 2 requests in 75 seconds" even though the app is only polling at 38 sec intervals.

**Comment by uangonline** [comment]
@helloworld111gh Couldn't agree more! :laughing:

**Comment by uangonline** [comment]
Everything seems back to normal now. Case close

**Comment by Electroglitch** [comment]
I just have to reference #608 
Nobody was changing links or anyting , extension was serving links left and right with the folowing error mesage:
"The signature in the URL is invalid. "for maybe 20 mins or so.
