### ISSUE TITLE
Getting new error: The signature in the URL is invalid.

### ISSUE THREAD

**Issue by Taruga** [rainforestapp/tester-chrome-extension#608]
I´m getting the following error on the last jobs:

The signature in the URL is invalid.

What´s this ?

**Comment by elpanatibu** [comment]
me too

**Comment by uangonline** [comment]
Yap another new bug.

**Comment by NeoWorker** [comment]
Same.

**Comment by luisdanielvc** [comment]
It's an old bug but is weird to see it from jobs gotten by extension

**Comment by zfonck123** [comment]
same bug....

**Comment by nummuss** [comment]
same bug....

**Comment by MarinaCec** [comment]
same here

**Comment by CharlieSpock** [comment]
5 job lost for this bug :( and a day with too many issues

**Comment by zfonck123** [comment]
![image](https://cloud.githubusercontent.com/assets/19192312/18733297/98b5743e-8037-11e6-8a69-24295ed1d351.png)

**Comment by erdeminofff** [comment]
I think they are changing some things in server now.

**Comment by ivasadzakov** [comment]
Same here.

**Comment by ahmed1979** [comment]
Same problem

**Comment by MarinaCec** [comment]
stay calm, they will fix soon

**Comment by Hanifmamun** [comment]
Same Issue

**Comment by muerte01** [comment]
same here annoying error

**Comment by RafaelBelmontes** [comment]
Same Issue

**Comment by gusttest** [comment]
Same problem.

**Comment by NeoWorker** [comment]
Seems it's back to normal, just got a normal hit.

**Comment by CharlieSpock** [comment]
I have 1 but vm not charge

![2a2](https://cloud.githubusercontent.com/assets/20996862/18733705/5b28593e-803b-11e6-94a9-1456097997d9.png)

**Comment by zfonck123** [comment]
same here today "............." alots errors

**Comment by CharlieSpock** [comment]
Too sad :( vm not charge again and again

![2a2](https://cloud.githubusercontent.com/assets/20996862/18733957/95501226-803d-11e6-8f96-7a85b51dae1a.png)

**Comment by MarinaCec** [comment]
@CharlieSpock just click restart job button

**Comment by zfonck123** [comment]
dont work

**Comment by zfonck123** [comment]
same stuck loading

**Comment by ukd1** [comment]
@Taruga, you cannot alter the URL at all now - it used to be common practice to get more work by doing this. Now, you cannot.

Locking this as the rest of the thread is off topic.
