### ISSUE TITLE
The signature in the URL is invalid.?

### ISSUE THREAD

**Issue by JrRandy** [rainforestapp/tester-chrome-extension#609]
Hit opens, message is:  The signature in the URL is invalid.

**Comment by JrRandy** [comment]
Closing due to duplicate

**Comment by HW71** [comment]
Just for reference:
Duplicate to #608 and explanation for this new behavior was given by @ukd1 here: https://github.com/rainforestapp/tester-chrome-extension/issues/608#issuecomment-248789012.
