### ISSUE TITLE
VM not loading...

### ISSUE THREAD

**Issue by mariaelite** [rainforestapp/tester-chrome-extension#610]
All day I could not do any hit

**Comment by zfonck123** [comment]
![image](https://cloud.githubusercontent.com/assets/19192312/18745586/b2137bf2-8090-11e6-8c5d-4e45acda7741.png)
and is a new day, and same problem

**Comment by kikejlg91** [comment]
Same here, i tought it was only me or my internet

**Comment by zfonck123** [comment]
all people with a same problems. .... today other bad day for do works!!!

**Comment by elpanatibu** [comment]
System slowdowns 2016-09-21 19:06:51 UTC, Kristen Hohenstein
Hey, testers! We're currently experiencing some App slowdown. I apologize for any inconvenience this might be causing you!

**Comment by elpanatibu** [comment]
i think they are a problem with dns. when i change from my isp to my hotspot from the phone with 3g data. i get all the hits again.

**Comment by zfonck123** [comment]
and portal, web page, and status very very very slow for can load the page

**Comment by nuevao** [comment]
Perhaps some senior problem. since yesterday I have had problems with several pages, including the page tester. They are very slow, despite the intenet service works as usual.

**Comment by kuartx** [comment]
Same problem for me, portal,website, test job very very slow to load the page =S

**Comment by nuevao** [comment]
Hi guys, today I continued the same problem. attach a picture of the console when loading test, you have any idea that this is about?
![captura1](https://cloud.githubusercontent.com/assets/16979522/18787223/e2ab8cac-816f-11e6-8940-998b895c3f13.JPG)


By the way I read that for those who are located in Venezuela, the problem arises specifically with Cantv ISP,.

**Comment by carlosds7** [comment]
Same problem for me..

**Comment by kikejlg91** [comment]
Cantv is killing me...

**Comment by nuevao** [comment]
The problem apparently is with CANTV, for now it is advisable to switch ISPs, there is no alternative for now.

**Comment by carlosds7** [comment]
@nuevao ISP? what is that?

**Comment by nuevao** [comment]
@carlosds7 Proveedor de servicio de internet, En Venezuela (Cantv, Movistar, Digitel, etc)

**Comment by carlosds7** [comment]
@nuevao A ok, yo ya llame a CANTV, les explique todo y me dijeron que esperara 48 horas.

**Comment by RnkSts** [comment]
Llamar a Cantv sinceramente es una perdida de tiempo, si no fuera porque no tenemos muchas alternativas, ya hubiera cambiado de servicio. Hope this issues with the internet service will be fixed soon, to continue working :confused:

**Comment by carlosds7** [comment]
@RnkSts Todavia tienes el mismo problema?

**Comment by RnkSts** [comment]
@carlosds7 A estas horas el problema esta presente, solo puedo hacer los minitrabajos de crowdflower, aunque hay algunos que no son posibles por esta situación, pero normalmente estoy activo desde medianoche cuando el internet esta normal, y si es posible trabajar en rainforest. Parece que Cantv no sabe manejar la sobrecarga y por eso hay problemas en horarios diurnos.

**Comment by carlosds7** [comment]
@RnkSts Hoy estuve activo todo el dia, y no me llego ni un trabajo, despues de las 12 llegan trabajos de rainforest?

**Comment by RnkSts** [comment]
@RnkSts No te puedo decir a que hora salen los trabajos ya que eso depende de los "Clientes" de rnfrst y la cantidad de trabajadores activos, lo que si puedo decirte que a eso de las 3am-4am en adelante es cuando **más** trabajos recibo, aunque pueden salir a cualquier hora.

**Comment by carlosds7** [comment]
a ok, ahora mismo me llego un trabajo, y no carga.. @RnkSts

**Comment by carlosds7** [comment]
A ok, ahora mismo me llego un trabajo, y no carga el terminal.. @RnkSts

**Comment by RnkSts** [comment]
@carlosds7 lo mejor es que desactives la extensión por ahora y esperes a que se arregle el internet en un rato, ya sabras que esta bien cuando cargue rápido los contenidos (puedes ver en facebook el tiempo de respuesta por ejemplo), al parecer el problema solo afecta ciertas paginas.

**Comment by nuevao** [comment]
Hello, who can continue with the problem, there is a temporary solution (hopefully) use VPN to connect to servers rainforest, so far is the simplest solution. Or the second option, change ISP obviously complicated for some of us. Greetings.

**Comment by zfonck123** [comment]
vpn ? but its legal use the vpn ? cf ban permanent if use vpn :/

**Comment by nuevao** [comment]
right, in CF, but "Rainforest" is not "CF", to my knowledge it is allowed, if you want to review the rules "[Wiki](https://github.com/rainforestapp/tester-chrome-extension/wiki)" and reviews, fortunately I found no problems.

**Comment by RnkSts** [comment]
@zfonck123 you can keep rainforest in other browser (if you want to use VPN) different to CF. You can install Chromium and disable Sync to use rainforest with VPN, and work to CF in Chrome, or use Firefox and Chrome together.

**Comment by carlosds7** [comment]
@RnkSts Eso de cambiar la VPN servira?

**Comment by RnkSts** [comment]
@carlosds7 No lo he probado, ya que desde hace 2 dias no tengo problemas para cargar la VM, pero puedes intentarlo tranquilamente a ver si te sirve, siempre y cuando no entres a CF con VPN activo.

**Comment by nerdatwork** [comment]
@carlosds7 @RnkSts Please use English when posting replies if you want Rainforest staff to help you.

**Comment by nuevao** [comment]
I think this case can be closed, apparently the problems were not RainForest, and already solved.
