### ISSUE TITLE
Display notification and/or blink a tab when new work is loading

### ISSUE THREAD

**Issue by ChrisRaven** [rainforestapp/tester-chrome-extension#613]
I see, that in the future version of the extension there will be a sound notification.

It would be nice, if there would be also an option to display a notification (e.g. for those who have sound turned off). Such simple code should be enough:

```
var notification = new Notification('Rainforest: New test', { icon: 'icons/icon48.png' });
setTimeout(function () { notification.close(); }, 3000); // to close the notification after 3s, otherwise it will be displayed permanently
```

Also, an option for blinking a tab would be useful. A code for this could look like this:

`chrome.windows.update(-2, {drawAttention: true});`

Although, I'm not sure, how to select the right tab. "-2" in the above example refers to the currently visible tab.

The best solution would be to add an options panel, when one can select, what kind of notification he would like to see (with checkboxes, so one can select none of the options, one of them, any two, or even all three possibilities).

Choosing an mp3/ogg file for the sound notification would also be a useful option in that panel.

**Comment by helloworld111gh** [comment]
The extension is open source, why not send a PR that adds that?

**Comment by ChrisRaven** [comment]
Because I don't know, how to do such panel. Also, I don't know how to choose the right tab to blink and how to store the selected audio file.
I've only given some pieces of code. If one with more knowledge in the topic can use it, it will be nice.

**Comment by sweeneyapps** [comment]
I would rather to wait this out..    Sound support is coming soon along w/ new options page.   Also new forum for all testers to discuss stuff.  The forum will be a good place to rally on suggesting new features.   If all testers want that options..  I will work on it in the future.

**Comment by JrRandy** [comment]
Sound support is here @sweeneyapps :)

**Comment by sweeneyapps** [comment]
yeah, just noticed this morning.  :)
