### ISSUE TITLE
Notification sound, can repeat more 100+

### ISSUE THREAD

**Issue by RafaelBelmontes** [rainforestapp/tester-chrome-extension#617]
![image](https://cloud.githubusercontent.com/assets/22337927/18770977/ed6efd3e-8108-11e6-8708-3a04cbdd242d.png)

![image](https://cloud.githubusercontent.com/assets/22337927/18770991/1d67078e-8109-11e6-8874-d92cfc8fa9c0.png)

![image](https://cloud.githubusercontent.com/assets/22337927/18771010/52ea668a-8109-11e6-9c78-bd81acfa81dd.png)

**Comment by JrRandy** [comment]
FYI - The number disappears on my screen when I run a zoom of 67%.  The box does not seem to scale very well :)

**Comment by shosti** [comment]
Ummmm... just don't set it to 100?

**Comment by JPierreS** [comment]
I notice you can set it to negative values too, such as -100, does that mean the sounds play in reverse ? ;-)))

**Comment by sweeneyapps** [comment]
@JPierreS lol... I'll do a PR soon to prevent the sound repeating when tester already started a job and also whenever WIP is dropped due to error.    Yup the extension will not play the sound if the value is less than 1.

**Comment by shosti** [comment]
Will add some limits.
