### ISSUE TITLE
 alarm

### ISSUE THREAD

**Issue by tulko** [rainforestapp/tester-chrome-extension#619]
we have alarm should not automatically turned off

**Comment by qpPykT** [comment]
What do you mean?

**Comment by androwg** [comment]
i think it should give an alert when there is an actual work not just another worker message

**Comment by tulko** [comment]
@androwg if the extension is not turned off I'm happy

**Comment by nerdatwork** [comment]
@tulko Even though sound notification is implemented the idle time policies are still in place. You cannot expect the extension NOT to turn off just because now it has sound. It is to make sure only the active testers are getting jobs.
