### ISSUE TITLE
Rejection (despite restart the job)

### ISSUE THREAD

**Issue by jguerrero2** [rainforestapp/tester-chrome-extension#624]
I made a mistake in a control question and I noticed just right after to answer the last step,  the "Restart Job" button was no longer available so I had to do it with F5,  I started working once again but this time I reported a bug in the second step.  When I check my profile I see the rejection and in my history page the hit with all steps instead the hit that was reported in the second step.

Why the rejection if the hit was restarted?
If the control question is the last step of the hit, I have no option to correct and start once again?

**Comment by ahad5** [comment]
I also have a security question rejection in the 4 step, but I did not see this step because I sent a report (login error) in the third step. Btw, I have not restarted the job.

**Comment by sweeneyapps** [comment]
this is only for extension only.  If u have problem with rejections,  u can submit a support ticket.   And don't forget to close this issues.   Thank you :)
