### ISSUE TITLE
Problem with extension

### ISSUE THREAD

**Issue by VeryDisappointedTester** [rainforestapp/tester-chrome-extension#629]
![extension 3](https://cloud.githubusercontent.com/assets/22333356/18870220/f30086dc-84af-11e6-93c3-4da1622e0cca.png)

**Comment by JrRandy** [comment]
Disable extension, log out of portal, log back into portal, and re-enable extension.  This resolves the failed fetches for me.  I think the cookie expires or something that the extension is trying to pull.

**Comment by VeryDisappointedTester** [comment]
Tnx for the info. I did that already. They need to put some kind of visual warning that something is wrong with extension. Its really annoying to keep open window with console all the time if u want to get at least some work.

**Comment by 2codefast** [comment]
Error 400 here, same problems, no hits and console is all red.
Even after so much changes problems in fetching are still present, 2$ a day for 5$ of spent electricity just to look at extension errors, dont think so.

**Comment by shosti** [comment]
When you look at the javascript console do you see any specific messages?

Also if you let me know your contributor ID I can look into it.

**Comment by ivijulsc** [comment]
I'm having the same problem.
Have to uninstall and install the extension two times every day becouse it bugs and console is all red. The problem is that it happens randomlly and i dont have console opened all the time... So sometimes i'm in the PC waiting for a HIT, and when i open console i see that a was buged for hours.
My ID is 36973932

**Comment by VeryDisappointedTester** [comment]
Again same problem
![extproblem](https://cloud.githubusercontent.com/assets/22333356/18990409/f4d5db06-8711-11e6-94e1-e71648e4d587.png)
My ID 34240529

**Comment by shosti** [comment]
Sorry I meant the "console" tab in the inspector.

**Comment by VeryDisappointedTester** [comment]
My fault. You said console in the first message. It is too late now, i already re-installed extension.  If problem appears again i will put a a picutre with console.

**Comment by JrRandy** [comment]
When its happened to me, it has stated "ERR_FILE_NOT_FOUND" and a log out and log back in to the portal worked to fix it.  I think the cookie is expiring, or being deleted or whatever the case may be (Assuming that the extension is pulling a cookie)

**Comment by cookin2** [comment]
Here is my console tab, I hope I copied the right thing.  My email is blanked out.

<a href="http://tinypic.com?ref=33eiveh" target="_blank"><img src="http://i66.tinypic.com/33eiveh.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by JrRandy** [comment]
@cookin2 - Turn off extension, log out of portal, log back into portal, and turn extension back on.  Confirm this works for you as well, as that is the same error I have seen.

**Comment by shosti** [comment]
@cookin2 can you email me a screenshot of the whole thing without blackouts? (Email is emanuel@rainforestqa.com) It's important to get the full URL.

**Comment by cookin2** [comment]
It's the same.  I delete extension, log out and back in, install the extension from the portal page and watch the index like a hawk :)  I have the extensions page bookmarked!

**Comment by cookin2** [comment]
@shosti   Sent it!

**Comment by shosti** [comment]
https://sentry.io/rainforest-1/tester-chrome-extension/issues/164941933/
