### ISSUE TITLE
You must use your legal name when signing or you risk your account being blocked.

### ISSUE THREAD

**Issue by roko777** [rainforestapp/tester-chrome-extension#631]
### You must use your legal name when signing or you risk your account being blocked.
where should I enter my name? In my account (portal.rainforestqa.com) ???In my account, for a long time already, and name and phone number.
You have had this inscription?

![1](https://cloud.githubusercontent.com/assets/16417121/18889782/22f8e2f6-8507-11e6-8267-7043ea29dd6e.jpg)

**Comment by awnosa** [comment]
same problem

**Comment by qpPykT** [comment]
@roko777 
When you signing NDA. 

@awnosa 
It's not a problem just reminder.

**Comment by NICOSYSTEM3** [comment]
SAME PROBLEM
![image](https://cloud.githubusercontent.com/assets/22378777/18892311/13d8ac0a-84d7-11e6-8e94-c3a5e86853ea.png)

**Comment by helloworld111gh** [comment]
This is not an issue, it's just a reminder that you have to use your real
name when you sign legal documents.
Please close this thread.
