### ISSUE TITLE
Only training jobs...

### ISSUE THREAD

**Issue by irishclouds** [rainforestapp/tester-chrome-extension#632]
In the last week i have many training jobs, today only 2 normal jobs with 2 steps and around 25 training jobs, same issue for yesterday, it's boring to do it, forever the same. Someone have the same problem?

**Comment by nerdatwork** [comment]
How many rejections did you get in last couple of days ?

**Comment by 2codefast** [comment]
Same here, no real work just tic tac and bingo, only in the morning do i get some 3 or 4 jobs that are real jobs, everything else is just bingo etc.
And no rejects for more than 2000 tasks.

**Comment by overx24** [comment]
today got 30+ training jobs and 3 times Your training is complete! but still get training

**Comment by nerdatwork** [comment]
@irishclouds @2codefast @overx24 The purpose of putting you in a training sandbox is to make sure you are doing every task as instructed and get trained well enough to work on real jobs.
