### ISSUE TITLE
157 step really can done in one hour ?

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#633]
![image](https://cloud.githubusercontent.com/assets/19192312/18923911/23f27a62-857c-11e6-902f-2260b33f1067.png)

**Comment by Genesis2015** [comment]
I finished it in about 30-35 minutes :)

**Comment by JrRandy** [comment]
Typically those fail out around step 50'ish, but if the terminal is working properly than yes 150 steps in under an hour is doable.

**Comment by zfonck123** [comment]
oks i will try finish it :D thx
