### ISSUE TITLE
Unfair rejection by report error 404

### ISSUE THREAD

**Issue by CharlieSpock** [rainforestapp/tester-chrome-extension#639]
![2a2](https://cloud.githubusercontent.com/assets/20996862/18980976/eaf9c2b0-86a7-11e6-80c3-7856e1f9d0b3.png)

i report that are not online to download and system take me to a bab job its look like any not refresh the old links i add 5 unfair rejection for this and all traning have same issue for me

**Comment by Angelituss** [comment]
I have the same problem and do not give me a solution.

**Comment by marius11** [comment]
Have you tried copy/pasting the link again? I rare cases, pasting inside the terminal might not done properly; a character from the URL might be ignored while pasting.

**Comment by nerdatwork** [comment]
@CharlieSpock Did you file a support ticket ?

**Comment by maciejgryka** [comment]
I'm fixing this (and will revert any unfair rejections people got), but this isn't really the right place to report things like that @CharlieSpock. Please open support tickets in such cases, like @nerdatwork suggested.
