### ISSUE TITLE
CI/CD for extension

### ISSUE THREAD

**Issue by jbarber** [rainforestapp/tester-chrome-extension#64]
This is a note for when we want to do full CI/CD of the extension, at the moment uploading to the app store is a manual process because generated auth tokens are only valid for 40 minutes (see just above [this part of the docs](https://developer.chrome.com/webstore/using_webstore_api#usingtheapi) and [this](https://github.com/rainforestapp/tester-chrome-extension/commit/959579682b54b126c7fd6f12f1cc811f33acaa36/deploy.sh#diff-60254338249f657a0a83f98258a56bfeR3)).

To overcome this, we probably have to use one of the API SDK and store the refresh token
https://developers.google.com/api-client-library/ruby/guide/aaa_oauth

The python version of their library is prod, so it's probably better to use that.

[![Issue 64](https://plusone-demo.herokuapp.com/count.svg?repo=rainforestapp/tester-chrome-extension&issue=64&sig=140ec626a3f89e5bfd720b05d35ae457f4f3cd068b656d80caeecdcca96d7664d7492b8201f9555cb15d20370495d0d01ecf7ac6e94c3b41baa8ebcc855319e5)](https://github.com/rainforestapp/tester-chrome-extension/issues/64)

**Comment by ukd1** [comment]
@jbarber I looked at this and got it working ...but i couldn't get the refresh token working. Apparently it's possible to get an offline token but I've not figured out how.

@campoy can you help or point us in the right direction for this? We'll trade you guys a blog post!

**Comment by campoy** [comment]
It seems like you should be using the refresh token that you obtain if you plan to use it after 40 minutes.

**Comment by ukd1** [comment]
@campoy we're trying to do this in CI, so storing a token and doing this every 40minutes is actually non-trivial. Is there anyway to get an offline / permanent / long-lived token?

**Comment by jbarber** [comment]
We can get the refresh token via the [oauth2 playground](https://developers.google.com/oauthplayground), the chrome store scope is https://www.googleapis.com/auth/chromewebstore. I don't see how to use these tokens with the various google API libraries though.

It looks like we can use the ruby gem [googleauth](https://github.com/google/google-auth-library-ruby) and the code:
```
require 'googleauth'
scopes =  ['https://www.googleapis.com/auth/chromewebstore']
ENV['CLIENT_ID_VAR] = ''
ENV[CLIENT_SECRET_VAR] = ''
ENV[REFRESH_TOKEN_VAR] = ''
authorization = Google::Auth.get_application_default(scopes)
# or maybe Google::Auth::UserRefreshCredentials.make_creds()
```

I think the credentials for API can be obtained via the [dashboard](https://console.developers.google.com/apis/credentials), but I don't have access. @ukd1 can we pair up later and see if we can generate the appropriate secrets?

**Comment by ukd1** [comment]
+1 to getting this done

**Comment by campoy** [comment]
I'm actually not very familiar with this API - but if you're interested I
can try to get you in touch with someone from that team.

**Comment by ukd1** [comment]
@campoy would swap for a blog post on it!

**Comment by ukd1** [comment]
@campoy ping! Did you have any luck?

**Comment by campoy** [comment]
An internal conversation is currently going on (since yesterday, sorry) and I'll keep you updated as soon as we have an expert that can help you ;)
