### ISSUE TITLE
A security error occured.

### ISSUE THREAD

**Issue by syakiersalleh** [rainforestapp/tester-chrome-extension#646]
It's been more than two weeks by now, the security error through the VM is an unstoppable issue. I have sent tickets to Rainforest, but the issue is not be resolved. There is no any new hit more. Anyone here facing the same problem as me? How do you resolve this problem?

**Comment by sweeneyapps** [comment]
it has to do w/ flash security sandbox violation.  Hopefully RF will response here or ur support ticket.   Otherwise, they are planning to replace Flash w/ HTML5.   That should solve the security error problem ASAP.

**Comment by nerdatwork** [comment]
@syakiersalleh Rainforest is working on a new system which will eliminate **almost all** errors and every tester will be pleasantly surprised. Keep the faith and _happy testing_.
