### ISSUE TITLE
64bit chrome browser Seems Not Compatiable with Rainforest Extension

### ISSUE THREAD

**Issue by manishflyboy** [rainforestapp/tester-chrome-extension#65]
I recently installed Chrome 64 bit browser and Rainforest extension after which for every hit i got the message 

Ooops Something Went Wrong on Our Server.

Links are attached for your further needful action.

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cxff28bb-b9fc-42d4-8f0a-e695f36d4fdb&browser=any&hitId=4570949&sig=ce76a3c892dd2c8435f19e881b542d5bb1f67f31855d4c7df3794ba6a0aa2385&turkSubmitTo=%2Fthanks&workerId=33361128

https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx509452-8ed5-4478-9482-771c65d6ac8c&browser=any&hitId=4530282&sig=240cdb9f25dfebecacdad3bd428a359676108ff3f509ff95a27326ddb5fd07b3&turkSubmitTo=%2Fthanks&workerId=33361128

**Comment by jbarber** [comment]
This is not a problem with Chrome. The issue is that the job has already been completed by the time you tried to do it.
