### ISSUE TITLE
Idle timer - maybe not working right?

### ISSUE THREAD

**Issue by cookin2** [rainforestapp/tester-chrome-extension#650]
I was reading, using the scroll bar and I got timed out.  I wasn't idle.
I was writing email - typing, and I got timed out.
I was using the touch screen because it's faster on some CF tasks.  I check things off, submit pages, etc and I time out.  I can understand why the touch screen isn't picked up.
I read that the idle program is supposed to pick up mouse and keyboard actions.  If this is true it should pick up when I use my mouse to scroll and when I use the keyboard to type?

**Comment by nerdatwork** [comment]
Were you doing that all in a single step ?

**Comment by cookin2** [comment]
No, they were separate.

**Comment by sweeneyapps** [comment]
@cookin2 did you do CF Tasks on Chrome and idle still happen?

**Comment by cookin2** [comment]
When I used the touch screen - yes.
I was reading the CS forum and using the mouse via the slide bar to scroll when it timed me out and I didn't realize it right away.

**Comment by pscohn** [comment]
I'd recommend not reading other websites while doing jobs - if you just stay on the job and actively work on it you shouldn't have a problem. Also we don't officially support using touch screens, so you should have a better experience on a computer.

**Comment by cookin2** [comment]
When I get work, I'm thrilled and stay right with it until it's done.
Thank you for the help and advice :)
