### ISSUE TITLE
Extension just stopped pulling

### ISSUE THREAD

**Issue by NeoWorker** [rainforestapp/tester-chrome-extension#652]
Guys, my extension just stopped pulling work. It stopped pulling a few minutes ago, I even reinstalled the extension but the problems persists.

Here's a pic of the extension's activity:
![developer tools - chrome-extension --immdjpjbcikbffjifkbncgfbohbjicpo-index_prod html_022](https://cloud.githubusercontent.com/assets/17706572/19050423/8343adac-897c-11e6-9910-f7cf25a6fb26.png)

Look at the first row, it's still 'Pending'.

And when I tried to restart the extension, I hear the notification sound, but I don't get any work, lol.

Is anyone facing this problem?

**Comment by clessweapon** [comment]
same here

**Comment by shosti** [comment]
This is expected behavior ("pending" means that it's connected over WebSockets). We're beta-testing "push-mode" for some workers; in push mode you won't see any polling requests, but you should get the normal amount of work.
