### ISSUE TITLE
Extension does not work

### ISSUE THREAD

**Issue by NICOSYSTEM3** [rainforestapp/tester-chrome-extension#655]
Good.
They have already spent more than 1 hour not receive blows of the extension.
Turn it off, nothing, then uninstalled, nothing, when I went to install again, the doorbell rang for a new job and did not open or tab or anything just rang.
Someone has been the same?
Anyone know how to fix it?

**Comment by tulko** [comment]
I have the same problem.

**Comment by NICOSYSTEM3** [comment]
and if you do not work, just still on.

**Comment by euparkeria** [comment]
After my extension switched completely to websockets a few hours ago I haven't gotten a single HIT. This is very abnormal for this time of the day.

**Comment by tulko** [comment]
@euparkeria as you know your extension change to ws
@ukd1 please help id 29649019

**Comment by erdeminofff** [comment]
It looks working now. But it doesn't take response from websocket server. I think they are still working with that.
![new bitmap image 25](https://cloud.githubusercontent.com/assets/8877357/19054444/18dce6e4-89c8-11e6-93e0-dec7054f54c9.png)

**Comment by tulko** [comment]
@erdeminofff  how you see that information

**Comment by erdeminofff** [comment]
chrome://extensions/, check developer mode checkbox , click "index.prop.html", you can see all activities about extansion in Network tab

**Comment by euparkeria** [comment]
My extension just started polling again and I got the first hit in hours.
