### ISSUE TITLE
Http Status 500 

### ISSUE THREAD

**Issue by VeryDisappointedTester** [rainforestapp/tester-chrome-extension#665]
This error is on almost every hit for hours.
![http status 500](https://cloud.githubusercontent.com/assets/22333356/19116948/8d140538-8b17-11e6-9f41-8c4bc1fd795d.png)

**Comment by JrRandy** [comment]
Thats an issue on the client side, as I had the same error after logging in to the site but was able to complete tests for other clients with no issue.  As this board is for issues with the extension, please close this as it is not related to the extension in any way.

**Comment by VeryDisappointedTester** [comment]
Finally stopped. Some people got 50-60 hits and all are reported on log in step.
When this happens Rainforest should stop hits from client until their problem is solved. It is impossibe to get normal hit when these hits pop-up every minute.
Btw 70% of issues are not related to extension.

**Comment by marius11** [comment]
@VeryDisappointedTester I don't want to disappoint you, but that's not how testing works. You're basically saying that a client should be removed for the same reason that the client is relying on Rainforest: to report bugs/unexpected problems.

I'm surprised you haven't been banned from this GitHub page because of your username.

**Comment by VeryDisappointedTester** [comment]
I'm saying that hits should be stopped until clients fix their server problems. When their server is down for 4 hours this is not bug or unexpected problem.  
Well, it is a problem but they dont need testers to tell them that their server is down.

**Comment by begsoon** [comment]
Our job is to report it with ''NO''.We don't need to talk them what to do.


Salute

**Comment by marius11** [comment]
The server isn't down. Parts of the code are throwing exceptions after certain events happen. This can also happen while testing software.
