### ISSUE TITLE
comma scenario

### ISSUE THREAD

**Issue by kwimy** [rainforestapp/tester-chrome-extension#667]
Extracted from last AMA (September)

If the instructions say Click on the first property. Do the headers say "Example Header 1" and "Example Header 2"? and the headers do say that, but a comma separates them, answer Yes. The headers are both displayed exactly how you see them in the quoted instructions. The comma is not part of either header, it is just separating the two.

What if instead a comma the headers are separated by or ?

I just found a similar scenario to that of example.
The question say: view at the field "Your name" but the page field said: Your name or business name

I've reported because there is no match between the quoted text of the instructions and what I see on the page but I could have applied the rule of the comma, I guess...or rule only applies if they're separated by a comma? and if they're separated by a hyphen one point or everything else, not the rule applies?

**Comment by JrRandy** [comment]
IMO, the comma scenario would not apply as the comma scenario references headers as in plural, and yours references a single field.  The field is not named "Your name" it is named "Your name or business name".  If it stated 'View the field the starts with "Your name" then it would apply.  Again, just my opinion.

**Comment by mariaelite** [comment]
This change of rules and exceptions, are beginning to be confused because they are every month.

**Comment by kwimy** [comment]
And what if instead a comma the "Example Header 1" and "Example Header 2" are separated by a hyphen a point or anything else other than a comma? Comma rule is then applied or not?
