### ISSUE TITLE
Issue : Extension always off, help please !

### ISSUE THREAD

**Issue by mueller01** [rainforestapp/tester-chrome-extension#669]
Issue : Extension always off, help please !

**Comment by nerdatwork** [comment]
Try reinstalling extension, if it doesn't work try reinstalling Chrome too. Login to Rainforest account then try turning the extension ON.

**Comment by qpPykT** [comment]
@nerdatwork  
I have some problems with extension it's just stops sending requests for check available hits. 
Disable and enable extension a few times from extensions page - it help with this but it's so annoying. I can't detect why it stops sending requests.

**Comment by nerdatwork** [comment]
@qpPykt You wont see any polling if you are from a batch of testers for whom socket mode HITs are activated. It is a good thing btw. 90% less red banners.

**Comment by qpPykT** [comment]
@nerdatwork I know preassignment with socket mode works very well. But I get very rare preassignment hits mostly I get just assignment hits.

**Comment by mueller01** [comment]
@ nerdatwork, I already try what you ask me to do, when I click extension, even though I already logged in profile, pop up always ask me to log in.

**Comment by Justtestiing** [comment]
Same problem here with extension.  Need to remove it and install it again to work. In last 5 hours had only 1 hit. The issue here is extension is not polling jobs, the moment i remove it and install again i get another worker thingy ...i close that after few minutes and extension just stops to work. So i just repeat the process with reinstall and yes instant after that i get another worker....

**Comment by JrRandy** [comment]
Also make sure you have an active account with RF.  I know this sounds silly, but it would not be the first time someone with a blocked account came complaining that they cannot get the extension to turn on :)

**Comment by mueller01** [comment]
profile is active

**Comment by mueller01** [comment]
should we sent a ticket for this issue ?

**Comment by JrRandy** [comment]
Do you know how to open the developer tools console?  If so, can you screenshot that and post?  A ticket will take a few days from what I have heard, lets see if we can diagnose whats going on.

**Comment by mueller01** [comment]
Do not know about developer tools console

**Comment by mueller01** [comment]
May be this ?
![dev](https://cloud.githubusercontent.com/assets/22122367/19167693/0c3869ce-8c37-11e6-82d4-c892ea0ae066.png)

**Comment by sweeneyapps** [comment]
Try this step:
1. disable extension.  
2. go to portal.rainforestqa.com/profile  and logoff.    
3. Then enable the extension and wait a few seconds to let it load.
4. back to portal.rainforestqa.com/profile to login.
5. click extension icon.  

let me know what the notification say.

**Comment by JrRandy** [comment]
Yes, switch to the "Console tab"

**Comment by mueller01** [comment]
Console tab is blank

**Comment by sweeneyapps** [comment]
JrRandy is incorrect.   It is not the right way to debug the extension.

**Comment by mueller01** [comment]
![dev 2](https://cloud.githubusercontent.com/assets/22122367/19167811/7ce3972a-8c37-11e6-962f-6dea0c534d07.png)

**Comment by sweeneyapps** [comment]
@mueller01 

Try this step:

1. disable extension.  
2. go to portal.rainforestqa.com/profile  and logoff.    
3. Then enable the extension and wait a few seconds to let it load.
4. back to portal.rainforestqa.com/profile to login.
5. click extension icon.  

let me know what the notification say.

**Comment by mueller01** [comment]
@sweeneyapps , It same happen, extension still ask to log in.

**Comment by sweeneyapps** [comment]
@mueller01  ok, it has to do something with extension not picking up auth info from Rainforest portal.

**Comment by rnfrst** [comment]
@mueller01 , when was the last time you did RF hit? From 2014? That must be the reason why your extension is not working.

**Comment by shosti** [comment]
@mueller01 let me know your contributor ID and I'll look into it.

**Comment by shosti** [comment]
@mueller01 it should be fixed for your account now; let me know if it's still an issue and I'll reopen the ticket.
