### ISSUE TITLE
Issue : There is no a link in my portal profile page to install extension.

### ISSUE THREAD

**Issue by mueller01** [rainforestapp/tester-chrome-extension#673]
![no link](https://cloud.githubusercontent.com/assets/22122367/19171604/cc736206-8c47-11e6-80f1-3de26a642b71.png)

**Comment by Valdetecm** [comment]
When was the last time you did a job for rainforest?

**Comment by JrRandy** [comment]
Could be due to your other blocked account as per your issue you posted in #509 .  Will need an admin to address your issue I think.

**Comment by mueller01** [comment]
It same account, Mueller is generated name before I change be ikonyo

**Comment by shosti** [comment]
@mueller01 OK I looked into it and it should be fixed. This may be an issue for other workers, so I'll fix it for everyone.

**Comment by roko777** [comment]
I updated the plugin.
In place of button inscription.
![3](https://cloud.githubusercontent.com/assets/16417121/19175696/a6fa1a3e-8c41-11e6-8977-8af292783d08.jpg)
**Thanks for installing the Chrome Extension!
Please edit your profile to change extension options.** Is this normal? Why disappeared plugin button?name Vladimir (I change it be roko)

**Comment by JrRandy** [comment]
Yes, its normal that if you have the plugin installed the button changes to a thank you.

**Comment by roko777** [comment]
It used to be different.  the plugin was installed and the button too)))
thank you.

2016-10-07 4:18 GMT+03:00 JrRandy <notifications@github.com>:
