### ISSUE TITLE
Websocket Testing

### ISSUE THREAD

**Issue by JrRandy** [rainforestapp/tester-chrome-extension#674]
I am apparently in the websocket test group, and have an issue.  "Something bad happened" error still occurs, and in the past 2 mins max, I have gotten at least 6 windows pop open with the error.  It appears that the websocket starts to spam windows if it hits a red error message.  Not sure if this is as designed or not, but figured it worth mentioning.  Not sure what the impact on the backend might be.

**Comment by JrRandy** [comment]
Job finally came through after I dont even know how many tries, and it was a 2 step training job.  Talk about disappointment lol

**Comment by shosti** [comment]
I think this was a bug on our part that was fixed recently. Sorry for the inconvenience.
