### ISSUE TITLE
Refreshing gives "You are using an outdated version of our Chrome extension."

### ISSUE THREAD

**Issue by 2codefast** [rainforestapp/tester-chrome-extension#677]
Refreshing gives this message.
What does extension have to do with refreshing?? 
**Extension is not giving any work, and now this.**
P.S Extension is the latest, and its not turned on.

**Comment by Genesis2015** [comment]
I can't find the link to the new version of the extension in my portal page :(

**Comment by shosti** [comment]
You can no longer refresh old links; please update to the latest version of the plugin (2.0.2) and wait for it to assign you jobs.

**Comment by 2codefast** [comment]
Links are from latest "sound" version, you want to say they are not valid?

**Comment by shosti** [comment]
@2codefast it should work fine; if you run into the error again, please paste the link you got here.

**Comment by 2codefast** [comment]
Nope, tryed few of them randomly, they are dead as dodo.
Double checked they are all links from the new 2.0.2 version, i see others also have issues with this sudenly.

**Comment by shosti** [comment]
@2codefast sorry to be clear, you can't reuse links any more. Every time the extension gives you a link, it will be for a unique job and won't be reusable.

**Comment by 2codefast** [comment]
@shosti Oh so in future, all links that ext gives us will not be usable, ok.
So 2$ daily will be bingo. Thank you

**Comment by JrRandy** [comment]
@shosti Are we websocket across the board now?

**Comment by shosti** [comment]
@JrRandy yes.

**Comment by JrRandy** [comment]
@shosti Awesome!  Can you peak at #674 and see if that is expected behavior?  If so I can close it.
