### ISSUE TITLE
Could not get a _ machine

### ISSUE THREAD

**Issue by Valdetecm** [rainforestapp/tester-chrome-extension#678]
This message is coming all the time when i get a hit, and it takes forever for me to get a machine

**Comment by Valdetecm** [comment]
Just gor a Job abandoned because i couldn't get a machine

**Comment by MarinaCec** [comment]
same here, every hit 

Could not get a safari_1440_900 machine.

**Comment by Genesis2015** [comment]
Same story here :(

**Comment by Electroglitch** [comment]
Got the terminal but after 4 or 5 clicking the restart job button ,not to mention i waited like minute between every click/restart 
so it's ok except i waisted like 5 mins waiting

**Comment by kwimy** [comment]
Same as @Valdetecm happens to me.

**Comment by Valdetecm** [comment]
Now Failed to fetch

**Comment by hunt40** [comment]
i got from one of them right now and tried 3 time and waited long enough and i got job abandoned,your terminals have problems i got job abandoned not fair at all

**Comment by VeryDisappointedTester** [comment]
Just now  "Could not get a chrome machine" for 6-7 minutes.

**Comment by 2codefast** [comment]
Counted 18 Restart Job until i got past Could not get a osx_firefox machine to get the job started. 
And VM is stil unresponsive even its loaded. hmmmm

**Comment by hunt40** [comment]
another one i hope i get it this time.still could not get

**Comment by VeryDisappointedTester** [comment]
Everytime i think "Thank God it is finally over" Rainforest keeps surprising me.
Now we have to restart job like 20-30 times.

**Comment by kwimy** [comment]
Job Abandoned again after refreshing Could not get a_machine several times.

**Comment by hunt40** [comment]
i hope this job abandons not counted againts us,all fault on their side ,i close the extension after 2 error,i am done with them for today,

**Comment by JrRandy** [comment]
High VM load
Incident Report for Rainforest QA
Investigating
We are investigating an issue with the VMs due to high load. We will keep you posted in updates.
Oct 7, 14:06 PDT

**Comment by JrRandy** [comment]
Abandon's do not negatively affect your account at this time (As I believe @kristen-allie stated about 7 times in the September AMA :))

**Comment by MarinaCec** [comment]
Could not get a chrome machine.


it come back...
