### ISSUE TITLE
Blocking policy #66  @pscohn reopen or merge, thanks.

### ISSUE THREAD

**Issue by ando100** [rainforestapp/tester-chrome-extension#68]
@pscohn Paul, let me do a walkthrough for you to end with beautiful solid Block..
Step1. Tester gets a hit through extension and it shows for example 10 steps, but tester 
can not open or click on it, because screen turns to:
We`re sorry, having too many concurrent users etc.. please try again later.
Step 2. Tester waits few minutes 
(timer is ticking 10/15 minutes)
Step 3 Tester retries.
Same issue- tester can see that test has been assigned, but getting message-
Sorry, we have too many...
Step 4.
Tester is already worried checking timer and all clocks available, then scratching his/her head. Having
glass of cold water perhaps. Waits.
Retry. Again out.
Step 5.
Tester waits a little more- then gives it another, the last try, hands are shaking,
blood pressure- code red- click with mouse and
Bang
You have requested this job too often, please return...

WWW- what went wrong?
referring to:
Headline: Examples of bad behavior that will result in a block:
Answer: Accepting jobs and failing to start them in a timely manner.

Tester accepted the job/ task but failed to start it, not depending
his/ her actions.

Please prove me wrong :)
Thanks.

**Comment by pscohn** [comment]
Responded to this in the other issue.
