### ISSUE TITLE
How will you know If Your Extension is Good to go.

### ISSUE THREAD

**Issue by zykezzz** [rainforestapp/tester-chrome-extension#680]
Hello there im just concerned because unlike before you can see and know if your extension is working fine thru polling on the developer tab. Right now im still wondering whether the extension is connected to the server or doing fine or if its stuck with an error. TIA

**Comment by sweeneyapps** [comment]
pretty much, if the icon is green...  it's working and connected w/ the server.   If you don't trust the icon...  it's ok to click on it twice and see if it turn green again.   If it turns green again then it's still in communication with the server.

**Comment by zykezzz** [comment]
Ok. Thanks for the reply. I really appreciate it. Actually i just had some trouble with it, i tried turning the extension off but it wont. it just stayed green and wont even change after a few clicks. But its fine now because of your answer. I will just use the old secret method of Uninstalling and installing the extension. Hehehehe. Thanks again

**Comment by erdeminofff** [comment]
There is actually an easy way. You can check ip adress of rainforest servers from Command Prompt. Go to Start and find and open "cmd". Then write "netstat" command. Check active connections. If you see 104.20.86.108 (I hope so) in Foreign Adress column in 2 minute, that's mean it's active.

**Comment by qpPykT** [comment]
@sweeneyapps 
I did not get any hits since the Rainforest completely switched to websocket. Extension with green icon and ver 2.0.2 but it's not open any new tabs with hits.

**Comment by hunt40** [comment]
i dont know how they distributed this hits but its ridiculous if some people get few hit after 4-5hours ,like i get just 1 hit today and reported and plus bug not add up,so while i am doing my honest job i still got shafted,its look very grim and not looking good some people get more hits via socket and some other get half of it or even less while doing proper job,they have to look into this how spread the jobs.

**Comment by VeryDisappointedTester** [comment]
According to Rainforest statistic 27 active testers did 500 hits in 3 minutes. Just look at the numbers on the RF site.
It is not possible that only 27 testers are active at this time. Also it is practically impossible for 27 testers to do 500 hits in 3 minutes.
Number of test runs keeps climbing even when there are no hits for hours and with only 15-20 active testers. Something is wrong here.

**Comment by zfonck123** [comment]
8 hours not jobs.....   and only 27 tester online ? what happened ?  @pscohn  @kristen-allie   :(

**Comment by zfonck123** [comment]
![image](https://cloud.githubusercontent.com/assets/19192312/19189144/4160e18a-8c64-11e6-9bda-9ad14cd9f19c.png)
  normal is 1000+ online

**Comment by VeryDisappointedTester** [comment]
Number of created runs is still climbing but at much lower rate. Many of us are not getting any hits but numbers keep climbing.

**Comment by erdeminofff** [comment]
I think it's now showing correct values. Old system it was shownig testers who extension is active. So number of free/active testers. Now system changed and it showing active testers who are testing website now.

**Comment by zfonck123** [comment]
that suck   30 tester of 1800 soo bad

**Comment by zfonck123** [comment]
....... 30/1800 tester...... ITS GREAT!!!!!! SARCASM!"!!!!!

**Comment by VeryDisappointedTester** [comment]
I would like to hear about this from RF staff. Is this true?

**Comment by zfonck123** [comment]
i dont know if that is true. but the update  dosent work...

**Comment by ellmirr0001** [comment]
extension works fine, im reciving hit after hit. did not encountered any problem

**Comment by begsoon** [comment]
Most of testers,didn't received any hit..almost 2 hours of nothing :D

**Comment by sweeneyapps** [comment]
yeah extension works as long you are seeing green leaf icon.  For some reason, if you don't trust the icon, you can click it and see if it changes.   If it changes to OFF then you click it again and it changes back to green leaf icon then extension is working as it should be.    It could be a change in the work distribution system and how Rainforest pass down work to all testers.  It's closed system and pretty much, I don't know how they distribute works to all testers.

The old extension does polling for a period of time and all testers are fighting for work.    Now with new extension on websocket connection, it works differently and RF server is now able to assign jobs directly to testers in real time.

**Comment by hunt40** [comment]
i got 1 small hit since 2 hours ,i want to say tons of thing but its change nothing so i will not say anything at all and if this continue like this in the future this is not right way to distribute.

**Comment by VeryDisappointedTester** [comment]
"extension works fine, im reciving hit after hit. did not encountered any problem"
So someone is receiving hit after hit while others are getting one hit in two hours.
Very interesting distribution system.

**Comment by JrRandy** [comment]
"Believe none of which you hear, and half of which you see".  I find it very hard to believe that anyone is getting "Hit after Hit" unless they are in the training sandbox

**Comment by qpPykT** [comment]
Yeah I got 4 hits for 9 hours it's looks like hit after hit :D

**Comment by VeryDisappointedTester** [comment]
" I find it very hard to believe that anyone is getting "Hit after Hit" unless they are in the training sandbox"
It is highly unlikely to me as well.

I dont believe that number of jobs is reduced because RF recived a lot of new testers. Registration is closed at the end of July. First two weeks of August were very good. In fact everything was fine until extension update. Something else is going on. 
If there is a lack of jobs it would be fair to say "Dear testers in the next few weeks/months there will be less work for everybody" That is all they need to say.
If they dont talk about it problem will not go away. Rainforest knows that there are hundreds of testers from all over the world who are earning for a living doing this. It would be fair to say that we dont expect much in the future.
One more thing. It would be nice if amount of work for everybody would be based on their stats.

**Comment by erdeminofff** [comment]
I finished 3 hit in last 45 minute. Also I did not complete one test (reported) because of server load issue. Job count did not decrease after distribution system changes. Also Tomorrow, first hours after this chnages,  job activity was very high. I was getting a test in every 2-3 minutes. So from my perspective, new system working wihout problem.  If you did not get hit after system change maybe there is a issue in extension. Try to uninstall extension , clear browser cache , and download again from profile page.

**Comment by JrRandy** [comment]
Its simple math versus expectations.  

Total RF Tests run in the history of time:  50,612,754
Testers online daily (using current stats):  5,244
Tests/Testers:  9,651 per tester all time
Assuming RF has been tracking test count for only 2 years:  9,651 tests per user / 24 months in 2 years:  402 tests per tester per month
There are 21.741 workdays per month on average (Excluding weekends):  402 tests/21.741 weeks days = 18.49 tests per worker per day.  Add in weekend days where you still get some, and that number goes even lower.  Understanding that the number of workers has increased over the last 2 years, that makes that average likely even lower now if the 5,244 testers online daily is accurate.

**Comment by Paolick** [comment]
Hello, I always have the same doubt, that if green is because the extension is working, but sometimes spends up to 1 hour do not get work, I noticed that now the jobs are preassigned not know if that has something to do, if anyone can advise me about it would do me a great favor because seriously I sometimes worry about because the extension does not work or because I was done something wrong.
Thank you

**Comment by hunt40** [comment]
@erdeminofff i like to know if did you get any hit since then?

**Comment by Paolick** [comment]
I have had very few HITS since I started to use pre-assigned mode.
Yesterday were only 6

**Comment by erdeminofff** [comment]
@hunt40 Yes, I got 2 after write comment test but  stucked to second one becasue of  server load issue. ( beetween 40 minute). Now Got another one when I am writing this one

**Comment by hunt40** [comment]
nothing for me so far so you got total 7 while i got 1 i dont know i reinstalled many times and its looks working ,have no clue why i not get at least few at same time frame.

**Comment by erdeminofff** [comment]
Did you sign job agreements from "get more jobs" section in your profile

**Comment by hunt40** [comment]
yeah long time ago,i am really frustrated right now and have no desire to do anything,yesterday was same

**Comment by erdeminofff** [comment]
It's hard to say what happening in system. There may a problem in your extension or Rainforest assigned a priority of experanced testers. Did you applied ip checking method to testing extension in my first comment?

**Comment by Paolick** [comment]
And after testing the IP that I can do? led since Wednesday have almost no HITS and I'm pretty frustrated

**Comment by hunt40** [comment]
yeah i did i have 4 different 104.x.x.x range,who know whats going on,still no hit

**Comment by erdeminofff** [comment]
So. your extension works. Now my job activity down. I did not get any hit in last 1 hour. Golden hour ends :)

**Comment by hunt40** [comment]
welcome to the waiting to hits club then

**Comment by zfonck123** [comment]
one hit each 4-5 hours....

**Comment by qpPykT** [comment]
ha-ha new numbers in the counter welcome back to the new reality :)

![rf-numbers](https://cloud.githubusercontent.com/assets/4960092/19198436/de6b1c58-8cc7-11e6-88dc-9104a2a0df3a.jpg)

**Comment by ukd1** [comment]
the stats being bust is out fault; they used to work using metrics from the old-extension endpoint; yesterday we went 100% new endpoint! No one fixed the stats...I've just done it this morning with @shosti <3

👍

**Comment by zfonck123** [comment]
i want roll back to the old system. this update .... IS...... bad :(

**Comment by qpPykT** [comment]
Now the system works good but there are not enough hits for all of us.

**Comment by hunt40** [comment]
its dead jim at least for me last 4 hours just 1 hit,i am going to drink

**Comment by Res87** [comment]
The first time after two years of testing with Rfqa,  2 hits after more than 14 hour. Realy i'm very very frustrated.

**Comment by tulko** [comment]
I can understand that reduce my hits, could understand 1 hit per hour. but if i get in 6 hours just 2? I note that are pushing. 
that tells me that someone has too many hits

**Comment by shosti** [comment]
Guys unless you have reports of the extension working *incorrectly* (i.e. getting no hits), there's not much to be done here. Closing this issue for now.

**Comment by shosti** [comment]
BTW if anyone thinks that there is a connection issue, post your contributor ID and I'll double-check that you're connected on the backend.

**Comment by tulko** [comment]
@shosti please see my account    29649019

**Comment by JrRandy** [comment]
@shosti Any chance we could get a "Connected" or "Not Connected" notification on our portal page?  Would eliminate alot of these concerns on the extension being artificially connected.

**Comment by tulko** [comment]
and it is a lost day for me

**Comment by sweeneyapps** [comment]
@JrRandy good idea :)

**Comment by shosti** [comment]
@JrRandy "green leef" == connected, period. No point adding it to the portal page; I'm just double-checking in case there's a bug. There doesn't seem to be, so I'm keeping this issue closed.

**Comment by zfonck123** [comment]
@shosti 34044189 this is my account can check it please ? :(

**Comment by shosti** [comment]
@zfonck123 according to the backend you got a work assignment--is that the case?

**Comment by zfonck123** [comment]
i get one work in this moment its a miracle :O

**Comment by hunt40** [comment]
actually i want some explanation why some people get 30+ test in 1 day while other get 9-10,i thought you have all these thousand testers because you need diversity,then with this new systems some people get tons of work while other sit here doing nothing.
