### ISSUE TITLE
new updated.... new hit down to tester.... sooo bad... app dosent work 

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#682]
![image](https://cloud.githubusercontent.com/assets/19192312/19189207/ad876686-8c64-11e6-9477-84d6bd724f8c.png)

**Comment by zfonck123** [comment]
8 hours only 1 job

**Comment by HW71** [comment]
Hmm, not quite sure, but: Do we really need a _new_ issue for that? Especially with such a subject (should be short and catchy, IMHO)? And: We already have a discussion about that in issue #680, right?
