### ISSUE TITLE
Question about Chrome extension

### ISSUE THREAD

**Issue by smellslikejavier** [rainforestapp/tester-chrome-extension#683]
Hi, according to the Latest News section: "As part of upgrading our infrastructure, we ask that *all* testers move to the latest version of our Chrome Extension". Now I'm a little worried about this since I have an old version of Mac OS X installed: 10.6.8, and recently Chrome has been telling me that this old versions will stop receiving updates for said browser. Does this mean I won't be able to use the Chrome extension anymore and thus lose the opportunity to continue working on Rainforest? :( I have the 2.0.2 version of the extension installed which is apparently the latest version.
Thanks!

**Comment by HW71** [comment]
Hi @smellslikejavier,

you wrote:

> recently Chrome has been telling me that this old versions will stop receiving updates for said _browser_.

So just to  be sure: you mean "will stop receiving updates for said _OS X version_", right?

If so: from my current point of view the "update of extensions" is supposed to be independent from "update of Chrome" itself - and hence you should be able to still get updates for the extensions. But I could think of some pitfalls, for example if future versions of the extension require additional stuff or changes not available in your old Chrome version. 
 
That being said version 2.0.2 is the recent version of the extension (as already noted by you) so everything should be fine. Well, at least for now... :-)

**Comment by smellslikejavier** [comment]
Oh thank you so much for replying HW71! :D 
Yes apparently Chrome will stop or has already stopped to support this following Mac OS X versions: Mac OS X 10.6, 10.7 and 10.8, so if you have those versions then you won't receive any more updates for your Chrome browser. 
I'm glad to know the Chrome extension is independent so I can still work on Rainforest for a while longer! 
In the meantime I hope they don't implement any additional stuff to the extension like you said, at least for now :( Since sadly I don't have the money to buy another new computer at the moment.
Thanks again for your reply!

**Comment by HW71** [comment]
You're welcome... :-)

Well, of course staying on an old browser version could also imply further issues (like security etc), but I understand that by the end of the day it's Google's decision which OS they want to support in future - and which they want to leave behind.

So keeping fingers crossed => hope you can get some new hardware, soon! :-)

Have a great one - and "happy testing"! 

-Erik

PS:
Please think about closing this one - this would help project members to keep track of unresolved issues that need to be followed up...

**Comment by smellslikejavier** [comment]
Ok I'll do that! thanks again :)

**Comment by shosti** [comment]
Just to confirm: the extension supports Chrome versions >= 32 (although newer versions may be more reliable).
