### ISSUE TITLE
Problem with connection lost

### ISSUE THREAD

**Issue by VeryDisappointedTester** [rainforestapp/tester-chrome-extension#686]
Just now i had Paperless hit. On 5-6 step i pressed YES and after 1-2 minutes i got connection lost and after that screenshot was taken and i am moved to next step. What now? I answered YES but on the screenshot is Connection Lost. So i restarted hit. After several steps again same situation...Restarted again.....Third time when this happened was even worse because next step was redirection step. So i had to report this after two steps with connection lost.
This is happening a lot lateley. It is not a problem when it happens in the middle of a step, just press reconnect and move on. But when it happens after hiting YES/NO you can't do anything about that. Once it happened on the last step so it was impossible to report. It is frustrating when this happens on 30-40 step and you have to do all over again. 
Is it possible to take screenshot of the moment when YES/NO was clicked? It would save us a lot of nerves.

**Comment by helloworld111gh** [comment]
Press Reconnect to reconnect to a terminal

**Comment by VeryDisappointedTester** [comment]
"This is happening a lot lateley. It is not a problem when it happens in the middle of a step, just press reconnect and move on. But when it happens after hiting YES/NO you can't do anything about that.
