### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by hupapa** [rainforestapp/tester-chrome-extension#688]
Hello all.

I was assigned a HIT where, when i started, it was being shared with another tester. So i refreshed the HIT and got this error : 
![rf error sts](https://cloud.githubusercontent.com/assets/21263840/19203643/4858f01a-8cd0-11e6-9583-8c6b9db49edc.png)
Then i clicked the "restart button" and finished the hit...
Is this error normal?

**Comment by 2codefast** [comment]
Its all but not new thats for shure, just more frequent since last night. In fact, you get 7-8 of this then you get the job you were assigned.

**Comment by helloworld111gh** [comment]
It means it failed to proxy to a USA IP so you could do a geo targeted HIT
(for the terminal, not you)
Just restart, it'll fix itself

**Comment by nerdatwork** [comment]
@helloworld111gh is 100% correct. If you are satisfied with the response please close this thread.
