### ISSUE TITLE
Bonus Payments are missing half

### ISSUE THREAD

**Issue by helloworld111gh** [rainforestapp/tester-chrome-extension#69]
I've recently completed a HIT, and when I get my bonus payment it is half of what is should be. It was a 4 step job so I should of got 16c, but I only got 8c.

**Comment by Dolazim** [comment]
Are hit is  datamata ?

**Comment by ukd1** [comment]
@helloworld111gh what does it list in the portal history section?

**Comment by Dolazim** [comment]
832042531		2016-02-12 01:55:28 UTC	00:07:16	—	6c

834601149		2016-02-12 02:18:57 UTC	00:03:49	—	4c

**Comment by helloworld111gh** [comment]
http://puu.sh/n5IoD/1964597ffb.png

**Comment by ukd1** [comment]
@helloworld111gh ok - you can't see this but it we've found a bug with something we just enabled, we've turned it off until we fix it. We'll also be fixing the bonuses for you and the others that got this early next week. Sorry about this.

/cc @shosti

**Comment by shosti** [comment]
The payments should be correctly shortly. Thanks for reporting the issue!
