### ISSUE TITLE
help with extension

### ISSUE THREAD

**Issue by tulko** [rainforestapp/tester-chrome-extension#693]
i not know how to  use well the "developer tools" of the extension. but I think it is not active, someone help me to read this information?

Another issue is reading my history of surfing. why the extension can read my history? For what purpose? 

id 29649019

**Comment by uqbiii** [comment]
![](http://www.mstoic.com/wp-content/uploads/2013/08/Enable-Developer-Mode-Chrome.png)
Understanding the whole background page of extension is difficult for non-developers, and now there is not much data since RainForest implemented WebSockets Pushing.
2nd: I think extension's feature of automatic closing error tabs and opening new tabs requires this permission to read your history.

**Comment by sweeneyapps** [comment]
green icon... you re good to go!    if it's OFF and icon is grey and you can't get it to green when you click on it.   Then something is wrong.    If there is problem with connecting to Rainforest server, the extension will notify you on what to do next.

**Comment by erdeminofff** [comment]
After update, network tab (in developer tool) no longer gives you server check informations. If you are not sure about extension, use this metod : 

-Download TCPView software and extract files somewhere.
-Run Tcpview.exe and check ip adresses listed in chrome rows and remote adress column:

104.25.172.10 
104.20.59.84
(This ip numbers may be increase after getting some jobs. But always start with 104.25. and 104.20)

-If you see there are chrome rows which including this two ip addresses and Send bytes - Rcvd bytes numbers are increasing in 1 minute, That's mean no need to worry about it.

**Comment by mobradovic** [comment]
> Download TCPView software 

Oh. My. God.

Open developer tools as usual.
Hit F5.
Click on "websocket?auth..blahblahblah...." on the left.
Make sure you're on the 'Frames' tab.
Bleed your eyes out looking at extension pooling/fetching every 30 sec.

**Comment by cookin2** [comment]
Thank you for that info!  I tried it out and there is no fetching or pooling.  I reinstalled the extension and it's still the same. 

I see this:  {"topic":"phoenix","ref":"7","payload":{"status":"ok","response":{}},"event":"phx_reply"} and {"topic":"phoenix","event":"heartbeat","payload":{},"ref":"11"}  

It seems to refresh about every 30 seconds, so I'm guessing that all is well?  There's even a workers:lobby when you're inactive lol

**Comment by sweeneyapps** [comment]
@cookin2 you re fine.

**Comment by cookin2** [comment]
@sweeneyapps Thank you so much for putting my mind at ease :)
