### ISSUE TITLE
Is RF alowing to join new members?

### ISSUE THREAD

**Issue by TyroneSt** [rainforestapp/tester-chrome-extension#694]
I ask this because I saw "10,863 Testers (24h)" in RF site when the average was 5000 since a long time ago and suddenly it was doubled :S. All what brings to my mind is that new testers are joining since any platform. If someone knows how this indicator works and explain it will be nice.

**Comment by sweeneyapps** [comment]
it's because of websocket technology.  All testers' computer are connected to server even if they are inactive.

**Comment by shosti** [comment]
Actually that's a bug in the front page stats. Should be fixed soon.

**Comment by shosti** [comment]
(cc @ukd1)

**Comment by TyroneSt** [comment]
Thanks for your answers guys, I am closing this topic.
