### ISSUE TITLE
Answer to shosti question

### ISSUE THREAD

**Issue by VeryDisappointedTester** [rainforestapp/tester-chrome-extension#695]
shosti
"If anyone has an alternative suggestion that would serve the same purpose, please open up a new issue.)"

First you need to tell us what do you want? 
We are a part of Rainforest as much as you are.
When you say what do you want we can talk. It is pointless to propose something before we find out what do you want.
10 minutes result? 
Testers available 24/7?
Anything else?
Please  tell us what do you want and then we can talk.

**Comment by shosti** [comment]
I meant an alternative way to let people know that a lot of work is available (which was in the issue description). 

@VeryDisappointedTester I understand that you're frustrated about your workload, but please keep your tone constructive. Unless you find a bug on the extension, complaining here about lack of work will not do anyone any good. I don't want to block you from
GitHub but I will if you hijack any more issue threads.

**Comment by VeryDisappointedTester** [comment]
I really don't see anything frustrating in my post. Just a question. But if u say so...

**Comment by shosti** [comment]
(Please don't be facetious, I was obviously referring to your other
recent posts.)
