### ISSUE TITLE
them with the new update... one hit each 4-8hours ?

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#697]
very frustrated....

**Comment by nerdatwork** [comment]
Unfortunately this is not the place to vent out frustration for less jobs as this is **not** an issue with the extension. Soon when the jobs via websockets will be enabled for every tester, testers who are online the most will get more jobs.

**Comment by zfonck123** [comment]
i am working online 16 hours in my pc,... and dont get jobs...

**Comment by uqbiii** [comment]
And you think posting here will solve the problem? Everyone is getting the same so there is no need of creating a Issue which is not an issues at all. Just wait and i hope everything will be back to normal soon, this new update is really good.

**Comment by uangonline** [comment]
websockets is already enabled. As you all aware that the extention is no longer polling.

**Comment by JrRandy** [comment]
Im not sure a Saturday/Sunday is an accurate depiction of what the volume looks like with Websockets.  Weekends are always slow, and right now it is not even 9am on the US west coast.

**Comment by khristianjose** [comment]
Im working today since 8 AM, and still didnt get any jobs lol, so sad.

**Comment by cookin2** [comment]
It's a holiday in the US, no hits yet for me either, so I'm hoping that's the reason!

**Comment by ellmirr0001** [comment]
I think that's not a problem, had 17 hits so far.

**Comment by mojenLXXXIII** [comment]
Completed 20 Hits , i also know guys who done more than that for today, lets admit it websockets is working fine but Hits are not distributed evenly.

**Comment by shosti** [comment]
Guys, I understand that people are frustrated, but continuing to post here will not help unless there's a bug in the extension preventing you from getting work (and could possibly prevent real bugs from getting noticed). We can't guarantee job availability, and we also can't guarantee that work distribution is 100% "fair" (because there are many possible definitions of "fair"). If you think you've found a real problem, please open an issue, otherwise this isn't the right forum for these kinds of discussions.

**Comment by nihlathar** [comment]
@shosti But it is the only place to vent and possibly get attention from a rfqa employee, plus, you're only saying that either because you do get normal amount of jobs or you're not a tester, so you're not affected, for the rest of us it's a big problem.

**Comment by luisdanielvc** [comment]
Don't worry, today is Columbus Day in the USA, that's why you see fewer jobs.

**Comment by Electroglitch** [comment]
@nihlathar Don't know how you didn't catch it but **shosti** is not tester ,he's a hacker :smile:

**Comment by begsoon** [comment]
This is not because of holidays,new technology called WebSocket is the reason.

**Comment by tulko** [comment]
@shosti I understand that have many definitions of just. But they might say, what is the criterion of justice.
if better testers have more work, it's just. I think being a good tester. How to identify your system to the best and the worst?
It's just information, it helps me to try to improve.

**Comment by VeryDisappointedTester** [comment]
Rainforest just wants 10 minutes result. Rainforest thinks that all testers with good quality work will continue to be active as much as they were before. Of course that everyone of us that do this for a living will not be active for 10+ hours just to get $2. We will all find alternative sooner or later.
When we all go results will be yes,yes,yes,yes,yes......
Let them do things their way. They dont want to listen so there is not much we can do. It is pointless to keep talking to someone who don't want to hear you.
