### ISSUE TITLE
Single and Double quotation.

### ISSUE THREAD

**Issue by TyroneSt** [rainforestapp/tester-chrome-extension#698]
I have a doubt about quotation rules, In all examples in the scenarios page it just uses the double quotation (" "). Please can anybody tell me if it applies the same rule for single quotation (' ')?

**Comment by sweeneyapps** [comment]
good question..  @kristen-allie can answer this.

**Comment by Electroglitch** [comment]
After how many months, you noticed this just now, really?
It doesn't matter rules are the same because it's the same thing (quoatation) doen't matter if test author uses ' or "

**Comment by JPierreS** [comment]
To my knowledge the rules has concerned single and double quotes, from the beginning of the rules.

**Comment by erdeminofff** [comment]
I asked this question 6 months ago to rainforest support. Here answer: 

> Hi. Some test authors using quotation marks with 'text' instead of "text". Few minutes ago I got a test like that. Test author was quoting button texts with using single quotation mark ('text') and for long texts, infos or other things he was using double quotation mark ("text"). I'm little confused here. Rules talking about only double usage not single. Checked punctuation rules in internet and it says: "Quotation marks can be used in two styles; single (‘ ’ or ') or double (“ ” or "), and can also appear in two different typefaces; either as so called dumb or straight quotes (' or ") or as smart quotes (‘ ’ or “ ”)" So what should I do? Should I evaluate single or double marks as same thing and using same quotation rules or not. Thank you



> Rainforest Support
> April 18, 2016 17:51
> Hello,
> 
> You should treat single quotes and double quotes the same way.
> 
> Sincerely,
> 
> Rainforest Support
> rainforestqa.com

**Comment by TyroneSt** [comment]
Thanks for your answer guys, now its more clear and I would suggest to use both quotation in the example scenarios.  I am closing the issue
