### ISSUE TITLE
Problem with extension

### ISSUE THREAD

**Issue by VeryDisappointedTester** [rainforestapp/tester-chrome-extension#699]
This error is on console page.
![01](https://cloud.githubusercontent.com/assets/22333356/19254984/d72590e2-8f59-11e6-9ac6-07dfb0ee87d2.png)
Any suggestion? 

I already reinstalled extension.

**Comment by sweeneyapps** [comment]
reload the extension and does this console error message reappear?

**Comment by VeryDisappointedTester** [comment]
No. I think that everything is ok now. 
![011](https://cloud.githubusercontent.com/assets/22333356/19255415/05aca578-8f5e-11e6-9835-656e2eb6eac2.png)
