### ISSUE TITLE
Why my extention not polling?

### ISSUE THREAD

**Issue by CharlieSpock** [rainforestapp/tester-chrome-extension#700]
After yesterday morning my ext not polling again, only few hit got yesterday, i talk with other testers and they got a "normally behavior of they extention" anyone have the same problem?

![2a2](https://cloud.githubusercontent.com/assets/20996862/19273249/2af0ec6a-8fa2-11e6-9059-075b9b2ba1df.png)

**Comment by marius11** [comment]
The extension is now using sockets to deliver jobs. Instead of sending requests to Rainforest (polling) to see if there are any jobs available, Rainforest now sends you the job if there is any.

**Comment by CharlieSpock** [comment]
@marius11 Thank for explanation!
