### ISSUE TITLE
What are the points to preassign a job

### ISSUE THREAD

**Issue by jjooeellkkaarrrr** [rainforestapp/tester-chrome-extension#701]
I would like to know the factors that the preassing of jobs are taken into account, as do 30 more in a day, I'm doing 10 jobs a day. If anyone knows, I would like to know.
Many thanks

**Comment by VeryDisappointedTester** [comment]
There is only one factor - We are all the same.
No matter how good or bad worker you are or how long you are active every day - We are all the same.
It does not matter if you report problems or just click YES - We are all the same.
This is how it works.
