### ISSUE TITLE
Why is ext. not working properly?

### ISSUE THREAD

**Issue by 2codefast** [rainforestapp/tester-chrome-extension#702]
Where are the jobs that ext. should make availabe for us?

Geting a 1-2 jobs/h is dissaster.
Jobs are distributed right? Where?
Before preasigned "upgrade" ops are opening jobs, and ext. keeps quiet whole day.

If its ext. problem let us know so we can shutdown our pc-s and at least cut cost for electricity.
Maybe in India, Pakistan or some other place its not such a big deal, but in Europe electricity costs and when that kilowatts earn you 2$ a day, it costs even more

**Comment by teddyslav** [comment]
Agreed. I spend 16h a day waiting for a job, the way things are at the moment I can not earn enough for electricity and internet connection :(
