### ISSUE TITLE
Unfair training test

### ISSUE THREAD

**Issue by huynhxuanvinh** [rainforestapp/tester-chrome-extension#704]
I have failed a training test that I'm sure 100% that I do it exactly. It's a test about book name "The Death Of The Heart" and rank of it in list. I'm sure I do it 100% exactly and now Rf send me a letter says I failed.

**Comment by uangonline** [comment]
Any screenshot?

**Comment by huynhxuanvinh** [comment]
Unfortunately, I don't have the screenshot but I'm sure I do it right, that hit has only 2 step demanding find the book named "The Death Of The Heart" and its ranking.

**Comment by RnkSts** [comment]
If you're really sure that you did the job correctly, you can find the screenshots in the rejections page and submit a ticket to support, if you have enough proofs.
