### ISSUE TITLE
Prioritized Work

### ISSUE THREAD

**Issue by JrRandy** [rainforestapp/tester-chrome-extension#709]
Since the new work distribution has been put in place for "Trusted workers", will there be somewhere we can see our status based on a % or ranking or anything?  Since it is not based on bugs, and restrospective only works if you click yes and 2 others click no (I have seen 1 of these retro emails only), is there anywhere else we can see what we need to improve upon?

**Comment by 2codefast** [comment]
"Prioritized Work" Its just a false excuse for extension not working properly, as you can see there is connecting bug reported on previous post.

**Comment by JrRandy** [comment]
I was not looking for conspiracy theories, or other negative feedback.  I was looking for feedback on how to improve my performance based on the algorithm they have put in place.  If you do not have constructive feedback, please refrain from posting in this item so those of us looking to improve our performance can get the info we need without them closing the thread for negative posts.  Thanks :)

**Comment by 2codefast** [comment]
You are trying to improve non existing performance made up by someone who has no other explanation for why are jobs not available. Good luck with that.

**Comment by helloworld111gh** [comment]
Don't be negative, you can be blocked by doing that. There is no issue with
the extension, I just turned it on and got a hit in 1 minute. If you are
getting no hits you may be soft blocked (aka very few hits) by the trusted
tester algo.

Anyways, yeah a way to know how we rank would be nice. EX using level
badges like what Crowdflower uses, and you get better priority based your
badges.

Also, what counts as a trusted tester? Top 10%, 5%...?

**Comment by Paolick** [comment]
I agree with "JrRandy" and if any editor, or worker RF were to read this post, it would be perfect, and I speak for many, that profile More detailed statistics are showing our% correct and errors or know noo just by rejection but if you really ought to give yes or no.
Thank you

**Comment by nihlathar** [comment]
I find this new 'feature' extremely confusing. I try to do my best work but there's no way to see if I'm not missing some small thing that puts me behind other workers, not that I have any idea how can they measure if I followed the instructions to the letter other than if I pressed yes when (based on what other testers have done) I should have pressed no instead. I'm seeing less work, but I only got 2 'disagreement' emails and also passed all ~15 trening jobs so far. So I really don't see the reason for why this is. I think there are many more users working now, for some reason, so there's just not enough work to distribute, is my guess.

**Comment by shosti** [comment]
We aren't yet making the reputation details public for a couple of reasons:

1. We want to continue validating/tweaking internally until we're highly confident in our metrics.
2. We want to avoid the possibility of people gaming the system.

I agree that it's nice to be able to track progress--once we're highly confident in our reputation metrics we may add them to the profile (we'll have to discuss internally). 

I can say, however, that in general they're based on *how well you follow instructions*. They're *not* based on bug count or general rejection rate, so don't worry about getting "outvoted" when you report a bug or anything like that. The best way to keep your reputation high is to keep on top of the rules and follow instructions carefully. If you feel like you've been doing a good job but still aren't getting much work, let @kristen-allie know and we can look into it on a case-by-case basis.

(cc @rainforestapp/tester-product)

**Comment by shosti** [comment]
> Also, what counts as a trusted tester? Top 10%, 5%...?

The better your ranking, the more likely you are to be prioritized (it's not that there's a single "tier" of trusted testers).

**Comment by ecliptica777** [comment]
In the last 2 weeks I get a lot of work. It's great, however, I am skeptical of the idea of distribution algorithm. I'm not sure that the algorithm is able to work without mistake. Last month I was wrongly blocked. I had to write to support and wait for me unlock.

on the other hand, the idea of giving more work to those who execute it better - true. We just need to understand where we are and to aspire to.

**Comment by begsoon** [comment]
@shosti  Are the testers who are invited to be part of exploratory testing ,trusted testers ?

**Comment by SDMask** [comment]
......with less HITs chances of improving would also become difficult!
@shosti Would it reset every set_ days (like the bug count) ?

**Comment by JrRandy** [comment]
Thanks for the reply @shosti   I can respect the fact that you want to be confident in the algorithm and ranking before releasing it, but if the work distribution has been implemented you must be pretty confident in the results.  My only point was that if we see nothing telling us that we are doing something incorrectly, and we believe that we are actually doing it correctly it results in a vicious cycle of poor performance with no way to improve.  I will wait it out and see what happens, with hopes that RF wants to improve its worker base as much as its worker base wants to improve for RF.

**Comment by Paolick** [comment]
@shosti I feel I'm getting a few hits, how do I write to @kristen-allie  to help me or advise me about it.
Thank you very much, and thank you very much for always watching us

**Comment by shosti** [comment]
@Paolick seeing as we just turned this on a few hours ago, I'd wait a while before contacting kristen :wink:.

**Comment by Paolick** [comment]
@shosti, perfect, thank you very much, also thanks again for responding so fast and be ever vigilant

**Comment by mueller01** [comment]
I feel like I've been doing a good job but still aren't getting much work, should I let @kristen-allie know too ?
How to contact she ?
Worker ID  28573311

**Comment by shosti** [comment]
Again, please wait a few days before making these kinds of requests 😄.

**Comment by euparkeria** [comment]
I believe a ranking score should be added to tester's profile, otherwise, people will always suspect they are ranked poorly. The score can be updated only once a day so testers could not associate its movements with any of their actions and start "gaming the system".

**Comment by tulko** [comment]
there may be a global reputation and a daily reputation
the global reputation  an average daily reputation of the last 30 days
the daily reputation is your is the quality of your work today and is used for work tomorrow
The global reputation is an plus of reputation in every day. for example; if your daily reputation is 70 and your global reputation is 50, I could be average or give a bonus to workers who are constantly in the last 30 days had a good reputation.

I am one of the parents of the child: reputation system and preassigned. i discuss some time ago, but there surely others.
although I do not see benefited me, I thought that was a good tester   :( 

 @kristen-allie  see my account my id 29649019

**Comment by uangonline** [comment]
This feature is still new, so it's better for us to wait and see for couple of days. Just keep in mind, old tester not always be a trusted tester.

**Comment by tulko** [comment]
I agree with you @uangonline although all are trusted testers. if someone is not trustworthy for being a corrupt, should not be tester.
better say "good tester" 
we know that the rules of confusing scenarios can not exhaust all possibilities
then I think that there is no algorithm, there are hidden training test. for I say this? 
the algorithm can not know if I did well a test, because if this is possible directly no need testers.
 then, if there are hidden test, there may be a feedback

**Comment by zfonck123** [comment]
@kristen-allie   my id 34044189

**Comment by tulko** [comment]
@kristen-allie  see my  hit 695864853 in job 9533103 Help me with this confusing scenario your rules does not solve this problem
Major rules, higher confusing scenarios

**Comment by JrRandy** [comment]
Closing as the forum is open to all now, and it looks like they had posted this as well :)
