### ISSUE TITLE
Extension getting turned OFF automatically

### ISSUE THREAD

**Issue by nerdatwork** [rainforestapp/tester-chrome-extension#71]
As the title suggest, without any warning the extension turns itself OFF. I have to manually turn it ON.

**Comment by RezwanulHaque** [comment]
I had same situation. I updated extension with version of 12th Feb, I think it has resolved.

**Comment by ahmedofhell** [comment]
Same problem here

**Comment by chmi16** [comment]
Same here. Since this morning open my RF portal and turn it off

**Comment by qpPykT** [comment]
Maybe this is a new feature. If your browser is inactive for a certain time (about 10-20 minutes), the extension goes into off mode.

**Comment by Genesis2015** [comment]
If the browser is inactive for 6 minutes (I think), the extension goes into off mode.
We need an official announcement about this changes.

**Comment by AggroTechCyber** [comment]
@Genesis2015 You have official announcement here: https://github.com/rainforestapp/tester-chrome-extension/pull/56

**Comment by ukd1** [comment]
This is working as expected, after 6 minutes of not using your computer, we turn the button off. This is so we can give work to testers who _are_ using their computer first!
