### ISSUE TITLE
slow connection to the MV

### ISSUE THREAD

**Issue by nuevao** [rainforestapp/tester-chrome-extension#710]
from the day yesterday and part of the afternoon, I have presented serious problems with the slowness of the MV. For some reason after the MV load and start to the job, begins my problem as if it had internet at 56kbps. It is super slow. Although I have made them the corresponding speed test, and all is well apparent, Has anyone had this problem or is it just mine?

**Comment by JrRandy** [comment]
If it is a safari VM, yes.  Most of the windows based VM's function pretty normal for me, but the Mac VM's and especially the safari VM's are know for being slower than a turtle stuck in quick sand.

**Comment by nuevao** [comment]
if that's very true the MAC environments are slow, but it seem incredible, happened to me with all MV (both Mac and Windows environment), so give up more of the jobs.

**Comment by RnkSts** [comment]
I only have problems with MAC, I like testing but when I get a Mac, with Safari, I fell happy and sad at the same time. I notice that in Mac machines there's a random "refresh" or something, a part of the screen turn white (or go back to a previous state o.o) and need to load that segment of the screen again, I see this more frequent when a pop-up is open, or when typing. I don't know how to explain it well, or if I'm the only who see this. lol

**Comment by nuevao** [comment]
I think you understand, but it is not my case. I have one meter local speed in my taskbar (My Computer), and I can see that when it goes well a common speed while perform tests is 200 Kbps to 300, but yesterday and today some tests have gone to less than 50 Kbps. which makes it almost impossible to do something. but now it is normal just after opening the Issue xD.
