### ISSUE TITLE
cant "on" my app

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#714]
![image](https://cloud.githubusercontent.com/assets/19192312/19333354/00e80cd8-90c3-11e6-823b-6fc801cef69c.png) this pop up open  :( help me please 34044189

**Comment by zfonck123** [comment]
![image](https://cloud.githubusercontent.com/assets/19192312/19333420/844f550e-90c3-11e6-80dd-79b3515cf773.png)

**Comment by zfonck123** [comment]
@shosti   cant open my app :(

**Comment by federicoall** [comment]
Same here.

**Comment by zfonck123** [comment]
@kristen-allie   @pscohn

**Comment by luisdanielvc** [comment]
Same here

**Comment by zfonck123** [comment]
back the app to work

**Comment by zfonck123** [comment]
install again the app

**Comment by luisdanielvc** [comment]
Reinstalling doesn't work :(
