### ISSUE TITLE
Can't turn on my ext!

### ISSUE THREAD

**Issue by CharlieSpock** [rainforestapp/tester-chrome-extension#715]
I reinstall the ext and not work properly

![2a2](https://cloud.githubusercontent.com/assets/20996862/19334241/fd58f7cc-90d0-11e6-9c6a-3b6a52b2d346.png)

**Comment by slrojasc** [comment]
I have the same problem

**Comment by lobogris20** [comment]
me too

**Comment by slrojasc** [comment]
you tried  tried uninstalling the extension and by reinstalling?

**Comment by CharlieSpock** [comment]
@Darkstar2 Say this on RF forum.

"Should not require uninstalling, you can go to console and RESET it with CTRL-R or toggle disable/enable.
Occasionally you may be disconnected, it should reconnect you automatically - should it remain gray you will have to manually reset. Another observed behaviour, if the extension turns gray whilst you are on a job, it will remain stuck on WIP, in this instance you will have to manually reset. Both issues were reported to the developer in our private channel, during testing phase, and he will look into that. :slight_smile:

Meanwhile for issues related to the extension it would also be a good idea to open a GITHUB issue as devs monitor that channel as well.

If you uninstall and reinstall and still not working, log out your profile,uninstall extension, close chrome, re-open, log back into your profile and re-install. Make sure you are using the latest version and allow chrome to auto update. :slight_smile:

Let's hope for a fix on this soon."

**Comment by nuevao** [comment]
This message appears at every moment, and the icon remains in gray![error](https://cloud.githubusercontent.com/assets/16979522/19334928/811d44cc-90cd-11e6-8abc-5f0cd5256410.JPG)

**Comment by NICOSYSTEM3** [comment]
I have the same problem
me too.  the icon remains in gray
![image](https://cloud.githubusercontent.com/assets/22378777/19334995/f3954540-90cd-11e6-8796-d48138f7ae8d.png)

**Comment by Paolick** [comment]
I have problems with the extension, the same said for you, someone managed to fix it?

**Comment by JrRandy** [comment]
No, seems to be an expanding issue.  Reset manually, reinstall, nothing works.  Spams error 503 and 429 in the console.  More and more people on the forum are beginning to report the issue.

**Comment by Zamoraks** [comment]
same problem here.

**Comment by JrRandy** [comment]
Not sure if related, but extension options have disappeared for me as well in my edit profile (Sound etc).

**Comment by JrRandy** [comment]
Posted in forum:  
ppadier2m
Hi all,

We've identified an issue with the extension (that you've all noticed :slight_smile:) and are currently working on a fix. I'll update once the issue is resolved. Thanks for your patience!

**Comment by sweeneyapps** [comment]
yeah it's only server-side problem..

**Comment by CharlieSpock** [comment]
The ext turns green normaly :dancing_men:
