### ISSUE TITLE
I'm having the same problem.

### ISSUE THREAD

**Issue by renangloor** [rainforestapp/tester-chrome-extension#717]
It appears several times a notification saying that I'm disconnected and probably the cause of this would be that I'm logged in on another computer, what it is not true.

**Comment by doncoi151189** [comment]
the same problem

**Comment by Taruga** [comment]
Same problem here. This is a bug for sure !

**Comment by Electroglitch** [comment]
Yes ,console is showing some red error also
 network tab plugin.js is in red and on the right side https://schrute.rainforestqa.com/assets/plugin.js 
status code 503

**Comment by cookin2** [comment]
I just got that message too and I have the extension off.  I logged out and logged in and installed the extension.  As soon as I turned it on - same message again, and again while typing this.  The only way to stop it, for me at least, is to uninstall the extension.

**Comment by Taruga** [comment]
The extension is causing a huge network flood and I can't even turn it green. I see a lot of HTTP POST requests

**Comment by Taruga** [comment]
![captura de ecra 2016-10-13 as 04 33 15](https://cloud.githubusercontent.com/assets/1231549/19335825/3a66b2d0-90fe-11e6-89f2-739a96ef1cf8.png)

**Comment by JrRandy** [comment]
Posted in forum:  
ppadier2m
Hi all,

We've identified an issue with the extension (that you've all noticed :slight_smile:) and are currently working on a fix. I'll update once the issue is resolved. Thanks for your patience!

**Comment by teckda** [comment]
same problem here

**Comment by sweeneyapps** [comment]
yeah it's only server-side problem..

**Comment by CharlieSpock** [comment]
The ext turns green now :dancing_men:

**Comment by ahmed1979** [comment]
same problem here

**Comment by vipinbabu** [comment]
I too have the same problem. The extension is not turning Green.

**Comment by ladystoneheart** [comment]
same here its gray all the time even clicking it many times.

**Comment by Brano1979** [comment]
Same problem here, network tab plugin.js is in red and on the right side https://schrute.rainforestqa.com/assets/plugin.js 
status code 503

**Comment by lyubashka** [comment]
I have a same problem...

**Comment by RnkSts** [comment]
Same here, if it is server side, well, it's time to wait

**Comment by akvinod** [comment]
same here as well.

**Comment by RnkSts** [comment]
Well I don't know if this if who fixed my extension, I just go to the extension develop tool (index_prod.html), Press F5 and the extension suddenly turn ON and get one job...

**Comment by ahmed1979** [comment]
RnkSts Thank you .. I try that and the extension turn ON and get 1 job

**Comment by lyubashka** [comment]
Thank you! Now again I turn on and off the expansion and lo!
Leaf green. Before there was always gray and did not react to anything.
Now waiting for a job)))

**Comment by Paolick** [comment]
Hello, I'm having problems with HIT's and in a previous issue said that he would write to kristen, how do I write to her and check out my profile to see poque not receive HIT's?
Thank you very much
