### ISSUE TITLE
Feature request: Configurable state of extension when (re)starting browser...

### ISSUE THREAD

**Issue by HW71** [rainforestapp/tester-chrome-extension#720]
Hi all,

I noticed that the extension seems to remember its last state when Chrome gets closed. I assume this is "works as designed" (and the preferred behavior for most users), but this could also cause issues (abandoned jobs) if you think about computers shared across family members. For a "real life" example please see below...

So in order to avoid "abandoned" Jobs in future I'd suggest to have an option in the profile page allowing us to configure the "Default Initial State" of the plugin.
Of course the default setting (after initial installation of the plugin) could be "on" (to keep the current behavior) - but in order to avoid situations as outlined below it would be great to have the possibility to turn the initial state to "off".

Thanks in advance for taking care! :-)

Have a great one & Cheers, Erik

**Example on how the current behavior could cause problems:**
My wife and me use one and the same laptop located in our living room. Even though we usually use different Linux profiles it happens quite often that my wife just uses just my account + browser, for example for "just" quickly checking mails.

Now today I noticed the sound notification of the RF extension while my wife was working on the laptop. After checking the notification I saw that it was just about this "You have been disconnected" error - but of course it could have also been a job assignment, and I'm pretty sure that my wife would just have closed that tab... :-)

**Comment by sweeneyapps** [comment]
yes, it's in the design to save the state of the extension because when there are new rolling updates from the server, the server will be able to reload the extension to new version.  That's why it has to save the state on your computer.   I think it will be easier to remind yourself when you are done working, you click it OFF.   It will always stay OFF.

for the sound notification, if you have it enabled.  The sound will play once when there's any other notifications.  For work assignment notification, it will repeat  the sounds the way you set it at.

**Comment by HW71** [comment]
Hi Paul,

thanks for the explanation and the technical background. OK, so saving the state in case the extension gets an auto update from the server (that's what you were talking about, right?) makes sense because then the new version can continue with the original state right after the new version has been initialized.

Hmm, just gave it another thought... Actually what causes the problem (at least in our case) is _not_ being away from the laptop for just a few minutes (with my wife taking the chance to "seize" the machine ;-)  ), but when I close the browser and leave the machine for a longer period of time (or shutting it down before going to bed). In such cases we won't have auto-updates anyways because the browser is closed.

Having that in mind:
Is there any chance for the extension to catch some "Close" event (or similar) from the browser in order to switch then the state to OFF before? Just did a quick search and found that this is an often requested feature in Google's API but at least with my quick search I just found some workarounds:

http://stackoverflow.com/questions/15798516/is-there-an-event-for-when-a-chrome-extension-popup-is-closed

If there's no chance to implement this with a reasonable effort then I'll close this issue, but it's good to see some "thumbs up" for my request => it doesn't seem to be _that_ exotic... :-)

**Comment by sweeneyapps** [comment]
yes auto updates..    I'll look into this and do some testing on my test extension to see if it's doable.    I'll update you later today.

**Comment by sweeneyapps** [comment]
I did some testing and came up with this

```javascript
// chrome/index.js
const reloader = () => {
  chrome.storage.local.set({ reload: true });
  window.location.reload(true);
}

// chrome/handleStateSaving.js
chrome.storage.local.get(['workerState', 'reload'], data => {
  if (data.reload && data.workerState === 'ready') {
    store.dispatch(updateWorkerState(data.workerState));
  }
  chrome.storage.local.set({ reload: false });
  resolve();
});
```
@shosti  
with this code, the extension will know whenever it's loading from the reloader or not.   I think, it will be a good case for this new feature request.  What do you think?

**Comment by shosti** [comment]
@sweeneyapps yeah, that looks like it could work pretty well. Wanna make a PR?

**Comment by sweeneyapps** [comment]
sure, I'll do that.
