### ISSUE TITLE
I had problem in training test : Job ID 9548579

### ISSUE THREAD

**Issue by mueller01** [rainforestapp/tester-chrome-extension#721]
I had problem in training test : Job ID 9548579

I look into Guide Rules & Tester Role :

Match text in quotes exactly - any difference in spelling, content, or punctuation should be reported with No and a note explaining the problem. You do not need to report capitalization differences, unless the test states otherwise. Any reference to text that is NOT in quotes does not have to be matched exactly.

Training test like this :

Look at the column named "State". 
Is it grouped by Country then State (ex: "US-AL", "US-CA")?

I think : Is it grouped by Country then State ( it is correct )

But : (ex: "US-AL", "US-CA")? : ( it is confused )

I Do not find "US-AL", "US-CA" in VM
I reported and get a rejection

I think if the instruction like this ?

Look at the column named "State". 
Is it grouped by Country then State (ex: US-AL, US-CA )?

It will be nice ?

**Comment by zfonck123** [comment]
ex   is example

**Comment by mueller01** [comment]
but ex with quotes

**Comment by zfonck123** [comment]
u dont need ifind it, only  say is is same to the example

**Comment by zfonck123** [comment]
contact and contactr affther the steep if have problems

**Comment by mueller01** [comment]
ok thanks

**Comment by sweeneyapps** [comment]
I want to remind you that forum.rainforestqa.com is open to all of us.   You can ask for help there.. instead of here because this is only for extension bug issues

**Comment by qpPykT** [comment]
@mueller01 
The question of how it is grouped not about that do you see this or that text or button.
