### ISSUE TITLE
Extension not always emitting sound

### ISSUE THREAD

**Issue by Valdetecm** [rainforestapp/tester-chrome-extension#726]
It has happened a couple of times where the extension opens a hit but doesn't emit any sound

**Comment by djux90** [comment]
my chrome was closed, i played a game. Then i hear sound and when i exit game, chrome was started and job was there

**Comment by uqbiii** [comment]
@Valdetecm You must have uninstalled then reinstalled extension, and doing so, sound turns OFF automatically in you Edit Profile page. Now you have to again select a sound and then you have to save settings. Hope this helps.

**Comment by sweeneyapps** [comment]
it could be hit and miss.   hard to debug.

**Comment by JPierreS** [comment]
@sweeneyapps  Nice pun there ;-)

@Valdetecm  Did you uninstall your extension by any chance ?  Whenever you uninstall extension it will revert back to the default which is off.  Upon reinstalling make sure you select the sound and click the save button in the edit your profile section.

**Comment by sweeneyapps** [comment]
@Valdetecm  does @JPierreS solve your problem?  let me us know.   If u don't have any issue w/ the sound then you can close this issue.  :)

**Comment by shosti** [comment]
@Valdetecm do you have any more information? If not I'll close this issue since there's not enough to go on.
