### ISSUE TITLE
My extension has been showing disconnection issues ( turning grey and green) since past 3 days.

### ISSUE THREAD

**Issue by sunshinegal6** [rainforestapp/tester-chrome-extension#733]
Hi,

My extension has been blinking ( turning green and grey constantly) every few seconds. I suppose it is happening probably due to some disconnection issues.. However, I can see that my internet connection is still stable and there's no noticeable drop in the speed or anything. I have been getting very few HITS since this problem started. And also for the very few HITS I could manage to get my hands on, I was getting frequent "connection lost" error in every single step... I had to repeatedly many times use the Reconnect button till the end of the steps so that I could Submit. Could someone please be kind enough to provide me with a possible solution to this issue? Thanks in advance.

**Comment by shosti** [comment]
Have you tried uninstalling and reinstalling the extension?

**Comment by sunshinegal6** [comment]
Thanks for replying... Yes I tried doing every possible thing I could think of.... removing and uninstalling the extension, clearing internet cache, logging out & in, restarting the system.... but nothing seems to work... My internet seems to have some conflict with the extension alone but is otherwise stable... My extension keep turning grey and green almost every 15 secs... Unable to do any HITS coz I keep getting Connection error in every step... also getting lesser number of HITS since this prob started...

**Comment by begsoon** [comment]
You should contact internet provider about that problem.

**Comment by sunshinegal6** [comment]
Hmmm thanks for all your kind replies.... I'll try checking with the Internet Provider... I don't have much hope though since my connection speed, ping and rest everything seems to be normal...

**Comment by begsoon** [comment]
I had the same problem a few days ago and problem was in router.

**Comment by sunshinegal6** [comment]
Oh okay.... Mine is a mifi device.... I tried resetting it but didn't help... Maybe the drivers need to be updated or something...

**Comment by uqbiii** [comment]
You should try this extensions, it will notify you about you internet connection status. All you have to do is to simply install it, then disconnect you router or wifi and also disable this extension, then turn ON your extensions then internet, then it will works. When it starts working, keep an eye on dots.
Green: Internet working
Yellow: Connection Issues
Red: No Internet
If these dots blink consistently then there must be some problem with  your internet. 
https://chrome.google.com/webstore/detail/internet-connection-statu/hgccfdagfbilbdbkgmfdmmdfmjjoakfo?utm_source=chrome-ntp-icon

**Comment by sunshinegal6** [comment]
@uqbiii: Thank you so much for your response.... I've followed your instructions step by step and installed the extension. The dot is in green color and it's not blinking or anything. So does that confirm that there is no problem with my internet connection?

If that's the case, I was wondering why does my RF extension alone keep blinking/disconnecting ( turning grey and green) every few seconds....I'm finding it impossible to work because of this problem... Not getting much HITS since this problem started...Today is the fourth day in a row and I'm really clueless about what needs to to done to resolve this disconnection issue. Any help would be much appreciated. Thanks.

**Comment by shosti** [comment]
There have been a few reports of this kind of behavior; I've been looking into it and think I have a solution in the works. 

What would be extremely helpful would be if you could do the following while it's happening:

1. Go to the JavaScript console
2. Type in DEBUG=true (there should be a bunch of output)
3. Click the arrows for "socket" and "messages" so they're visible
4. Take a screenshot of the output and mail it to me at emanuel@rainforestqa.com (there's some security stuff in there so don't post it publicly)

**Comment by sunshinegal6** [comment]
Actually I'm not sure how to explain this... Hmmm after three consecutive days , finally today for nearly half an hour or something, the extension worked fine ( i.e, it stayed green w/o any disconnection ). But after that, it again started blinking grey and green and was getting disconnected in every few seconds. 

Strangely enough, after I posted the last message here, my extension again seems to be back to normal.... I'm not sure if this is a 'temporary miracle' or something... Hence, I just wanted to say that I'll mail you the screenshot as soon as the problem starts showing up again.. Thanks once again for all your help... I really appreciate it.

**Comment by sunshinegal6** [comment]
Yesterday, after I installed the Internet Connection Status extension shared by uqbiii, I was a bit surprised to notice that my RF extension stopped blinking and stayed green without getting disconnected. Today morning when I logged in, the RF extension again started showing the same problem as before, i.e. turning grey and green alternatively every few seconds.

On a hunch, I decided to do the same steps I followed while installing the Internet Connection Status extension, i.e, first turn OFF the extension, then disconnect the router, then turn ON the extension and then the internet. And I was surprised to see that every-time I followed these steps ( in the same order ), my RF extension goes back to normal without any issues.

However, I'm still confused with this weird behavior of my extension. I'm afraid if this 'new-found technique' too would stop working after a while. Hence, I'd like to know the root cause of this problem. And also, whether the problem is related to RF extension or my internet? From the look of things, I suppose the problem lies in the extension itself. Is there any way this extension problem could be resolved for good? Any help would be much appreciated. Thanks in advance.

**Comment by sunshinegal6** [comment]
@shosti : My extension is again giving trouble like day before yesterday and nothing I do seems to help.

I keep getting connection lost errors 'n' number of times in every single step. Whenever the extension works fine, I get a decent number of HITS. But once it starts blinking, my HITS are drastically reduced to almost zero.

You had asked me to mail a screenshot of the output while the extension has disconnection issues.... Like you had mentioned in your previous post, after typing in DEBUG =true, there was a bunch of output. 
Since it was not possible to take the screenshot of the entire console, I've only expanded the arrows for socket and messages that appeared in the first row. I hope that's alright. If not kindly explain to me what I need to do next to help you resolve this extension issue asap. Many thanks for all your help.

**Comment by pat87** [comment]
I have this too. Works fine when I am connected to my regular wireline broadband at home. 

When I am away and try using it on my laptop with my jio mifi hotspot, the extension polls every 15 seconds. It turns grey/green/grey every 15 seconds. 

Any idea what is causing this and how it can be fixed?

**Comment by sunshinegal6** [comment]
Yes that's exactly the same issue I've been experiencing since last Sunday .... My extension too changes color every 15 seconds, i.e, it keeps disconnecting every few seconds. Because of this problem, I'm hardly able to get any HITS... And even if I do manage to get a couple of them, I'm sometimes forced to abandon the job because I keep getting "Connection Lost" error repeatedly for every single step. It's not easy to keep clicking on Reconnect button every 2 seconds... Each time I click YES/No for screenshot, that time too I get connection lost error... That leaves me wondering whether the screenshot taken was proper or not. 

From yesterday noon till around today noon, my extension started working normal, without me doing anything. Today again it has started blinking grey and green. I really have no clue what I should do to get this issue resolved. I just know one thing, this problem started since last Sunday. Till then everything was going fine. Am really getting fed up and disappointed... I've mailed the screenshot of the console errors to @shosti . Hope he'll be able to find a permanent fix to this problem..

**Comment by shosti** [comment]
Thanks for your help debugging this. Unfortunately, it looks like a
connection issue on your end (probably with frequent short
disconnections), which means that there's not really much we can do
about it (even if the extension worked it's unlikely that the VM
connection would work). You might want to report the issue to your ISP
or try an alternative way of connecting.

**Comment by sunshinegal6** [comment]
@shosti: Thanks so much for trying to help us out with the extension issue.. My internet connection is otherwise stable...So I'm not sure how to explain this weird situation to my ISP  .. Anyways will see if there's anything that can be done to resolve this extension problem.... Thanks once again.

**Comment by HW71** [comment]
@sunshinegal6 
Not quite sure if this helps, but just fyi: Some years ago I had a similar issue with my internet connection and in order to have some kind of "proof" I could show to my ISP I stumbled upon a tool called "smokeping":

http://www.smokeping.org

With his you can define multiple "target" sites that get for example "ping"ed constantly with a configurable number of attempts (but you can also use other commands to check different protocols).

The result would then be a chart similar to that (in this case we only have one target host - but it's also possible to specify multiple hosts in one "job" - or multiple targets that can be selected from the menu on the web frontend):

http://oss.oetiker.ch/smokeping/doc/reading_detail.png

Besides this "fancy" smoke chart you'll get additionally some colored vertical bars in case the "loss-rate" exceeds a specific value. Now this might be the interesting part for you, because I guess that you'll also see some lost packages over time.

The biggest advantage of this tool is also a major drawback: You can configure almost everything - and this makes it hard to get it up and running - but there's a lot of information available on how to configure it correctly.

Additionally I guess it's not available for Windows (not 100% sure, though) - but you can run it on an SBC like Raspberry without problems (that's what I did).

Keeping fingers crossed! :-)

Have a great one & Cheers, Erik

**Comment by shosti** [comment]
Thanks for your help debugging this. Unfortunately, it looks like a
connection issue on your end (probably with frequent short
disconnections), which means that there's not really much we can do
about it (even if the extension worked it's unlikely that the VM
connection would work). You might want to report the issue to your ISP
or try an alternative way of connecting.
