### ISSUE TITLE
virtual machine with errror

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#736]
![image](https://cloud.githubusercontent.com/assets/19192312/19598058/a8dd71a4-9766-11e6-8413-9cf3c9ae4fec.png)

**Comment by marius11** [comment]
This issue is not related to the extension. You can check the forums (https://forum.rainforestqa.com/) for more information or the news feed (https://portal.rainforestqa.com/).

**Comment by zfonck123** [comment]
thx, i will go register to the forum thanks
