### ISSUE TITLE
Connection Error dial tcp 52.7.223.84:443:i/o timeout if you are the tester, please report this issue machine ID: 9031367

### ISSUE THREAD

**Issue by sigitsenyo** [rainforestapp/tester-chrome-extension#74]
Connection Error
dial tcp 52.7.223.84:443:i/o timeout
if you are the tester, please report this issue
machine ID: 9031367

**Comment by akshithaaravi** [comment]
I got this terminal browser ; IE, after 10 mins I got this message.

Terminal 9062381 
Connection Error
dial tcp 52.7.223.84:443:i/o timeout
if you are the tester, please report this issue

**Comment by pscohn** [comment]
This is an issue that comes up occasionally depending on the client, and are fixed as we get the reports.
