### ISSUE TITLE
Context Menu under Rainforest Icon :)

### ISSUE THREAD

**Issue by sweeneyapps** [rainforestapp/tester-chrome-extension#743]
Another cool way to set user's options quickly...    

chrome.contextMenus API

![image](https://cloud.githubusercontent.com/assets/7229364/19747766/8d65abfa-9b92-11e6-927f-15f7b3135568.png)

https://gist.github.com/sweeneyapps/1b122cce0502676ff7e2032985c69191

**Comment by qpPykT** [comment]
How about melody selection options in the same menu.

**Comment by ellmirr0001** [comment]
could it be possible to set two different sounds, one for getting a hit and one when ext goes off.

**Comment by shosti** [comment]
@sweeneyapps you up for opening a PR? :smile:

**Comment by sweeneyapps** [comment]
sounds fun.  I'll work on it sometime this week.    Any suggestion such as texts for the context menu..   ex: "Disabled" or "0 x Repeat Sound"  or something.   

or

Notification Sound > off, arpeggio, office, solemn
Sound Repeat > 1, 2, 3, 4, 5, 6, 7, 8

**Comment by shosti** [comment]
The second set sounds good since it's similar to what we do in the profile.

**Comment by Valdetecm** [comment]
Hi!
Would it also be possible to add a quick way to switch from notification on/off? By notification i mean that one that pops up when there is work available, not just the sound notification ;)

**Comment by sweeneyapps** [comment]
@Valdetecm I'll add that too.
