### ISSUE TITLE
Extension stops loading

### ISSUE THREAD

**Issue by Zunami007** [rainforestapp/tester-chrome-extension#749]
Sometimes, when I check my extension, I notice, that it stopped loading. You can see it on my desktop time and time of the last action in the extension. Is that a normal behaviour? Usually I refresh the page and than it works again .. 

![2](https://cloud.githubusercontent.com/assets/22084629/19988120/db4c76ae-a21e-11e6-98e7-74de551bbe0f.png)

**Comment by helloworld111gh** [comment]
Was the extension still green, or did it turn gray?

**Comment by Zunami007** [comment]
It was green. I only noticed it by looking in the extension

**Comment by HW71** [comment]
@Zunami007 
Is it possible that a new Websocket has been connected? I noticed this behavior in case the connection gets lost in between. In such cases you would see a second "websocket?auth" line on the left in the dev tools. But the "frames" shown are related to the first (abandoned) websocket.

Just guessing, but maybe that's the cause for the behavior you noticed...

HTH & Cheers, Erik

**Comment by Zunami007** [comment]
@HW71 
It is possible .. I will check it, if it happens again. Thanks! :)

**Comment by Zunami007** [comment]
@HW71 
It is just like you said :)

![unbenannt](https://cloud.githubusercontent.com/assets/22084629/20016118/7d8c4e22-a2be-11e6-8a49-74c1ac879940.png)

**Comment by HW71** [comment]
Cool... :) Glad to hear we were able to sort this out...
But this also means: you've got some issues with your Internet connection, right? :-(
Did you encounter slow performance or other issues with your internet connection recently while doing your regular stuff on the web?

**Comment by Zunami007** [comment]
not at all, everything works fine, connection is quick and stable. 
But it is not really a problem:  I receive a normal amount of hits - just noticed this by checking it and wondered, because I did not see and click on the second or third websocket line were the time of last refresh fits :). Usually I refreshed the extension to get back to normal, as I thought :)

**Comment by HW71** [comment]
OK, great... :)
So I'm not quite sure if @shosti (or someone else from RF) would like to comment on this - maybe there's another reason for getting multiple websocket entries, but at least for me this only occurred in case the connection got dropped (for example Wifi or router outage and such). That's also the reason why I think you have drops in the connection (even though you don't encounter any issues during "normal" surfing because of the way how HTTP handles the data transfer). 

If on the other hand everything is fine for you now please feel free to close this issue.

Have a great one & Cheers, Erik

**Comment by Zunami007** [comment]
Yes, I will close it, at least it seems not be something "worse".

Tank you, Erik for your kind reply 👍

**Comment by shosti** [comment]
Guys, in general this kind of speculation about low-level issues is not very helpful. If you notice a *behavior* issue (stuck grey, stuck WIP, not getting any jobs for a day, something like that) please open a ticket, but the details of how it works on the WebSocket level are generally hard to predict and not that important. For instance, the Chrome console isn't always predictable in what it logs, and it's definitely plausible that it just stops logging duplicate frames after a while. (Of course, feel free to discuss this kind of stuff for fun on the forum :wink:.) 

I've yet to see a case where the socket is disconnected but the icon stays green; please open a ticket if you have some hard evidence that that might be happening.

**Comment by shosti** [comment]
(btw multiple WebSocket connections is entirely expected and normal--the extension will try to open a new connection whenever it gets disconnected, which can happen for all sorts of normal reasons.)
