### ISSUE TITLE
You are active on another computer

### ISSUE THREAD

**Issue by koolorcool** [rainforestapp/tester-chrome-extension#752]
I have been facing this issue since yesterday regularly when the extension turns off and says "You are active on another computer Please turn off your extension elsewhere before turning it on here"

I am using only one 1 laptop where I use Rainforest extension.

Tried to reinstall,clear cache but problem persists.

Also tried changing my ISP but still problem persists.

**Comment by shrestha15207** [comment]
i had that issue yesterday but its gone now. you may just wait for some time and everything will be okay. Sometimes extension go crazy but it will be fine :)

**Comment by koolorcool** [comment]
i hope so i was advised by someone to report it here

**Comment by shosti** [comment]
This does seem to be happening in certain circumstances. I haven't been able to reproduce locally, but here's my theory as to what's happening:

1. Extension is connected/ready
2. A network error happens and the connection closes, but not cleanly
3. The extension opens a new connection and tries to move to "ready", but the server hasn't timed out the old connection so it sends the "already_ready" message
4. After a little while the old connection on the server times out so the new one can move to "ready"

The solution I can think of is a bit hacky--when we "automatically" push the worker state on reconnect (as opposed to manually clicking the icon), we shouldn't show the error message on "already_ready" but instead retry automatically for a minute or so (enough time to be sure that a stale connection would time out).

**Comment by koolorcool** [comment]
I have changed my isp and it seems to work fine but still checking...
