### ISSUE TITLE
ACCOUNT STANDING: Blocked -- Unfair

### ISSUE THREAD

**Issue by doncoi151189** [rainforestapp/tester-chrome-extension#753]
Today I blocked from RF, I always follow the instructions and use "Guide Rules: confusing Scenarios", "Rules & Guide Role Tester". I can not log in to froum.rainforestqa.com .This is not fair
although I might be doing wrong, but I have never done a bad action, I always report "No" if the uncertainty in the task. Please consider my.
![untitled](https://cloud.githubusercontent.com/assets/22788096/20030217/f288a6d8-a392-11e6-98ca-a3ad15a7f476.png)

**Comment by qpPykT** [comment]
@doncoi151189 
Help button in the your account profile maybe help you. Here place for bugs now.
