### ISSUE TITLE
Question about Chrome App

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#757]
I am have one account Crowdflower, with two ID worker,  One is Elite Chrowdlower and another is Cliksense, in this time i can only working with one a same time. 

my question is. i am useing Elite Crowflower ID worker,  my husband can use the another id (cliksense), for doing work in another "PC" And another public IP ?

**Comment by shosti** [comment]
In the future please direct this sort of question to the forum so we can keep this repo focused on technical issues.

Ideally, you should only use one CrowdFlower account at a time. We currently don't directly prevent you from using multiple channels at a time, but we might in the future. I'd suggest using separate CrowdFlower accounts for you and your husband if at all possible.
