### ISSUE TITLE
Banned testers

### ISSUE THREAD

**Issue by Profica** [rainforestapp/tester-chrome-extension#758]
Hello, so... is there anyone from Rainforest to explain why are some testers banned, when some testers had small or zero number of rejections? Will it be some announcement about this event, soon it will be almost a week, and no one still didn't answer anything on facebook group or our messages sent to help center. And what about our payments, that we didn't got from CF elite, is there any progress?

Cheers.

**Comment by marius11** [comment]
You can use the forum here: https://forum.rainforestqa.com/

The GitHub page is used to report problems with the extension, or possible bugs and other issues.

**Comment by Profica** [comment]
I can't use forum, because I am one of the banned testers

**Comment by marius11** [comment]
Send a ticket by clicking the green "Help" button from your profile.
