### ISSUE TITLE
Work on the list of CrowdFlower.

### ISSUE THREAD

**Issue by jombere** [rainforestapp/tester-chrome-extension#76]
Good afternoon friends let me know that they have solved regarding work on the list of crowflower, although not shown, I think it should resolve that soon.

**Comment by jbarber** [comment]
Can you clarify what your talking about?

**Comment by pscohn** [comment]
@jombere We're still working on a new system to get jobs posted to Crowdflower, and you can check https://github.com/rainforestapp/tester-chrome-extension/issues/24 to see when we post an update.

**Comment by jombere** [comment]
thank you
