### ISSUE TITLE
State changes not being acknowledged?

### ISSUE THREAD

**Issue by JrRandy** [rainforestapp/tester-chrome-extension#769]
I believe when I changed states (Available to unavailable, Unavailable to Available) I would get an acknowledgement in the console about said state change.  Seems this morning, I am sending the request for state change, and getting no response but the system continues to acknowledge heartbeats.

@shosti - Is this normal and I was halucinating before?  Or should I be seeing a response from the server on state changes?

![noack](https://cloud.githubusercontent.com/assets/6944427/21013144/e54cd3d8-bd26-11e6-80c7-04b085907742.jpg)
![noack2](https://cloud.githubusercontent.com/assets/6944427/21013149/e8ad3a68-bd26-11e6-9537-f05c7d19445d.jpg)

**Comment by shosti** [comment]
Please re-read the contributing guidelines--only open issues here if they're a) bug reports, or b) feature requests. To be clear, a bug report means a *behavior* issue (i.e. something not working correctly from *your* perspective), not implementation things like the above. Implementation can change very often and is often unrelated to things you see in the console.

**Comment by JrRandy** [comment]
@shosti I posted this here, because I believe it is a bug.  I am 99.9% positive that yesterday I was getting acknowledgements, and I was also getting hits.  Today I am not getting acknowledgements and I am not getting hits.  There are LOTS of us on the forum experiencing the same issue, while some others are getting hits so fast they cannot close the browser window.  This lead me to believe that the system is not seeing us available for work due to not acknowledging our availability and therefor not sending the waiting hits to us.  It is only sending hits to the people it is seeing online, and they are getting slammed with hits.

If this is not a bug, than that is fine.  But I do know the rules, and this is why I posted here.

**Comment by JrRandy** [comment]
In this screenshot you can see that I finally got an acknowledgement to my worker state, and 3 seconds later I got a hit.  I guess it was an issue :)

![noack3](https://cloud.githubusercontent.com/assets/6944427/21022220/d9b9c490-bd49-11e6-8874-2ed35e94cce1.jpg)

**Comment by shosti** [comment]
It was in fact a bug, but the problem is that reporting implementation things like ^ is usually not helpful and uses up a lot of time to look into (it wasn't helpful in this case). Reporting issues such as "no one's getting work right now", on the other hand, *is* very helpful. Just try to make sure that you report the *actual* issue (i.e. not getting work in an abnormal manner) rather than speculating about the cause (additional details can be helpful in some circumstances but are often unnecessary).

**Comment by JrRandy** [comment]
Ok, fair enough.  I was trying not to be "that guy" coming and saying 'I'm not getting hits something must be broken'.  Either way, thank you for fixing.
