### ISSUE TITLE
how to become new member ?

### ISSUE THREAD

**Issue by amare95** [rainforestapp/tester-chrome-extension#77]
i ame an member in rainforest since two years and i forgot how to become contributor at rainforest ! 
friend of mine i told him about rainforest and he is very intrest in it . 
but i forgot the detail how to become new member at rainforest . 

and he send help message before ...

**Comment by pscohn** [comment]
Please see our new Frequently Asked Questions page in the Wiki: https://github.com/rainforestapp/tester-chrome-extension/wiki/Frequently-Asked-Questions
