### ISSUE TITLE
Chrome extension give me few jobs a day

### ISSUE THREAD

**Issue by suplazam** [rainforestapp/tester-chrome-extension#770]
The chrome extension give me around five jobs a day, when my friend have a lot of jobs a day. Please, check my account for a bug. I am on in the chrome extension about 14 hours a day. My CrowdFlower Contributor ID (34044300)

**Comment by sweeneyapps** [comment]
this is only for extension bugs issues and new feature idea.    Nothing to do with your account problem.

You will need to go there...  here's link below
https://forum.rainforestqa.com
or 
https://portal.rainforestqa.com/help
