### ISSUE TITLE
Extension is gray

### ISSUE THREAD

**Issue by rodrigo95pl** [rainforestapp/tester-chrome-extension#773]
What should i do?

**Comment by nihlathar** [comment]
I have the same problem for close to a week now, extension stays gray on the "on" state, it happened before but would quickly go away, now I can't fix it no matter what if I reinstall the extension, or the browser, nothing helps. Account is in good standing according to profile page so what else is there?

**Comment by shosti** [comment]
Please provide more details (read https://github.com/rainforestapp/tester-chrome-extension/blob/develop/CONTRIBUTING.md for examples). What version of Chrome are you using? Does it still give you work? Do you see any errors in the JS console for the extension?

In general it's best to ask these sorts of questions on the forum first before asking here, as there are a lot of forum users who might have answers.

**Comment by nihlathar** [comment]
> What version of Chrome are you using? Does it still give you work? Do you see any errors in the JS console for the extension?

1. 64bit beta
2. No
3. This is what it looks like for me http://imgur.com/2inYyYW

**Comment by shosti** [comment]
Oh, you need the specific JS console for the plugin. Please ask on the forum
for instructions on how to get it.

**Comment by rodrigo95pl** [comment]
Still having problem. Already reinstall browser and extension, the problem still happens.

What version of Chrome are you using? most recent version, i believe that 32-bit.
Does it still give you work? I still work
Do you see any errors in the JS console for the extension? How can i see this?

**Comment by shosti** [comment]
Guys, unfortunately there's really not enough for me to go on. Please ask for help in the forum for how to get more information (esp the JS logs), then if you're still having a problem open up a new ticket.
