### ISSUE TITLE
Extension cannot open tab if no window is open

### ISSUE THREAD

**Issue by helloworld111gh** [rainforestapp/tester-chrome-extension#776]
## What isn't working?
I have multiple profiles on my Chrome installation. I have the Rainforest extension running on one of these profiles. I sometimes get HIT when the profile containing the extension is closed and not running, But when I try to accept the HIT by clicking on the notification, nothing happens.

## What should happen?
The extension should of opened a new tab with the HIT.

### Your exact browser version (from [chrome://version](chrome://version))
55.0.2883.87
### Screenshot of JS logs for the extension
http://puu.sh/t12kA/6e823e2254.png
### Steps to reproduce (if possible)
1. Have multiple profiles
2. Install and enable extension on one profile (enable work confirmation)
3. Open the other profile, and close the one with the RF extension
4. Get a HIT, and try to accept the HIT.

**Comment by shosti** [comment]
Thanks for the detailed bug report! I'll have to look more deeply into the Chrome APIs, but it may not be possible to open a tab from another profile--if that's the case, would going offline when you switch profiles be acceptable?

**Comment by helloworld111gh** [comment]
Yes, that is also an acceptable fix. But note that it is possible to have
multiple profiles open at the same time, so it should only be turned off
when there is no windows attached to the profile.

**Comment by shosti** [comment]
Actually it looks like it's easy enough to open a new window, will change.
