### ISSUE TITLE
PROBLEM WITH ID CONTRIBUIDOR PLEASE HELP ME

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#779]
![image](https://cloud.githubusercontent.com/assets/19192312/21630432/82ef13e0-d207-11e6-8d85-0d70a091973c.png)
THIS IS MY ID HELP!!!
I Am use Elite CrowdFlower
34044189

![image](https://cloud.githubusercontent.com/assets/19192312/21630421/6fd2a1be-d207-11e6-9ece-d49e6da57d5b.png)

**Comment by zfonck123** [comment]
cant log in

**Comment by zfonck123** [comment]
please if all migred to one profile, i wan my best profile!!   34044189 please help me @pscohn  @sweeneyapps

**Comment by helloworld111gh** [comment]
Please note that this github page is
>
> "*not* a place to ask about account issues."

Violators

> "*will be instantly and permanently blocked..."*

See
https://forum.rainforestqa.com/t/reminder-chrome-extension-repo-is-not-for-account-support/3186

Please close this issue, and use forum.rainforestqa.com
