### ISSUE TITLE
Error in connection establishment

### ISSUE THREAD

**Issue by DrogonRocks** [rainforestapp/tester-chrome-extension#780]
## What isn't working?
I think that sometimes "Worker state" stops working, i don't know if inside the extension something is wrong but from my end while doing those hits i didn't noticed anything wrong but im reporting it anyways because maybe you know what those erros means @shosti 

## Details:
 I always keep Developers tools open to catch any error and today i noticed/got 3 errors, i got a hit and when i checked the console i didn't find the "Worker state" log, all i saw was heartbeats (i make sure i scrolled up and down inside the console to see if i could find the new "Worker state" for the current hit but it wasn't there) i also noticed 3 websockets more, when normally there's only one, i did the following after that:
1.- After finishing the hit i deleted the extension, closed my browser, log in back and download the extension.
2.- Got another hit and i got the same errors in the console, so i repeated step 1, and this third time when i got another hits i didn't got the first error, but i keep getting this one: " Unchecked runtime.lastError while running tabs.remove: No tab with id: 964" the last 3 numbers changed because i re-installed the extension.

### Your exact browser version (from [chrome://version](chrome://version))
Latest chrome version: Versión 55.0.2883.87 m (64-bit)

### Screenshot of JS logs for the extension
http://image.prntscr.com/image/ab7c4f064f264a95bfa5b6a29ef01229.png

### Steps to reproduce (if possible)
Just wait for a hit i guess, i managed to reproduce it only 2 times

### Any other details
Just to clarify, i don't have any kind of net problems, i don't use WiFi and i only use/have 1 profile on my Chrome browser, i don't know if this errors are important but since i saw them im reporting them as detailed as i can.

![screenshot_26](https://cloud.githubusercontent.com/assets/19175204/21746669/68204916-d523-11e6-9979-1eb0e7c77606.png)

**Comment by shosti** [comment]
I appreciate the effort, but I can't act on a bug report without a behavior issue (i.e. "What doesn't work for you"), and console logs don't count--they're often very hard to interpret (the ones you sent seem consistent with correct behavior to me).
