### ISSUE TITLE
Extension was on but doesn't catch much the jobs like the other testers

### ISSUE THREAD

**Issue by mueller01** [rainforestapp/tester-chrome-extension#783]
## What isn't working?
Extension was on but doesn't catch much the jobs like the other testers

## Details:
Worker id 28573311

### Your exact browser version (from [chrome://version](chrome://version))
Version 56.0.2924.87 (64-bit)

### Screenshot of JS logs for the extension
![js log](https://cloud.githubusercontent.com/assets/22122367/22715666/a52dbe88-edc4-11e6-9ea2-3d4db1253d59.png)

### Any other details

Extension was on but doesn't catch much the jobs like the other testers
@shosti help me please?
Worker id 28573311
Thank you so much!

**Comment by shosti** [comment]
It looks like you are receiving jobs, so there's not a bug with the extension (we don't guarantee work availability).
