### ISSUE TITLE
unable to do anything on VM stuck in between. Error: Either this VM does not exist yet or this machine is incapable of taking screenshots in this state.

### ISSUE THREAD

**Issue by srsaurabh32** [rainforestapp/tester-chrome-extension#786]
## What isn't working?
stuck in between with an error at 17th step. Error is as stated in the headline.

### Your exact browser version (from [chrome://version](chrome://version))
Version 58.0.3029.110 (64-bit)

### Screenshot of JS logs for the extension
![image](https://cloud.githubusercontent.com/assets/19935406/26260145/c9f399bc-3ce9-11e7-97bd-82f4f0c2c051.png)

**Comment by shosti** [comment]
This isn't an extension issue, please ask for help on the forum.
