### ISSUE TITLE
Test Applications For Qa Id Rainforest no Notificactions Neobux

### ISSUE THREAD

**Issue by Lomaximo** [rainforestapp/tester-chrome-extension#788]
Since a year of having done the work of Test Applications For Rainforest Qa I never got the notification to be able to create the account 32390416. And I have not given concrete answers for this case although I already give it for lost. I do not know if performing this work Change Payment Channel For Rainforest There will be the possibility that I receive some notification about the case.
![1](https://user-images.githubusercontent.com/20029178/28495554-35794b4e-6f1e-11e7-906b-59fe5a1da059.png)
![2](https://user-images.githubusercontent.com/20029178/28495555-3a631da6-6f1e-11e7-99a9-1840f81bdbb5.png)

**Comment by shosti** [comment]
Please read the README before opening tickets here; this repo is not for general troubleshooting, please go to the forum for that.
