### ISSUE TITLE
Pasting in terminal 

### ISSUE THREAD

**Issue by BonesKnows** [rainforestapp/tester-chrome-extension#79]
Is it possible to make it instant? instead of letter by letter.

**Comment by marius11** [comment]
It's not possible to make it instant because of the lag involved.

**Comment by jbarber** [comment]
Closing as prohibited by fundamental physical constraints of the known universe (i.e. speed of light).

Also, the VNC protocol (which the terminal uses) has no concept of pasting, so it's emulated by sending individual key presses. It we send these presses too quickly, the terminal gets confused and garbles the "paste", hence the pause between characters.

**Comment by helloworld111gh** [comment]
The VNC guide says it has copy and pasting?
https://www.realvnc.com/products/vnc/documentation/5.3/guides/user/ah1025296.html

**Comment by jbarber** [comment]
@helloworld111gh The terminal has copy and pasting...

I just looked into this further by splunking through the Real VNC code, and it looks I was wrong WRT the protocol not having a paste concept. It's called [ClientCutText](https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#clientcuttext). Unfortunately our VNC server doesn't support it, so we'd still have to emulate it by sending the buffer a key-press at a time.

**Comment by JPierreS** [comment]
@jbarber  The slow pasting is something that I first noticed last year (can't recall when, but probably late summer)    When I started work on this task back in September 2014 and for a great part of 2015, pasting was near instant, and I never had an issue with dropped characters.  The only issue would be for IOS terminals.    When we have one of those tests with lots of forms to paste into, it increases the time to test completion, particularly on big jobs.

**Comment by helloworld111gh** [comment]
@jbarber will instant c&p be supported in the future? if you're not using custom vnc solution have you checked if there is new version with instant c&p support?

**Comment by jbarber** [comment]
Only if there is time.

On 22 February 2016 at 21:46, Richard <notifications@github.com> wrote:

> @jbarber <https://github.com/jbarber> will instant c&p be supported in
> the future? if you're not using custom vnc solution have you checked if
> there is new version with instant c&p support?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rainforestapp/tester-chrome-extension/issues/79#issuecomment-187400697>
> .
>



-- 
Jonathan Barber
