### ISSUE TITLE
Something bad happened

### ISSUE THREAD

**Issue by jatana222** [rainforestapp/tester-chrome-extension#793]
## Im on my last step (Step 19) and was about to submit the test but an error prevented me on doing it. It says "Something bad happened" no matter how many times I tried. I think it will be that way until my time run out and it become Job abandoned. What went wrong?

This is for Rainforest Job 14658694
Terminal 50366367

### My exact browser version (from [chrome://version](chrome://version)) is 60.0.3112.101 (Official Build) (32-bit) (cohort: Stable)

![image](https://user-images.githubusercontent.com/31346175/29713038-603e8c9c-89cf-11e7-8dee-c66e0a29de68.png)

**Comment by shosti** [comment]
This is not an extension-related bug; please read the contributor guide before opening up bug reports here.
