### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by rolerpro** [rainforestapp/tester-chrome-extension#795]
Extension can't work if i'm not logged in on portal, but i can't login there because i reset my phone and now i can't enter OTP, i know my password, but i'm stacked on step with OTP.
**The problem here is that your algorithm for resetting password is not working**, there is bug. When i enter my e-mail and click submit on "reset your password" page it didn't sent me any e-mail for resetting. I tried several times (it's not problem with my e-mail, i'm @live) and i contacted your support but there is no answer on my ticket 2 months, so fix this bug because i can't reset my password and i can't run extension.

**Comment by jbarber** [comment]
Hello @rolerpro, I've looked at the logs for our application, and it seems to be sending email correctly to you as far as I can tell. Can you check your spam folder to make sure they aren't being directed there? I'll dig in a bit more and see if I can see anything wrong.

Cheers

**Comment by rolerpro** [comment]
Dear @jbarber as i said it's not problem in my email, i'm @live and i receive messages from other apps for resetting password, problem is only with your. I also checked spam, trash, filter, everything. I tried to take a look in developer console on networking when i'm sending call for resetting, but i didn't find usefully information there.

**Comment by RnkSts** [comment]
@rolerpro Did you check your Crowdflower inbox? (if you're not from Mturk)

**Comment by rolerpro** [comment]
@RnkSts nope, i checked it now and there are instructions for reset password, i reset it successfully. Thank you very much!
I don't know why i received it in crowd-flower when message is "check your email :D ", i didn't think about crowd-flower. Thank you for this suggestion and if you can please check that message because it's confusing if we are not receiving links in e-mail
