### ISSUE TITLE
Reset password notification not received from Rainforest QA

### ISSUE THREAD

**Issue by vadivurv** [rainforestapp/tester-chrome-extension#798]
Reset password notification not received from Rainforest QA

Details:
I was forget my password -i try to reset my password using our  rainforest reset password portal ,
using my account email id ,but i was not received any reset passowrd notifigation from rainforest QA portal ,kidly advice on this.

Your exact browser version (Version 63.0.3239.84)

![2](https://user-images.githubusercontent.com/32436262/34321097-fe9afbc6-e82c-11e7-8363-4253e826da90.JPG)
![password](https://user-images.githubusercontent.com/32436262/34321100-05a0ff7e-e82d-11e7-937e-a790275d61fb.JPG)

Thanks and Regards
Vadivu

**Comment by shosti** [comment]
This is not an extension issue, please ask on the forum instead.
