### ISSUE TITLE
Rejections!

### ISSUE THREAD

**Issue by braneb** [rainforestapp/tester-chrome-extension#80]
I see there is new, rejections tab on our profiles...can someone of You, guys from RF tell us more about this..is there a possibility to dispute rejections like it was before and is there limit for rejections now... Thank you in advance!

**Comment by pscohn** [comment]
@braneb There is no dispute system for rejections since they don't affect your pay, but if you are blocked we will take a look at the rejections to make sure they are fair.

I added this information to the Wiki, so I'm closing this issue.
