### ISSUE TITLE
i cant login

### ISSUE THREAD

**Issue by cristinate** [rainforestapp/tester-chrome-extension#802]
hi 
please send me on this email emiliacristinamanuca@yahoo.com new password i cant login in my account rainforest
i understand you can activate my account because my crowdflower is dezactivate last year and for this reason you block my account rainforest
i receive this message  We're unable to pay your bonuses from rainforest last year because my crowdflower has dezactivate 
and at the same time you block my account rainforest

please send new password and reactivate my account
thank you
long life

**Comment by sweeneyapps** [comment]
@cristinate please use https://portal.rainforestqa.com/help to submit a support ticket. 

thanks, Paul

**Comment by cristinate** [comment]
thanks
i send 3 ticket but not receive any answer
