### ISSUE TITLE
Machine ID 9133350 - Connection error

### ISSUE THREAD

**Issue by DrDejan** [rainforestapp/tester-chrome-extension#82]
Connection error
dial tcp 67.221.170.49:443: i/o timeout
If you are a tester, please report this issue.
Machine ID: 9133350

**Comment by Genesis2015** [comment]
Same here

**Comment by akshithaaravi** [comment]
Connection error
dial tcp 67.221.170.49:443: i/o timeout
If you are a tester, please report this issue.
Machine ID: 9163200

**Comment by ando100** [comment]
@akshithaaravi  and @Genesis2015 I do not want to be internet police or smth, but this is not the place these things should be reported, you can report in your tester interface and you are in good hands:)

**Comment by jbarber** [comment]
These happen because the remote server is down. We should make this more explicit in the error message.
