### ISSUE TITLE
Jobs with more number of steps 

### ISSUE THREAD

**Issue by akshithaaravi** [rainforestapp/tester-chrome-extension#84]
The job is with 19 steps, it goes to the terminal and with 2 seconds I get this message "We're sorry, we've reached the maximum number of concurrent testers we can support. Please reload and try again." and if I refresh , again its the same , it will go the job and then immediately " We are sorry message." and 3rd refresh I get this "You have requested this job too often. Please return the work."

This happens only with jobs with more steps, I have never done jobs with more than 20 steps max. Please check and advise.

I have the URL, not sure if I can put it here. I have sent it to the help desk and also a mail.

**Comment by pscohn** [comment]
This has to do only with the number of available terminals, and not with how many steps there are. The best thing to do is wait for a minute or two and refresh.
