### ISSUE TITLE
getting error and error and error, cant do one job.

### ISSUE THREAD

**Issue by masterpeing** [rainforestapp/tester-chrome-extension#85]
Well iam having errors all the time , cant start one job today

getting these errors :

-Ooops: another worker accepted the job before you! It doesn't look like there is any more work for any of our hits; please try again shortly - you can refresh this page, or return this hit.

 - Something is wrong on our servers cant start the job ( or something similar).

please help!

my id : miguel maineri

**Comment by BonesKnows** [comment]
same here

**Comment by haap19** [comment]
me too

**Comment by helloworld111gh** [comment]
Oops are normal, it means someone else got job faster than you.
No fix, just close tab and wait for new job

**Comment by marius11** [comment]
@helloworld111gh Although there are frequent server error messages. More than usual. RF's status page confirms it.

**Comment by helloworld111gh** [comment]
Oh then yeah that looks bad, nothing we as tester can do though, just have
to wait for them to fix it.

**Comment by warpten09025** [comment]
This is normal
