### ISSUE TITLE
Console error/no work for tester

### ISSUE THREAD

**Issue by pscohn** [rainforestapp/tester-chrome-extension#9]
From a tester:

"I got your Chrome extension , but there is no work form me with it. 
Notifier is ON (I mean "NO" on green Rainforest logo ) .I provide you with information of error shown on extension's background page : "

![screenshotproblem](https://cloud.githubusercontent.com/assets/7697355/11076902/5716c0e2-87cb-11e5-8453-51af73341928.jpg)

**Comment by ukd1** [comment]
@pscohn could you ask the tester if they were running multiple windows? Did they change any of the code?

**Comment by pscohn** [comment]
I've asked him - although I can say I have the extension installed myself and saw the error earlier when I posted this (doesn't appear now, though).

**Comment by pscohn** [comment]
Tester responds,

"I were running only one window and didn't changed the extension code. Reason of the problem could be fact that I installed beta extension from GitHub earlier and 1.0.0 version after that, without uninstalling Beta? Now I got only  1.0.0 version  downloaded from tester profile, but for me there is no work to be done. (Note that I reinstalled extension and problem still persists)"

**Comment by ukd1** [comment]
@pscohn the tester should not be using the github version, as it doesn't automatically get work, nor does it point to the right server by default (as, it's for testing).

**Comment by pscohn** [comment]
@ukd1 He says there that he only has the one version downloaded from tester profile now, though

**Comment by pscohn** [comment]
Closing as fixed/duplicate.
