### ISSUE TITLE
ERROR: Something went wrong on our server, sorry about this. Please reload and try again.

### ISSUE THREAD

**Issue by vladfuller** [rainforestapp/tester-chrome-extension#93]
Forever getting this error

ERROR: Something went wrong on our server, sorry about this. Please reload and try again.

Please help... im getting this error the last hour

**Comment by ukd1** [comment]
can you paste the url please?

**Comment by vladfuller** [comment]
i just closed the tab, cant remind what link was.. but after close and get
a new job it worked

2016-02-25 23:08 GMT-04:30 Russell Smith <notifications@github.com>:

**Comment by hunt40** [comment]
this is what happens now another server error and what you have to but refresh and bam

You have requested this job too often. Please return the work.

just get few hit and its gone too because server error,and some people other forums claim they got 5 hits back to back.

so fair great

**Comment by marius11** [comment]
@hunt40 That happens when there are a lot of concurrent testers (over 800).
