### ISSUE TITLE
Extension Update Errors

### ISSUE THREAD

**Issue by Foreverrr** [rainforestapp/tester-chrome-extension#94]
First, I tried to install the the new version from the Rainforest Profile, I click Get Chrome Extension > Add extension and I get the next message "Manifest file is invalid"

Second, I tried to install it from Chrome Web Store, it was installed but it opened a new login page and asked me to login at https://portal.rnfrst.com/login which is different from website that we usually use to login, https://portal.rainforestqa.com/login

So we can't login on https://portal.rnfrst.com/login cause it's a different website than the one were we have our accounts, so it seems that a lot of users have this issue because they don't know they need to login at https://portal.rainforestqa.com/login and the extension opens https://portal.rnfrst.com/login

Until they fix it, just go to https://portal.rainforestqa.com/login and login and the extension will find your account and everything will work :)

**Comment by ahmedofhell** [comment]
Same Problem Here, Thanks for your advice.

**Comment by Foreverrr** [comment]
@juliankrispel 

You still need to change https://portal.rainforestqa.com/ to https://portal.rnfrst.com/ on some files, even at version 1.2.3 it still opens https://portal.rnfrst.com/

**Comment by juliankrispel** [comment]
Unfortunately we had skipped the compile step for 1.2.2 and 1.2.3, 1.2.4 fixes this, sorry guys

**Comment by juliankrispel** [comment]
It's deployed we just need to wait for the chrome extension store to refresh its cache

**Comment by Foreverrr** [comment]
Yeah, I've installed it, now it works

**Comment by juliankrispel** [comment]
yey :+1:
